common/protob/messages-monero.proto
core/src/apps/monero/get_address.py
core/src/apps/monero/layout/common.py
core/src/apps/monero/layout/confirms.py
core/src/trezor/messages/MoneroGetAddress.py
python/trezorlib/messages/MoneroGetAddress.py

- pagination added to show_address
- integrated address supported
- QR code fixed (prefix with monero: as GUI does)
Relates to (PR to Monero will follow):
- https://github.com/monero-project/monero-gui/issues/2184
- https://github.com/monero-project/monero/pull/5594
Btw the trezor-common repo is synced automatically?
Regarding the UI: I've added the get_address with scrolling to monero in order to avoid shared code modification (import changes -> memory increase). Feel free to revamp the UI. This is the working prototype for get_address to work.
Thanks!

xmr: get_address - pagination, integrated address

---

ci/Dockerfile
core/tests/run_tests_device_emu_monero.sh

ci: download monero tests binary in docker

---

core/src/trezor/ui/mnemonic_bip39.py
core/src/trezor/ui/mnemonic_slip39.py

core/ui: enlarge backspace button

---

core/src/trezor/ui/scroll.py

- AFAIK only Monero uses this so there should be no side effects.
- Tested in emu, works

PaginatedWithButtons fix, fixes #306

---

core/src/apps/management/recovery_device.py

Show total number of words during device recovery

---

core/src/apps/management/common/layout.py
python/trezorlib/tests/device_tests/test_msg_resetdevice_shamir.py
python/trezorlib/tests/device_tests/test_msg_resetdevice_t2.py

Maybe there is a nicer way to do this (regarding the division and adding one), so I'm filling a PR.
closes #289

Check three words in backup

---

python/trezorlib/tests/device_tests/test_msg_recoverydevice_shamir_dryrun.py

Added test that tries to enter different shares than the ones loaded in device and expects dryrun failure.

tests: added shamir invalid seed dryrun test

---

core/embed/extmod/modtrezorcrypto/modtrezorcrypto-sha512.h
core/mocks/generated/trezorcrypto/__init__.pyi
core/src/apps/common/seed.py
core/tests/test_apps.common.seed.py
core/tests/test_apps.wallet.signtx.fee_threshold.py

Pending approval of https://github.com/satoshilabs/slips/pull/675

Add SLIP-0021 implementation and tests.

---

common/defs/support.json
common/defs/wallets.json

Hello, 
I don't know if this is correct, but seems Polis support to connect was missing. 
Also, added reference for PolisPay app, with the launch of connect v8 Electron is supported. 
App with support is being tested and will be launched soon.
ref: #396

[TRIVIAL] Polis support on Connect and PolisPay wallet URL

---

common/defs/misc/misc.json

Remove "blockchain_link" empty object from "misc definitions

Remove "blockchain_link" empty object from "misc" definitions

---

core/embed/firmware/version.h
core/src/apps/management/reset_device.py
core/src/trezor/crypto/slip39.py
core/tests/test_trezor.crypto.slip39.py
python/trezorlib/tests/device_tests/test_msg_resetdevice_shamir.py
python/trezorlib/tests/device_tests/test_shamir_reset_recovery.py

identical to #402, except based on a release branch
fixes #400.
DRAFT for now because it points to the release branch. Before merging, we must decide whether to merge there, or create a hotfix sub-branch.

shamir hotfix EMS vs MS

---

core/src/apps/management/common/layout.py

Please review. I'm a bit scared doing anything in SLIP-39 without review :).
closes #395

core/slip39: fix UI for 33 words

---

core/docs/hardware/hardware.md
core/docs/src/communication.md
core/tests/test_apps.wallet.address.py
core/tests/test_trezor.crypto.hashlib.sha1.py
core/tests/test_trezor.crypto.hashlib.sha3_512.py
crypto/ed25519-donna/README.md
python/CHANGELOG.md

Updated some links 1

---

python/src/trezorlib/cli/trezorctl.py

Fixes https://github.com/trezor/trezor-firmware/issues/411

python: add --beta switch to trezorctl firmware_update command

---

core/src/apps/ethereum/networks.py
core/src/apps/ethereum/networks.py.mako
core/tests/test_apps.ethereum.address.py
tests/device_tests/test_msg_ethereum_getaddress.py
tests/device_tests/test_msg_ethereum_signtx.py

fixes #437 
@tyrion70 please build this and ensure that it works fine with your wallet app

core/ethereum: add support for wanchain slip44 id

---

core/src/apps/common/cache.py
core/src/apps/common/seed.py

Fixes Sluggish U2F authentization with SLIP-0039 seed https://github.com/trezor/trezor-firmware/issues/386.

core: Cache seed without passphrase.

---

core/src/apps/binance/helpers.py

this PR implements a fix for #482

Fix binance divisibility

---

core/src/apps/management/recovery_device/homescreen.py

I really dislike the `_request_secret` function, it got way too big. I will tackle that in another issue.
I will also send fw with this to @sorooris to check it out.
Updates #453

Ask for the word count again after first incorrect mnemonic

---

core/src/apps/management/load_device.py
core/src/apps/management/recovery_device/recover.py
core/src/trezor/crypto/slip39.py
core/tests/test_apps.cardano.address.py
core/tests/test_apps.cardano.get_public_key.py
core/tests/test_trezor.crypto.slip39.py
tests/device_tests/common.py
tests/device_tests/test_msg_loaddevice.py
tests/device_tests/test_msg_recoverydevice_supershamir.py
tests/device_tests/test_msg_recoverydevice_supershamir_dryrun.py

Built on top of #480, let's merge that first.
@ciny you can review the 8c73bed commit in meantime.
Updates #458

Store correct backup type in load device 

---

core/src/apps/wallet/sign_tx/scripts.py

Following https://gitter.im/trezor/community?at=5d6ce506d3fda15e7450589d.

core/wallet: fix segwit multisig comment

---

core/src/apps/management/recovery_device/homescreen.py
core/src/apps/management/recovery_device/recover.py

This PR fixes #455. device tests for this will be added as part of #462

Fix accepting 1of1 slip39 share

---

ci/build.yml
ci/prebuild.yml
ci/test.yml

It's annoying how narrow the boxes are. Is it worth it or not really?
Before:
After:

ci: reorder titles of Jobs for a better overview

---

core/src/apps/binance/layout.py

Binance UX improvements

---

core/src/apps/management/reset_device/layout.py

Enables 1of1 in reset device and alters the texts accordingly.
Closes #500

core: enable 1of1 in reset device

---

core/src/apps/management/recovery_device/homescreen.py

Fix info button when shares reach its threshold

---

core/src/apps/stellar/operations/serialize.py
core/src/apps/stellar/writers.py
legacy/firmware/stellar.c
tests/device_tests/test_msg_stellar_sign_transaction.py

fixes #581 
changes in core and legacy are minor, but i'd still appreciate if you took a look, esp. on the legacy code, and whether it is ok to call `stellar_hashupdate_string` like this

Stellar: fix ManageDataOp value padding 

---

core/tests/mock.py
core/tests/storage.py
core/tests/test_apps.management.recovery_device.py

the `Mock` code is unused but I left it in since I already had it.

core: draft unit test for process_slip39

---

common/defs/wallets.json

Add Stakenet Wallet reference
This change is related to changes in #140

common: Add XSN to wallets.json, it requires PR #140

---

tests/download_emulators.sh
tests/emulators/.gitignore
tests/emulators/shell.nix

Let me know if this is the nix way.

Patch emulators on NixOS for upgrade tests

---

core/src/apps/webauthn/__init__.py
core/src/main.py

I confirm this way the test passes on device.

core/webauthn: set webauthn interface in its app not in main.py

---

tests/buttons.py
tests/click_tests/reset.py
tests/click_tests/test_reset_slip39_advanced.py
tests/click_tests/test_reset_slip39_basic.py

This PR resolves #547 and #557 
I'm not entirely sure about the 16 groups/shares advanced test, it takes about 3 minutes on my machine and 5 on CI.

tests: click tests for basic and advanced slip39

---

ci/Dockerfile
core/tests/run_tests_device_emu_monero.sh

- tests new HF12
- attempt to fix #405

WIP tests: use new monero testing binary v0.15.0.0

---

core/src/apps/webauthn/confirm.py
core/src/apps/webauthn/fido2.py
core/src/trezor/workflow.py
core/tests/run_tests_device_emu_fido2.sh

Enable random ordering of FIDO2 device tests

---

core/src/apps/webauthn/fido2.py
core/src/trezor/ui/__init__.py

Fixes #733. I haven't tested this myself, but @bosomt has.

Fix continuous display blinking with Android

---

common/defs/coins_details.json

This is a small fix of info about Auxilium coin.
(details were discussed in email)
Thanks!

Update of coin_details.json

---

python/default.nix

As requested by @matejcik in #781

Drop pyargs

---

core/src/apps/common/mnemonic.py
core/src/apps/debug/load_device.py
core/src/apps/management/recovery_device/recover.py
core/src/apps/management/reset_device/__init__.py
core/src/trezor/crypto/slip39.py
core/tests/test_apps.cardano.address.py
core/tests/test_apps.cardano.get_public_key.py
core/tests/test_trezor.crypto.slip39.py
docs/core/misc/slip0039.md

Will fix #407 when done. This is now a draft of the documentation.

core: add documentation for SLIP-39 handling in Trezor

---

docs/core/build/embedded.md
docs/core/build/emulator.md
docs/core/build/index.md

Make `pipenv shell` usage a bit more explicit.

Docs/core: Improve build section

---

core/Makefile
docs/tests/ui-tests.md
tests/conftest.py
tests/ui_tests/__init__.py

Introduce --ui-check-missing to test/remove missing tests

---

core/embed/bootloader/main.c
core/src/usb.py
core/tests/production_tests/main.py
legacy/bootloader/usb.c
legacy/firmware/usb.c
legacy/webusb.c
legacy/webusb.h

Don't show WebUSB popup in firmware, in bootloader only if no firmware present

---

legacy/bootloader/usb.c
legacy/firmware/usb.c

original PR in https://github.com/trezor/trezor-firmware/pull/756

legacy/bootloader: soft reset after firmware upload

---

core/embed/bootloader/messages.c

Fixes #77 
Please test on the real device. I have not tested this one!

core/bootloader: make read more benevolent and read error more helpful

---

core/src/apps/wallet/get_address.py
tests/device_tests/test_msg_getaddress_show.py
tests/ui_tests/fixtures.json

TT fix for second issue in #855

core: show yours/others in get_address for multisig

---

core/src/apps/common/sdcard.py
core/src/trezor/sdcard.py
core/tests/test_trezor.sdcard.py
tests/conftest.py
tests/device_tests/test_sdcard.py
tests/ui_tests/__init__.py
tests/ui_tests/fixtures.json

Fixes #868. Happens to fix a somewhat nasty problem in the previous `get_filesystem` code too.

Do not ask for formatting in SD-protect checks

---

core/embed/firmware/mphalport.c
core/embed/trezorhal/usb_vcp-impl.h

I was hoping that this would fix the data losses when debugging via in the screen command, but it didn't really help. Still seems worth merging though.

core: Prevent data loss when writing to USB VCP.

---

core/embed/boardloader/main.c

because DMA can't access the CCMRAM
fixes https://github.com/trezor/trezor-firmware/issues/820

core/boardloader: use SRAM as SD card read buffer

---

legacy/firmware/fsm.c
legacy/firmware/fsm_msg_coin.h
legacy/firmware/fsm_msg_ethereum.h
legacy/firmware/fsm_msg_lisk.h
legacy/firmware/fsm_msg_nem.h
legacy/firmware/layout2.c
legacy/firmware/layout2.h

Implements showing of the XPUBs in GetAddress for Multisig (something we already have for TT).
It also fixes the second issue of https://github.com/trezor/trezor-firmware/issues/855

legacy: show xpubs with multisig get_address

---

common/protob/messages-webauthn.proto
core/src/apps/common/cbor.py
core/src/apps/webauthn/add_resident_credential.py
core/src/apps/webauthn/common.py
core/src/apps/webauthn/credential.py
core/src/apps/webauthn/fido2.py
core/src/apps/webauthn/list_resident_credentials.py
core/src/trezor/messages/WebAuthnCredential.py
core/tests/test_apps.webauthn.credential.py
python/src/trezorlib/cli/fido.py
python/src/trezorlib/messages/WebAuthnCredential.py

Implements https://github.com/trezor/trezor-firmware/issues/698

Ed25519 in FIDO2

---

common/defs/support.json

Thank you for Trezor Connect's BitZeny support

Add Connect support indicator for BitZeny

---

core/embed/extmod/modtrezorio/modtrezorio-fatfs.h
core/mocks/generated/trezorio/fatfs.pyi
core/src/apps/common/sdcard.py
core/src/boot.py
core/src/storage/sd_salt.py
core/tests/test_trezor.io.fatfs.py
tests/device_tests/test_sdcard.py
tests/ui_tests/fixtures.json

SD-protect - properly show "Wrong card"

---

core/src/apps/webauthn/credential.py
core/src/apps/webauthn/fido2.py
core/src/trezor/utils.py
core/tests/test_apps.webauthn.credential.py
core/tests/test_trezor.utils.py

Implements https://github.com/trezor/trezor-firmware/issues/735

FIDO2: Add maxCredentialCountInList and related improvements

---

core/embed/bootloader/bootui.c
core/embed/bootloader/bootui.h
core/embed/bootloader/messages.c

core/bootloader: distinguish between a vendor change and downgrade with wipe

---

docs/SUMMARY.md
docs/misc/update-wipes.md

QA wanted to clear things up a bit, so I've documented this.
@matejcik @prusnak have I forgotten something?
@trezor/qa is it comprehensible?

Docs: Document when firmware wipes storage

---

common/defs/bitcoin/bitzeny.json
common/defs/bitcoin/vipstarcoin.json

Hi, I did PR to this repo before.
Then I changed my email address.
Therefore, I'm doing PR again.

common: Fix maintainer email for vipstar/bitzeny

---

core/src/apps/webauthn/fido2.py
tests/fido_tests/u2f-tests-hid/HIDTest.cc

Solves https://github.com/trezor/trezor-firmware/issues/804
1. The following tests were failing due to an incorrect implementation of U2FHID in Trezor T.
- test_InitOther (fixed now)
- test_Interleave (fixed now)
- test_Limits (looks like something I fixed several months ago)
- test_OnlyInitOnBroadcast (looks like something I fixed several months ago)
2. The following tests may have failed due to the emulator being too slow or too quick to respond.
- test_LongEcho
- test_Timeout
- test_Busy
I disabled strict timing checks in HIDTest and increased the receive-timeout. Strict timing checks in HIDTest can be enabled by using a new `-t` command line option.

Enable u2f-tests-hid and disable strict timing

---

common/protob/messages-monero.proto
core/src/trezor/messages/MoneroTransferDetails.py
python/src/trezorlib/messages/MoneroTransferDetails.py

Adds field required for protocol update.
This PR is subset of #942, but I guess #942 will take longer to review, so I am adding it as a separate PR in case this gets to the upstream faster, so I can incorporate changes also to the Monero codebase.

XMR: proto - add fields for protocol optimization

---

core/src/apps/webauthn/fido2.py

- Improve FIDO2 and U2F error codes on uninitialized device.
- Return ERR_OPERATION_DENIED only upon user decline or timeout, otherwise it cancels the operation on all connected authenticators.

FIDO on uninitialized device

---

docs/SUMMARY.md
docs/core/src/event-loop.md

There was some gap between me learning about the event loop and finishing the documentation, so things might be missing that are obvious to me.
Please let me know what you think.
Also this should probably be linked from some index - which?

Document trezor-core event loop

---

docs/SUMMARY.md
docs/misc/third-parties.md

As discussed with @slush0 it seems as a good idea to have this list also here.
I have added the ones @prusnak mentioned and also added all parties that had over 100 stars on [this list](https://github.com/trezor/connect/network/dependents?package_id=UGFja2FnZS01MTA2MzE4OQ%3D%3D).

Document affected third parties by a breaking change

---

legacy/firmware/u2f.c

Fixes https://github.com/trezor/trezor-firmware/issues/961:
1. Adds bogus app ID used by Firefox to indicate error in U2F.
2. Figures out which error to display based on past U2F_AUTHENTICATE check-only requests on the same channel.

Improve U2F error handling in T1

---

python/src/trezorlib/debuglink.py
tests/device_tests/signtx.py
tests/device_tests/test_msg_signtx.py
tests/device_tests/test_msg_signtx_bcash.py
tests/device_tests/test_msg_signtx_bgold.py
tests/device_tests/test_msg_signtx_dash.py
tests/device_tests/test_msg_signtx_decred.py
tests/device_tests/test_msg_signtx_grs.py
tests/device_tests/test_msg_signtx_komodo.py
tests/device_tests/test_msg_signtx_segwit.py
tests/device_tests/test_msg_signtx_segwit_native.py
tests/device_tests/test_msg_signtx_zcash.py
tests/device_tests/test_multisig.py
tests/device_tests/test_multisig_change.py
tests/device_tests/test_op_return.py
tests/device_tests/test_protection_levels.py

This should make editing signtx tests easier in the future.
Also introduces conditional expected responses - extremely useful! Very expressive! Such code!

readability improvements to sign_tx tests

---

common/protob/messages-bitcoin.proto
core/src/apps/bitcoin/sign_tx/decred.py
core/src/apps/bitcoin/sign_tx/helpers.py
core/src/trezor/messages/TxInputType.py
core/src/trezor/messages/TxOutputType.py
legacy/firmware/signing.c
legacy/firmware/transaction.c
python/src/trezorlib/messages/TxInputType.py
python/src/trezorlib/messages/TxOutputType.py
tests/device_tests/test_msg_signtx_decred.py

Drop Decred script_version

---

build-docker.sh
ci/.gitignore
ci/Dockerfile
ci/environment.yml
ci/shell.nix

Let's use NixOS in Docker build instead of Debian

ci: use NixOS in Docker

---

.github/ISSUE_TEMPLATE/bug_report.md

changed "firmware version OR revision" to "version AND revision"

trivial update

---

core/ChangeLog
legacy/firmware/ChangeLog

I believe we should start using the same also for bootloaders and the boardloader?

Start using more detailed changelog

---

common/tools/coin_info.py

Fixes https://github.com/trezor/trezor-firmware/issues/1060

common/tools: validate for string emptiness in cointool

---

legacy/firmware/config.c
legacy/firmware/fsm_msg_common.h

Set initialized in storage to false if no mnemonic is present

---

core/ChangeLog
core/src/trezor/ui/qr.py

Fixes https://github.com/trezor/trezor-firmware/issues/1067

core/ui: Fix repaint bug in QR code rendering #1067.

---

crypto/bignum.c
crypto/tests/test_bignum.py

This fixes https://github.com/satoshilabs/trezor-firmware/issues/85 and was discussed there and reviewed in https://github.com/satoshilabs/trezor-firmware/pull/88.

Make bn_format faster

---

core/src/apps/debug/__init__.py
python/src/trezorlib/debuglink.py
tests/device_tests/test_msg_getaddress_show.py
tests/device_tests/test_msg_recoverydevice_bip39_dryrun.py
tests/device_tests/test_msg_recoverydevice_bip39_t2.py
tests/device_tests/test_sdcard.py

fixes #1142 (hopefully), by not saving all layouts in memory when nothing is reading them

use watch_layout only explicitly

---

ci/build.yml
ci/deploy.yml
ci/test.yml
core/CHANGELOG.md
core/Makefile
core/SConscript.unix
core/embed/unix/main.c
core/emu.py
core/emu.sh
core/tests/run_tests.sh
core/tests/run_tests_click_emu.sh
docs/ci/jobs.md
tests/emulators.py

core/emulator: assume `-m main` when no arguments are provided

---

core/embed/firmware/bootloader_hashes.py
python/src/trezorlib/_internal/firmware_headers.py

commit 6d407c84d7dae44a162b55110c08e76b71fb0b7f did not replace everything

python: use stdlib blake2s on python 3.6+

---

ci/build.yml
ci/deploy.yml
ci/posttest.yml
ci/test.yml

AFAICT this does not break anything.
Closes #1183.

Ci: replace 'dependends' with 'needs'

---

core/src/apps/cardano/README.md

As requested in [discussion](https://github.com/trezor/trezor-firmware/pull/1112#discussion_r459369404) in the 2nd Cardano PR I am adding a `README.md` file for Cardano.
In addition to useful links I've also added some details about Cardano, since I had to write them for internal purposes anyways. If it's too much/redundant information, I can remove them as you wish. Also if you feel like something important is missing please let me know.
Also, who should be mentioned as the maintainer of the Cardano app? Is that us/me? Or someone from your end? Or both depending on the type of the problem?

Add Cardano README.md

---

python/src/trezorlib/protobuf.py

See: https://github.com/bitcoin-core/HWI/pull/367

python: silenced unused variables

---

crypto/shamir.c

Fixes https://github.com/trezor/trezor-firmware/issues/1151

Fix undefined behavior in shamir unbitslice()

---

core/Makefile
core/SConscript.boardloader
core/SConscript.bootloader
core/SConscript.bootloader_ci
core/SConscript.firmware
core/SConscript.prodtest
core/SConscript.reflash
core/SConscript.unix

Build system-only change, should not have any effect.

core: introduce TREZOR_MODEL flag

---

docs/storage/index.md

is be used -> is used
We se -> We use

docs: fix typo

---

legacy/firmware/signing.c

legacy: replace confusing Version group ID error message

---

docs/SUMMARY.md
docs/common/communication/index.md

See also b16b4823d57f2f5f48b1007a5c10a4fd7d414ec2.

docs: add bitcoin signing to book index

---

legacy/bootloader/CHANGELOG.md

Just something worth documenting imho. It seems to me it was introduced in https://github.com/trezor/trezor-firmware/commit/806f943116f4df8a666b6bd7182bfcbe5cf3c13a.

docs: add feature to 1.8.0 bootloader changelog

---

crypto/ecdsa.c

Resolves https://github.com/satoshilabs/trezor-firmware/issues/95.

Improve comments and error handling in ecdsa_verify_digest()

---

core/CHANGELOG.md
core/src/apps/management/apply_settings.py
core/src/apps/management/wipe_device.py
tests/device_tests/test_msg_wipedevice.py
tests/ui_tests/fixtures.json

make sure run-time settings are reset after wipe

---

ci/deploy.yml
ci/prebuild.yml

It speeds up the job about ~2 mins. Not exactly sure if it is worth it in the _style_, it might be confusing if smth changes.

Skip submodules download where applicable in CI

---

.yamllint.yml
Makefile
ci/build.yml
ci/posttest.yml
legacy/gitian/gitian.yml
poetry.lock
pyproject.toml

A little bit of OCD-fixing for Monday evening. We can also check the line lengths but it seems like too much work - as you want though.

Introduce yamllint

---

ci/test.yml

Counterpart of trezor/micropython#4.

chore(vendor): update micropython to version with more precise memory profiling

---

core/CHANGELOG.md
core/src/apps/bitcoin/sign_tx/approvers.py
core/src/apps/bitcoin/sign_tx/tx_info.py
crypto/ecdsa.c
crypto/ecdsa.h
crypto/tests/test_check.c
legacy/firmware/CHANGELOG.md
legacy/firmware/layout2.c
legacy/firmware/layout2.h
legacy/firmware/signing.c
tests/device_tests/test_msg_signtx_replacement.py

Implements https://github.com/trezor/trezor-firmware/issues/1367.

Replacement transactions in T1

---

legacy/Makefile.include

Fixes https://github.com/trezor/trezor-firmware/issues/7

fix(legacy): fix emulator build on darwin

---

python/src/trezorlib/cli/btc.py
python/src/trezorlib/tools.py
python/tests/test_tools.py
tests/device_tests/test_descriptors.py

Descriptors contain optional checksum. Let's compute it at and append it to the descriptor.

fix(python): append checksum to descriptors

---

core/src/apps/bitcoin/keychain.py

Supersedes https://github.com/trezor/trezor-firmware/pull/1468
I squash the commits and fetched them to CI to see whether this builds OK

fix(core): add exceptions for unchained capital paths

---

core/embed/bootloader/bootui.c
core/embed/bootloader/main.c
core/embed/extmod/modtrezorui/display-unix.h

Fixes https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/1073573197

style(core): fix bootloader formatting

---

core/Makefile
docs/core/build/embedded.md
legacy/Makefile.include

Let's merge this AFTER openocd 0.11 stable is released.

openocd: separate stlink configs deprecated - now combined

---

crypto/bignum.c
crypto/bignum.h

Part of https://github.com/trezor/trezor-firmware/issues/1524 - addresses point 4

style(crypto): cleanup unused functions

---

core/src/trezor/ui/layouts/tt.py

Fixes #1513. Thanks for nice bug report @matejcik!

fix(core): fix title shown for multisig address

---

core/embed/trezorhal/usbd_conf.c

Fixes #1566 - core T1 build. See also #1539.

core/embed/usb: add back usb fs code for T1 and redo fifo sizing

---

.github/workflows/prebuild.yml

Added the rest of the checks from travis-ci to github actions, checks will run on pull requests.

feat(ci): add checks to github actions

---

crypto/tests/test_check.c
crypto/tests/test_check_cashaddr.h
crypto/tests/test_check_monero.h
crypto/tests/test_check_segwit.h

Supersedes https://github.com/trezor/trezor-firmware/pull/1562

fix(crypto): use ck_assert_uint_eq where we compare unsigned values

---

ci/shell.nix
core/embed/rust/Cargo.lock
core/embed/rust/Cargo.toml
core/embed/rust/rust-toolchain
core/embed/rust/src/lib.rs
core/embed/rust/src/micropython/gc.rs
docs/core/build/embedded.md
docs/core/build/emulator.md

When we need it, we will re-enable.
Also add some build documentation.
@mmilata is there anything to be done on the nix side? Not sure if it's worth changing the image when we expect we might be going back to nightly again.

Disable Nightly Rust

---

legacy/intermediate_fw/trezor.c

Erase just the first firmware word

fix(legacy/intermediate_fw): don't erase the whole firmware sector

---

core/src/trezor/ui/components/tt/info.py

fix(core): spaces in Shamir info texts 

---

core/.changelog.d/1620.fixed
core/Makefile
core/embed/extmod/modtrezorutils/modtrezorutils.c
core/embed/trezorhal/common.c
core/embed/trezorhal/common.h
core/embed/unix/common.c
core/embed/unix/common.h
core/mocks/generated/trezorutils.pyi
core/src/apps/base.py
core/src/trezor/utils.py

Fixes https://github.com/trezor/trezor-firmware/issues/1620

fix(core): unify Features.revision reporting with legacy

---

core/CHANGELOG.md
crypto/blake256.c
crypto/tests/test_check.c
legacy/firmware/CHANGELOG.md
tests/device_tests/test_msg_signmessage.py
tests/ui_tests/fixtures.json

Rust-related buildsystem changes were dropped.

Merge 21.06 release branch

---

common/defs/blockchain_link.json

As mentioned here: https://github.com/trezor/connect/pull/832#pullrequestreview-686298766

Cardano blockchain link definitions

---

core/embed/trezorhal/random_delays.c

style(core): trezorhal/random_delays.c

---

common/defs/blockchain_link.json
common/defs/support.json

additionally updated support in suite (trop, xrp, txrp)

fix(common): fix Ropsten key in blockchain_link

---

common/protob/messages-common.proto
core/CHANGELOG.md
core/src/apps/debug/__init__.py
core/src/trezor/messages.py
core/src/trezor/ui/components/tt/scroll.py
python/src/trezorlib/debuglink.py
python/src/trezorlib/messages.py
tests/common.py
tests/device_tests/cardano/test_sign_tx.py
tests/device_tests/test_msg_backup_device.py
tests/device_tests/test_msg_getaddress_show.py
tests/device_tests/test_msg_resetdevice_bip39_t2.py
tests/device_tests/test_msg_resetdevice_slip39_advanced.py
tests/device_tests/test_msg_resetdevice_slip39_basic.py
tests/device_tests/test_msg_signmessage.py
tests/device_tests/test_msg_signtx_replacement.py
tests/device_tests/test_reset_backup.py
tests/device_tests/test_reset_recovery_bip39.py
tests/device_tests/test_reset_recovery_slip39_advanced.py
tests/device_tests/test_reset_recovery_slip39_basic.py

partial revert of 54db2291f2335585fc14c0c5317353527fb2f452 from #1671, and adapting the test suite to cope.
Should fix https://github.com/trezor/trezor-suite/issues/3990 and remove most potential compatibility headaches.
We want this to go to the 2.4.1 release branch.

Do not send ButtonRequests for paging events

---

core/.changelog.d/1707.fixed
core/tools/keyctl-proxy

* don't use format strings in keyctl-proxy
* fix typo in keyctl-proxy help
* rename fw_or_type to image_type in keyctl-proxy to avoid confusion

keyctl-proxy fixes

---

python/src/trezorlib/cli/firmware.py

Connected with issue #1715
- `trezorctl firmware download` command no longer requires a trezor device to be connected

fix(python/trezorctl): firmware download does not require connected trezor

---

core/.changelog.d/1708.fixed
core/src/trezor/ui/components/tt/scroll.py
tests/device_tests/test_cancel.py
tests/ui_tests/fixtures.json

fix(core): properly respond to USB events while on a paginated screen

---

common/defs/fido/binance.json
core/.changelog.d/1705.fixed
core/src/apps/webauthn/knownapps.py
legacy/firmware/.changelog.d/1705.fixed

Fixes https://github.com/trezor/trezor-firmware/issues/1705.

Add new rpId to Binance's FIDO definition.

---

.github/workflows/prebuild.yml

This adds a changelog check to GitHub actions for external pull requests. I also adjusted the naming of other checks while on it. I can do it in a separate commit if that would be better. 
Resoles #1651

feat(ci): add changelog check to github actions and small improvments

---

common/protob/pb2py
core/src/trezor/_proto_messages.mako
core/src/trezor/messages.py
python/src/trezorlib/_proto_messages.mako
python/src/trezorlib/messages.py
python/src/trezorlib/protobuf.py
python/tests/test_protobuf_encoding.py
python/tests/test_protobuf_misc.py

Add support for recursive protobuf messages (CI run)

---

common/.gitrepo

subrepo:
subdir:   "common"
merged:   "8335ee632"
upstream:
origin:   "git+ssh://git@github.com/trezor/trezor-common"
branch:   "master"
commit:   "8335ee632"
git-subrepo:
version:  "0.4.1"
origin:   "https://github.com/ingydotnet/git-subrepo"
commit:   "a04d8c2"

git subrepo push common

---

core/.changelog.d/1163.fixed
core/SConscript.firmware
core/SConscript.unix
core/embed/extmod/modtrezorio/modtrezorio.c
core/src/apps/common/sdcard.py
core/src/apps/workflow_handlers.py
core/src/boot.py
core/src/storage/sd_salt.py
core/src/trezor/__init__.py
core/src/trezor/sdcard.py
core/tests/test_trezor.sdcard.py

refactor(core): disable SD card, SBU, fatfs for T1 build

---

python/CHANGELOG.md
python/src/trezorlib/cli/__init__.py

fix(python/trezorctl): fix "invalid value" of ChoiceType with default

---

ci/shell.nix

https://blog.rust-lang.org/2021/07/29/Rust-1.54.0.html

chore(nix): update rust to 1.54

---

crypto/ed25519-donna/ed25519.c
crypto/sha2.c

Fixes https://github.com/trezor/trezor-firmware/issues/1787.

Fix GCC 11.1.0 compile errors in core

---

ci/shell.nix

https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1550-2021-09-09

chore(nix): update rust to 1.55

---

core/.changelog.d/1163.fixed
core/.changelog.d/1545.changed
core/.changelog.d/1557.added
core/.changelog.d/1581.changed
core/.changelog.d/1604.added
core/.changelog.d/1683.changed.1
core/.changelog.d/1683.changed.2
core/.changelog.d/1683.fixed.4
core/.changelog.d/1683.incompatible.3
core/.changelog.d/1704.changed
core/.changelog.d/1705.fixed
core/.changelog.d/1707.fixed
core/.changelog.d/1708.fixed
core/.changelog.d/1744.changed
core/.changelog.d/1765.removed
core/.changelog.d/1767.added
core/CHANGELOG.md
legacy/firmware/.changelog.d/1705.fixed
legacy/firmware/.changelog.d/1743.changed
legacy/firmware/.changelog.d/1765.removed
legacy/firmware/.changelog.d/1767.added
legacy/firmware/CHANGELOG.md
legacy/firmware/stellar.c

We want a merge commit (see #1711) so someone will have to push this manually or override the linear-history setting.

Merge 21.09 release branch

---

poetry.lock
pyproject.toml

Fixes https://github.com/trezor/trezor-firmware/issues/1826

chore(build): demjson does not support py3 anymore -> demjson3

---

common/defs/blockchain_link.json

Updating the definitions according to https://github.com/trezor/trezor-suite/pull/3627

fix(common): cardano blockfrost definitions

---

common/defs/coins_details.json
common/defs/support.json
core/src/apps/ethereum/networks.py

Followup of #1853. cc @yura-pakhuchiy

chore(common): bring back eth:xDAI

---

core/.changelog.d/1639.changed
legacy/firmware/.changelog.d/1639.changed

Fixes #1639. The only non-cosmetic change seems to be the improved finder pattern detection. Bumped to master since there are only variable name changes since the 1.7.0 release. Code size seems to stay the same.
~~Waiting for nayuki/QR-Code-generator#127.~~

chore(vendor): update QR-code-generator

---

legacy/firmware/layout2.c

As reported by Boso, BIP86 is not handled in the GetAddress dialog

fix(legacy): add Taproot account handling to GetAddress dialog

---

crypto/tools/mktable.c

Fixes https://github.com/trezor/trezor-firmware/issues/1913

fix(crypto): fix wrong input handling in mktable

---

core/src/apps/cardano/README.md

fixes #1920 
@mroz22 please take a look

docs(core/cardano): add derivation scheme docs

---

crypto/zkp_context.c
crypto/zkp_context.h

Fixes https://github.com/trezor/trezor-firmware/issues/1534#issuecomment-974823621.

Onvej sl/zkp context fix

---

legacy/Makefile
legacy/bootloader/Makefile

just a cosmetic change to legacy makefile

sort legacy makefiles

---

crypto/monero/base58.c

Closes https://github.com/satoshilabs/trezor-firmware/issues/127.

Clarify incorrect monero/base58.c code comment

---

.github/workflows/project_automation.yml

This PR adds automatically every new pull request to the project "Pull requests" and its entry column.

ci: auto add new pull requests to the specified project and column

---

ci/shell.nix
core/embed/rust/Cargo.toml

https://blog.rust-lang.org/2021/10/21/Rust-1.56.0.html
https://blog.rust-lang.org/2021/12/02/Rust-1.57.0.html

build: update rust to 1.57

---

.gitlab-ci.yml

ci: fix hardware tests

---

build-docker.sh
ci/Dockerfile

follow-up to https://github.com/trezor/trezor-firmware/pull/1939

fix(ci): copy pyright directory in Dockerfile

---

core/embed/extmod/modtrezorio/modtrezorio-poll.h
core/embed/extmod/trezorobj.h

Followup to https://github.com/trezor/trezor-firmware/pull/1952
Let's see if the CI goes through with this added extra checks

chore(core/embed): check for negative values in trezor_get_uint

---

core/embed/rust/src/protobuf/decode.rs
core/embed/rust/src/time.rs
core/embed/rust/src/trezorhal/display.rs
core/embed/rust/src/ui/animation.rs
core/embed/rust/src/ui/component/base.rs
core/embed/rust/src/ui/component/label.rs
core/embed/rust/src/ui/component/mod.rs
core/embed/rust/src/ui/component/pad.rs
core/embed/rust/src/ui/component/text/formatted.rs
core/embed/rust/src/ui/component/text/layout.rs
core/embed/rust/src/ui/component/text/mod.rs
core/embed/rust/src/ui/component/text/paragraphs.rs
core/embed/rust/src/ui/display.rs
core/embed/rust/src/ui/geometry.rs
core/embed/rust/src/ui/layout/obj.rs
core/embed/rust/src/ui/mod.rs
core/embed/rust/src/ui/model_tt/component/confirm.rs
core/embed/rust/src/ui/model_tt/component/dialog.rs
core/embed/rust/src/ui/model_tt/component/loader.rs
core/embed/rust/src/ui/model_tt/component/mod.rs
core/embed/rust/src/ui/model_tt/component/page.rs
core/embed/rust/src/ui/model_tt/component/paginated.rs
core/embed/rust/src/ui/model_tt/component/passphrase.rs
core/embed/rust/src/ui/model_tt/layout.rs
core/embed/rust/src/ui/model_tt/theme.rs
core/src/trezor/loop.py
core/src/trezor/ui/__init__.py

Rust UI: loaders, hold to confirm, pagination for model T

---

core/embed/extmod/rustmods/modtrezorui2.c
core/embed/rust/librust.h
core/embed/rust/src/ui/component/mod.rs
core/embed/rust/src/ui/component/paginated.rs
core/embed/rust/src/ui/component/text/layout.rs
core/embed/rust/src/ui/component/text/paragraphs.rs
core/embed/rust/src/ui/geometry.rs
core/embed/rust/src/ui/model_t1/component/dialog.rs
core/embed/rust/src/ui/model_t1/component/mod.rs
core/embed/rust/src/ui/model_t1/component/page.rs
core/embed/rust/src/ui/model_t1/component/title.rs
core/embed/rust/src/ui/model_t1/layout.rs
core/embed/rust/src/ui/model_tt/component/mod.rs
core/embed/rust/src/ui/model_tt/component/page.rs
core/embed/rust/src/ui/model_tt/component/swipe.rs
core/mocks/generated/trezorui2.pyi
core/src/trezor/ui/__init__.py
core/src/trezor/ui/layouts/t1.py

Rust UI: pagination for T1

---

ci/environment.yml

Fixes the environment build after the configuration of the runner was changed to fix HWI tests.

ci: fix the environment build after changing runner config

---

.github/workflows/project_automation.yml

I missed trailing space in the name and it is not working for issues now, should be ok after we merge this.

ci: fix adding issues to project

---

common/defs/bitcoin/decred.json
common/defs/bitcoin/decred_testnet.json

Connected with https://github.com/trezor/trezor-firmware/issues/2099:
- changing decred block times

chore(common): change decred block times in defs

---

python/.changelog.d/2126.changed
python/src/trezorlib/btc.py
python/src/trezorlib/ethereum.py
python/src/trezorlib/tools.py

Finalizing PR https://github.com/trezor/trezor-firmware/pull/1225:
- just some renaming and docs changes

feat(python): extend sign_message to also sign bytes, not only string

---

core/.changelog.d/2135.changed
core/src/apps/debug/__init__.py
python/.changelog.d/2135.fixed
python/src/trezorlib/protobuf.py

fixes #2132 
we will see if it breaks something else at the same time

fix(core/debug): only wait for layout when _enabling_ watch_layout

---

tests/connect_tests/connect_tests.sh

This fixes trezor-connect tests. [proof of job here](https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/2175182101)

fix(tests): change script running connect tests

---

common/defs/misc/misc.json

* we'll have Cardano in Suite soon
* Cardano node repo has changed

fix(common): update defs for cardano

---

docs/misc/hello_world_feature_TT.md

Connected with https://github.com/trezor/trezor-firmware/issues/691:
- creating a `README` file with description of a simple `hello-world` feature implemented on `TT`
- the example lives on https://github.com/trezor/trezor-firmware/tree/grdddj/docs_hello_world_feature branch - and we may want to preserve it there, so that it is easily accessible
There may be some misconceptions or inaccuracies, some review is needed. It does not even try to explain all the details - it assumes readers can read the code and understand some basic concepts.

feat(docs): add hello-world feature on TT

---

.github/workflows/project_automation.yml

adds issues to a new beta project as requested by @hynek-jina

ci: add issues to a new project

---

ci/build.yml
ci/test.yml
docs/ci/jobs.md
storage/tests/tests/test_random.py

test(storage): increase timeout for test_random_upgrade

---

.github/workflows/project_automation.yml

@hynek-jina Should be happy 🙂 This will add newly opened issues to the beta project https://github.com/orgs/trezor/projects/60

ci: add newly opened issues to the beta project

---

.github/workflows/project_automation.yml

Removes the automation that adds issues to Backlog project

ci: remove automation for adding issues to backlog project

---

core/embed/rust/build.rs
core/embed/rust/src/micropython/list.rs
core/embed/rust/src/micropython/mod.rs
core/embed/rust/src/micropython/testutil.rs

create a MicroPython list from an iterator

List::from_iter

---

core/emu.py

Improving the quality of an important development tool

Type hints to emu.py

---

tests/conftest.py
tests/ui_tests/__init__.py
tests/ui_tests/reporting/html.py
tests/ui_tests/reporting/testreport.py

Record tests tweaks + upscale images for T1/TR

---

core/.changelog.d/2284.added
core/embed/bootloader/.changelog.d/2284.added
core/embed/bootloader/CHANGELOG.md
core/embed/bootloader/main.c
core/embed/bootloader/version.h
core/embed/extmod/modtrezorutils/modtrezorutils.c
core/embed/firmware/main.c
core/embed/trezorhal/common.h
core/embed/trezorhal/supervise.h
core/embed/trezorhal/util.s
core/mocks/generated/trezorutils.pyi
core/src/all_modules.py
core/src/apps/management/reboot_to_bootloader.py
core/src/apps/workflow_handlers.py
core/src/trezor/utils.py
python/.changelog.d/2284.added
python/src/trezorlib/cli/device.py

Jump and stay in bootloader from firmware through SVC call reverse trampoline.

Jump and stay in bootloader for TT

---

core/.changelog.d/2130.removed
core/embed/firmware/main.c

Do not initialize touch controller in firmware

---

core/embed/extmod/modtrezorcrypto/modtrezorcrypto-slip39.h

Fixes https://github.com/trezor/trezor-firmware/issues/2359.

fix(core): correct range in error message

---

crypto/bip32.c
crypto/ed25519-donna/ed25519.c
crypto/ed25519-donna/ed25519.h
crypto/tests/test_check_cardano.h

Some refactoring to reduce code duplication (24bc70bc2e9ef5fd6960f43dcc5eb2552fd23058) and dead code and confusing API (3db6dde190a4dff4bd1699b8fe33b94feff9dcef), as discussed internally.
QA not needed.

Refactor ed25519.c

---

docs/core/emulator/index.md

chore(docs): Emulator disclaimer

---

crypto/ed25519-donna/curve25519-donna-helpers.c
crypto/ed25519-donna/ed25519.c

This is continuation of https://github.com/trezor/trezor-firmware/pull/607, which fixes https://github.com/trezor/trezor-firmware/issues/571. This PR builds on top of https://github.com/trezor/trezor-firmware/pull/2361.
QA not needed.

Initialize local variables to zero in ed25519-donna

---

python/.changelog.d/2354.added
python/.changelog.d/2364.fixed
python/CHANGELOG.md
python/src/trezorlib/__init__.py
python/src/trezorlib/cli/trezorctl.py
python/tox.ini

trezorlib 0.13.3 (Click compat fix)

---

ci/deploy.yml
docs/ci/jobs.md

fixes the ci pipeline on tags other than firmware tags

ci: fix jobs on tags only

---

core/.changelog.d/2366.added
core/embed/extmod/modtrezorio/modtrezorio-poll.h
core/embed/extmod/modtrezorio/modtrezorio.c
core/embed/extmod/modtrezorutils/modtrezorutils.c
core/embed/trezorhal/usb.c
core/embed/trezorhal/usb.h
core/embed/unix/profile.c
core/embed/unix/profile.h
core/embed/unix/usb.c
core/mocks/generated/trezorio/__init__.pyi
core/mocks/generated/trezorutils.pyi
core/src/apps/homescreen/homescreen.py
core/src/trezor/utils.py

Detect whether USB data pins are connected

---

core/embed/rust/src/ui/model_tt/component/loader.rs

Position was wrong in hold to confirm situations.

Fix UI2 loader position

---

ci/test.yml

chore(ci): do not allow failure for Connect tests

---

core/.changelog.d/2453.fixed
core/src/apps/monero/get_address.py

fix(xmr): fixes #2453, incorrect address display

---

python/src/trezorlib/toif.py

Add grayscale toif conversion from images with transparent pixels - some exports from designs produce transparent PNGs, this simplifies toif generation a bit

Add grayscale toif conversion from images with transparent pixels

---

ci/shell.nix
core/.changelog.d/2213.fixed.1
core/tests/run_tests_device_emu_monero.sh
core/tests/test_apps.monero.crypto.py
crypto/monero/base58.c

Fixes sending tx to an integrated address as described in #2213
@matejcik

fix(xmr): fix tx sending to an integrated address

---

core/embed/rust/build.rs
core/embed/rust/src/trezorhal/mod.rs
core/embed/rust/src/trezorhal/storage.rs
core/embed/rust/trezorhal.h

Cherry-picked storage interface from #2214
Closes #2533

Expose storage interface to rust

---

core/Makefile

by adding target to rust tests invoked from makefile

Fix rust tests with ASAN

---

core/embed/rust/src/ui/model_tt/component/keyboard/pin.rs

Using pads + child components to get rid of text flickering when button is pressed when pin is empty.

Optimize pin keyboard rendering for TT UI2

---

core/src/trezor/wire/__init__.py
core/src/trezor/wire/codec_v1.py

taken out from #2335 
very likely fixes the current click-test problems.

fix(core/debug): separate buffer for debuglink to prevent BufferLock deadlocks

---

ci/test-hw.yml
ci/test.yml
docs/ci/jobs.md
docs/developers/libraries.md
docs/hardware/model-one/firmware-format.md
docs/legacy/index.md
docs/misc/hello_world_feature_TT.md
docs/misc/update-wipes.md
docs/python/show-text.md
docs/tests/device-tests.md
python/README.md
tools/generate_ci_docs.py

Based on comments https://www.notion.so/satoshilabs/Broken-Links-docs-FIRMWARE-7fd9e24c7c7a422db16eef6a859de0b4

chore(docs): Clean up dead links

---

tests/conftest.py

this resolves a problem when each xdist runner would clear the directory and stomp over one another

fix(tests): fix instability of multicore runners

---

python/.changelog.d/2289.added
python/.changelog.d/2414.added
python/.changelog.d/2433.removed
python/.changelog.d/2445.added
python/.changelog.d/2517.added
python/.changelog.d/2542.fixed
python/.changelog.d/2547.added
python/.changelog.d/2561.added
python/.changelog.d/2576.incompatible
python/.changelog.d/noissue.removed
python/CHANGELOG.md
python/MANIFEST.in
python/docs/OPTIONS.rst
python/src/trezorlib/__init__.py
python/src/trezorlib/_internal/firmware_headers.py

No major changes, but I need to push out a version with the firmware parsing refactors

trezorlib 0.13.4 release

---

core/embed/rust/src/ui/model_tr/component/bip39.rs
core/embed/rust/src/ui/model_tr/component/button.rs
core/embed/rust/src/ui/model_tr/component/choice.rs
core/embed/rust/src/ui/model_tr/component/choice_item.rs
core/embed/rust/src/ui/model_tr/component/mod.rs
core/embed/rust/src/ui/model_tr/component/passphrase.rs
core/embed/rust/src/ui/model_tr/component/pin.rs
core/embed/rust/src/ui/model_tr/component/simple_choice.rs

- making ChoicePage more flexible by making it accept implementation of Choice trait instead of ChoiceItem
- fixes positioning of middle button with arms -> x offset was used like with outline, but not needed -> button was somewhat uncentered

make ChoicePage more flexible, fix middle button with arms position

---

core/embed/rust/src/ui/display/mod.rs

fixes success animation bugs (i16 overflow after changing coord type and comparison instead of shift)

fix success animation

---

core/tools/headertool.py
python/src/trezorlib/_internal/firmware_headers.py
python/src/trezorlib/firmware/consts.py
python/src/trezorlib/firmware/vendor.py

should fix both problems from #2616
@TychoVrahe please confirm

Headertool fixes

---

common/defs/blockchain_link.json
common/defs/misc/misc.json

https://github.com/trezor/trezor-suite/pull/7262

chore: Cardano preview testnet

---

ci/hardware_tests/t1_hw_test.sh
ci/test-hw.yml

ci: use new firmware filenames

---

core/embed/rust/src/ui/display/loader/circular.rs
core/embed/rust/src/ui/display/loader/mod.rs
core/embed/rust/src/ui/display/loader/rectangular.rs
core/embed/rust/src/ui/display/loader/starry.rs
core/embed/rust/src/ui/display/mod.rs
core/embed/rust/src/ui/model_tr/constant.rs

Implements loaders from design.
Didn't do any integration into T2B1 branch so far, but this should work anywhere where loaders are called.
closes #2622

implement loaders for T2B1

---

.gitlab-ci.yml

ci: conditionally use cached-nix-shell in env setup

---

core/src/trezor/ui/layouts/tt_v2/reset.py

Fixes https://github.com/trezor/trezor-firmware/issues/2717

fix(core): remove the possibility of AssertionError in select_word

---

python/.changelog.d/2801.fixed
python/.changelog.d/2832.fixed
python/src/trezorlib/cli/firmware.py
python/src/trezorlib/client.py
python/src/trezorlib/models.py
python/src/trezorlib/transport/bridge.py
python/src/trezorlib/transport/udp.py
python/tools/pybridge.py

It's a script that emulates Trezor Bridge with trezorlib. The main advantage is that it dumps protobufs when it can, and you can edit it to add message filters.
The main disadvantage is that it's nowhere near as robust as the real thing, ofc.
---
fixes #2801 
---
minor type checking improvements

trezorlib improvements

---

.gitlab-ci.yml
ci/Dockerfile
ci/build.yml
ci/shell.nix
ci/test-hw.yml
docs/ci/jobs.md
tests/ui_tests/fixtures.json

Revert cached-nix-shell

---

core/embed/bootloader/version.h
core/embed/firmware/version.h

Bump firmware and bootloader versions

---

core/embed/bootloader/version.h
core/embed/firmware/version.h
tools/bump-version.py

Bump core version to 2.6.1, core/bootloader to 2.1.1

---

python/.changelog.d/2904.fixed
python/src/trezorlib/device.py

fix(cli): don't try to initialize device after wipe in bootloader

---

core/.changelog.d/1049.added
core/.changelog.d/15.added
core/.changelog.d/1749.added
core/.changelog.d/1901.added
core/.changelog.d/1922.changed
core/.changelog.d/2151.added
core/.changelog.d/2152.added
core/.changelog.d/2205.changed
core/.changelog.d/2525.changed
core/.changelog.d/2587.changed
core/.changelog.d/2595.changed
core/.changelog.d/2611.changed
core/.changelog.d/2623.added
core/.changelog.d/2651.changed
core/.changelog.d/2682.added
core/.changelog.d/2692.added
core/.changelog.d/2692.changed
core/.changelog.d/2746.changed
core/.changelog.d/2784.fixed
core/.changelog.d/2818.added
core/.changelog.d/2834.changed
core/.changelog.d/2841.added
core/.changelog.d/2899.fixed
core/.changelog.d/450.added
core/.changelog.d/noissue.security
core/CHANGELOG.md

Please merge & push using CLI so that the merge commit is preserved. Previous release: #2887

Merge 23.04 release branch

---

core/embed/rust/src/ui/model_tt/component/homescreen/render.rs

style(core/rust): fix indent

---

ci/shell.nix
ci/test-hw.yml
ci/test.yml
docs/ci/jobs.md
tools/version.sh

Depends on trezor/micropython#10.

ci: fix darwin build and monero tests

---

core/src/trezor/ui/layouts/tt_v2/homescreen.py

@grdddj please check if this solves your problem

fix(core): do not handle click signal in non-debug builds (fixes #3026)

---

core/embed/extmod/modtrezorutils/modtrezorutils-meminfo.h
core/embed/unix/common.c

build: emulator darwin fixes

---

core/embed/prodtest/main.c

closes #2756 
closes #2885 
builds on https://github.com/trezor/trezor-firmware/pull/2961

prodtest for T2B1

---

common/defs/coins_details.json
common/defs/wallets.json

chore(common): add kmd wallet

---

core/site_scons/boards/trezor_1.py
core/site_scons/boards/trezor_r_v3.py
core/site_scons/boards/trezor_r_v4.py
core/site_scons/boards/trezor_r_v6.py
core/site_scons/boards/trezor_t.py
tests/test_python_support.py

Fixes https://github.com/trezor/trezor-firmware/issues/3093
- testing `core/site_scons` python files for compatibility with older python versions
- fixing the incompatibility with 3.8

SConscript python version fix

---

ci/shell.nix

I keep installing gdb again and again but it's useless on CI so no reason to have it in the shell by default. If this PR is merged then it and other tools can be accessed with `nix-shell --arg devTools true --run "poetry shell"`.
Not sure if I'm not overdoing it with the nrf*things license, maybe they don't have lawyers searching github repos ...

chore(nix): add developer tools to shell.nix

---

core/SConscript.unix
core/embed/extmod/modtrezorutils/modtrezorutils.c

Since #3104 the emulator only shows black screen.

Fix backlight on frozen emulator

---

tests/device_tests/test_busy_state.py

fix(tests): mark flaky busy_expiry test

---

core/site_scons/boards/discovery.py

Failing job: https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/4663850613
See also: #3108

build(core): fix DISC1 boardloader build

---

core/site_scons/boards/discovery.py

style(core): discovery.py

---

common/models.json

feat(common): add model and color information (fixes #3160)

---

python/.changelog.d/+06ca7357.fixed
python/.changelog.d/+bdb3ea1b.changed

docs(python): add missing changelog entries

---

core/embed/boardloader/.changelog.d/2955.fixed
core/embed/boardloader/.changelog.d/2989.added
core/embed/boardloader/.changelog.d/3222.fixed
core/embed/boardloader/CHANGELOG.md
core/embed/boardloader/version.h
tools/bump-version.py

generate a new boardloader release because of the delays thing

Boardloader 2.1.1

---

core/embed/bootloader/.changelog.d/+14e1ae91.added
core/embed/bootloader/.changelog.d/+84ec609d.changed
core/embed/bootloader/.changelog.d/+95c27be5.added
core/embed/bootloader/.changelog.d/2955.fixed
core/embed/bootloader/.changelog.d/2989.added
core/embed/bootloader/.changelog.d/3222.changed
core/embed/bootloader/CHANGELOG.md
core/embed/bootloader/version.h

Generate changelog and bump versions so that we can start merging new BL features.

Bootloader 2.1.2

---

ci/build.yml
core/SConscript.bootloader_emu
docs/ci/jobs.md

ci: build bootloader emulators

---

core/embed/bootloader/.changelog.d/3122.changed
core/embed/bootloader/.changelog.d/3205.added
core/embed/bootloader/CHANGELOG.md
core/embed/bootloader/version.h

chore(core): generate changelog, bump bootloader version after release

---

core/embed/trezorhal/optiga.h
core/embed/trezorhal/optiga/optiga.c
core/embed/trezorhal/optiga/optiga_commands.c
core/embed/trezorhal/optiga_commands.h
core/embed/trezorhal/unix/optiga.c
storage/storage.c

Cherry-picks from release/23.09.

Sync with release/23.09

---

ci/shell.nix

ci(nix): use ST fork of OpenOCD

---

core/embed/prodtest/.towncrier.template.md
core/embed/prodtest/CHANGELOG.md
core/embed/prodtest/CHANGELOG.unreleased
core/embed/prodtest/towncrier.toml
core/embed/prodtest/version.h
tools/generate-changelog.py

Prodtest versioning

---

poetry.lock
pyproject.toml
python/.changelog.d/3045.fixed
python/requirements.txt
python/setup.cfg
python/src/trezorlib/_rlp.py
python/src/trezorlib/cli/ethereum.py
python/tests/test_rlp.py

supersedes https://github.com/trezor/trezor-firmware/pull/3046
not tested, please test before merging

fix(python): drop simple-rlp dependency and use internal copy

---

ci/build.yml
ci/check_changelog.sh
ci/check_release_commit_messages.sh
ci/posttest.yml
ci/prebuild.yml
create_monorepo.py
docs/misc/contributing.md

chore: update branch name to main where its used

---

core/embed/prodtest/main.c

fix failing optiga communication in prodtest

---

legacy/debug_signing/sign_firmware_v3_signature.py
python/.changelog.d/+13d8ef2d.changed
python/src/trezorlib/_internal/firmware_headers.py
python/src/trezorlib/cli/__init__.py
python/src/trezorlib/cli/firmware.py
python/src/trezorlib/client.py
python/src/trezorlib/firmware/consts.py
python/src/trezorlib/firmware/legacy.py
python/src/trezorlib/firmware/models.py
python/src/trezorlib/models.py

mainly concerned with the firmware command, plus some internal rearrangements
supersedes https://github.com/trezor/trezor-firmware/pull/3347

Trezorlib features for TS3

---

core/embed/firmware/version.h

chore(core): bump version to 2.6.5

---

.github/workflows/core.yml
.github/workflows/legacy.yml

ci: update table with links to html reports

---

core/embed/rust/src/ui/component/text/paragraphs.rs

This PR resolves #3450 by implementing a small change that reduces the size of the `AddressDetails` struct from **3308** bytes to **2028** bytes. 
To achieve this, I've introduced `TextLayoutProxy`, which acts as a proxy for the heavy `TextLayout` structure stored within the `visible` field of the `Paragraphs` component. The `TextLayoutProxy` dynamically constructs the `TextLayout` structure as needed.
**In implementing `TextLayoutProxy`, it leverages `ParagraphSource.at()` to retrieve referenced paragraphs and their layouts. This decision involves some tradeoff in terms of speed.**

refactor(core): shrink size of Paragraphs struct

---

common/protob/messages-management.proto
core/src/apps/base.py
core/src/trezor/messages.py
python/src/trezorlib/messages.py
rust/trezor-client/src/protos/generated/messages_management.rs
tests/device_tests/test_language.py

Also returns False when blob is newer than firmware. Comparison includes build version (as in major.minor.patch.build) which we don't report in Features, not completely sure if that's right.
Fixes #3543.

Report mismatched translation blob in Features

---

core/embed/firmware/version.h

chore(core): bump version to 2.6.6

---

core/embed/firmware/version.h
core/translations/cs.json
core/translations/de.json
core/translations/en.json
core/translations/es.json
core/translations/fr.json

Release will be 2.7.0, which makes main 2.7.1.

chore(core): bump version to 2.7.1

---

.github/workflows/core.yml
tools/check-bitcoin-only

Fixes failing GitLab CI. See also #3582.

test(core): ignore {0} in bitcoin-only firmware

---

docs/core/build/emulator.md
docs/core/emulator/index.md

[no changelog]
This is a minor change in Emulator docs (and also in docs for emulator build) to guide most people to trezor-user-env. Based on Slack conversation.

docs: hint usage of trezor-user-env

---

core/Makefile

fix flashing f4 firmware via debugger
broken since #3548

fix flashing f4 firmware via debugger

---

core/src/apps/common/request_pin.py
core/src/apps/webauthn/fido2.py
core/src/boot.py

This PR fixes issue #2540. The refactor applies to apps/webauthn/fido2.py and apps/common/request_pin.py. 
I couldn't locate the other two files (apps/homescreen/homescreen.py,  trezor/ui/loader.py)mentioned in the issue. They might have been renamed or deleted.

Fix utime operations

---

core/embed/prodtest/README.md

fix prodtest SBU command documentation

fix prodtest SBU command documentation

---

core/embed/trezorhal/stm32u5/haptic/drv2625/drv2625.c

uninitialized struct causing mayhem

fix haptic driver initialization

---

core/embed/rust/src/ui/display/font.rs
core/embed/rust/src/ui/model_mercury/component/instructions.rs
core/embed/rust/src/ui/model_mercury/component/mod.rs
core/embed/rust/src/ui/shape/text.rs

This PR adds only the instruction component definition. The actual usage will be added in another PR.

T3T1 Instructions component

---

core/embed/rust/src/ui/geometry.rs
core/embed/rust/src/ui/shape/corner_highlight.rs
core/embed/rust/src/ui/shape/mod.rs

Adds a new shape which serves to highlight information within a rectangle.

T3T1 corner shape

---

core/translations/signatures.json

chore(core): sign translations for 2.7.0, including Czech blob

---

core/embed/trezorhal/stm32f4/displays/st7789v.c
core/embed/trezorhal/stm32u5/sdcard.c

set proper GPIO speeds for T3T1

set proper GPIO speeds for T3T1

---

core/embed/boardloader/main.c
core/embed/bootloader/messages.c
core/embed/firmware/bl_check.c
core/embed/lib/translations.c
core/embed/trezorhal/flash.h
core/embed/trezorhal/stm32f4/flash.c
core/embed/trezorhal/stm32u5/flash.c
core/embed/trezorhal/stm32u5/platform.h
core/embed/trezorhal/unix/flash.c
legacy/flash.c
storage/flash_area.c
storage/flash_area.h

Introducing flash_area_write_data function, which aims to simplify writing arbitrarily large data to flash.

introduce flash_area_write_data

---

core/embed/trezorhal/stm32u5/i2c.c

communication with optiga was sometimes losing data

slowdown i2c on u5 to 200kHz

---

core/embed/models/model_T3T1.h
python/src/trezorlib/cli/firmware.py
python/src/trezorlib/models.py

fill T3T1 model full name

---

core/embed/trezorhal/boards/Clocks_T3T1_revE.md
core/embed/trezorhal/boards/trezor_t3t1_revE.h
core/embed/trezorhal/stm32f4/usbd_conf.c
core/embed/trezorhal/stm32u5/platform.c

switching to crystall-less operation on T3T1.

feat(core): use HSI as PLL source on T3T1

---

.github/workflows/core.yml
.github/workflows/legacy.yml

Fixes #3676
URLs:
* core: https://data.trezor.io/dev/firmware/emu-latest/trezor-emu-core-INTERNALMODEL-COINS where
* legacy: https://data.trezor.io/dev/firmware/emu-latest/trezor-COINS.elf
Where INTERNALMODEL is e.g. T2T1 and COINS is either `universal` or `btconly`.

ci: actions: upload emulator binaries to data.trezor.io

---

docs/core/build/embedded.md
docs/core/build/emulator.md

docs: minor fix of build emu

---

poetry.lock

relevant to https://github.com/trezor/trezor-firmware/issues/3687

build(deps): bump PyYAML from 6.0.0 to 6.0.1

---

core/embed/boardloader/.changelog.d/3205.added
core/embed/boardloader/.changelog.d/3370.added
core/embed/boardloader/CHANGELOG.md
core/embed/boardloader/version.h

release boardloader

---

common/protob/messages-management.proto
core/embed/bootloader/messages.c
core/embed/bootloader/protob/messages.pb.h
core/embed/bootloader/protob/messages.proto
core/embed/extmod/modtrezorutils/modtrezorutils.c
core/embed/lib/unit_variant.c
core/embed/lib/unit_variant.h
core/mocks/generated/trezorutils.pyi
core/src/apps/base.py
core/src/trezor/messages.py
core/src/trezor/utils.py
python/src/trezorlib/messages.py
rust/trezor-client/src/protos/generated/messages_management.rs

See https://satoshilabs.slack.com/archives/CL1D61PQF/p1709894058788049.

Add unit packaging variant field to Features

---

core/tests/unittest.py

chore(core): add colors to unittest prints

---

core/embed/trezorhal/optiga/optiga_transport.c
core/embed/trezorhal/stm32f4/random_delays.c
core/embed/trezorhal/stm32f4/usb.c

Some improvements as discussed in https://github.com/trezor/trezor-firmware/issues/3739. It would be good to get this in before signing the new prodtest version. However, it is untested! At the very least we should merge https://github.com/trezor/trezor-firmware/commit/25840aa0839a13e533ee8099cf192912be6a2681 and https://github.com/trezor/trezor-firmware/commit/443dc1f77d1f7cdd57099349d5b21a329ad4d828, which I'd think are no-brainers.
Based on subsequent discussion IRL, I am not sure if I understood correctly your [comment](https://github.com/trezor/trezor-firmware/issues/3739#issuecomment-2083677347) @TychoVrahe. I implemented https://github.com/trezor/trezor-firmware/commit/041dbe406d09ade0ee3ee7273f32596cdaa38c14 to work around that.

Optiga communication improvements

---

core/embed/prodtest/main.c
core/embed/trezorhal/common.h
core/embed/trezorhal/stm32f4/common.c
core/embed/trezorhal/stm32u5/common.c
core/embed/trezorhal/stm32u5/mpu.c

fix prodtest WIPE on STM32U5

---

core/embed/bootloader/.changelog.d/3770.changed
core/embed/bootloader/CHANGELOG.md
core/embed/bootloader/version.h
core/embed/prodtest/.changelog.d/+version.added
core/embed/prodtest/.changelog.d/3770.changed
core/embed/prodtest/CHANGELOG.md
core/embed/prodtest/version.h

**DO NOT MERGE** via github, I'll fast-forward manually to keep the tags
includes the latest required changes
tag at e8c65b9f2435c5b46b4e209e4db412dee57df613
@TychoVrahe please check reproducible build:
```
./build-docker.sh --skip-legacy --skip-normal --models T3T1 --targets bootloader,prodtest core/bl2.1.6
```
results:
```
Built from commit e8c65b9f2435c5b46b4e209e4db412dee57df613
Fingerprints:
2d6c50d88a09d3d60160155fdfa9c589fa461d04b96b4b8412ac1bea2fd7861f build/core-T3T1-bitcoinonly/bootloader/bootloader.bin
8fd0e95fb60235236763cc87e152874d71e637260154f1451817f207e3bbcc27 build/core-T3T1-bitcoinonly/prodtest/prodtest.bin
```
sha256sums:
```
f8e323323bdda6516bde8acf41bca117619bed204ab60f01e0248a18f5bf4b38  build/core-T3T1-bitcoinonly/bootloader/bootloader.bin …
```

Bootloader 2.1.6, prodtest 0.2.6

---

core/src/apps/cardano/seed.py

docs(core): fix reference to SLIP-23 in cardano node derivation

---

.github/actions/ui-comment/action.yml
.github/actions/ui-report/action.yml
.github/workflows/common.yml
.github/workflows/core.yml
.github/workflows/legacy.yml
.github/workflows/prebuild.yml

ci: actions: run prebuild & common nightly, bump dependencies

---

.github/workflows/prebuild.yml

Fixes failing scheduled workflow: https://github.com/trezor/trezor-firmware/actions/runs/9024775075/attempts/1

ci: actions: no block-fixup on scheduled pipelines

---

core/embed/rust/src/trezorhal/bitblt.rs
core/embed/rust/src/ui/model_tr/layout.rs
core/embed/rust/src/ui/model_tt/component/loader.rs
core/embed/rust/src/ui/model_tt/layout.rs
core/embed/rust/src/ui/shape/display/mod.rs

Rust style chores

---

core/embed/rust/src/ui/model_mercury/component/number_input_slider.rs

add value info to brightness dialog in mercury

add value info to brightness dialog in mercury

---

core/embed/rust/src/ui/model_mercury/component/status_screen.rs

adds status animation to mercury UI

T3T1 status animation

---

.github/workflows/core.yml
core/Makefile
core/embed/rust/Cargo.toml
core/embed/rust/build.rs
core/embed/rust/src/micropython/runtime.rs
core/embed/rust/src/ui/model_mercury/component/page.rs
core/embed/rust/src/ui/model_mercury/layout.rs
core/embed/rust/src/ui/shape/display/mod.rs

pointed at T3T1 branch but doesn't block its merging

T3T1 Rust tests

---

core/embed/rust/src/time.rs
core/embed/rust/src/ui/model_mercury/component/vertical_menu.rs

changed the quiz enter animation to fit the design better

quiz enter animation

---

core/embed/rust/librust_qstr.h
core/embed/rust/src/ui/model_mercury/component/frame.rs
core/embed/rust/src/ui/model_mercury/flow/confirm_action.rs
core/embed/rust/src/ui/model_mercury/layout.rs
core/embed/rust/src/ui/model_tr/layout.rs
core/embed/rust/src/ui/model_tt/layout.rs
core/mocks/generated/trezorui2.pyi
core/src/apps/base.py
core/src/apps/common/passphrase.py
core/src/apps/management/apply_settings.py
core/src/apps/management/authenticate_device.py
core/src/apps/management/change_language.py
core/src/apps/management/change_wipe_code.py
core/src/apps/management/get_next_u2f_counter.py
core/src/apps/management/reboot_to_bootloader.py
core/src/apps/management/sd_protect.py
core/src/apps/management/set_u2f_counter.py
core/src/apps/misc/cipher_key_value.py
core/src/apps/misc/get_entropy.py
core/src/apps/monero/layout.py
core/src/apps/stellar/layout.py
core/src/trezor/ui/layouts/mercury/__init__.py
core/src/trezor/ui/layouts/mercury/fido.py
core/src/trezor/ui/layouts/tr/__init__.py
core/src/trezor/ui/layouts/tt/__init__.py
tests/click_tests/common.py
tests/click_tests/test_autolock.py
tests/click_tests/test_pin.py

Depends on #3887 and #3898 but setting `main` as base to see UI diff.

T3T1 UI: more tap/hold prompts

---

core/embed/rust/src/ui/model_mercury/flow/confirm_action.rs
core/embed/rust/src/ui/model_mercury/layout.rs

fix(core/ui): T3T1: ethereum signtx hold

---

core/src/apps/management/backup_device.py
core/src/apps/management/recovery_device/homescreen.py
core/src/storage/device.py
python/.changelog.d/3868.added
python/.changelog.d/3868.incompatible
python/src/trezorlib/cli/device.py
tests/click_tests/test_repeated_backup.py
tests/common.py
tests/device_tests/test_repeated_backup.py
tests/input_flows.py

chore(core): add ability to set up a device with SLIP39 "single"

---

core/src/apps/bitcoin/sign_tx/approvers.py
core/tests/test_apps.bitcoin.approver.py
legacy/firmware/signing.c
tests/device_tests/bitcoin/payment_req.py

Skips `mask_public_key` and `signature` checks when they're received as empty from client.
Legacy fw changes were difficult to test because of [this issue](https://github.com/trezor/trezor-firmware/issues/3892), but the same changes applied to 1.12.1 worked fine.
More rationale in Notion: https://www.notion.so/satoshilabs/Request-signature-checks-removal-bc5f3174ca9543e6ae31b6bc08087e76

Request signature optional

---

core/embed/prodtest/.changelog.d/3932.added
core/embed/prodtest/.changelog.d/3932.fixed
core/embed/prodtest/CHANGELOG.md
core/embed/prodtest/version.h

Prodtest 0.2.7

---

core/embed/firmware/version.h

chore(core): bump version to 2.7.3

---

core/embed/rust/src/ui/model_mercury/component/homescreen.rs

fix lockscreen Not connected label hiding

---

core/embed/firmware/version.h

chore(core): bump version to 2.8.1

---

core/CHANGELOG.T2B1.md
core/CHANGELOG.T2T1.md
core/CHANGELOG.T3T1.md
core/CHANGELOG.md

docs(core): fix 2.8.0 release date

---

.github/workflows/core.yml
core/towncrier.toml
tools/generate-changelog.py
tools/towncrier.toml

- build with production bootloader in CI
- T3T1 changelog in `generate-changelogs.py`

T3T1 related tooling chores

---

core/translations/signatures.json

chore(core): add signature for 2.8.0 translation blobs

---

core/.changelog.d/3035.fixed
core/embed/extmod/modtrezorio/ff.c
core/embed/extmod/modtrezorio/ff.h
core/embed/extmod/modtrezorio/modtrezorio-fatfs.h
core/mocks/generated/trezorio/fatfs.pyi
core/src/apps/common/sdcard.py

feat(core): add progress indicator when formatting SD cards

---

core/embed/rust/src/ui/model_mercury/flow/confirm_action.rs

Expanding on work done in #4024 , this PR extracts non-generic code from heavily used `new_confirm_action_uni` function and thus saves about 4.5kB of flash space.

refactor confirm action

---

common/defs/misc/misc.json
common/defs/support.json

* unsupport NEM mosaics for Trezor Safe models -- NEM support was removed but the supportinfo still claims that the individual mosaics (aka tokens) are supported. This has no effect on anything except downstream consumers of our support.json
* drop wallets and links from misc.json -- we are no longer a source of truth for these values, they have been ported into the definitions repo https://github.com/trezor/definitions/commit/cc7c7b838ca05d92ec3beef2127fa552d7c64fa8#diff-773344d02ca5932c3e6b140788e2e766c5187000230493ed3a8186335b5182b2

Common defs cleanup

---

legacy/bootloader/usb.c

Resolves https://github.com/satoshilabs/trezor-firmware/issues/188.

Avoid overflow in readprotobufint()

---

core/embed/extmod/modtrezorcrypto/modtrezorcrypto-crc.h
core/mocks/generated/trezorcrypto/crc.pyi

style(core): fix indentation in crc32 documentation

---

core/tests/test_trezor.crypto.base32.py

[no changelog]
Unification of the spacing of noqa comments.

test(core): unify noqa style

---

core/embed/boardloader/CHANGELOG.md
core/embed/boardloader/version.h
core/embed/bootloader/CHANGELOG.md
core/embed/bootloader/version.h
core/embed/prodtest/.changelog.d/3900.fixed
core/embed/prodtest/CHANGELOG.md
core/embed/prodtest/version.h

add changelogs and bump versions for boardloader, bootloader, prodtest, for T3B1

T3B1 version release

---

core/src/trezor/ui/layouts/mercury/__init__.py

fix(core/ui): fix ethereum cancel flow

---

core/.changelog.d/4063.changed
core/embed/rust/src/ui/model_mercury/component/share_words.rs
core/embed/rust/src/ui/model_mercury/component/swipe_content.rs
core/embed/rust/src/ui/util.rs

Two stage animation instead of "continuous rolling"

improve share words swiping animation

---

core/embed/rust/src/ui/display/mod.rs
core/embed/rust/src/ui/model_mercury/flow/set_brightness.rs
core/embed/rust/src/ui/model_mercury/mod.rs
core/embed/rust/src/ui/model_mercury/theme/backlight.rs
core/embed/rust/src/ui/model_tt/component/page.rs
core/embed/rust/src/ui/model_tt/component/set_brightness.rs
core/embed/rust/src/ui/model_tt/component/simple_page.rs
core/embed/rust/src/ui/model_tt/component/swipe.rs
core/embed/rust/src/ui/model_tt/layout.rs
core/embed/rust/src/ui/model_tt/mod.rs
core/embed/rust/src/ui/model_tt/theme/backlight.rs
core/embed/rust/src/ui/ui_features.rs

Refs #3969 
See this: https://github.com/trezor/trezor-firmware/pull/3991#discussion_r1664224156

feat(core): make brightness an u8

---

core/CHANGELOG.T2T1.md
core/CHANGELOG.md

docs(core): fix 2.8.0 changelog

---

core/embed/rust/src/ui/model_tr/component/share_words.rs
core/embed/rust/src/ui/shape/cache/drawing_cache.rs
core/embed/rust/src/ui/shape/display/mod.rs
core/embed/rust/src/ui/shape/mod.rs
core/embed/rust/src/ui/shape/progressive_render.rs
core/embed/rust/src/ui/shape/render.rs
core/site_scons/models/T3B1/trezor_t3b1_revB.py

fixes compilation of T2B1 / model_tr UI with new rendering.
fixes also some conditionals based on xframebuffer feature.

fix T2B1 compilation with new rendering

---

core/embed/trezorhal/stm32u5/consumption_mask.c

tune consumption mask protection on T3B1

---

core/embed/rust/src/ui/model_mercury/component/button.rs
core/embed/rust/src/ui/model_mercury/component/keyboard/passphrase.rs

chore(core): remove unused mercury ButtonContent

---

rust/trezor-client/src/client/common.rs
rust/trezor-client/src/client/ethereum.rs
rust/trezor-client/src/flows/sign_tx.rs
rust/trezor-client/src/lib.rs
rust/trezor-client/src/transport/protocol.rs
rust/trezor-client/src/transport/udp.rs
rust/trezor-client/src/transport/webusb.rs
rust/trezor-client/src/utils.rs

chore(rust/trezor-client): run clippy

---

core/embed/trezorhal/stm32f4/displays/st7789v.c
core/embed/trezorhal/stm32f4/xdisplay/st-7789/display_driver.c
core/embed/trezorhal/stm32f4/xdisplay/st-7789/display_panel.c
core/embed/trezorhal/stm32f4/xdisplay/st-7789/display_panel.h
core/embed/trezorhal/stm32f4/xdisplay/st-7789/panels/lx154a2482.c
core/embed/trezorhal/stm32f4/xdisplay/st-7789/panels/lx154a2482.h
core/embed/trezorhal/stm32u5/displays/panels/lx154a2482.c
core/embed/trezorhal/stm32u5/displays/panels/lx154a2482.h
core/site_scons/models/T3T1/trezor_t3t1_revE.py
core/site_scons/models/T3T1/trezor_t3t1_v4.py

According to instructions from display manufacturer.

update display initialization sequence on T3T1

---

docs/ci/jobs.md

generate pipeline docs

---

.github/workflows/bot-common-sync.yml

ci: fix trezor-common sync action

---

core/.changelog.d/4167.fixed
core/embed/rust/src/ui/model_mercury/flow/confirm_output.rs
core/embed/rust/src/ui/model_mercury/flow/util.rs

fix(core): tweak swipes in ETH staking flow

---

core/embed/bootloader/version.h
core/embed/firmware/version.h
core/embed/prodtest/version.h
core/translations/cs.json
core/translations/de.json
core/translations/en.json
core/translations/es.json
core/translations/fr.json
core/translations/it.json
core/translations/pt.json
core/translations/signatures.json
core/translations/tr.json

Also bump bootloader, prodtest.

core: bump version to 2.8.4

---

core/SConscript.bootloader_ci
core/embed/bootloader_ci/main.c
core/embed/bootloader_ci/version_check.c
core/embed/bootloader_ci/version_check.h

fix bootloader_ci production build

---

core/SConscript.unix
core/embed/extmod/modtrezorcrypto/modtrezorcrypto-tropic.h

This will fail in CI because libtropic submodule (expected in vendor/) cannot be cloned (this repo is currently private). Please clone libtropic submodule manually into vendor/ to check out if ping is fixed in emulator. @ibz

fixup! feat(core): TROPIC01 ping

---

core/embed/bootloader/CHANGELOG.md
core/embed/bootloader/version.h

Bootloader 2.1.9

---

core/README.md

docs: add Safe 3 and Safe 5 in documentation

---

core/embed/rust/src/ui/flow/swipe.rs

chore(core/embed): remove unused import

---

core/embed/lib/image_hash_conf.h
core/embed/trezorhal/hash_processor.h
core/embed/trezorhal/stm32f4/syscall_dispatch.c
core/embed/trezorhal/stm32f4/syscall_stubs.c
core/embed/trezorhal/stm32u5/hash_processor.c

chore(core/embed): fixup sha256 context type name

---

core/embed/prodtest/.changelog.d/4313.fixed
core/embed/trezorhal/stm32u5/mpu.c

fix OTP write access

---

core/embed/firmware/version.h
core/embed/prodtest/version.h

core, prodtest: bump version

---

tests/github.py

fix(tests): make update_fixtures.py fetch legacy fixtures

---

core/embed/trezorhal/stm32f4/syscall_dispatch.c

This PR fixes broken custom haptic effect used in loaders (fixes #4316)

fix(core): fix haptic custom effect in loaders

---

core/embed/firmware/version.h
core/embed/prodtest/version.h
core/translations/cs.json
core/translations/de.json
core/translations/en.json
core/translations/es.json
core/translations/fr.json
core/translations/it.json
core/translations/pt.json
core/translations/signatures.json
core/translations/tr.json

chore(core): bump core, prodtest versions

---

core/Makefile
core/translations/cli.py

Also:
* do not expand `##Safe3` when running `cli.py gen`
* make `cli.py` executable

translations: check if language file version matches firmware

---

core/Makefile

fix sizecheck on U5 models

---

core/embed/projects/prodtest/.changelog.d/4310.fixed
core/embed/projects/prodtest/.changelog.d/4313.fixed

Not sure how this happened, probably during the release branch merge?

delete processed changelog entries for prodtest

---

core/embed/projects/prodtest/.changelog.d/4405.fixed
core/embed/projects/prodtest/README.md
core/embed/projects/prodtest/main.c

Fixes reading the version. Also some discrepancies in readme are fixed.

fix BOOTLOADER VERSION command in prodtest

---

core/embed/models/T3W1/boards/trezor_t3w1_revA.h

use SMPS on T3W1

---

core/embed/io/haptic/drv2625/drv2625.c

On T3W1, we use reset pin for haptic driver. Turns out, we need to bring the IC out of reset before attempting communication with it....

fix haptic driver with reset pin initialization

---

shell.nix

ci(nix): macOS: fix `--args devTools true`

---

core/.changelog.d/4421.fixed
core/embed/rust/src/ui/model_mercury/flow/confirm_action.rs

Don't swipe left if there is no menu

---

python/src/trezorlib/toif.py

fix toif generation from grayscale

---

core/embed/rust/src/ui/component/cached_jpeg.rs
core/embed/rust/src/ui/model_mercury/component/homescreen.rs
core/embed/rust/src/ui/model_mercury/ui_firmware.rs
core/embed/rust/src/ui/shape/bitmap.rs
core/embed/rust/src/ui/shape/canvas/mono8.rs
core/embed/rust/src/ui/shape/canvas/rgb565.rs
core/embed/rust/src/ui/shape/canvas/rgba8888.rs
core/embed/rust/src/ui/shape/utils/imagebuf.rs
core/src/trezor/ui/layouts/homescreen.py

fixes #4424 
This is a patch over an underlying issue that causes the previous homescreen to stay in memory. It should be removed when we discover the root cause.

Fix RSOD "no image buf"

---

core/embed/rust/src/ui/model_tr/component/title.rs

fix(core/ui): fix a bug causing marquee on model TR to not start

---

core/embed/projects/prodtest/.changelog.d/4407.changed
core/embed/projects/prodtest/README.md
core/embed/projects/prodtest/main.c

As requested by testers.
fixes #4407

change resolution of TOUCH_POWER command parameter to milliseconds

---

tests/device_tests/bitcoin/test_getaddress.py

This pull request fixes a minor issues in multisig test founded by @karliatto.

Fix minor issues in multisig tests

---

common/tools/requirements.txt

Adding `requirements.txt` to `common/tools/` so we can create python environment.
I wanted to document it here but I found out that it was already documented, just the file `requirements.txt` was not there https://github.com/trezor/trezor-firmware/blob/main/common/tools/README.md?plain=1#L9

fix(common): add requirements.txt to tools

---

Makefile
core/.changelog.d/3324.fixed
core/.changelog.d/3692.fixed
core/.changelog.d/4402.fixed
core/.changelog.d/4462.added
core/.changelog.d/4491.fixed
core/embed/projects/bootloader_ci/.changelog.d/1049.added
core/embed/projects/bootloader_ci/.changelog.d/2243.added
core/embed/projects/bootloader_ci/.changelog.d/2414.added
core/embed/projects/bootloader_ci/.changelog.d/2623.added
core/embed/projects/bootloader_ci/.changelog.d/3370.added
core/embed/projects/prodtest/.changelog.d/4405.fixed
docs/misc/changelog.md
legacy/firmware/.changelog.d/15.added
legacy/firmware/.changelog.d/2675.removed
legacy/firmware/.changelog.d/3216.removed
legacy/firmware/.changelog.d/4324.added
legacy/intermediate_fw/.changelog.d/163.fixed
python/.changelog.d/3442.removed.1
python/.changelog.d/3728.added
python/.changelog.d/4041.added
python/.changelog.d/4076.added
python/.changelog.d/4464.deprecated
tools/generate-changelog.py

docs: require changelog fragments to end with a period

---

core/embed/rust/build.rs
core/embed/rust/src/ui/display/font.rs
core/embed/rust/src/ui/layout_bolt/component/share_words.rs

fix(core): fix a few "unused" warnings

---

core/embed/projects/prodtest/main.c

Fix displayed batch number in prodtest

---

core/embed/projects/firmware/version.h
core/embed/projects/prodtest/version.h
core/translations/cs.json
core/translations/de.json
core/translations/en.json
core/translations/es.json
core/translations/fr.json
core/translations/it.json
core/translations/pt.json
core/translations/signatures.json
core/translations/tr.json

bump core to 2.8.8, prodtest to 0.2.13

---

core/translations/cli.py
core/translations/crowdin.py
python/src/trezorlib/_internal/translations.py

Following https://github.com/trezor/trezor-firmware/pull/4495#pullrequestreview-2565362115.
[no changelog]

feat(python): check that translations are using correct layout names

---

legacy/firmware/fsm.c
tests/ui_tests/fixtures.json

fix(legacy): fix a minor typo in a warning message

---

docs/core/index.md

docs(core): update `index.md`

---

core/embed/io/touch/ft6x36/ft6x36.c

This PR fixes the issue with repeated initialization and deinitialization of the touch driver on T3W1.
The T3W1 touch controller (FT3168) behaves slightly differently from the FT6X36 used on T2T1/T3T1. It switches from active mode to monitor mode after a period of inactivity (currently ~12s). While in monitor mode, the controller fails to process I2C transactions - it does not ACK written data, and read data is either zeroed or contains garbage. It seems, this switching behavior cannot be disabled.
This issue affects operations such as repeated initialization and deinitialization sequences, reading the touch controller version, or configuring the touch controller while it is in monitor mode.
Based on observations, the controller can be "woken up" with a single I2C transaction, after which …

fix(core): wake up touch controller from monitor mode

---

core/embed/rust/src/ui/layout/obj.rs

fix(core): correct a small comment typo

---

core/translations/it.json
core/translations/signatures.json

- shortening the title ensures that instruction fits on the screen

fix(core): fix italian copy for word quiz

---

core/tools/codegen/gen_font.py

Remove C font generation

---

.github/workflows/core-hw.yml

It would help to find the relevant device logs for a specific test (especially when the log files are large).
Tested locally with `pytest -vs tests/device_tests/test_msg_ping.py`:
<details>
<summary> Device-side logs </summary>
```
$ tio --timestamp --no-autoconnect /dev/ttyACM0 
[17:16:13.321] tio v2.5
[17:16:13.321] Press ctrl-t q to quit
[17:16:13.322] Connected
[17:16:16.408] 937232000 trezor.wire.message_handler DEBUG 0 receive: <Cancel>
[17:16:16.412] 937235000 trezor.loop DEBUG spawn new task: <generator object 'with_context' at 20017470>
[17:16:16.414] 937238000 trezor.workflow DEBUG start: <generator object 'with_context' at 20017470>
[17:16:16.417] 937241000 trezor.loop DEBUG close spawned task: <generator object 'homescreen' at 20015f80>
[17:16:16.419] 937244000 trezor.ui DEBUG …
```

ci(core): add timestamp to device debug logs

---

python/.changelog.d/3993.added
python/src/trezorlib/cli/firmware.py
python/src/trezorlib/client.py
python/src/trezorlib/exceptions.py
python/src/trezorlib/firmware/__init__.py
python/src/trezorlib/firmware/core.py
python/src/trezorlib/firmware/legacy.py
python/src/trezorlib/firmware/models.py
python/src/trezorlib/firmware/util.py
python/src/trezorlib/firmware/vendor.py
python/src/trezorlib/models.py
python/tools/pybridge.py

Add support for unrecognized Trezor models (fixes #3993)

---

core/embed/upymod/modtrezorutils/modtrezorutils-meminfo.h
core/mocks/generated/trezorutils.pyi
core/src/trezor/utils.py

Fix a few comments

---

.github/workflows/core.yml
core/embed/rust/build.rs

Fix rust-analyzer

---

.github/workflows/core.yml

Fix a small typo in `.github/workflows/core.yml`

---

core/embed/projects/prodtest/README.md
core/embed/projects/prodtest/cmd/prodtest_touch.c
core/embed/rust/rust_ui_prodtest.h
core/embed/rust/src/ui/api/prodtest_c.rs
core/embed/rust/src/ui/layout/simplified.rs
core/embed/rust/src/ui/layout_bolt/prodtest/mod.rs
core/embed/rust/src/ui/layout_caesar/prodtest/mod.rs
core/embed/rust/src/ui/ui_prodtest.rs

Implements simple drawing canvas where user can draw with finger or pen.

add touch-draw command to prodtest

---

.github/workflows/core.yml
.github/workflows/prebuild.yml

ci: build T2B1 firmware for release branches

---

python/src/trezorlib/client.py
python/src/trezorlib/debuglink.py
python/src/trezorlib/transport/session.py
tests/device_tests/test_protection_levels.py

[wip] sessions in trezorlib

---

common/defs/blockchain_link.json

Added 4 backend endpoints to each EVM.
Relates to this Issue in Suite repo - https://github.com/trezor/trezor-suite/issues/16886
Relates to this Pull Request in Suite repo - https://github.com/trezor/trezor-suite/pull/17336

feat(blockchain-link): added 4 backend endpoints for each EVM

---

core/embed/rust/src/ui/layout_delizia/component/swipe_content.rs

so that it covers the interval from the Attach event until timer running out.
Without this change, it is possible to slip in a TouchStart event before the animation timer has had a chance to start, and lose the matching TouchEnd.
This fixes the problem where a user wildly tapping on the screen can start a hold-to-confirm and have it run without holding.

fix(core/rust): correctly extend SwipeAttach animation duration

---

core/embed/rust/src/ui/layout_delizia/component/frame.rs
core/embed/rust/src/ui/layout_delizia/component/number_input_slider.rs
core/embed/rust/src/ui/layout_delizia/flow/set_brightness.rs

Fix delizia set brightness setting

---

.github/workflows/core-hw.yml

ci(core): enable STORAGE_INSECURE_TESTING_MODE for HW device tests

---

core/emu.py
core/src/boot.py
docs/legacy/index.md
legacy/firmware/trezor.c

https://satoshilabs.slack.com/archives/GN09MB5FT/p1738931104017779

Add emulator warnings

---

core/embed/rust/src/ui/layout_eckhart/component/button.rs
core/embed/rust/src/ui/layout_eckhart/firmware/action_bar.rs
core/embed/rust/src/ui/layout_eckhart/firmware/text_screen.rs
core/embed/rust/src/ui/layout_eckhart/ui_firmware.rs

Eckhart UI - action bar improvements

---

.gitignore

Make Cursor editor a 1st class citizen of `trezor-firmware` by ignoring it.

chore: gitignore Cursor config

---

core/embed/projects/firmware/version.h
core/translations/cs.json
core/translations/de.json
core/translations/en.json
core/translations/es.json
core/translations/fr.json
core/translations/it.json
core/translations/pt.json
core/translations/signatures.json
core/translations/tr.json

bump core to 2.8.10

---

core/src/apps/cardano/layout.py

Otherwise, we may run out of heap due to recursion, e.g.:
```
[12:23:10.171] Large alloc: size=1604 flags=0 result=0x0
[12:23:10.171] 110068000 trezor.loop ERROR exception:
[12:23:10.172] Traceback (most recent call last):
[12:23:10.173]   File "trezor/loop.py", line 162, in _step
[12:23:10.174]   File "trezor/wire/context.py", line 127, in with_context
[12:23:10.175]   File "apps/cardano/seed.py", line 188, in wrapper
[12:23:10.175]   File "apps/cardano/get_native_script_hash.py", line 23, in get_native_script_hash
[12:23:10.177]   File "apps/cardano/layout.py", line 152, in show_native_script
[12:23:10.178]   File "apps/cardano/layout.py", line 146, in show_native_script
[12:23:10.179]   File "trezor/ui/layouts/caesar/__init__.py", line 746, in confirm_properties
[12:23:10.180] …
```

fix(core): scope Cardano confirmation to allow GC

---

.github/workflows/release-emu.yml

ci: fix release emu job

---

python/src/trezorlib/debuglink.py
python/src/trezorlib/transport/__init__.py
python/src/trezorlib/transport/bridge.py
python/src/trezorlib/transport/hid.py
python/src/trezorlib/transport/protocol.py
python/src/trezorlib/transport/udp.py
python/src/trezorlib/transport/webusb.py
tests/conftest.py

Based on [the first commit](https://github.com/trezor/trezor-firmware/pull/4655/commits/7eb4297280b352ea7f800a60456ba7bc82c25e22) of https://github.com/trezor/trezor-firmware/pull/4655.
Also, add a timeout in order to prevent tests from getting stuck in case there is an USB packet loss.

Ignore unrelated responses

---

tests/ui_tests/reporting/testreport.js

Add green to UI diff

---

.github/workflows/legacy.yml

ci: add timeouts for legacy.yml

---

core/.changelog.d/4827.fixed
core/src/apps/management/change_language.py
core/src/apps/management/reboot_to_bootloader.py

fix(core): allow firmware upgrade even if language change failed

---

poetry.lock
pyproject.toml
python/src/trezorlib/transport/protocol.py
setup.cfg
tests/conftest.py
tests/device_tests/test_bip32_speed.py
tests/device_tests/test_busy_state.py

`pytest-retry` collects retry attempts' log and handles `PYTEST_TIMEOUT` during retries:
```
==================================================== the following tests were retried ====================================================
test_ping failed on attempt 1! Retrying!
Traceback (most recent call last):
File "/home/rzeyde/src/trezor-firmware/python/src/trezorlib/transport/udp.py", line 150, in read_chunk
chunk = self.socket.recv(64)
TimeoutError: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/rzeyde/src/trezor-firmware/.venv/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
result: TResult | None = func()
trezorlib.transport.Timeout: Timeout reading UDP packet (5.0s)
test_ping failed …
```

chore(python): replace `pytest-rerunfailures` with `pytest-retry`

---

core/SConscript.firmware
core/SConscript.unix

feat(core): increase MicroPython bytecode optimizations

---

core/embed/rust/src/ui/layout_eckhart/component_msg_obj.rs
core/embed/rust/src/ui/layout_eckhart/firmware/brightness_screen.rs
core/embed/rust/src/ui/layout_eckhart/firmware/mod.rs

- Do not confirm brightness value by releasing the finger, but by clicking on the `x` button
- Change the slider color when holding it

Fix behavior of set brightness screen

---

tests/conftest.py

Should help with [the following kind of hardware tests' errors](https://github.com/trezor/trezor-firmware/actions/runs/14207984894/job/39809710980) (the retry mechanism seem to get stuck).
It's easier to review with `--ignore-space-change`:
```diff
diff --git a/tests/conftest.py b/tests/conftest.py
index be4363d56..83e6512c9 100644
--- a/tests/conftest.py
+++ b/tests/conftest.py
@@ -282,6 +282,7 @@ def client(
_raw_client.reset_debug_features()
_raw_client.open()
+    try:
try:
_raw_client.sync_responses()
_raw_client.init_device()
@@ -348,7 +349,7 @@ def client(
with ui_tests.screen_recording(_raw_client, request):
yield _raw_client
-
+    finally:
_raw_client.close()
```

test(core): close `_raw_client` in case `client()` fixture fails

---

core/embed/projects/bootloader_ci/messages.c

Long-term neglected bootloader CI - only minimal change needed to make the firmware update run on TS5.

fix firmware upload in bootloader_ci

---

core/embed/io/nfc/st25r3916b/card_emulation.c
core/embed/io/nfc/st25r3916b/ndef.c
core/embed/io/nfc/st25r3916b/nfc.c

fixed stack smashing error on nfc deinit. also nfc files are only for kernel_mode.

fix NFC deinitialization

---

.github/workflows/core-hw.yml
.github/workflows/core.yml
.github/workflows/legacy.yml
ci/test.yml
docs/ci/jobs.md
tests/conftest.py

```
$ pytest tests/device_tests/binance/test_get_address.py tests/device_tests/bitcoin/test_firo.py tests/device_tests/bitcoin/test_op_return.py -v
========================================================================================== test session starts ===========================================================================================
platform linux -- Python 3.10.10, pytest-8.3.2, pluggy-1.5.0 -- /home/rzeyde/src/trezor-firmware-2/.venv/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/rzeyde/src/trezor-firmware-2/.hypothesis/examples')
Using --random-order-bucket=module
Using --random-order-seed=583888
rootdir: /home/rzeyde/src/trezor-firmware-2
configfile: setup.cfg
plugins: xdist-2.5.0, forked-1.4.0, …
```

test(core): automatically skip altcoin tests

---

core/embed/projects/bootloader/CHANGELOG.md
core/embed/projects/bootloader_ci/CHANGELOG.md
legacy/intermediate_fw/CHANGELOG.md

[before](https://github.com/trezor/trezor-firmware/blob/592590cf66a9b62dfeee7e4d2afb6e01005e5b2c/core/embed/projects/bootloader/CHANGELOG.md) vs [after](https://github.com/trezor/trezor-firmware/blob/ddafd45ae1ebf5b4cf435dbc34b7f114b1f7c294/core/embed/projects/bootloader/CHANGELOG.md)

docs: fix broken changelog links

---

core/site_scons/models/T3W1/__init__.py

build(core): default T3W1 to revision C

---

.github/workflows/core.yml
core/embed/upymod/modtrezorutils/modtrezorutils.c
core/mocks/generated/trezorutils.pyi

fix(core): check QSTR run-time allocations only for frozen debug builds

---

core/embed/rust/build.rs

Eckhart: fix T3W1 rust tests

---

.gitignore
tests/conftest.py

Don't stop tests in case of transient communication failure

---

core/embed/rust/librust.h
core/embed/rust/librust_qstr.h
core/embed/rust/src/micropython/coveragedata.rs
core/embed/rust/src/micropython/mod.rs
core/embed/rust/src/trezorhal/ble/micropython.rs
core/embed/rust/src/ui/layout_caesar/prodtest/mod.rs
core/embed/upymod/rustmods.c
core/mocks/generated/coveragedata.pyi
core/src/prof/__main__.py

It is needed for https://github.com/trezor/trezor-firmware/pull/4935.

feat(core): don't use heap for storing coverage data

---

.github/workflows/bot-common-sync.yml
.github/workflows/bot-project-automation.yml

ci: replace user tokens with github app integration

---

.github/workflows/bot-common-sync.yml

ci: fix trezor-common sync env variable name

---

.github/workflows/bot-common-sync.yml

ci: fix generate token job

---

core/SConscript.prodtest
core/embed/projects/prodtest/README.md
core/embed/projects/prodtest/cmd/prodtest_fuel_gauge.c
core/embed/sys/powerctl/fuel_gauge/battery_data_jyhpfl333838.h
core/embed/sys/powerctl/fuel_gauge/battery_model.c
core/embed/sys/powerctl/fuel_gauge/battery_model.h
core/embed/sys/powerctl/fuel_gauge/fuel_gauge.c
core/embed/sys/powerctl/fuel_gauge/fuel_gauge.h
core/site_scons/models/T3W1/trezor_t3w1_revB.py
core/site_scons/models/T3W1/trezor_t3w1_revC.py

This PR introduce a fuel gauge library as a core of the battery state-of-charge estimator. 
**fuel_gauge** library implements an Extended kalman filter which on certain noise, and covariance configuration runs an optimal SoC estimate on battery voltage, current and temperature input data.   
**battery_model** library are the automatically generated files from the battery characterization tool, which consist of used battery characteristics such as ocv curves and internal resistance evolution in temperatures.
This library do not work standalone to the rest of the system and has to be delicately incorporated into the power manager in the near future. However, the basic function is covered in fuel_gauge prodtest as a part of this PR.

Fuel gauge

---

.github/workflows/core-hw.yml

It was renamed in https://github.com/tio/tio/releases/tag/v3.0.

fix(tools): use `tio --no-reconnect` instead of `--no-autoconnect`

---

core/embed/rust/src/translations/obj.rs
core/embed/rust/src/translations/translated_string.rs

style(core): simplify Rust translation conversions

---

core/src/trezor/loop.py

Otherwise, GC will keep the last task alive.

fix(core): clear `loop.this_task` before restart

---

core/embed/io/usb/stm32/usb_class_vcp.c

Fixes inconsistency of used interface.

fix VCP polling

---

core/embed/projects/bootloader/workflow/wf_ble_pairing_request.c
core/embed/projects/bootloader/workflow/wf_firmware_update.c
core/embed/projects/bootloader/workflow/wf_host_control.c
core/embed/rust/src/trezorhal/sysevent.rs

These werent properly rebased.

fix sysevents polling deadlines

---

core/embed/io/nrf/stm32u5/nrf.c

fixes issue with stoping and restarting communication with NRF - if there is an spi request signal on calling start, prepare the transaction. And don't prepare transaction in callback if communication is stopped.
Additionally, nrf_register_listener needs to be called after initialized flag is set.

fix nrf start/stop, service listener registration

---

common/protob/messages-management.proto
core/src/apps/base.py
core/src/trezor/enums/Capability.py
core/src/trezor/enums/__init__.py
python/src/trezorlib/messages.py
rust/trezor-client/src/protos/generated/messages_management.rs
tests/device_tests/test_basic.py

Thinking maybe there should be one for LED too?

core: add T3W1 Capabilities to Features

---

.github/workflows/core.yml
core/Makefile
core/embed/rust/src/micropython/coveragedata.rs
core/src/prof/__main__.py
core/tools/coverage-annotate.py
core/tools/coverage-collect.py

Unfortunately, it cannot be visualized by `coverage`, so we'll probably need another tool.
Also enabled coverage report for T3B1.

feat(core): count per-line hits during profiling

---

core/src/trezor/ui/layouts/eckhart/__init__.py
tests/device_tests/test_msg_applysettings.py
tests/input_flows.py

This PR fixes `Eckhart UI` text failures caused by the latest rebase of `ui-eckhart` onto `main`

Fix failing Eckhart tests

---

core/Makefile

add bin to hex conversion to Makefile

---

core/embed/projects/prodtest/.changelog.d/5050.changed
core/embed/projects/prodtest/README.md
core/embed/projects/prodtest/cmd/prodtest_prodtest.c

report build version in prodtest intro and version

---

core/embed/rust/src/ui/layout_eckhart/firmware/device_menu_screen.rs

Follow-up for https://github.com/trezor/trezor-firmware/pull/4959.
Not urgent - can definitely wait after https://github.com/trezor/trezor-firmware/pull/4775 is merged.

refactor(core): unify `menu` and `about` Eckhart screens into an enum

---

core/src/apps/ethereum/sign_tx.py
core/src/trezor/ui/layouts/bolt/__init__.py
core/src/trezor/ui/layouts/caesar/__init__.py

Copilot got assigned to my PR #4958 after I merged, but he/she found a some [issues](https://github.com/trezor/trezor-firmware/pull/4958#pullrequestreview-2857128668).

Address later comments on ETH approve flow

---

core/src/trezor/ui/layouts/eckhart/__init__.py

Eckhart UI: ETH approve

---

.github/workflows/release-emu.yml

is borked for core: https://github.com/trezor/trezor-firmware/actions/runs/15256358634:
```
Error when evaluating 'strategy' for job 'core_emu_arm'. .github/workflows/release-emu.yml (Line: 94, Col: 16): Error from function 'fromJson': Unexpected symbol: 'T2B1'. Located at line 1 position 1 within JSON., .github/workflows/release-emu.yml (Line: 94, Col: 16): Unexpected value ''
Error when evaluating 'strategy' for job 'core_emu'. .github/workflows/release-emu.yml (Line: 44, Col: 16): Error from function 'fromJson': Unexpected symbol: 'T2B1'. Located at line 1 position 1 within JSON., .github/workflows/release-emu.yml (Line: 44, Col: 16): Unexpected value ''
```
Also added inputs for `workflow_dispatch` so we can more easily test it.

ci: fix model handling in release-emu.yml

---

core/embed/projects/bootloader/wire/wire_iface_ble.c

Fixes BLE error message in bootloader.

fix BLE communication error message

---

core/embed/sec/secret/inc/sec/secret.h
core/embed/sec/secret/stm32f4/secret.c
core/embed/sec/secret/stm32u5/secret.c
core/embed/sec/secret/unix/secret.c
core/embed/sys/mpu/stm32f4/mpu.c
core/embed/upymod/modtrezorutils/modtrezorutils.c

Otherwise, it fails during HW CI for T2B1:
https://github.com/trezor/trezor-firmware/actions/runs/15287736774/job/43001358093
https://github.com/trezor/trezor-firmware/actions/runs/15287736774/job/43001358104

fix(core): fix firmware build with `DISABLE_OPTIGA=1`

---

core/SConscript.prodtest_emu
core/embed/sys/power_manager/unix/power_manager.c

fix prodtest emulator build for T3W1

---

core/embed/rust/src/ui/component/text/layout.rs
core/embed/rust/src/ui/flow/swipe.rs
core/embed/rust/src/ui/layout/obj.rs

Fix warnings in device build

---

core/embed/rust/librust_qstr.h
core/embed/rust/src/translations/generated/translated_string.rs
core/embed/rust/src/ui/layout_eckhart/flow/confirm_firmware_update.rs
core/embed/rust/src/ui/layout_eckhart/flow/mod.rs
core/embed/rust/src/ui/layout_eckhart/ui_firmware.rs
core/mocks/trezortranslate_keys.pyi
core/translations/en.json
core/translations/order.json
core/translations/signatures.json

This PR implements `confirm_firmware_update` trait function for Eckhart UI according to latest [FIgma](https://www.figma.com/design/Dkl7W5PLqpr3TnXJ5hbnfd/--Future-Prod---Safe-7?node-id=6374-5410) design.

Firmware update for Eckhart UI 

---

core/embed/rust/src/ui/layout_eckhart/bootloader/connect.rs
core/embed/rust/src/ui/layout_eckhart/bootloader/welcome_screen.rs

wrong/old feature name was used

eckhart - fix menu button not showing on some screens in bootloader

---

core/translations/cs.json
core/translations/de.json
core/translations/es.json
core/translations/fr.json
core/translations/it.json
core/translations/pt.json
core/translations/signatures.json

Following https://github.com/trezor/trezor-firmware/pull/4987, we can now map the new fonts for Eckhart. Fixes https://github.com/trezor/trezor-firmware/issues/4859.

Eckhart UI: map foreign glyphs

---

core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs
core/embed/rust/src/ui/layout_eckhart/flow/confirm_value_intro.rs
core/embed/rust/src/ui/layout_eckhart/theme/firmware.rs
tests/click_tests/test_lock.py

Eckhart UI: remove hold to lock

---

common/protob/messages-debug.proto
common/protob/messages.proto
core/embed/upymod/modtrezorutils/modtrezorutils.c
core/mocks/generated/trezorutils.pyi
core/src/apps/debug/__init__.py
core/src/trezor/enums/MessageType.py
core/src/trezor/enums/__init__.py
core/src/trezor/messages.py
core/src/trezor/utils.py
legacy/firmware/protob/Makefile
python/src/trezorlib/debuglink.py
python/src/trezorlib/messages.py
rust/trezor-client/src/messages/generated.rs
rust/trezor-client/src/protos/generated/messages.rs
rust/trezor-client/src/protos/generated/messages_debug.rs
tests/conftest.py
tests/device_tests/test_debuglink.py

Also, add GC leak check for every test setup/teardown.
It will also run during HW device tests (after it was removed in https://github.com/trezor/trezor-firmware/pull/4993).

test(core): collect GC statistics via new debuglink RPC

---

common/protob/messages-common.proto
core/src/trezor/enums/FailureType.py
core/src/trezor/enums/__init__.py
legacy/firmware/fsm.c
python/src/trezorlib/messages.py
rust/trezor-client/src/protos/generated/messages_common.rs

Add FailureTypes specific for THP. 
Could be merged before the rest of THP to help with Suite development.

Add THP FailureTypes

---

core/embed/sys/mpu/stm32u5/mpu.c

This PR fixes a firmware crash that occurred while writing to the OTP memory (in the firmware and prodtest on all U5 models). The issue was introduced with the secure monitor.
Writing to the OTP memory requires access to the non-secure OTP area as well as to the non-secure FLASH controller registers that were disabled by introducing the secure monitor.

fix(core): fix write to otp memory (U5 only)

---

core/embed/rust/src/ui/layout_eckhart/firmware/keyboard/passphrase.rs
core/embed/rust/src/ui/layout_eckhart/firmware/keyboard/pin.rs

chore(core/eckhart): extend pin/pp touch area

---

core/embed/rust/src/ui/layout_bolt/mod.rs
core/embed/rust/src/ui/layout_eckhart/mod.rs

fix(core): correct a small typo in `screen_update()`

---

core/src/trezor/log.py

It has been removed by mistake in #5056.

fix(core): re-add logging level filtering

---

core/.changelog.d/5114.fixed
core/src/apps/common/passphrase.py

[Screencast from 2025-05-30 07-16-42.webm](https://github.com/user-attachments/assets/b7464381-56af-4606-9827-5834d31ecf2d)

feat(core): delay passphrase on host prompt

---

ci/hardware_tests/device/device.py
ci/hardware_tests/tpmb/model/base.scad
common/protob/messages-cardano.proto
core/embed/rust/librust_qstr.h
core/embed/rust/src/translations/generated/translated_string.rs
core/embed/rust/src/ui/layout_bolt/component/coinjoin_progress.rs
core/embed/rust/src/ui/layout_delizia/component/coinjoin_progress.rs
core/embed/rust/src/ui/layout_eckhart/firmware/progress_screen.rs
core/mocks/trezortranslate_keys.pyi
core/tools/translations/rules.json
core/translations/cs.json
core/translations/de.json
core/translations/en.json
core/translations/es.json
core/translations/fr.json
core/translations/it.json
core/translations/pt.json
core/translations/signatures.json
python/tools/mem_read.py

Also, remove duplicated `coinjoin__title_do_not_disconnect` string.

chore(core): fix "trezor" -> "Trezor"

---

core/tools/trezor_core_tools/combine_firmware.py

Combine tool got broken after some changes in layout parser due to secure monitor introduction. 
This PR fixes it.

Fix combine tool script

---

.github/workflows/core.yml

Following https://github.com/trezor/trezor-firmware/pull/5248#issuecomment-3003548144.

ci(core): build T2B1 firmware on pull requests

---

tests/input_flows.py

chore(core): remove unneeded `debug.read_layout()`

---

core/.changelog.d/5189.changed.1
core/embed/rust/src/ui/layout_caesar/component/flow.rs
core/embed/rust/src/ui/layout_caesar/component/input_methods/simple_choice.rs
core/embed/rust/src/ui/layout_caesar/ui_firmware.rs
core/src/trezor/ui/layouts/caesar/__init__.py
python/src/trezorlib/debuglink.py
tests/device_tests/cardano/test_sign_tx.py
tests/input_flows.py

feat(core): use multi-item menus for Solana staking

---

python/docs/OPTIONS.rst

Update python docs - OPTIONS.rst

---

core/embed/rust/src/ui/api/firmware_micropython.rs
core/embed/rust/src/ui/layout_bolt/ui_firmware.rs
core/embed/rust/src/ui/layout_caesar/ui_firmware.rs
core/embed/rust/src/ui/layout_delizia/flow/confirm_action.rs
core/embed/rust/src/ui/layout_delizia/ui_firmware.rs
core/embed/rust/src/ui/layout_eckhart/ui_firmware.rs
core/embed/rust/src/ui/ui_firmware.rs
core/mocks/generated/trezorui_api.pyi
core/src/trezor/ui/layouts/delizia/__init__.py
core/src/trezor/ui/layouts/menu.py

Use external menu on `confirm_action`

---

core/embed/rust/src/ui/api/firmware_micropython.rs
core/embed/rust/src/ui/layout_bolt/ui_firmware.rs
core/embed/rust/src/ui/layout_caesar/ui_firmware.rs
core/embed/rust/src/ui/layout_delizia/flow/util.rs
core/embed/rust/src/ui/layout_delizia/ui_firmware.rs
core/embed/rust/src/ui/layout_eckhart/ui_firmware.rs
core/embed/rust/src/ui/ui_firmware.rs
core/mocks/generated/trezorui_api.pyi

Allow external menu on `confirm_value`

---

core/embed/rust/src/ui/layout_eckhart/firmware/keyboard/slip39.rs
tests/click_tests/test_recovery.py

fix(core/eckhart): fix slip39 overflow bug

---

tests/persistence_tests/test_shamir_persistence.py

chore(core): remove obsolete comment

---

core/embed/rust/src/ui/layout_eckhart/component/button.rs
core/embed/rust/src/ui/layout_eckhart/theme/bootloader.rs
core/embed/rust/src/ui/layout_eckhart/theme/firmware.rs
core/embed/rust/src/ui/layout_eckhart/theme/mod.rs

Eckhart UI: remove unused button code

---

core/embed/projects/bootloader/.changelog.d/5345.changed
core/embed/projects/bootloader/workflow/wf_unlock_bootloader.c
core/embed/rust/src/ui/layout_caesar/bootloader/mod.rs
core/embed/rust/src/ui/layout_delizia/bootloader/mod.rs
core/embed/rust/src/ui/layout_eckhart/ui_bootloader.rs

erase storage on bootloader unlock

---

core/embed/sys/task/stm32/systask.c

This small PR fixes a recently introduced issue in the NMI handler that affects the upcoming T3W1 boardloader and may also impact existing bootloaders on STM32U5 devices. **Specifically, it stops treating a Flash ECC double-error NMI as a fatal condition.**
On the STM32U5 an NMI can be raised under a few conditions, one of which is detection of a Flash ECC double-error. Although double-errors are normally extremely rare, they can occur if a Flash write- or erase-operation is interrupted by a power loss or reset.
If the boardloader or bootloader treats this NMI as a fatal error, it can brick the device when they attempt to read from a Flash region that was incompletely written and now contains ECC errors.

fix(core): fix nmi handling

---

core/embed/projects/prodtest/README.md
core/embed/projects/prodtest/cmd/prodtest_rtc.c
core/embed/sys/time/inc/sys/rtc.h
core/embed/sys/time/stm32u5/rtc.c

this PR adds commands for setting time in prodtest

rtc setup in prodtest

---

core/embed/rust/src/ui/layout_eckhart/ui_bootloader.rs

not entirely by figma design but usable

improve Eckhart boot warning screen

---

core/embed/rust/src/ui/api/firmware_micropython.rs
core/embed/rust/src/ui/layout_delizia/component/vertical_menu.rs
core/embed/rust/src/ui/layout_delizia/ui_firmware.rs
core/mocks/generated/trezorui_api.pyi
core/src/trezor/ui/layouts/delizia/__init__.py
python/src/trezorlib/debuglink.py
tests/input_flows.py

~Rebased over https://github.com/trezor/trezor-firmware/pull/5362.~
Currently enabled for `confirm_value()` layouts.

Allow pagination of Delizia menus in UI tests

---

.github/workflows/core-hw.yml
.github/workflows/core.yml
core/SConstruct

make fw build less verbose

---

common/tests/fixtures/solana/sign_tx.associated_token_account_program.json
core/.changelog.d/5369.fixed
core/src/apps/solana/layout.py
core/src/apps/solana/predefined_transaction.py
core/src/apps/solana/sign_tx.py
core/src/apps/solana/transaction/__init__.py

Tested on T3T1 emulator:
```
$ SOLTX=8001000408c112d4b0dde7b7f53618eff7359c776a101ff2850c92ab324f4328c4470954cc38546bf3f814d4ef7ec18c4a3404661763497407dfd0bc045abd5dde7df045434e9cf63c972db76a2ac2d73d98c4662604767974257bab071e97655db50dbee6668b310266f4553f407cd2b86f8e083fe7b0594cd979d83217731aaf663d946f559156f1a25c6d134f2af7e60a9a0d347ec79156636462d5d1ad26f135348f698c97258f4e2489f1bb3d1029148e0d830b5a1399daff1084048e7bd8dbe9f8590306466fe5211732ffecadba72c39be7bc8ce5bbc5f7126b2c439b3a400000000af1c3432188ca3a635135a13a18951acebd5a9f603da8785e0818628a45a377287604aca52c63edddede01bb21aaee0635717080c3895c7f408c7bb8f0a697d04060005024974060006000903fe91030000000000050600010021202a0101043a0002012521030404042a2a05202b0002162a2a261924251d1e1b1c1f1a231816172a0e2210120c1128090b0d0f080a22271817011413152 …
```

fix(core): fix Solana rent calculation

---

tests/input_flows.py

Found when debugging THP tests.

test(core): remove extra input flow confirmations in Eckhart

---

tests/ui_tests/reporting/common.py

Following https://github.com/trezor/trezor-firmware/issues/5422#issuecomment-3119917644.

test(core): add missing script to main diff report

---

core/embed/rust/src/ui/layout_eckhart/theme/bootloader.rs

- now that we have more space
[no changelog]

Eckhart UI: use large QR code in bld wireless setup

---

core/src/trezor/ui/layouts/delizia/__init__.py
core/src/trezor/ui/layouts/eckhart/__init__.py
core/src/trezor/ui/layouts/menu.py

Related to the discussion here: https://github.com/trezor/trezor-firmware/pull/5349#issuecomment-3069192726

Improve menu interaction typing

---

core/embed/projects/prodtest/cmd/prodtest_power_manager.c
core/embed/rtl/cli.c
core/embed/rust/src/ui/layout_eckhart/prodtest/welcome.rs
core/embed/sys/power_manager/stm32u5/power_manager.c
core/embed/sys/power_manager/stm32u5/power_manager_internal.h
core/embed/sys/power_manager/stm32u5/power_monitoring.c

prodtest fixes

---

python/src/trezorlib/transport/bridge.py

The protocol detection never worked (length field missing in header) - leave it to a higher layer. Seems to work fine now with trezor-user-env where bridge is used by Suite automated tests. cc @szymonlesisz

fix(python): bridge THP detection

---

core/embed/rust/src/ui/layout_eckhart/flow/confirm_set_new_pin.rs
tests/device_tests/test_msg_changepin_t2.py

Eckhart wrong pin flow return message

---

core/src/apps/bitcoin/authorize_coinjoin.py
core/src/apps/bitcoin/get_public_key.py
core/src/apps/common/keychain.py
core/src/trezor/ui/__init__.py

Otherwise, the traceback object is growing without being cleared.
Following https://github.com/trezor/trezor-firmware/issues/5472#issuecomment-3174382038.

fix(core): don't reuse singleton exception objects

---

core/embed/rust/src/ui/layout_eckhart/bootloader/bld_header.rs
core/embed/rust/src/ui/layout_eckhart/ui_bootloader.rs

chore(core): remove unusued code from BldHeader

---

core/.changelog.d/5532.fixed
core/embed/io/haptic/drv2625/drv2625.c

fix(core/io): Incomplete disabling of haptics

---

core/embed/projects/bootloader/main.c
core/embed/rust/rust_ui_bootloader.h
core/embed/rust/src/ui/api/bootloader_c.rs
core/embed/rust/src/ui/layout_eckhart/ui_bootloader.rs
core/embed/rust/src/ui/ui_bootloader.rs

boot sequence tuning

---

core/embed/io/ble/stm32/ble.c

- where the is nRF reset, we want to restart the pairing if there was paring mode before
- when nRF has no peers, but we are advertising with whitelist - turn the advertising off

fine tune BLE behavior after unexpected events

---

core/src/trezor/wire/thp/__init__.py

will return 0 for T2T1, perhaps it should be None :thinking:

fix(core): set model variant in THP DeviceProperties

---

core/embed/rust/src/ui/layout_eckhart/flow/show_share_words.rs

- there shouldn't be an option to skip backup
[no changelog]

fix(core/eckhart): remove menu from WordQuiz intro

---

core/embed/io/ble/inc/io/ble.h
core/embed/io/ble/stm32/ble.c
core/embed/rust/librust_qstr.h
core/embed/rust/src/trezorhal/ble/micropython.rs
core/embed/rust/src/trezorhal/ble/mod.rs
core/mocks/generated/trezorble.pyi

expose currently connected BLE host address to application

---

core/embed/projects/firmware/version.h
core/translations/cs.json
core/translations/de.json
core/translations/en.json
core/translations/es.json
core/translations/fr.json
core/translations/it.json
core/translations/pt.json
core/translations/signatures.json

chore(core): bump version to 2.9.2

---

common/protob/messages-management.proto
core/embed/projects/bootloader/protob/pb/messages.pb.h
core/embed/projects/bootloader/protob/pb/messages.proto
core/embed/projects/bootloader/protob/protob.c
core/src/trezor/messages.py
python/src/trezorlib/messages.py
rust/trezor-client/src/protos/generated/messages_management.rs

add battery SoC to features message

---

nordic/trezor/trezor-ble/src/ble/connection.c

causing problems on specific devices, lets observe further

remove 2M PHY udpate request

---

core/embed/rust/src/trezorhal/ble/micropython.rs

Following https://github.com/trezor/trezor-firmware/commit/71d6052652d10b1eb17d5c7e411bfb21cf36ce3c:

fix(core): correct BLE interface syshandle

---

core/src/apps/homescreen/device_menu.py

- cancelling via exception seems wrong and it's confusing in the logs
[no changelog]

Cancel device menu via UI result

---

nordic/trezor/trezor-ble/src/ble/advertising.c

adjust advertisment intervals

---

core/embed/rust/src/trezorhal/ble/micropython.rs
core/mocks/generated/trezorble.pyi
core/src/apps/management/ble/unpair.py
tests/device_tests/test_ble.py

[Slack](https://satoshilabs.slack.com/archives/C04HCEL0WQ2/p1757419337670249)

BLE unpairing-related fixes

---

core/embed/rust/src/ui/display/font.rs
core/embed/rust/src/ui/layout_eckhart/component/button.rs

This helps with the connection button which contains MAC addresses.

Split strings by ":"

---

core/embed/upymod/modtrezorutils/modtrezorutils.c
core/mocks/generated/trezorutils.pyi
core/src/apps/homescreen/device_menu.py
core/src/trezor/utils.py

show nRF version in About menu

---

core/embed/projects/bootloader/main.c
core/embed/sys/power_manager/unix/power_manager.c

stop charging indication when battery is fully charged

---

build-docker.sh

Merges `signing-t3w1-20250919` into `main`.
Please merge using `git merge --ff-only` & push manually so that the merge commit is preserved.

Merging signing T3W1 20250919

---

common/protob/messages-thp.proto
core/src/apps/homescreen/device_menu.py
core/src/apps/thp/pairing.py
core/src/trezor/messages.py
core/tests/test_apps.thp.paired_cache.py
python/src/trezorlib/messages.py
rust/trezor-client/src/protos/generated/messages_thp.rs

Part of #5783 that contains incompatible storage changes and should make it to the freeze.

feat(core/eckhart): cache THP app/host name along with MAC

---

nordic/trezor/trezor-ble/src/ble/advertising.c
nordic/trezor/trezor-ble/src/ble/ble_management.c

fix stack overflow crash in nrf app

---

core/src/trezor/ui/layouts/eckhart/__init__.py

Allow cancel on Solana recipient

---

core/embed/projects/prodtest/cmd/prodtest_tropic.c
core/embed/sec/rng/rng_common.c
core/embed/sec/tropic/stm32/tropic01.c

Bump `libtropic` to version 1.0.0

---

core/embed/projects/bootloader/workflow/wf_firmware_update.c

timeout FW installation when the next message doesn't arrive in time

---

core/embed/projects/prodtest/cmd/prodtest_secrets.c

Fix error handling in secrets-certdev-write.

---

core/embed/projects/bootloader/workflow/wf_wipe_device.c
core/embed/sys/notify/inc/sys/notify.h
core/embed/upymod/modtrezorutils/modtrezorutils.c
core/mocks/generated/trezorutils.pyi
core/src/apps/management/ble/unpair.py
core/src/apps/management/wipe_device.py
core/src/trezor/utils.py

add notifications device wipe & unpairing

---

core/Makefile

add clean_prodtest_emu makefile target

---

storage/norcow_blockwise.h

fix integer overflow in storage

---

core/embed/projects/prodtest/cmd/prodtest_optiga.c

https://satoshilabs.slack.com/archives/C05GZ8KME05/p1759240778297889

Hotfix for invalid Infineon certificate format

---

core/src/trezor/ui/__init__.py

Restore previous behaviour on non-THP devices, where we don't need to wait for ButtonRequest THP ACK.
See https://github.com/trezor/trezor-firmware/issues/5851#issuecomment-3336980777.

fix(core): wait for `_handle_button_requests` only on THP devices

---

core/translations/fr.json
core/translations/signatures.json

chore(core): shorten french string

---

core/embed/projects/prodtest/.changelog.d/5900.fixed
core/site_scons/models/T3W1/trezor_t3w1_revC.py

switch tropic silicon revision to ACAB

---

core/src/trezor/ui/layouts/eckhart/__init__.py

chore(core): remove unused function in `trezor.ui.layouts.eckhart`

---

core/embed/rust/src/ui/layout_eckhart/firmware/hint.rs

Adjust page counter position

---

.github/workflows/common.yml

Marking as draft since this needs `release/25.10` to be merged first. #5917

ci: enable T3W1 in docker build

---

core/.changelog.d/5911.added
core/embed/rust/librust_qstr.h
core/embed/rust/src/translations/generated/translated_string.rs
core/embed/rust/src/ui/api/firmware_micropython.rs
core/embed/rust/src/ui/layout/device_menu_result.rs
core/embed/rust/src/ui/layout_bolt/ui_firmware.rs
core/embed/rust/src/ui/layout_caesar/ui_firmware.rs
core/embed/rust/src/ui/layout_delizia/ui_firmware.rs
core/embed/rust/src/ui/layout_eckhart/component_msg_obj.rs
core/embed/rust/src/ui/layout_eckhart/firmware/device_menu_screen.rs
core/embed/rust/src/ui/layout_eckhart/ui_firmware.rs
core/embed/rust/src/ui/ui_firmware.rs
core/mocks/generated/trezorui_api.pyi
core/mocks/trezortranslate_keys.pyi
core/src/apps/homescreen/device_menu.py
core/src/ble.py
core/src/storage/device.py
core/translations/en.json
core/translations/order.json
core/translations/signatures.json
tests/click_tests/device_menu/common.py

Solves #5911 
- #5906
- #5630 
- https://github.com/trezor/trezor-firmware/pull/5941

Eckhart BLE toggling in device menu

---

core/src/apps/common/lock_manager.py

reset all settings on wallet wipe

---

core/embed/rust/src/translations/generated/translated_string.rs
core/translations/cs.json
core/translations/de.json
core/translations/en.json
core/translations/es.json
core/translations/fr.json
core/translations/it.json
core/translations/pt.json
core/translations/signatures.json

```
Translation                                              Before          After          Saved    Saved%
--------------------------------                  -------------  -------------  -------------  --------
translation-T2B1-cs-CZ-2.9.3                     |         30.9KB |         28.0KB |          2.9KB |     9.36%
translation-T2B1-de-DE-2.9.3                     |         28.6KB |         25.8KB |          2.9KB |     9.90%
translation-T2B1-es-ES-2.9.3                     |         30.7KB |         27.7KB |          3.1KB |     9.84%
translation-T2B1-fr-FR-2.9.3                     |         35.1KB |         31.9KB |          3.2KB |     9.06%
translation-T2B1-pt-BR-2.9.3                     |         29.8KB |         27.0KB |          2.9KB |     9.49% …
```

Cleanup translated strings per layout
