core/Makefile
Flashing FW via JLink/JTrace on STM32F42x models will not cause "firmware integrity failed" error and sectors that were unchanged won't need erase, so each FW flash will have proper padding.
=> Flash with JLink/JTrace will keep FW integrity, but not unnecessarily erase unchanged sectors

core/embed/prodtest/README.md, core/embed/prodtest/main.c, core/embed/trezorhal/haptic.h, core/embed/trezorhal/stm32u5/haptic/drv2625/drv2625.c
This PR adds ability to test haptics in prodtest.
Simple `HAPTIC duration_ms` command is added, with a limit to 6500ms.
=> add haptic to prodtest

core/.changelog.d/3940.added, core/embed/extmod/modtrezorutils/modtrezorutils.c, core/embed/lib/unit_variant.c, core/embed/lib/unit_variant.h, core/embed/prodtest/main.c, core/mocks/generated/trezorutils.pyi, core/src/apps/common/sdcard.py, core/src/storage/sd_salt.py, core/src/trezor/utils.py, docs/core/misc/memory.md
Allows SD card hotswap based on production date for Model T, the 2018 and earlier dont have the ability.
Pointing this to T3T1/U5 branch because there is some flash_otp refactoring done and want to avoid conflicts.
=> allow SD card hotswap based on production date for Model T

core/embed/firmware/main.c
Currently any exception that is not caught by an `except` block results in the hardware freezing with black screen (tested on Model T). We do define an unhandled exception callback but it doesn't seem to be used as the top-level exceptions are caught by [micropython C code](https://github.com/micropython/micropython/blob/v1.19.1/shared/runtime/pyexec.c#L129) which just does some cleanup and printing.
This PR adds a call to `error_shutdown` after returning from micropython. Other possibility would be to define `MICROPY_BOARD_AFTER_PYTHON_EXEC` micorpython hook.
=> core: handle uncaught exceptions from main.py

core/SConscript.firmware
Adding missing `debug` feature, which was missing and causing development keys not being included for translations
=> Fix hardware build

tests/ui_tests/reporting/html.py, tests/ui_tests/reporting/testreport.css, tests/ui_tests/reporting/testreport.js, tests/ui_tests/reporting/testreport.py
This PR adds the third column to the table for comparing screenshots captured in UI tests 
resoves #2509 
The third column show the difference between the recorded and the current screenshot.
=> feat(tests): show screenshot diff

core/embed/rust/librust_qstr.h, core/embed/rust/src/ui/layout/obj.rs, core/embed/rust/src/ui/model_tr/layout.rs, core/embed/rust/src/ui/model_tt/layout.rs, core/mocks/generated/trezorui2.pyi, core/src/apps/bitcoin/sign_tx/approvers.py, core/src/apps/bitcoin/sign_tx/helpers.py, core/src/apps/bitcoin/sign_tx/layout.py, core/src/trezor/ui/__init__.py, core/src/trezor/ui/layouts/common.py, core/src/trezor/ui/layouts/tr/__init__.py, core/src/trezor/ui/layouts/tr/reset.py, core/src/trezor/ui/layouts/tt/__init__.py, core/src/trezor/wire/context.py
some preliminary work for the global layout PR.
fixes #2672
also converts most functions in the layout files to `def -> Awaitable` format (instead of `async def -> T` with a single "return await").
=> Method signatures for Rust layout objects

core/embed/rust/src/ui/layout/mod.rs, core/embed/rust/src/ui/layout/simplified.rs, core/embed/rust/src/ui/mod.rs, core/embed/rust/src/ui/model_tr/bootloader/intro.rs, core/embed/rust/src/ui/model_tr/bootloader/menu.rs, core/embed/rust/src/ui/model_tr/bootloader/mod.rs, core/embed/rust/src/ui/model_tt/bootloader/mod.rs
introduces 'simplified' layout object for bootloader, common for all UI implementaitons.
originally part of #2521 , extracted into separate PR to simplify review and merging
=> refactor: extract common layout handling from bootloader

core/embed/trezorhal/unix/touch/touch.c
This pull request contains a fix for #3506  issue.
The `touch_read()` function has been refactored to merge successive `SDL_MOTION`` events into one.
The behavior of the function was made more clearer and more precise:
1) The `TOUCH_START` event is generated only if `SDL_MOUSEDOWN` event
was detected inside the simulator display area
2) When holding the mouse button and moving, `TOUCH_MOVE` is generated
3) When holding the mouse button down and leaving the display area, the `TOUCH_END` event is simulated.
The x,y coordinates are same as in the last `TOUCH_MOVE` event
=> fix(core): fix mouse event processing in the simulator

core/embed/trezorhal/stm32u5/mpu.c
fix prodtest mpu setting on U5 - allow read of MCU ID
=> fix prodtest mpu setting on U5 - allow read of MCU ID

core/embed/boardloader/main.c, core/embed/boardloader/memory_stm32f4.ld, core/embed/bootloader/main.c, core/embed/lib/buffers.h, core/embed/trezorhal/lowlevel.h, core/embed/trezorhal/secret.h, core/embed/trezorhal/stm32f4/secret.c, core/embed/trezorhal/stm32u5/lowlevel.c, core/embed/trezorhal/stm32u5/secret.c, core/vendor/cmsis_5, core/vendor/cmsis_device_u5
-fixes option bytes configuration on STM32U5
- improves robustness of BHK handling on STM32U5
- fixes missing symlinks
=> configure option bytes on STM32U5

core/embed/rust/src/ui/model_tt/component/homescreen/render.rs
This PR addresses crashes in the simulator caused by overflow in the blur algorithm.
On the right side of `+=` or `-=` operations, the value may become negative, resulting in a `u16` overflow for `RUST_PROFILE == 'dev'`.
This bug does not affect any hardware or simulators running with `RUST_PROFILE=='release'`.
=> fix(core): fixed blurring algo panic in debug mode

core/embed/rust/src/ui/component/text/formatted.rs, core/embed/rust/src/ui/component/text/op.rs, core/embed/rust/src/ui/model_tr/component/flow_pages.rs, core/embed/rust/src/ui/model_tr/component/input_methods/choice.rs, core/embed/rust/src/ui/model_tt/component/fido.rs, core/embed/rust/src/ui/model_tt/component/keyboard/passphrase.rs, core/embed/rust/src/ui/model_tt/component/simple_page.rs
This PR alters the logic of certain components by eliminating the requirement for `&mut self` in `paint()` functions. The PR serves as preparation for merging a new drawing library that requires it.
Two approaches were used:
1) Interior mutability utilizing `Cell` or `RefCell`.
2) Moving the mutation of component state to event processing.
**The behavior of the device was not affected by this change.**
=> refactor(core): prepare for non mutable paint function

tests/ui_tests/reporting/common.py, tests/ui_tests/reporting/html.py, tests/ui_tests/reporting/testreport.js, tests/ui_tests/reporting/testreport.py
This pull request enhances the UI Test Report in the following ways:
- Clicking to reveal diffs is no longer necessary, as they are now loaded automatically.
- Even when there are a lot of images on the page, the UI response remains smooth.
- Additionally, screenshot diffs are now visible on the `/differing_screens.html` page.
=> feat(tests): improve screenshot diffs

core/embed/trezorhal/unix/touch/touch.c
The PR adds capability to perform swipe gestures using arrow keys for touch models. 
Current implementation. Arrow key dictates direction of swipe.
- intuitive for following some instructions (e.g. "Swipe up" is performed by arrow key "Up")
- not intuitive for scrolling (the direction is mirrored, scroll down is performed by arrow key "Up")
I can switch it up but it depends on what's more useful.
=> feat(core/emu): handle arrow buttons as swipes

core/embed/bootloader/main.c, core/embed/trezorhal/stm32f4/touch/ft6x36.c, core/embed/trezorhal/stm32f4/touch/stmpe811.c, core/embed/trezorhal/stm32u5/common.c, core/embed/trezorhal/stm32u5/touch/sitronix.c, core/embed/trezorhal/touch.h, core/embed/trezorhal/unix/touch/touch.c
Correct touch initialization is not enforced until unit variant is written, which is done later in production when display+touch is already present.
=> allow T3T1 to start without touch during testing

core/embed/models/model_D002.h, core/embed/models/model_D002_layout.c
This tiny PR fixes the broken build on **disc2** platform:
```
make build_firmware TREZOR_MODEL=DISC2 BOOTLOADER_DEVEL=1
```
It doesn't affect any other platform.
=> fix(core): fix build on disc2 model

core/embed/trezorhal/stm32u5/secure_aes.c
According to errata, BHK loading into SAES key register must be done in ascending order.
Though i have verified that encryption and decryption still works (comparing results from SAES using BHK and regular hw AES peripheral using same key), the key is loaded into key reg according to the access order to the backup register thus ends up being different from what one would expect by looking into reference manual.
I don't think this makes any difference in our case, but nevertheless, lets follow the docs.
https://www.st.com/resource/en/errata_sheet/es0499-stm32u575xx-and-stm32u585xx-device-errata-stmicroelectronics.pdf
=> fix order of loading BHK into SAES key register

core/embed/rust/src/ui/layout/simplified.rs, core/embed/rust/src/ui/mod.rs, core/embed/rust/src/ui/model_tr/mod.rs, core/embed/rust/src/ui/model_tt/bootloader/mod.rs, core/embed/rust/src/ui/model_tt/mod.rs
to abstract over some common operations between models.
This also fixes test failure on T2B1 caused by incorrect import symbols.
related to #3608
=> refactor(core): introduce Simplified trait

ci/build.yml, docs/ci/jobs.md
Fixes https://github.com/trezor/trezor-user-env/issues/232:
- adding emulator of T3T1 model into Gitlab, so it can be fetched by trezor-user-env in the same way as all other models
=> Add T3T1 build into Gitlab

.github/workflows/core.yml
Skipping `build_prodtest` as it's failing with
```
scons: *** [build/prodtest/embed/prodtest/vendorheader.o] Source `embed/vendorheader/T3T1/vendorheader_unsafe_signed_prod.bin' not found, needed by target `build/prodtest/embed/prodtest/vendorheader.o'.
```
=> ci: actions: add T3T1 firmware build

core/embed/prodtest/main.c, core/embed/trezorhal/sdcard.h, core/embed/trezorhal/stm32f4/sdcard.c, core/embed/trezorhal/stm32u5/sdcard.c, core/embed/trezorhal/unix/sdcard.c
Due to the HW limitation and tester concept it is not possible to set the SD detect signal when testing the SD card on T3T1.
[no changelog]
=> do not require sd detect pin for running SD card test on T3T1

core/embed/rust/Cargo.lock, core/embed/rust/Cargo.toml, core/embed/rust/src/strutil.rs, core/embed/rust/src/translations/blob.rs, core/embed/rust/src/translations/flash.rs, core/embed/rust/src/translations/mod.rs, core/embed/rust/src/translations/obj.rs, core/embed/rust/src/translations/translated_string.rs
* the public interface to Translations is now completely safe
* it is more obvious that `map_translated` needs to work the way it does
* documentation is improved
=> refactor(core): improve safety of translation blobs

core/embed/rust/src/micropython/buffer.rs, core/embed/rust/src/strutil.rs, core/embed/rust/src/translations/generated/translated_string.rs, core/embed/rust/src/translations/generated/translated_string.rs.mako, core/embed/rust/src/translations/translated_string.rs, core/embed/rust/src/ui/component/base.rs, core/embed/rust/src/ui/component/text/formatted.rs, core/embed/rust/src/ui/component/text/op.rs, core/embed/rust/src/ui/component/text/paragraphs.rs, core/embed/rust/src/ui/layout/obj.rs, core/embed/rust/src/ui/layout/util.rs, core/embed/rust/src/ui/model_tr/component/address_details.rs, core/embed/rust/src/ui/model_tr/component/flow_pages.rs, core/embed/rust/src/ui/model_tr/component/loader.rs, core/embed/rust/src/ui/model_tr/component/progress.rs, core/embed/rust/src/ui/model_tr/layout.rs, core/embed/rust/src/ui/model_tt/component/address_details.rs, core/embed/rust/src/ui/model_tt/component/dialog.rs, core/embed/rust/src/ui/model_tt/component/number_input.rs, core/embed/rust/src/ui/model_tt/component/page.rs, core/embed/rust/src/ui/model_tt/component/progress.rs, core/embed/rust/src/ui/model_tt/layout.rs
This is a minimally-invasive change that uses TString as the internal storage for `Paragraph`, modifies `Paragraphs` and `ParagraphSource` accordingly. (in code, this looks mostly like replacing the `T: StringType` argument with a lifetime `'a` instead).
The invasiveness of the change is limited by using `Paragraphs<'static>` in most downstream usages. Even so, this generated a fair amount of churn as type parameters went away.
Going forward we can apply a similar conversion to components where we need it - `Label` is an obvious candidate, correct @TychoVrahe ?
I haven't tested the effect of this change on bootloader code. It _does_ apply to bootloader. In theory, in bootloader only one variant `TString::Str` should exist, and as such, the enum _should_ be completely optimized out. In …
=> TStringify Paragraphs

core/embed/rust/Cargo.lock, core/embed/rust/Cargo.toml, core/embed/rust/src/ui/macros.rs, core/embed/rust/src/ui/model_tr/component/input_methods/choice_item.rs, core/embed/rust/src/ui/model_tr/component/input_methods/number_input.rs, core/embed/rust/src/ui/model_tr/component/input_methods/passphrase.rs, core/embed/rust/src/ui/model_tr/component/input_methods/pin.rs, core/embed/rust/src/ui/model_tr/component/input_methods/wordlist.rs, core/embed/rust/src/ui/model_tt/component/keyboard/bip39.rs, core/embed/rust/src/ui/util.rs
This small PR adds the [ufmt](https://docs.rs/ufmt/latest/ufmt/) crate for string formatting.
Additionally, the `heapless` crate needed to be upgraded. However, there are some breaking changes: the `String<N>` type no longer implements the `From` trait; it has been replaced by the `TryFrom` trait. Consequently, all occurrences of `from` calls have been replaced by `try_from`, and `unwrap!` has been added where necessary.
**Note: Previous version of heapless used `unwrap()` internally in `from` implementation. So the final behavior remains the same.**
Changes Made:
- Added ufmt crate for string formatting.
- Upgraded heapless crate.
- Replaced occurrences of `from` with `try_from`.
- Added `unwrap!` where necessary.
**This PR does not alter the behavior of the device from the user's …
=> refactor(core): add ufmt, bump heapless from 0.7.6 - 0.8.0

core/SConscript.boardloader, core/SConscript.bootloader, core/SConscript.bootloader_ci
Set stack protector to `strong`, for bootloader and boardloader. The benefit of `all` is virtually none and this saves us a lot of flash space.
=> set stack protector to strong

ci/build.yml, docs/ci/jobs.md
Since we need them in `trezor-user-env` and `GH-Actions` cannot build them.
=> Temporarily add ARM T3T1 emulators into Gitlab

core/embed/bootloader/main.c, core/embed/firmware/main.c, core/embed/prodtest/main.c, core/embed/prodtest/optiga_prodtest.c, core/embed/trezorhal/secret.h, core/embed/trezorhal/secure_aes.h, core/embed/trezorhal/stm32f4/secret.c, core/embed/trezorhal/stm32u5/secret.c, core/embed/trezorhal/stm32u5/secure_aes.c, storage/storage.c
Improves security of u5 based models by including U5 HW keys (DHUK and BHK) in storage encryption and decryption procedures.
=> use U5 HW keys for additional storage encryption

python/src/trezorlib/debuglink.py
Currently the tokens take up most of the lines in test output. I usually die of old age before I scroll up to the stack trace (if it's in the terminal buffer at all).
=> feat(python): more compact debuglink logging

core/embed/prodtest/main.c, core/embed/trezorhal/sdcard.h, core/embed/trezorhal/stm32f4/sdcard.c, core/embed/trezorhal/stm32u5/sdcard.c, core/embed/trezorhal/unix/sdcard.c
Use half the speed to make it easier to work with tester in production.
Added a `clk_div` param `sdcard_power_on_unchecked` to achieve this, which is not very nice solution due to bad portability, but simple enough given the time pressure. The `sdcard_power_on_unchecked` is only used in prodtest so the impact is limited.
=> slow down SDIO communication in T3T1 prodtest

core/embed/prodtest/README.md, core/embed/prodtest/main.c, core/embed/trezorhal/stm32f4/touch/ft6x36.c, core/embed/trezorhal/stm32f4/touch/stmpe811.c, core/embed/trezorhal/stm32u5/touch/sitronix.c, core/embed/trezorhal/touch.h, core/embed/trezorhal/unix/touch/touch.c
Adds TOUCH VERSION and VARIANT READ commands to prodtest, so that production can check the version of firmware in touch controller and stored device variant.
=> feat(core/prodtest): add commands TOUCH VERSION and VARIANT READ

core/embed/reflash/main.c
I don't what what is reflash firmware good for, but it won't get compiled. which could indicate it is no longer used. This pull requests fixes it so it at least compiles without errors.
=> Fix reflash firmware

core/embed/trezorhal/stm32u5/hash_processor.c
The original version was failing in some scenarios - not entirely sure why, but using `HAL_HASHEx_SHA256_Accmlt_End` function with zero data to retrieve hash fixes the problem and does not require weird `HASH->STR |= HASH_STR_DCAL;` statement. Guessing that the `HAL_HASHEx_SHA256_Finish` was misused.
=> fix stm32u5 sha256 calculation

core/embed/firmware/main.c
just that we can see if that happens.
=> move OEM key check after display initialization so that error message can be displayed

crypto/tests/test_curves.py, poetry.lock, pyproject.toml
I haven't run the `crypto/tests/test_curves.py` - let's see what the CI thinks.
I just confirmed that running `poetry install` creates a valid environment on macOS - thus this PR fixes https://github.com/trezor/trezor-firmware/issues/3687
=> build(deps): drop curve25519-donna and ed25519 from deps

core/embed/bootloader/main.c, core/embed/trezorhal/stm32f4/common.c, core/embed/trezorhal/stm32f4/supervise.c, core/embed/trezorhal/stm32u5/common.c
it was occasionally crashing while rebooting, because there was display update in progress and the SVC call blocked other interrupts. 
Moved the `ensure_compatible_settings` from svc handler to initial `svc_reboot_to_bootloader` call, so that inside the handler it is ensured that the display operations have finished.
The removal led to some weird hardfault during the reboot, due to some weirdness in returning from SVC. Basically it seemed that stack pointer, instead of the stack[0] value was changed, and the next stack[6] modification hardfaulted. 
The modification fixed it on U5 at least.. 
@hiviah could you try if this works on F4 also? does this modification makes sense to you?
[no changelog]
=> fix T3T1 reboot to bootloader 

core/embed/trezorhal/stm32u5/lowlevel.c
This PR sets OEM key option bytes to 0xff.. value, which is interpreted as not set.
There is no possibility to read what is set, so this is only done when changing other option bytes - so we still need to check that the OEM key is not set later in fw.
=> fix(core): ensure correctly programmed oem key option bytes

core/embed/trezorhal/boards/trezor_t3t1_revE.h, core/embed/trezorhal/boards/trezor_t3t1_v4.h
The boards use 3.3V voltage.
This modification sets BOR level to cca 2.8V and enables PVD, also at about 2.8V.
The supervisor IC is set to 2.9V, this does not entirely matter, but i think its preferable to have it set this way, so it is apparent what the board voltage is.
The original 1.8V setting came from U5 discovery kit.
=> set proper VDD level for T3T1 boards

core/Makefile, core/SConscript.bootloader, core/SConscript.bootloader_emu, core/SConscript.firmware, core/SConscript.unix, core/embed/rust/build.rs, core/site_scons/boards/discovery.py, core/site_scons/boards/discovery2.py, core/site_scons/boards/stm32f4_common.py, core/site_scons/boards/stm32u5_common.py, core/site_scons/boards/trezor_1.py, core/site_scons/boards/trezor_r_v10.py, core/site_scons/boards/trezor_r_v3.py, core/site_scons/boards/trezor_r_v4.py, core/site_scons/boards/trezor_r_v6.py, core/site_scons/boards/trezor_t.py, core/site_scons/boards/trezor_t3t1_revE.py, core/site_scons/boards/trezor_t3t1_v4.py, core/site_scons/tools.py
removes most of the duplications between sconscript and bindgen build stages.
unfortunately, some duplicated declarations are still in makefile test targets, but at least we have more precise control over what is being tested. 
closes #3526
=> refactor(core): generate macros for rust bindgen automatically

core/Makefile
the combined binary needs flashing on `BOARDLOADER_START` address, as on U5 we dont run boardloader from start of the flash but with some offset to create space for the secret/HDP area
=> fix flash_combine makefile command

core/SConscript.bootloader, core/SConscript.bootloader_emu, core/SConscript.firmware, core/SConscript.unix, core/site_scons/tools.py
the previous version actually did not work well because the later sconscript files were overriding the environment variable, resulting in unix macros always being used.
=> fix bindgen macros generation

core/embed/prodtest/.changelog.d/+version.added, core/embed/prodtest/README.md, core/embed/prodtest/main.c
- Adds `FIRMWARE VERSION` command to prodtest.
- Improves error handling. For example the `VARIANT` and `OTP WRITE` commands used to crash when used for a second time in a row.
- Improves prodtest documentation and gives examples of how commands are actually used.
=> Add FIRMWARE VERSION command to prodtest

core/embed/trezorhal/stm32f4/usb_vcp-impl.h, core/embed/trezorhal/stm32f4/usbd_conf.c
Configures USB FS to use 6 endpoints - we need that when we use VCP and FIDO together.
=> fix USB configuration for STM32U585

core/embed/rust/build.rs, core/embed/rust/src/trezorhal/haptic.rs, core/embed/rust/src/ui/model_tt/component/button.rs, core/embed/rust/src/ui/model_tt/component/loader.rs, core/embed/rust/src/ui/model_tt/component/page.rs, core/embed/trezorhal/haptic.h, core/embed/trezorhal/stm32u5/haptic/drv2625/drv2625.c
add the loader feedback to tt ui (as fallback for mercury for T3T1)
still needs to be added to mercury too, but thats a separate PR
=> add haptic feedback to TT UI loader

core/embed/rust/src/ui/model_mercury/component/frame.rs
32 pixels instead of 16 in mercury UI. (tt has 44px button + 6*4px expansion, here we have 42px + 32 expansion)
=> T3T1: expand menu btn

core/embed/rust/src/ui/model_mercury/bootloader/mod.rs, core/embed/rust/src/ui/model_mercury/component/loader.rs, core/embed/rust/src/ui/model_mercury/component/progress.rs, core/embed/rust/src/ui/model_mercury/mod.rs, core/embed/rust/src/ui/model_mercury/shapes.rs, core/embed/rust/src/ui/model_mercury/theme/mod.rs
Closer match to figma design.
Round edge of sector is missing as it would be quite difficult to implement.
This is used in bootloader, progress and Loader component, although i expect Loader to be replaced by a hold to confirm animation at some point.
=> T3T1 loaders improvement

core/embed/lib/gfx_bitblt_mono8.c, core/embed/lib/gfx_bitblt_rgb565.c, core/embed/lib/gfx_bitblt_rgba8888.c, core/embed/lib/gfx_color.h, core/embed/rust/src/trezorhal/bitblt.rs, core/embed/rust/src/ui/shape/bitmap.rs, core/embed/rust/src/ui/shape/canvas/common.rs, core/embed/rust/src/ui/shape/circle.rs, core/embed/rust/src/ui/shape/text.rs, core/embed/rust/src/ui/shape/toif.rs, core/embed/trezorhal/stm32f4/dma2d_bitblt.c
- adds generic mono4 blending with alpha
- adds alpha to circle, toif and text
The alpha for blending mono4 is computed by multiplying the mono4 value with the aplha, then use 8bit blend. When dma2d accelerated, the color is set to constant and the alpha channel is set to the multiple of alpha and step on the gradient.
The circle blending with alpha is not ideal when ring/outline is drawn - alpha blending will result in some of the foreground color visibility in the inner circle. This could be fixed by using native rings, or composing the ring in side layer and blending the result. However, for current use case this seems acceptable and we can implement more precise circle blending later.
=> add alpha capabilities to drawlib

core/SConscript.bootloader, core/SConscript.bootloader_ci, core/SConscript.bootloader_emu
Added the missing font to bootooader builds, using regular as that is what it was designed with.
=> fix TS3 bootloader crash when entering menu

core/embed/trezorhal/stm32f4/xdisplay/st-7789/display_driver.c, core/embed/trezorhal/stm32f4/xdisplay/st-7789/display_fb.c, core/embed/trezorhal/stm32f4/xdisplay/st-7789/display_fb.h
the previous protection relied at bg_copy being finished, but after that, it takes some time for the panel to refresh and actually show the new data.
i am switching to time-based protection. We could also consider some more sophisticated approaches like measuring number of TE signals after copying the data, but it seems unnecessarily complicated.
To limit the impact, i am only adding the wait if the backlight value is going up - as this is where the risk is.
=> T3T1: fix old frame flickering when rising backlight

core/Makefile, core/embed/rust/build.rs
this way Cargo build can run without the envvar set, e.g. in rust-analyzer
=> build(core): move default values for bindgen macros (back) into build.rs

core/embed/bootloader/bootui.c, core/embed/bootloader/main.c, core/embed/bootloader/messages.c, core/embed/lib/image.h, docs/core/misc/boot.md
During a recent code review I was getting lost in the bitwise complement logic that is used for vtrust flags. This PR should improve legibility by renaming the code constants to what I believe to be more intuitive names and by adding more documentation.
`VTRUST_ALL` -> `VTRUST_NO_WARNING`
`VTRUST_ALL` no longer represents "ultimate trust". It represents the absence of any vendor screen warnings.
`VTRUST_RED` - > `VTRUST_NO_RED` etc.
When the corresponding bit is set, it represents that no red screen should be shown, etc.
=> Improve VTRUST bits documentation and naming.

core/embed/lib/gfx_color.h
fixes blending/copying mono4 when using new_rendering.
=> fix alpha component extraction

core/embed/rust/src/ui/model_mercury/component/button.rs, core/embed/rust/src/ui/model_mercury/component/keyboard/bip39.rs, core/embed/rust/src/ui/model_mercury/component/keyboard/common.rs, core/embed/rust/src/ui/model_mercury/component/keyboard/mnemonic.rs, core/embed/rust/src/ui/model_mercury/component/keyboard/passphrase.rs, core/embed/rust/src/ui/model_mercury/component/keyboard/pin.rs, core/embed/rust/src/ui/model_mercury/component/keyboard/slip39.rs, core/embed/rust/src/ui/model_mercury/component/mod.rs, core/embed/rust/src/ui/model_mercury/component/share_words.rs, core/embed/rust/src/ui/model_mercury/layout.rs, core/embed/rust/src/ui/model_mercury/theme/mod.rs, core/src/trezor/ui/layouts/mercury/recovery.py
Hopefully final PR for keyboards
Passphrase keyboard
- redesign
Recovery keyboard
- both BIP39 and SLIP39 redesign
- pill-shaped button used for auto-complete and confirm
PIN keyboard:
- minor change - bullets shown are a little bit smaller
=> T3T1 keyboards

core/embed/rust/Cargo.lock, core/embed/rust/Cargo.toml, core/embed/rust/build.rs
this fixes build on macOS - see https://github.com/trezor/trezor-firmware/issues/3774
=> chore(core/rust): bump buildgen to 0.62.0

core/embed/trezorhal/stm32f4/xdisplay/st-7789/display_driver.c
the whole interenal framebuffer needs to be cleared when changing display orientation, otherwise, some residual image can pop-out
=> fix clearing st7789's internal framebuffer

core/embed/rust/src/ui/model_mercury/component/hold_to_confirm.rs, core/embed/rust/src/ui/model_mercury/component/mod.rs, core/embed/rust/src/ui/model_mercury/component/prompt_screen.rs, core/embed/rust/src/ui/model_mercury/component/tap_to_confirm.rs, core/embed/rust/src/ui/model_mercury/flow/confirm_action.rs, core/embed/rust/src/ui/model_mercury/flow/confirm_reset_recover.rs, core/embed/rust/src/ui/model_mercury/flow/get_address.rs, core/embed/rust/src/ui/model_mercury/flow/prompt_backup.rs, core/embed/rust/src/ui/model_mercury/flow/show_share_words.rs
Implements tap-to-confirm animation for mercury UI.
=> tap to confirm animation for mercury UI

core/embed/extmod/modtrezorcrypto/modtrezorcrypto-monero.h, core/embed/extmod/modtrezorio/modtrezorio-poll.h, core/embed/extmod/modtrezorui/modtrezorui-display.h, core/embed/extmod/modtrezorutils/modtrezorutils.c, core/mocks/generated/trezorcrypto/crc.pyi, core/mocks/generated/trezorio/__init__.pyi, core/tools/build_mocks
This PR changes the `gen` script to include empty lines when converting comments into documentation.
=> Change build_mocks to include empty lines

core/.changelog.d/3922.fixed, core/embed/trezorhal/stm32u5/secret.c
Fixes bootloader lock check, and consequently, device authentication check, which is refused when bootloader is unlocked.
=> fix bootloader lock check on STM32U5

core/src/trezor/ui/layouts/tr/__init__.py, core/src/trezor/ui/layouts/tr/recovery.py, core/src/trezor/ui/layouts/tr/reset.py
some things about Rusty button requests were mishandled on the TR part. This PR brings it all (hopefully) up to spec.
=> fix(core): TS3 device freeze

core/embed/rust/src/ui/model_mercury/component/swipe_content.rs
Attempt to mitigate queue overflow when swiping.
The animation frame requests are useless in first swipe phase - as the animation is driver by touch move (or rather SwipeMove) events.
=> reduce animation frame requests when swiping

core/.changelog.d/3919.fixed, core/embed/rust/src/ui/model_mercury/flow/get_address.rs
adds missing swipe right to address QR screen.
=> add missing swipe right to address QR screen - mercury ui

python/src/trezorlib/cli/ethereum.py
This tiny pull request removes hardcoded `0x` prefix for sign-tx ethereum cli command with a publish flag. web3 lib adds it upfront.
=> fix(python): remove duplicated 0x prefix for publish sign-tx

rust/trezor-client/src/client/ethereum.rs
- This PR fixes Invalid `convert_signature` function in `trezor-client` Package
The current implementation of the `convert_signature` function in the `trezor-client` package contains a potential error in the way the signature's `s` component is handled. Specifically, the line:
```rust
let s = resp.signature_r().try_into().map_err(|_| Error::MalformedSignature)?;
```
This line incorrectly references `resp.signature_r()` instead of `resp.signature_s()`, leading to a logical error where the `r` component is duplicated as `s`.
Please review the changes and merge them if they meet the project's standards. Thank you for considering this fix.
=> fix(trezor-client): fix convert_signature invalid s conversion

core/translations/cli.py, core/translations/cs.json, core/translations/de.json, core/translations/en.json, core/translations/es.json, core/translations/fr.json, core/translations/signatures.json
1e03b8afec2f43f82292c3e5a4ee058ec9877679 makes sure that the version number in translation jsons stays up-to-date with  in-tree firmware version.
(also fixes what seemed to be duplicated keys in en.json?)
the rest is updating signatures.json with (a) actual signatures for 2.7.1 and 2.7.2, and (b) the current merkle root for version 2.7.3
=> Update translation versions

core/embed/trezorhal/stm32f4/usb.c, core/embed/trezorhal/stm32f4/usb_hid-impl.h, core/embed/trezorhal/stm32f4/usb_webusb-impl.h
This small PR fixes random delays in the USB driver while receiving/sending USB data packets for HID and WEBUSB interfaces.
Before this change, `wait_random()` was called multiple times in `usb_class_data_in()` and `usb_class_data_out()` while finding the proper interface to handle a request. Moreover, the fix 62e3a414ad7a20d09fd4ea6709ae4ca5d1335a4f may not succeed at all if the VCP interface was not the first one or the only one.
This change have no effect on device behaviour in production.
=> fix(core/embed): fix random delays in usb driver

core/embed/bootloader/main.c, core/embed/bootloader_ci/main.c, core/embed/extmod/modtrezorio/modtrezorio-usb.h, core/embed/prodtest/main.c, core/embed/trezorhal/stm32f4/dma2d_bitblt.c, core/embed/trezorhal/stm32f4/usb/usb.c, core/embed/trezorhal/stm32f4/usb/usb_class_hid.c, core/embed/trezorhal/stm32f4/usb/usb_class_vcp.c, core/embed/trezorhal/stm32f4/usb/usb_class_webusb.c, core/embed/trezorhal/stm32f4/usb/usb_internal.h, core/embed/trezorhal/stm32f4/usb/usbd_def.h, core/embed/trezorhal/unix/usb.c, core/embed/trezorhal/usb.h, core/site_scons/models/D001/discovery.py, core/site_scons/models/D002/discovery2.py, core/site_scons/models/T1B1/trezor_1.py, core/site_scons/models/T2B1/trezor_r_v10.py, core/site_scons/models/T2B1/trezor_r_v3.py, core/site_scons/models/T2B1/trezor_r_v4.py, core/site_scons/models/T2B1/trezor_r_v6.py, core/site_scons/models/T2T1/trezor_t.py, core/site_scons/models/T3T1/trezor_t3t1_revE.py, core/site_scons/models/T3T1/trezor_t3t1_v4.py
This PR continues the refactoring of USB drivers and includes the following changes:
1. **Introduces the `usb_deinit()` routine and clarifies the highest-level API of the driver.** - required by entering/exiting low power modes, not used now.
2. Removes unnecessary calls to `usb_stop()` scattered throughout the codebase, as they always accompany `usb_deinit()`.
3. Removes the dependency of the class driver on the global context of the USB driver.
4. Fixes the build of the disc2 target.
These changes does not affect the device behavior.
=> USB driver refactoring II

core/embed/trezorhal/haptic.h, core/embed/trezorhal/stm32u5/haptic/drv2625/drv2625.c, core/embed/trezorhal/stm32u5/haptic/drv2625/drv2625.h
This PR focuses on refactoring the haptic controller driver. It does not fix any problems or introduce new features, but includes the following changes:
1. Removed `haptic_calibrate()` since it's unused, and using calibration requires more effort than just having this routine.
2. Removed the `HAPTIC_ALERT` effect since it's unused.
3. Polished the haptic driver API (`haptic.h`). Added the `haptic_deinit()` function, allowing repeated driver initialization and deinitialization, and ensured all functions that can fail return `bool`.
4. Refactored the driver to avoid using many global variables, resulting in the driver state being clear and well-defined in a single location.
The original goal was to prepare the haptic driver for power management features (e.g., suspending before entering low …
=> Haptic driver refactoring

core/embed/rust/src/ui/component/base.rs, core/embed/trezorhal/bg_copy.h, core/embed/trezorhal/stm32f4/displays/st7789v.c, core/embed/trezorhal/stm32f4/xdisplay/st-7789/display_driver.c, core/embed/trezorhal/stm32f4/xdisplay/st-7789/display_fb.c, core/embed/trezorhal/stm32f4/xdisplay/st-7789/display_fb.h, core/embed/trezorhal/stm32f4/xdisplay/st-7789/display_internal.h, core/embed/trezorhal/stm32f4/xdisplay/st-7789/display_io.c, core/embed/trezorhal/stm32f4/xdisplay/st-7789/display_nofb.c, core/embed/trezorhal/stm32u5/bg_copy.c, core/embed/trezorhal/xdisplay_legacy.c
This PR improves the display refreshing algorithm for the T3T1 model with the following enhancements:
1. Simplified the framebuffer switching algorithm, enabling full framerate, especially for simpler animations.
2. Modified the semantics of `display_get_frame_buffer()` and `display_refresh()`. Details are provided below.
3. Fixed the issue of waiting for the TE signal on the T2T1 model (with `NEW_RENDERING`=1).
4. Shorten `ANIM_FRAME_TIMER` deadline from 18ms to 1ms
The functions `display_get_frame_buffer()` and `display_refresh()` should now be used as a pair:
On the T3T1 model, all framebuffer switching (except when running in handler mode) is done in the background.
- `display_get_frame_buffer()`: Retrieves a new framebuffer for writing. This function may block for a while if the …
=> Improved T3T1 framebuffer switching

core/.changelog.d/+optiga.fixed, core/embed/trezorhal/optiga/optiga_transport.c
Changes Optiga's `MAX_RETRY_READ_MS` introduced in https://github.com/trezor/trezor-firmware/pull/3766. I increase it to 6 seconds in order to account for the maximum throttling down delay [1] of 5 seconds when Optiga's security event counter is high.
[1] https://github.com/Infineon/optiga-trust-m-overview/blob/main/docs/OPTIGA%E2%84%A2%20Trust%20M%20Solution%20Reference%20Manual.md#security-monitor-characteristics.
=> Increase Optiga MAX_RETRY_READ_MS to 6 sec

common/protob/messages-management.proto, core/embed/extmod/modtrezorcrypto/modtrezorcrypto-optiga.h, core/embed/trezorhal/optiga.h, core/embed/trezorhal/optiga/optiga.c, core/embed/trezorhal/unix/optiga.c, core/mocks/generated/trezorcrypto/optiga.pyi, core/src/apps/base.py, core/src/trezor/messages.py, python/src/trezorlib/messages.py, rust/trezor-client/src/protos/generated/messages_management.rs
Adds a new `optiga_sec` field to `Features`, which contains the value of Optiga's security event counter (SEC). Benefits:
- Makes it easier to diagnose issues involving communication with Optiga
- We can collect analytics in Suite to see how prevalent the issues with Optiga's SEC are.
- Suite could instruct users to keep their Trezor plugged in when the SEC counter is high.
=> Add optiga_sec field to Features

core/.changelog.d/+optiga.added, core/.changelog.d/+optiga.fixed
* It seems overly self-assured to call the RSODs "fixed" :)
* the exposed `optiga_sec` should have its own changelog
=> docs(core): update Optiga-related changelogs

core/embed/extmod/modtrezorcrypto/modtrezorcrypto-optiga.h, core/embed/trezorhal/optiga.h, core/embed/trezorhal/optiga/optiga.c, core/embed/trezorhal/optiga_commands.h, core/embed/trezorhal/unix/optiga.c, storage/storage.c
- Mainly refactoring to make the Optiga error handling easier to use and read.
- A small optimization in counter initialization.
=> Clean up Optiga error handling

storage/storage.c
`OPTIGA_PIN_SECRET_SIZE` is not available when optiga is not used and its usage here seems incorrect.
(this configuration is used on DISC2 devkit)
=> fix storage compilation for U5 models without optiga

core/Makefile, core/embed/trezorhal/stm32f4/touch/stmpe811.c, core/embed/trezorhal/stm32u5/touch/sitronix.c
This PR fixes the bugs in the touch driver introduced by #3900 on both discovery kits.
1) Fixes duplicated `TOUCH_MOVE` events with the same coordinates
2) Fixes `touch_activity()` detectioin on disc2 kit
3) Fixes `flash_firmware`/`flash_bootloader` make targets for disc1 kit
=> Fix touch driver on dev kits

core/embed/bootloader/main.c, core/embed/bootloader_ci/main.c, core/embed/trezorhal/stm32f4/platform.h, core/embed/trezorhal/stm32f4/util.s, core/embed/trezorhal/stm32u5/limited_util.s, core/embed/trezorhal/stm32u5/platform.h, core/embed/trezorhal/stm32u5/util.s
This PR fixed memory clearing during the transition from the boardloader to the bootloader.
Prior to this change, the memory was filled with potentially uninitialized values. After this change, the memory is correctly set to zero as expected. This bug did not pose any security issues since the memory was always overwritten.
Additionally, the unused `jump_to_unprivileged` function has been removed in this PR.
=> Fix memory clearing in boardloader

core/embed/trezorhal/stm32f4/backlight_pwm.c, core/embed/trezorhal/stm32f4/backlight_pwm.h, core/embed/trezorhal/stm32f4/common.c, core/embed/trezorhal/stm32f4/displays/st7789v.c, core/embed/trezorhal/stm32f4/xdisplay/st-7789/display_driver.c
This PR is about refactoring the backlight driver and preparing it for entering and exiting low-power modes (not done yet).
1. Simplified and clarified the driver API and removed model-specific functions.
2. Eliminated multiple global variables and introduced a single driver instance variable.
3. Slightly changed the driver logic without affecting its functionality.
This PR will be followed by the display driver refactoring, where additional cleanup will be done.
=> Backlight driver refactoring

core/embed/unix/main.c
we need to cherry-pick two commits into the micropython submodule, and adapt one of the fixes
matching: https://github.com/trezor/micropython/pull/12 (we'll need to merge that one manually by fast-forward so that the branch stays in sync with this submodule update)
fixes #4004
=> build(core): fix build for GCC13

core/embed/bootloader/emulator.c, core/embed/trezorhal/unix/common.c, core/embed/unix/main.c
In 5fc3c6e617619eee14429d44ab6e064ed3f5801e the termination code was modified not to raise micropython SystemExit just before exit(). Unfortunately this is needed for test coverage reports as `prof.py` relies on this exception to write out coverage data.
This has not been caught by CI because the coverage jobs were failing intermittently for long enough time for everyone to learn to ignore them. Hopefully I'll fix this next.
=> Fix broken coverage reporting

core/embed/rust/src/ui/model_mercury/component/swipe_content.rs
Extracted code that doesn't need to be generic from SwipeContent to AttachAnimation and SwipeContext.
As SwipeContent is heavily used this refactor saves ~6kB of flash.
=> refactor SwipeContent

core/.changelog.d/4030.added, core/embed/rust/src/ui/model_mercury/flow/confirm_firmware_update.rs, core/embed/rust/src/ui/model_mercury/flow/mod.rs, core/embed/rust/src/ui/model_mercury/layout.rs, core/embed/rust/src/ui/model_tr/layout.rs, core/mocks/generated/trezorui2.pyi
The PR changes the UI of confirming interaction-less firmware update. 
Only firmware part is changed.
Surprisingly, it also reduced flash size by one block: `512B`
=> feat(core/mercury): change FW update UI

core/.changelog.d/4060.fixed, core/embed/rust/src/ui/component/swipe_detect.rs
Adjusting the swipe detection in order to prefer vertical swipes over horizontal, as vertical swipes are more common operation vs. special cases like entering menu. This aims to improve reliability of swipes when swiping somewhat diagonally.
=> prefer vertical swipes over horizontal

core/embed/rust/src/ui/model_mercury/flow/confirm_set_new_pin.rs, core/embed/rust/src/ui/model_mercury/flow/prompt_backup.rs
This minor commit saves `1 KiB` of debug flash. I ain't much but it's for free.
=> refactor(core/mercury): init Paragraphs from Vec

core/embed/prodtest/.changelog.d/3752.added, core/embed/prodtest/.changelog.d/4064.added, core/embed/prodtest/README.md, core/embed/prodtest/main.c, core/embed/trezorhal/board_capabilities.h, core/embed/trezorhal/stm32f4/board_capabilities.c
adding several new commands to prodtest.
TOUCH_CUSTOM - to show arbitrary rectangle and report touches
TOUCH_IDLE - to test that there are no touches
(using underscore to avoid conflicts due to startswith usage)
`BOOTLOADER VERSION` and `BOARDLOADER VERSION` with obvious purpose.
=> add more thorough touch testing to prodtest

core/embed/extmod/modtrezorcrypto/modtrezorcrypto-ed25519.h, core/mocks/generated/trezorcrypto/ed25519.pyi, core/tests/test_trezor.crypto.curve.ed25519.py, crypto/ed25519-donna/ed25519.c, crypto/ed25519-donna/ed25519.h
The function `generate_secret()` from the `ed25519` Python module generates a random 256-bit key and then "clamps" it, i.e. sets the three least significant bits to 0 and the two most significant bits to 0 and 1. I believe that the clamping should not be applied here.
The functions `ed25519_publickey()`, `ed25519_sign()` and `ed25519_cosi_sign()` first hash the secret key and then apply the clamping on the first 256 bits of the hash. In other words, the rest of the module implementation assumes that it is working with an unclamped secret key. This means that clamping does not need to be applied during key generation and it technically violates the rules for generating Ed25519 keys:
> The private key is 32 octets (256 bits, corresponding to b) of cryptographically secure random data. …
=> Remove bias in ed25519.generate_secret()

.github/workflows/core.yml, .github/workflows/legacy.yml, core/SConscript.bootloader_emu
=> ci: add arm emulator build in github actions

core/embed/prodtest/main.c
fix expected param numbers for TOUCH_IDLE command
=> fix expected param numbers for TOUCH_IDLE command

core/SConscript.firmware, core/SConscript.unix, core/embed/rust/Cargo.toml, core/embed/rust/src/ui/model_mercury/cshape/mod.rs, core/embed/rust/src/ui/shape/cache/drawing_cache.rs
this fixes compilation of T3T1 bootloader with new rendering, which was overflowing RAM.
=> introduce ui_overlay feature

core/src/apps/debug/__init__.py, python/.changelog.d/4089.changed, python/.changelog.d/4089.fixed, python/src/trezorlib/transport/webusb.py
* converts USB errors to TransportExceptions
* retries USB calls with a short timeout instead of waiting on blocking calls -- this means that Python-level signals (such as KeyboardInterrupt) will successfully stop a USB wait, so you can easily ctrl+c out of a stuck trezorctl
* this also allows pytest-timeout to kill a stuck hardware test
(we should also leverage this to be able to re-sync USB communication after a lost packet. this is not done in this PR however.)
in addition, I noticed and fixed a race condition in debuglink on the device side, which makes hw tests more resilient too
=> trezorlib: WebUSB resilience

.pylintrc, core/src/apps/base.py, core/src/apps/bitcoin/sign_tx/layout.py, core/src/apps/debug/__init__.py, core/src/apps/management/recovery_device/homescreen.py, core/src/apps/workflow_handlers.py, core/src/boot.py, core/src/trezor/ui/__init__.py, core/tests/test_apps.bitcoin.signtx_decred.py, core/tests/test_apps.common.coins.py, python/src/trezorlib/debuglink.py, tools/trezor-pylint-plugin/trezor_pylint_plugin.py
in all cases where Python code checks for T2B1, the same should apply for T3B1.
complement to #4072
=> Enable conditional branches for T3B1

common/defs/README.md, common/tools/coin_info.py, common/tools/cointool.py, common/tools/support.py, core/src/apps/common/coininfo.py, core/src/apps/common/coininfo.py.mako, core/src/apps/ethereum/networks.py, core/src/apps/ethereum/networks.py.mako, core/src/apps/ethereum/tokens.py, core/src/apps/ethereum/tokens.py.mako, core/translations/cli.py, core/translations/cs.json, core/translations/de.json, core/translations/es.json, core/translations/fr.json, core/translations/signatures.json, tests/translations.py
Templates for coin data contain a list of models. T3B1 was not on that list.
This PR moves the list out of the templates, and uses `support.json` as an authoritative data source for the list of models.
Additionally, there's a small cleanup of supportinfo tooling -- now that we no longer track `suite` and `connect`, I also removed "missing-means-unsupported" feature.
=> T3B1: support all coins that should be supported

core/.changelog.d/4161.fixed, core/src/apps/bitcoin/scripts_decred.py, core/src/apps/bitcoin/sign_tx/decred.py, tests/device_tests/bitcoin/test_decred.py, tests/txcache/decred_testnet/1f00fc54530d7c4877f5032e91b6c507f6a1531861dede2ab134e5c0b5dfe8c8.json, tests/txcache/decred_testnet/8b6890c10a3764fe6f378bc5b7e438148df176e9be1dde704ce866361149e254.json
Decred shares code with bitcoin and a recent change broke signing stake
based inputs. Add decred specific script construction and fix tests.
This fixes a bug introduced by c9e6ca30c925a213bc92c7b283875d166d3c4f75
This is partly my fault as the test input was flawed and did not have the proper script opcode prefix.
Feel free to take these changes and adjust as you like. I do not need credit. Just hope to get the bug fixed asap.
closes #4161
=> decred: Add input_derive_script.

core/embed/bootloader/.changelog.d/3709.changed, core/embed/bootloader/.changelog.d/4081.changed, core/embed/bootloader/.changelog.d/4133.added, core/embed/bootloader/.changelog.d/4133.changed, core/embed/bootloader/.changelog.d/4140.fixed, core/embed/bootloader/CHANGELOG.md, core/embed/bootloader/main.c, core/embed/prodtest/.changelog.d/3752.added, core/embed/prodtest/.changelog.d/4064.added, core/embed/prodtest/.changelog.d/4140.changed, core/embed/prodtest/CHANGELOG.md, core/embed/prodtest/optiga_prodtest.c, core/embed/trezorhal/secret.h, core/embed/trezorhal/stm32f4/secret.c, core/embed/trezorhal/stm32u5/secret.c
This PR fixes several unreleased bootloader issues, recently introduced:
- reporting bootloader unlock state via features
- firmware downgrade protection was using incorrect version in one place
- unlocking bootloader on U5 was granting HDP access to firmware, which is unwanted as it contains other stuff than optiga pairing secret
- and finally, fixes prodtest issue when running prodtest on unlocked bootloader. Note that there are differences between F4 and U5. Unlocking bootloader on F4 will result in prodtest being able to pair optiga again (unless optiga is locked of course). On U5 this is not allowed (as HDP contains other stuff so we can't make it accessible again).
=> fix bootloader unlocking issues

core/translations/it.json, core/translations/pt.json, core/translations/signatures.json, core/translations/tr.json
fixes `translations/cli.py gen` after #4047
=> Fix Safe3 fonts for pt/br/it

core/embed/rust/src/ui/component/base.rs, core/embed/rust/src/ui/flow/swipe.rs
=> chore(core): remove duplicated FlowMsg conversion

.github/actions/upload-coverage/action.yml, .github/workflows/core.yml, .github/workflows/prebuild.yml
Example comment below :arrow_down:, wording suggestions appreciated.
Also remove Italian from the language matrix for full CI pipeline (with `translations` PR label) as discussed with @Hannsek
=> ci: warn when Cargo.lock is edited, don't test :it:

core/embed/trezorhal/stm32f4/monoctr.c
fix needed due to some usage changes we did on last minute - non-production builds need better emulation.
=> fix f4 monoctr in non-production builds

core/embed/rust/src/io.rs
This PR resolves issue #4217, which caused slow decoding of user JPEG images.
The bug appeared after the permanent switch to `NEW_RENDERING` and only affects the T model. Since the bug is not present in any official release, no update to the release notes is required.
=> fix(core): fix slow jpeg decoding

core/embed/boardloader/main.c, core/embed/trezorhal/secret.h, core/embed/trezorhal/stm32f4/secret.c, core/embed/trezorhal/stm32u5/secret.c
This PR fixes unwanted behavior, which happens on soft restarts on U5 mcus. 
The BHK is not unlocked during normal reboots, and this was detected in bootloader, which then invoked reboot and unlocked BHK (via TAMP_CR2_BKERASE). 
This is somewhat sub-optimal, as its adds additional boardloader-bootloader cycle, which takes some time and also flickers the display, even more so if display content isn't retained during boardloader-bootloader handoff.
This isn't issue for current models in production, as normally there are either power cycles, or reboots from firmware/bootloader that behave correctly, but one can observe this during development when resetting with debugger, or even pin resets on discovery kits.
To address this, BHK unlock cycle is done immediately in boardloader. In theory, we …
=> reboot immediately in boardloader if BHK is locked

core/embed/trezorhal/stm32f4/bootutils.c
This PR fixes the firmware deadlock issue that occurred after the interaction-less update. Th bug was introduced in PR #4188, and only affects T and TS3 models. 
The fix adds a transition from handler mode to thread mode before jumping to the bootloader.
=> fix(core): fix handover to bootloader

core/embed/rust/build.rs
to make it easier to run cargo separately, and support rust-analyzer without tweaking its config
=> build(core/rust): provide a default value for BUILD_DIR

core/SConscript.bootloader, core/SConscript.bootloader_ci, core/SConscript.bootloader_emu, core/SConscript.firmware, core/SConscript.prodtest, core/SConscript.reflash, core/SConscript.unix, core/embed/extmod/modtrezorutils/modtrezorutils-meminfo.h, core/site_scons/models/D001/__init__.py, core/site_scons/models/D002/__init__.py, core/site_scons/models/T2B1/__init__.py, core/site_scons/models/T2T1/__init__.py, core/site_scons/models/T3B1/__init__.py, core/site_scons/models/T3T1/__init__.py, core/site_scons/models/__init__.py, core/site_scons/tools.py, core/site_scons/ui/__init__.py, core/site_scons/ui/common.py, core/site_scons/ui/mercury.py, core/site_scons/ui/tr.py, core/site_scons/ui/tt.py
This PR refactors how UI configuration is done in sconscripts.
A single configuration file per given UI type is introduced. This file defines what fonts, build constants etc should be used in build, depending on concrete target.
Each model carries information what UI type its using.
=> refactor ui configuration in build scripts

core/embed/trezorhal/stm32f4/xdisplay/st-7789/display_fb.c, core/embed/trezorhal/stm32f4/xdisplay/st-7789/display_internal.h
This PR fixes the problem of decreased display framerate on TS5.
Two issues were addressed:
1. Incorrect detection of exception/handler mode inside `display_refresh()`, which caused unnecessary waiting for the TE signal.
2. Removed unnecessary framebuffer copying in `display_get_frame_buffer` (this is not actually a bug fix, but an optimization).
The bug 1) was introduced in #4188, so no changelog entry is needed.
=> TS5 framerate fix

core/embed/trezorhal/stm32f4/syscall_stubs.c
This PR fixes a bug introduced in PR #4188 that causes a deadlock when upgrading to a higher firmware version from the firmware itself (also known as an interaction-less update).
No changelog entry is needed, as this bug is not present in any official release.
=> fix(core): fix interaction-less update

python/.changelog.d/4076.added, python/src/trezorlib/protobuf.py
This makes protobuf messages look much nicer in IPython:
Before:
<tt>In[5]: client.features
Out[5]:
<Features: {'vendor': 'trezor.io', 'major_version': 2, 'minor_version': 7, 'patch_version': 2, 'device_id': '[redacted]', 'pin_protection': True, 'language': 'en-US', 'label': '[redacted]', 'initialized': True, 'revision': b'\xdau\xd8\xf4\xb6t\x10\xb4\n\x9c\xfd)T\xd1\x83\xd8\x1d\xd6\xe8\xe8', 'unlocked': False, 'model': 'T', 'fw_vendor': 'SatoshiLabs', 'capabilities': [<Capability.Bitcoin: 1>, <Capability.Bitcoin_like: 2>, <Capability.Binance: 3>, <Capability.Cardano: 4>, <Capability.Crypto: 5>, <Capability.Ethereum: 7>, <Capability.Monero: 9>, <Capability.Ripple: 11>, <Capability.Stellar: 12>, <Capability.Tezos: 13>, <Capability.U2F: 14>, <Capability.Shamir: 15>, <Capability.ShamirGroups: …
=> feat(python): add pretty-printing of protobuf messages in IPython

core/src/trezor/crypto/slip39.py, core/tests/test_trezor.crypto.slip39.py
Implements a function which extends a set of SLIP-39 mnemonics by extra shares, while maintaining the threshold.
This, for example, allows extending a 2-of-2 backup to 2-of-3, where the first two shares remain the same. It also allows reconstructing lost shares by providing any threshold number of shares and requesting the original share count.
The implementation is limited to Slip39_Basic, i.e. single group.
Slack thread: https://satoshilabs.slack.com/archives/C016ACNF1BN/p1727975559358469
=> SLIP-39 extend_mnemonics()

core/embed/trezorhal/mpu.h, core/embed/trezorhal/stm32f4/mpu.c, core/embed/trezorhal/stm32f4/xdisplay/st-7789/display_driver.c, core/embed/trezorhal/stm32f4/xdisplay/st-7789/display_fb.c, core/embed/trezorhal/stm32f4/xdisplay/stm32f429i-disc1/display_driver.c, core/embed/trezorhal/stm32f4/xdisplay/ug-2828/display_driver.c, core/embed/trezorhal/stm32f4/xdisplay/vg-2864/display_driver.c, core/embed/trezorhal/stm32u5/mpu.c, core/embed/trezorhal/stm32u5/xdisplay/stm32u5a9j-dk/display_driver.c, core/embed/trezorhal/stm32u5/xdisplay/stm32u5a9j-dk/display_fb.c, core/embed/trezorhal/stm32u5/xdisplay/stm32u5a9j-dk/display_internal.h
This small PR adds precise access control for the framebuffer (and resolves #4207).
This change is primarily aimed at devices using two framebuffers (T3T1) but also affects devices using a single framebuffer (T2B1, T3B1).
Before this change, the unprivileged app had access to both framebuffers at any time. Now, an unprivileged application has access only to the framebuffer acquired by `display_get_frame_buffer()` until it releases it by calling the `display_refresh()` function.
=> Framebuffer access control

core/embed/trezorhal/stm32f4/reset_flags.c, core/embed/trezorhal/stm32u5/reset_flags.c
This PR fixes a recently introduced bug in the refactoring of the low-level module that is blocking the production build.
The reset flags for STM32F4 and STM32U5 were mistakenly swapped.
=> fix(core): correct swapped F4/U5 reset flags

.github/workflows/core.yml, core/embed/trezorhal/unix/systimer.c
* do not build T3W1 production images because we don't have the right vendor header
* memory bug in emulator found by ASan
=> ci: fix failing nightly pipeline

core/embed/prodtest/.changelog.d/4252.added, core/embed/prodtest/README.md, core/embed/prodtest/main.c, core/embed/trezorhal/stm32f4/touch/ft6x36.c, core/embed/trezorhal/stm32f4/touch/stmpe811.c, core/embed/trezorhal/stm32u5/touch/sitronix.c, core/embed/trezorhal/touch.h, core/embed/trezorhal/unix/touch.c
Fixes #4252 .
This PR adds TOUCH_POWER command to prodtest, that forces the power supply to turn on for specified time, so that its output can be measured without the need to have touch panel connected.
=> add TOUCH_POWER command to prodtest

core/embed/lib/gfx_draw.c, core/embed/trezorhal/unix/display_driver.c, core/site_scons/models/T3W1/emulator.py
This PR introduces support for 32bit colors in emulator.
T3W1 emulator is switched to use these colors.
=> support 32 bit colors in emulator

docs/common/reproducible-build.md
fixes #3418
fixes #4254 
@bosomt please try reproducible builds based on these instructions
@Hannsek please review in terms of readability
=> docs: update reproducibility instructions

core/.changelog.d/4261.fixed, core/embed/rust/src/ui/model_mercury/component/number_input_slider.rs
This PR adds handling of the `TouchStop` event for `NumberInputSliderDialog` struct on T3T1 (resolves #4261). 
Changes include:
1. In `NumberInputSliderDialog` event function, handling of the `None` value (`TouchEnd` event in `NumberInputSlider` ) is added. It fixes the logic, when the _Adjust_ or _Apply_ strings are shown to the user.
=> fix(core/rust) Handle touchStop event in brightess dialog

core/SConscript.bootloader_emu, core/embed/bootloader/emulator.c, core/embed/bootloader/main.c, core/embed/bootloader/messages.c, core/embed/lib/error_handling.c
This PR fixes the Trezor firmware build and runtime on macOS.
- Fixes a crash caused by the stack protector during display initialization in the firmware emulator.
- Resolves several issues with building bootloader_emu using Apple Clang.
This also solved the problem with 64-bit arm builds mentioned in #4259.
=> Fix emulators on MacOS

python/.changelog.d/4282.added, python/src/trezorlib/cli/device.py
This PR adds a shortcut in trezorlib for the "academic" seed:
`trezorctl device load -a`
`trezorctl device load --academic`
Changes include:
1.  Adding `-a`/`--academic` argument to the device load function and providing "academic" mnemonic in trezorlib
2. Resolving possible collisions with `mnemonic` and `slip0014` arguments
=> chore(python): add shortcut in trezorlib for academic seed

core/embed/prodtest/.changelog.d/4310.fixed, core/embed/prodtest/main.c
This PR fixes #4310,  the bug of CPUID READ command in protest.
=> fix(core/prodtest): fix CPUID READ command

core/.changelog.d/4271.added, core/src/apps/bitcoin/keychain.py
Unchained plans to support p2wsh using the same `m/45` path we use for p2sh. This change adds the `UNCHAINED_` patterns to bitcoin `InputScriptType.SPENDP2SHWITNESS`.
=> feat: support Unchained p2wsh path

core/Makefile, core/translations/order.py
One more check in addition to #4327 that aims to prevent the situation where the indices in `order.json` are not contiguous, which can easily happen during merge conflict resolution (see fix in: #4299).
=> core/translations: check order.json for holes

.github/workflows/core.yml, .github/workflows/legacy.yml
Currently the comment with links to UI reports is posted when at least one of the following is satisfied:
1. there are changes in `fixtures.json` compared to `main`,
2. at least one _Device tests_ job fails.
Unfortunately there are cases when the comment would be useful but isn't posted:
* only a _Click tests_ job fails,
* in the current run everything passes, there are no changes in `fixtures.json`, comment isn't posted but in some previous run this was not the case so PR now contains outdated comment.
The first issue can be solved by extending `2.` to click tests and persistence tests, however this creates too many GitHub API requests and gets us 429 rate limited.
So until we figure out something better let's just post the comments always and hope that people who never touch the UI code …
=> ci: always post UI report comment to PR

core/.changelog.d/4295.fixed, core/embed/rust/src/ui/model_mercury/flow/set_brightness.rs
This PR aligns the color and icon of 'Success' string in `SetBrightness` flow to match one in `GetAddress` flow.
Changes include:
1. Changing font color to green and adding icon to `Success` string in `SetBrightness` flow.
=> fix(core): Fix success color and icon in set_brightness flow

core/.changelog.d/4294.fixed, core/embed/rust/src/ui/model_mercury/flow/show_tutorial.rs
This PR aligns the Swipe Right action in tutorial flow Menu Page with the Cancel Menu action (pressing the cross).
Changes include:
1. Changing Right direction swipe action in the Menu page
=> chore(core): Fix swipe-back action in tutorial flow menu

core/embed/trezorhal/mpu.h, core/embed/trezorhal/stm32f4/consumption_mask.c, core/embed/trezorhal/stm32f4/mpu.c
MPU_MODE_KERNEL_SRAM is removed as it doesn't have any effect.
The SRAM is always accessible by kernel, and blocked in APP mode. Making it explicitly available again doesn't provide any value.
Only placed it was used was consumption mask on F4. This still works after removal on T2B1.
=> remove MPU_MODE_KERNEL_SRAM

core/SConscript.unix
With this change, the command `PYOPT=0 TREZOR_MEMPERF=1 make build_unix_frozen` successfully creates a local build with `micropython.alloc_count()` included.
=> fix(core): fix TREZOR_MEMPERF flag

poetry.lock, python/src/trezorlib/cli/__init__.py
Click 8.1.3 -> 8.1.7
- Change log: https://click.palletsprojects.com/en/stable/changes/
- Releases: https://github.com/pallets/click/releases
Autoflake 1.4 -> 2.3.1
- Releases: https://github.com/PyCQA/autoflake/releases
=> Bump autoflake and click packages

core/embed/rust/librust_qstr.h, core/embed/rust/src/ui/model_mercury/flow/confirm_action.rs, core/embed/rust/src/ui/model_mercury/flow/confirm_firmware_update.rs, core/embed/rust/src/ui/model_mercury/flow/confirm_output.rs, core/embed/rust/src/ui/model_mercury/flow/confirm_reset.rs, core/embed/rust/src/ui/model_mercury/flow/confirm_set_new_pin.rs, core/embed/rust/src/ui/model_mercury/flow/confirm_summary.rs, core/embed/rust/src/ui/model_mercury/flow/continue_recovery.rs, core/embed/rust/src/ui/model_mercury/flow/get_address.rs, core/embed/rust/src/ui/model_mercury/flow/mod.rs, core/embed/rust/src/ui/model_mercury/flow/prompt_backup.rs, core/embed/rust/src/ui/model_mercury/flow/request_number.rs, core/embed/rust/src/ui/model_mercury/flow/request_passphrase.rs, core/embed/rust/src/ui/model_mercury/flow/set_brightness.rs, core/embed/rust/src/ui/model_mercury/flow/show_share_words.rs, core/embed/rust/src/ui/model_mercury/flow/show_tutorial.rs, core/embed/rust/src/ui/model_mercury/flow/util.rs, core/embed/rust/src/ui/model_mercury/flow/warning_hi_prio.rs, core/embed/rust/src/ui/model_mercury/layout.rs, core/mocks/generated/trezorui2.pyi
This PR separates the Rust flows from micropython layer.
The idea is to do the uPy argument parsing in `ui/model_mercury/layout.rs` and then pass them as regular arguments to code in `ui/model_mercury/flow/**.rs`, i.e. they won't be passed as `args: &[Obj], kwargs: &Map`. The goal is to keep the rust flows independent from `micropython` sub-crate. This separation is done for two reasons:
- it simplifies the code in `flows` creation
- it paves the way for apps done completely in Rust and for [UiFeatures](#4322)
This PR has no impact on UI or features.
Note:
- there is a few places with the usage of `Obj` and `IterBuf` - last place is `get_address.rs`, **postponing this for now**
=> refactor(core/mercury): separate upy args parsing

core/SConscript.kernel, core/embed/rust/src/trezorhal/display.rs, core/embed/util/bl_check/bl_check.c, core/site_scons/tools.py
This PR fixes an invalid symbol for the deflated bootloader used in the kernel and the problem with rust unit test build.
1. The structure of the symbol for deflated has been changed, so it no longer contains the path of the original file.
2. Fixed the problem with linking unused symbol `display_wait_for_sync`.
=> fix(core): fix invalid symbol for deflated bootloader

shell.nix
* fix broken OpenOCD on Mac OS X
* also update to openocd-cubeide-v1.13.0
* backports nixos/nixpkgs#229537
* as this causes rebuild (from binaries) of arm-gcc-embedded we only do it with `--args devTools true` to avoid CI slowdown (1-3 minutes per workflow)
=> shell.nix: embedded devtools fixes

core/embed/io/haptic/drv2625/drv2625.c
=> fix enabling/disabling haptics before the driver is initialized

core/site_scons/tools.py
Latest changes from https://github.com/trezor/trezor-firmware/pull/4234 broke compilation with `CMAKELISTS=1`, so this adds some needed escaping.
=> fix cmakelists generation

.github/workflows/core.yml
For `Connect` end-to-end tests, we have this requirement:
- being able to run tests with an emulator from a specified firmware feature/branch, that is still under development (not merged into `main`)
Currently, emulators are built for all PRs, but not uploaded to data.trezor.io ... the artifacts can be found manually in GHActions logs, but it is not a good and reliable way of finding the URL, e.g. https://github.com/trezor/trezor-firmware/actions/runs/11856555307/artifacts/2193027474
With this change, it will be possible to dynamically get the latest emulators for all the models from a static URL - e.g. `data.trezor.io/dev/firmware/emu-branches/trezor_host_protocol/trezor-emu-core-T2B1-universal`
Notes:
- it will need to be tested how the branches with `/` in the name behave (if they …
=> feat(ci): upload emulators from all branches to data.trezor.io

core/Makefile, core/embed/sys/task/unix/system.c
also ~set default~ force-set PYOPT=0 for `make build_unix` which is the previous behavior before #4234 removed it
=> Fix error output in emulator

core/embed/rust/src/ui/flow/swipe.rs
That way we won't pass raw touch events to underlying component if that touch is already part of a swipe.
Fixes a crash when you would swipe right over a Cancel button in menu.
=> fix(core): use the filtered event for subsequent processing

core/embed/rust/src/ui/model_mercury/flow/confirm_output.rs
`flow_confirm_output` behaved wrong in "Cancel" screen which is followed by "Tap to cancel" screen. The swipe settings was not aligned with the `handle_swipe` implementation.
=> fix(core/mercury): tap to cancel UX

core/src/trezor/ui/__init__.py, core/src/trezor/ui/layouts/common.py, core/src/trezor/ui/layouts/homescreen.py
fixes flickering when account discovery is running
=> fix(core): properly send the resume signal to homescreen layouts

.github/actions/ui-report/action.yml, .github/workflows/core.yml, .github/workflows/legacy.yml
No significant speedup observed, the longest (T2B1) ui-report action takes 6m30s (previously around 8m?). May still be worth it for not filling the log with useless info.
=> ci: less verbose S3 upload

core/.changelog.d/3692.fixed, core/embed/rust/src/ui/model_tr/component/input_methods/choice.rs
=> fix(core) Fix auto-mover hitting wall scenario

.github/workflows/core.yml
In the AddressSanitizer-enabled emulator build job, when building bootloader emulator, the Rust standard library tries to link with ASAN runtime even though we do not support it at all. I don't understand what causes it, possibly rustc/cargo notices that `ADDRESS_SANITIZER=1` is set and does this? May or may not be related to #4234.
https://github.com/trezor/trezor-firmware/actions/runs/12020560773/job/33509404323
This patch disables bootloader emulator in the job since there's not point in it anyway.
=> ci: fix bootloader_emu trying to link with ASAN

legacy/firmware/.changelog.d/4324.added, legacy/firmware/crypto.c
This change supports new Unchained paths for p2wsh addresses on legacy devices.
=> Legacy firmware support for Unchained paths

core/embed/util/option_bytes/stm32u5/option_bytes.c
Adjusted option bytes for larger boardloader area, pull it automatically from flash layout settings.
=> fix option bytes settings for U5G models

.github/workflows/core.yml, .github/workflows/legacy.yml
Let's see if not posting the comment right after the job starts helps.
Also disable this for legacy firmware since two comments are twice as annoying and the changes are rare anyway. You can still see the table under the artifacts list.
=> ci: work around rate limit, no comment for legacy

build-docker.sh, core/embed/projects/firmware/mpconfigport.h, core/embed/projects/unix/mpconfigport.h, core/site_scons/tools.py
`git rev-parse --short`
> shortens the object name to a unique prefix with at least length characters. The minimum length is 4
Means the prefix length depends on the exact contents of your .git database, and shallow git clones get shorter prefix.
=> build(core): use deterministic git rev-parse

core/embed/projects/kernel/main.c, core/embed/sys/task/inc/sys/applet.h, core/embed/sys/task/stm32/applet.c
trustozone setting changed: assets area as unprivileged.
=> fix translation area access from coreapp applet

core/embed/rust/src/trezorhal/display.rs, core/embed/rust/src/ui/shape/display/fb_mono8.rs, core/embed/rust/src/ui/shape/display/fb_rgb565.rs, core/embed/rust/src/ui/shape/display/fb_rgba8888.rs
This PR resolve crashes when uninitialized display returns null ptr as framebuffer and firmware attempts to render into it.
We will need to run some stages of prodtest of T3W1 running without display and this enables it, but we should probably consider allowing this explicitly via some OTP flag, and implement somewhat more elegant way to shutdown when this is not allowed. however, I consider this out of scope in this PR.
=> resolve crashes when running without display

core/embed/util/rsod/rsod.c
adds default title, footer or message if some of these are not set
=> fix missing rsod info

crypto/ed25519-donna/ed25519-donna-impl-base.c
This pull request builds on top of https://github.com/trezor/trezor-firmware/pull/4374, it fixes https://github.com/trezor/trezor-firmware/issues/4393. I don't know if we want to update the version of gcc once the issue is fixed, so I kept it the same as the version of gcc-arm-embedded. Which means you need to update gcc to version 14 to verify if this pull request indeed resolves the issue.
=> Make ge25519_cmove_stride4b constant time

core/embed/io/display/st-7789/display_fb.c, core/embed/io/display/st-7789/display_internal.h
This PR fixes problem with raising backlight before the display driver IC actually copies framebuffer from its internal memory to panel.
Addition display refresh cycle is now waited before raising the backlight to avoid remnants of previous frame being shown.
=> fix display refresh on TS5

core/embed/sys/linker/stm32f4/firmware.ld
moved the crypto data to flash 1.
=> re-balance distribution in flash on F4 models

core/src/apps/bitcoin/get_address.py, core/src/apps/bitcoin/multisig.py, tests/device_tests/bitcoin/test_multisig.py
This pull request aims to fix an issue introduced in https://github.com/trezor/trezor-firmware/pull/4351 and [discovered](https://github.com/trezor/trezor-firmware/pull/4351#issuecomment-2533092420) by @andrewtoth: The signatures and witnesses for multisig scripts were serialized without regard to the order specified by `MultisigPubkeys`.
=> Fix serialization of signatures and witnesses in multisig

core/.changelog.d/2299.changed, core/.changelog.d/3633.changed, core/.changelog.d/3813.fixed, core/.changelog.d/3863.added, core/.changelog.d/4041.added, core/.changelog.d/4176.fixed, core/.changelog.d/4271.added, core/.changelog.d/4294.fixed, core/.changelog.d/4295.fixed, core/.changelog.d/4302.added, core/.changelog.d/4302.added.1, core/.changelog.d/4302.added.2, core/.changelog.d/4302.added.3, core/.changelog.d/4302.fixed, core/.changelog.d/4309.fixed, core/.changelog.d/4326.fixed, core/CHANGELOG.T2B1.md, core/CHANGELOG.T2T1.md, core/CHANGELOG.T3B1.md, core/CHANGELOG.T3T1.md, core/CHANGELOG.md, core/translations/signatures.json
Merges `release/24.12` into main.
Please merge using `git merge --ff-only` & push manually so that the merge commit is preserved. Previous release: #4340
=> Merge 24.12 release branch

.github/workflows/common.yml, .github/workflows/core.yml, .github/workflows/legacy.yml, .github/workflows/prebuild.yml, build-docker.sh
Only for scheduled and manual pipelines so as not to slow down regular PRs.
I tried all models in a single build but ran into `No space left on device`. Job per model is faster but eats more compute time because every job builds its own docker image.
You can see all fingerprints in [workflow summary](https://github.com/trezor/trezor-firmware/actions/runs/12148645944?pr=4420#summary-33877558860).
Based on #4418.
=> ci: add build-docker.sh jobs

.clang-format
Update clang-format style to add new line at EOF if missing
=> style: update cstyle to add new line at EOF if missing

rust/trezor-client/Cargo.lock, rust/trezor-client/Cargo.toml, rust/trezor-client/src/transport/udp.rs, rust/trezor-client/src/transport/webusb.rs
The Rust client will unilaterally timeout after 100 seconds which causes connection errors when interacting with the device between protocol messages. 100 seconds is borderline for some use cases such as complicated transaction verification. This isn't seemingly a problem with the web or Python libraries so without a keep-alive mechanism this fix at least alleviates the problem with no ill effects.
Can we bump the version with this fix also?
=> Fix Rust Trezor-Client Timeouts

rust/trezor-client/src/transport/udp.rs, rust/trezor-client/src/transport/webusb.rs
fixes test failure introduced in #4459
=> refactor(rust/trezor-client): nicer way to specify timeouts

core/.changelog.d/3324.fixed, core/embed/rtl/error_handling.c, core/embed/rust/src/ui/layout_samson/component/error.rs
=> fix(core): rework 'too many PIN attempts' RSOD

build-docker.sh
macOS recently introduced sha256sum command which can not read from stdin if "-c" option is provided
using shasum first fixes this issue
=> build(build-docker): use shasum first, then sha256sum

core/embed/io/usb/inc/io/usb.h, core/embed/io/usb/unix/usb.c, core/embed/upymod/modtrezorio/modtrezorio-hid.h, core/embed/upymod/modtrezorio/modtrezorio-poll.h, core/embed/upymod/modtrezorio/modtrezorio-webusb.h, core/mocks/generated/trezorio/__init__.pyi, core/src/apps/webauthn/fido2.py, core/src/trezor/wire/codec/codec_v1.py, core/tests/test_trezor.wire.codec.codec_v1.py
This PR changes the way reading from USB works: the polling mechanism is only used to detect if there is a new message, the reading itself is done separately.
The emulator implementation is modified a bit, since there is a need to do the PING-PONG and it is undesirable to emit a CAN_READ event due to this- therefore the message is read into buffer during polling, and the read from the buffer upon read.
This should enable some optimized usage of the message buffer, but this is not done in this PR.
=> split polling can_read and reading from USB

core/.changelog.d/4491.fixed, core/embed/io/display/st-7789/display_driver.c, core/embed/io/display/st-7789/display_panel.c, core/embed/io/display/st-7789/display_panel.h
note to self: dont forget to sync the new ifdefs with https://github.com/trezor/trezor-firmware/pull/4477
=> fix wrong RSOD color on some older Model T devices

common/models.json
Following up on [Suite PR](https://github.com/trezor/trezor-suite/commit/8764cd149ad60ba74efb5238c0277199624fb385), Adding new color variant of T3T1 also to FW part.
=> feat(common): add new t3t1 color variant

common/defs/blockchain_link.json
Update Solana backend domains.
[solana1.trezor.io](https://solana1.trezor.io/) and others are dead, replaced by [sol1.trezor.io](https://sol1.trezor.io/)
=> fix(common): update solana domains

core/.changelog.d/4500.fixed, core/embed/rust/src/ui/layout_samson/component/button_controller.rs, core/embed/rust/src/ui/layout_samson/component/page.rs
This PR fixes an issue that happens when the "middle" button is pressed on a page that should not handle middle or left button presses. If, when releasing the "middle" button (left + right), the left one is the first one to be released, this triggered a left button press which would cancel an otherwise uncancelable page, like this one:
To reproduce the bug (before the fix):
* `trezorctl device setup`
* keep confirming ever page until you arrive at the page shown in the screenshot above
* press the left button and keep it pressed
* while the left button is pressed, press the right button and keep both pressed
* release the left button
* now the process is canceled even though it should not be possible to cancel it
Note: this fix affects both the `ButtonController` and the `ButtonPage`. …
=> Disallow canceling on uncancelable pages on T3B1

core/.changelog.d/3772.fixed, core/embed/rust/src/ui/event/button.rs, core/embed/rust/src/ui/layout_samson/component/button_controller.rs, core/embed/rust/src/ui/layout_samson/component/hold_to_confirm.rs, core/embed/rust/src/ui/layout_samson/component/loader.rs
On TS3, when holding a button to confirm, pressing the other button now cancels the "hold".
Note: we want to cancel it without an animation rather than with the "shrinking" animation as if the held button was released!
=> Make button press cancel current hold

core/embed/rust/src/translations/generated/translated_string.rs, core/embed/rust/src/translations/generated/translated_string.rs.mako, core/mocks/trezortranslate_keys.pyi.mako, core/translations/cli.py, core/translations/cs.json, core/translations/de.json, core/translations/es.json, core/translations/fr.json, core/translations/it.json, core/translations/pt.json, core/translations/tr.json, python/src/trezorlib/_internal/translations.py, python/src/trezorlib/debuglink.py
Following #4489.
Also, use layout names for translation font keys.
=> Support per-layout translations entries

python/src/trezorlib/firmware/models.py
The keys were also entered [into notion](https://www.notion.so/satoshilabs/Trezor-signing-derivation-paths-b3b6e733d3434bd3a834ce5fc9bd557b?pvs=4#182dc52606068076aba4fc2346049c32)
=> chore(python): add production keys for T3W1

core/.changelog.d/4492.fixed, core/embed/io/display/st-7789/display_fb.c, core/embed/projects/bootloader/.changelog.d/4492.fixed, core/embed/rust/librust_qstr.h, core/embed/rust/src/time.rs, core/embed/rust/src/ui/api/firmware_micropython.rs, core/embed/rust/src/ui/display/mod.rs, core/embed/upymod/modtrezorui/modtrezorui-display.h, core/mocks/generated/trezorui.pyi, core/mocks/generated/trezorui_api.pyi, core/src/trezor/ui/__init__.py, core/tests/test_trezor.ui.display.py
fixes #4392 fixes #4465 
The slow fade in bootloader was due to function raising backlight was taking too long, waiting for display TE signal each time. Waiting for TE is removed as its no longer needed due to different mechanism using pending update - so now we will normally wait only once, after the display content is changed. In addition, the backlight fading function is rewritten to ensure constant fading time, at the possible expense of smoothness.
To mitigate the residual image issue, additional wait cycle is added when raising backlight.
As part of this fix i did i minor refactor, fading from python is now done by calling rust functions. The behavior of the fade is unified, so fading from python will behave a bit differently
Additional problem with fading is done before display …
=> fix fading issues

core/embed/io/nrf/stm32u5/nrf.c, core/embed/upymod/modtrezorio/modtrezorio-ble.h, core/embed/upymod/modtrezorio/modtrezorio-hid.h, core/embed/upymod/modtrezorio/modtrezorio-poll.h, core/embed/upymod/modtrezorio/modtrezorio-webusb.h, core/mocks/generated/trezorio/__init__.pyi, core/mocks/generated/trezorio/ble.pyi, core/src/trezor/wire/codec/codec_v1.py, core/tests/test_trezor.wire.codec.codec_v1.py
This PR fixes few issues with T3W1 / BLE:
- NRF driver didn't proprely disable one of the interrupts
- wrong code alignment in trezorlib
- adjustments to codec_v1 were made to accommodate the fact that our BLE implementation uses differently sized RX and TX packets
=> minor t3w1/ble related fixes

core/embed/io/display/st-7789/display_driver.c, core/embed/io/display/st-7789/display_fb.h, core/embed/io/display/st-7789/display_internal.h, core/embed/io/display/st-7789/display_nofb.c
follow up for https://github.com/trezor/trezor-firmware/pull/4492
turns out model T, or rather non-framebuffer models, also need this treatment.
=> fix flashing old display content on model T

legacy/firmware/messages.c
Fixes #3892 hopefully.
It seems that some Cortex-M3 instructions support unaligned access and some don't? Couldn't find it explained in a single place, however it seems that STRD (64bit store) can't handle it.
=> fix(legacy): uint64 protobuf field decoding

core/.changelog.d/4537.fixed, core/src/trezor/ui/layouts/bolt/recovery.py, core/src/trezor/ui/layouts/caesar/recovery.py, core/src/trezor/ui/layouts/delizia/recovery.py
- seems that keyboard LayoutObj was not properly deallocated resulting in MemoryError. Fix by calling the dunder `del` method explicitly fixes the issue
- the problem was on Model T (Bolt), but applying it for all layouts to prevent similar problem
=> fix(core): explicitly delete keyboard layout

poetry.lock, pyproject.toml
compat with python 3.13 - see #4474 and https://github.com/trezor/trezor-firmware/pull/4476#issuecomment-2595214828
kills compat with python 3.8 which is EOL now - https://endoflife.date/python
=> chore(python): bump pillow dependency

Makefile, docs/misc/changelog.md, tools/changelog.py
Added also to `make style`.
[no changelog]
=> style: add `make changelog_style` for automatic changelog formatting

.github/workflows/release-emu.yml
Don't merge this yet, I want to test it on a forked repo to see if it will do what I want it to. 
It utilizes the releases.json file that adds a model list to the version in order to have emulators released for the same models we release firmware for.
=> ci: create emualtor release workflow for release versions

core/embed/rust/src/ui/shape/cache/jpeg_cache.rs
=> adjust jpeg cache size to allow work on larger displays

core/embed/rust/build.rs, core/embed/rust/src/micropython/gc.rs, core/embed/rust/src/trezorhal/display.rs, core/embed/rust/src/trezorhal/storage.rs
By default, ARM eabi has `-fshort-enums` switched on, so we need to pass this flag to clang when building bindings for rust to account for this behavior.
For contrast, unix builds don't use this. SDL also enforces building without this flags via static asserts, so we can't use `-fshort-enums` for the whole of unix, so i opted for using different settings for unix and embedded targets.
=> unify size of enums between rust and C

core/embed/projects/boardloader/main.c, core/embed/projects/bootloader/messages.c, core/embed/projects/bootloader_ci/messages.c, core/embed/sys/linker/stm32u5g/bootloader.ld, core/embed/sys/linker/stm32u5g/firmware.ld, core/embed/sys/linker/stm32u5g/prodtest.ld, core/embed/util/image/image.c, python/src/trezorlib/firmware/core.py, python/src/trezorlib/firmware/models.py
This PR alters the way image hashes are calculated.
Padding between headers and code is now included into hashed area.
In practice, this affects only U5G models, as image and vendor headers are aligned to 512B and such is also is the code alignment on F4 and U585.
T3W1, even though running on U5G, both its image headers and vendor headers are aligned to 1024B, by coincidence, so existing boardloaders and bootloaders should continue to work.
Therefore, only D002 will break and needs reflashing of board+bootloader to work.
Thanks to this change, code alignment can be omitted from trezorctl.
=> calculate image hash including padding between header and code

.github/actions/upload-coverage/action.yml
For example: https://github.com/trezor/trezor-firmware/actions/runs/12976369614/job/36188913357
```
Run nix-shell --run "poetry run make -C core coverage"
make: Entering directory '/home/runner/work/trezor-firmware/trezor-firmware/core'
./tools/coverage-report
COVERAGE_THRESHOLD set to 77%
.coverage.core_click_test12
.coverage.core_click_test13
.coverage.core_click_test14
.coverage.core_click_test15
.coverage.core_click_test16
.coverage.core_click_test17
.coverage.core_device_test30
.coverage.core_device_test31
.coverage.core_device_test32
.coverage.core_device_test33
.coverage.core_device_test34
.coverage.core_device_test35
.coverage.core_fido2_test1
.coverage.core_monero_test2
.coverage.core_persistence_test2
.coverage.core_u2f_test2
.coverage.gw0
.coverage.gw1
.coverage.gw2 …
```
=> ci: fix `JSONDecodeError` when combining `.coverage.gw*` files

core/SConscript.firmware
It is useful to find the top-most stack consuming functions:
```
$ make build_firmware
$ arm-none-eabi-size -A build/firmware/firmware.elf | grep .stack_sizes
.stack_sizes          7523           0
$ cargo install stack-sizes@0.4.0
$ stack-sizes build/firmware/firmware.elf | grep trezor_lib | sort -k2 -n | tail -n10
0x081c1721	3536	trezor_lib::ui::api::firmware_micropython::new_confirm_properties::h2ab0feebaf154486
0x081c0e7d	3560	trezor_lib::ui::api::firmware_micropython::new_confirm_modify_output::h04465b97d57fafb6
0x081c6161	3688	trezor_lib::ui::api::firmware_micropython::new_show_checklist::he16b109bc4dff398
0x081c4089	4240	trezor_lib::ui::api::firmware_micropython::new_request_pin::h3280c5eff8900a22
0x081be3e1	4960	trezor_lib::ui::api::firmware_micropython::new_confirm_action::h860f87 …
```
=> build(core): export Rust functions' stack sizes

core/embed/rust/src/ui/layout_bolt/bootloader/mod.rs, core/embed/rust/src/ui/layout_delizia/bootloader/mod.rs
applies to cases when vendor info is shown but no warning is set.
[no changelog]
=> fix boot screen background color 

core/embed/io/display/ltdc_dsi/display_driver.c, core/embed/io/display/ltdc_dsi/panels/lx200d2406a/lx200d2406a.h, core/embed/io/display/ltdc_dsi/panels/lx250a2401a/lx250a2401a.h, core/embed/io/display/ltdc_dsi/panels/stm32u5a9j-dk/stm32u5a9j-dk.h
This PR adjusts T3W1 display refresh rate to be closer to 60Hz.
This is done by adjusting lane byte frequency, as opposite to adjusting porch setting, after discussing this with display supplier.
=> adjust T3W1 display refresh rate

tests/device_tests/bitcoin/test_authorize_coinjoin.py
Otherwise, the current timeout is exceeded when running the test on the following hardware models:
```
>       assert delay <= max_expected_delay
E       assert 72.02440977096558 <= 60
```
```
>       assert delay <= max_expected_delay
E       assert 77.36052393913269 <= 60
```
=> test(core): increase test timeout for HW devices

.github/workflows/core-hw.yml, core/tests/run_tests_device_emu_monero.sh, shell.nix
Fixes #3128. Work in progress, `gen_trezor_wallet_passphrase`.
=> Update monero tests binary

core/embed/gfx/gfx_draw.c, core/embed/projects/prodtest/.changelog.d/4564.fixed, core/embed/projects/prodtest/main.c
This PR fixes problem with test rendering of 1BPP fonts in C. 
Welcome screen (with QR) in prodtest for T3B1 and T3B1 is fixed to account for smaller display -> smaller QR size, different text position and colors (which are due to different background color).
=> fix QR and text display in T3B1 prodtest 

common/protob/messages-debug.proto, core/Makefile, core/src/apps/debug/__init__.py, core/src/trezor/messages.py, python/src/trezorlib/debuglink.py, python/src/trezorlib/messages.py, rust/trezor-client/src/protos/generated/messages_debug.rs, tests/click_tests/common.py, tests/click_tests/recovery.py, tests/click_tests/reset.py, tests/click_tests/test_autolock.py, tests/click_tests/test_lock.py, tests/click_tests/test_pin.py, tests/click_tests/test_tutorial_caesar.py, tests/click_tests/test_tutorial_delizia.py, tests/common.py, tests/conftest.py, tests/input_flows.py, tests/input_flows_helpers.py, tests/ui_tests/__init__.py, tests/ui_tests/reporting/testreport.py, tests/upgrade_tests/recovery_old.py
In case the main workflow is restarting after a `DebugLinkDecision`, sending the response of `DebugLinkGetState` may get interrupted (see #4401).
Let's make the full `DebugLinkGetState` fetching explicit, to avoid the "restart" race condition.
=> test(core): don't fetch full `DebugLinkState` by default

core/embed/projects/prodtest/cmd/prodtest_haptic.c, core/embed/projects/prodtest/cmd/prodtest_touch.c
This PR fixes the haptic test in prodtest. The bug was introduced in #4430 but is not present in any official release.
The logic for driver initialization and deinitialization has been refined:
1) All drivers are initialized in `drivers_init()` when prodtest starts.
2) Each test calls `{driver}_init()` and checks the result.
3) No test should call `{driver}_deinit()`, ensuring that all drivers remain active throughout.
=> fix(prodtest): fix haptic test

core/embed/sys/startup/inc/sys/sysutils.h, core/embed/sys/startup/stm32/bootutils.c, core/embed/sys/startup/stm32/sysutils.c, core/embed/sys/task/stm32/system.c
This small PR fixes a problem introduced in #4499.
The Optiga secret stored in backup registers was unintentionally cleared during the transition from the bootloader to the firmware.
This fix prevents it from being cleared during all forward transitions from the boardloader → bootloader → kernel.
The bug was not present in any released version.
=> fix(core): fix optiga pairing issue

core/embed/io/display/ltdc_dsi/display_gfxmmu.c
This PR changes the default color used by GFXMMU if pixels out of range are accessed.
Previously white, now black.
Turns out, there are cases that access these pixels, i.e. for blurring, and black makes more sense here.
=> fix default (out of range) color used by gfxmmu

.github/workflows/core-hw.yml
Otherwise, the problematic tests seem to be running in CI: 
https://github.com/trezor/trezor-firmware/actions/runs/13230566082/job/36927073823
[no changelog]
=> test(core): use `TESTOPTS` in `core-hw.yml` run step

.github/actions/ui-report/action.yml, .github/workflows/core.yml, tests/conftest.py, tests/emulators.py
Otherwise, tailing and uploading when running `make test_emu_ui_multicore` fail: 
https://github.com/trezor/trezor-firmware/actions/runs/13049022289/job/36405211984?pr=4558
=> ci(core): collect debug logs also from `multicore` tests

.github/workflows/core-hw.yml
Currently, both jobs are testing universal firmware:
=> ci(core): add a missing `BITCOIN_ONLY` definition to `core-hw.yml`

.github/workflows/core-hw.yml, poetry.lock
Currently, there are no logs from failed tests in case of a timeout:
https://github.com/trezor/trezor-firmware/actions/runs/13252434089/job/36993028885
For example, in the above run, all tests seem to timeout (after 20m) after the first test failure (at `04:31:28`), causing the job to timeout (at `08:11:22`) - and there are no pytest failure logs :(
=> Configure hardware CI timeouts to collect pytest logs

core/embed/sys/startup/stm32/bootutils.c
This small PR fixes the `reboot_device()` behavior on the STM32F4 platform.
`reboot_device()` was changed in #4499; instead of resetting the CPU, it now jumps to the bootloader’s `reset_handler`. While this isn’t entirely incorrect, resetting the CPU is preferable. Therefore, this PR reverts that change.
=> fix(core): fix reboot_device function behaviour

core/embed/projects/prodtest/README.md, core/embed/rtl/cli.c
Add an option to exit from prodtest interactive mode with ".+ENTER" command.
If test script or test equipment connects to prodtest serial, it may happen that somebody already switched it to interactive mode before. To make it easier for it, it may switch back to non-interactive mode and don't deal with the colored responses etc. 
Prodtest will confirm the exit command with `OK` in standard mode to be well machine readable.
=> feat(core/prodtest): Allow prodtest to exit from interactive mode 

core/embed/rust/src/ui/display/mod.rs
- IIUC, casting to and from `i32` can be removed.
- `timer.elapsed()` can be evaluated once per loop iteration.
=> refactor(core): simplify `fade_backlight_duration`

core/embed/gfx/jpegdec/stm32u5/jpegdec.c
This PR fixes the issue with decoding grayscale JPEG images on the homescreen, which causes DMA2D to be non-functional in the core app.
No changelog entry needed.
=> fix(core): fix hw jpegdec issue with grayscale images

core/embed/sys/powerctl/stwlc38/stwlc38.c, core/embed/sys/powerctl/stwlc38/stwlc38.h, core/embed/sys/powerctl/stwlc38/stwlc38_defs.h, core/embed/sys/powerctl/stwlc38/stwlc38_internal.h
This PR fixes deinitialzation of STWLC38 driver: 
- interrupt is disabled
- ~~wlc itself is disabled~~
=> fix stwlc38 deinitialization

core/site_scons/models/T3W1/trezor_t3w1_revB.py
this PR increments T3W1 revB revision, making the builds incompatible with revA build. Prevents accidental uploading/running fw on boards with incompatible bootloader.
=> bump T3W1 revB revision

core/embed/rust/src/ui/layout_bolt/component/loader.rs, core/embed/rust/src/ui/layout_caesar/component/loader.rs, core/embed/rust/src/ui/layout_delizia/component/loader.rs
This issue was found while debugging a flaky click test on T3T1 emulator: 
`tests/click_tests/test_lock.py::test_hold_to_lock`
Sample failures:
https://github.com/trezor/trezor-firmware/actions/runs/13209659963/job/36880750418 
https://github.com/trezor/trezor-firmware/actions/runs/13189762414/job/36820368643 
https://github.com/trezor/trezor-firmware/actions/runs/13146713535/job/36686537519 
https://github.com/trezor/trezor-firmware/actions/runs/13124809110/job/36619045092 
https://github.com/trezor/trezor-firmware/actions/runs/13103415015/job/36554567296 
https://github.com/trezor/trezor-firmware/actions/runs/13093382180/job/36532710349
With the following logging added [1], the test failure seems to happen when the loader detects that it is `ShrunkCompletely` (probably due to animation …
=> fix(core): correct loader completion detection

core/embed/rust/src/ui/layout_delizia/flow/util.rs
Otherwise, it fails when showing 4 items.
Note that each item uses in 2 paragraphs. Also, items are separated by an empty paragraph.
So 3 items use 8 (2\*3+2) paragraphs and 4 items use 11 (2\*4+3) paragraphs.
=> feat(core): allow more paragraphs in `ShowInfoParams`

core/embed/rust/librust_qstr.h, core/embed/rust/src/translations/generated/translated_string.rs, core/embed/rust/src/ui/api/firmware_micropython.rs, core/embed/rust/src/ui/layout_bolt/ui_firmware.rs, core/embed/rust/src/ui/layout_caesar/ui_firmware.rs, core/embed/rust/src/ui/layout_delizia/ui_firmware.rs, core/embed/rust/src/ui/layout_eckhart/component/button.rs, core/embed/rust/src/ui/layout_eckhart/component/mod.rs, core/embed/rust/src/ui/layout_eckhart/component/select_word_screen.rs, core/embed/rust/src/ui/layout_eckhart/component/share_words.rs, core/embed/rust/src/ui/layout_eckhart/component/vertical_menu.rs, core/embed/rust/src/ui/layout_eckhart/component/vertical_menu_screen.rs, core/embed/rust/src/ui/layout_eckhart/component_msg_obj.rs, core/embed/rust/src/ui/layout_eckhart/flow/mod.rs, core/embed/rust/src/ui/layout_eckhart/flow/show_share_words.rs, core/embed/rust/src/ui/layout_eckhart/theme/mod.rs, core/embed/rust/src/ui/layout_eckhart/ui_firmware.rs, core/embed/rust/src/ui/ui_firmware.rs, core/mocks/generated/trezorui_api.pyi, core/mocks/trezortranslate_keys.pyi, core/src/trezor/ui/layouts/delizia/reset.py, core/src/trezor/ui/layouts/eckhart/reset.py, core/translations/en.json, core/translations/order.json, core/translations/signatures.json
this PR:
- renames `new_show_share_words_delizia` to `new_show_share_words_extended` because it will be used by eckhart as well
- creates a full-screen and partial components for showing share words
- creates a full-screen component for selecting a word
=> Eckhart share words and select word components

core/embed/projects/prodtest/README.md, core/embed/projects/prodtest/cmd/prodtest_display.c
Add simple `display-text` command to prodtest, which prints the text given in argument.
This is quite useful when the external controller needs to logs some data on tested trezor.  
We use this during battery test to log battery voltage, and actual current load.
prodtest excepts arguments splitted with space character and display-text command excepts only single argument, so to print several words use different spacing character such as "_".
=> Add display-text command to prodtest

core/embed/rust/src/ui/component/maybe.rs, core/embed/rust/src/ui/layout_eckhart/component/button.rs, core/embed/rust/src/ui/layout_eckhart/component/keyboard/bip39.rs, core/embed/rust/src/ui/layout_eckhart/component/keyboard/common.rs, core/embed/rust/src/ui/layout_eckhart/component/keyboard/keypad.rs, core/embed/rust/src/ui/layout_eckhart/component/keyboard/mnemonic.rs, core/embed/rust/src/ui/layout_eckhart/component/keyboard/mod.rs, core/embed/rust/src/ui/layout_eckhart/component/keyboard/passphrase.rs, core/embed/rust/src/ui/layout_eckhart/component/keyboard/pin.rs, core/embed/rust/src/ui/layout_eckhart/component/keyboard/slip39.rs, core/embed/rust/src/ui/layout_eckhart/component/mod.rs, core/embed/rust/src/ui/layout_eckhart/component_msg_obj.rs, core/embed/rust/src/ui/layout_eckhart/flow/mod.rs, core/embed/rust/src/ui/layout_eckhart/flow/request_passphrase.rs, core/embed/rust/src/ui/layout_eckhart/theme/mod.rs, core/embed/rust/src/ui/layout_eckhart/ui_firmware.rs
- button styles for keyboards
- module with common keyboard stuff, i.e. _MultiTapKeyboard_
- keypad grid with dims of 4x3 with buttons overlaying each other when in pressed state
- Full-screen _Pin Keyboard_ component
- Full-screen _Passphrase Keyboard_ component
- first prototype of a _request passphrase_ flow
- Full-screen _Mnemonic Keyboard_ component + _MnemonicInput_ trait
- BIP39 input component
- SLIP39 input component
=> Eckhart keyboards screens

Makefile, common/protob/pb2py
Add `pb2py` for python style linting, i.e. running `make style` now includes `pb2py`.
=> Include pb2py for python style linting

.clang-format
If you create a .c or .h file with CRLF EOL sequence `make cstyle_check` wont recognize any issue nor fix anything with `make cstyle` command. 
On the other hand `make editor_check` will fails with error:
```
Wrong line endings or no final newline
Not all lines have the correct end of line character
```
this PR fix the clang-format to enforce LF EOL sequence, so `make cstyle` command will deal with this automatically.
=> Fix cstyle and editor_check inconsistency

.gitmodules, core/SConscript.prodtest, core/embed/projects/prodtest/README.md, core/embed/projects/prodtest/cmd/prodtest_tropic.c, core/embed/projects/prodtest/main.c, core/embed/sec/tropic/inc/sec/tropic.h, core/embed/sec/tropic/stm32/tropic01.c, core/site_scons/models/T3W1/trezor_t3w1_revA.py, core/site_scons/models/T3W1/trezor_t3w1_revA0.py, core/site_scons/models/T3W1/trezor_t3w1_revB.py, core/vendor/libtropic
This PR integrates libtropic as submodule to fw, adds STM32 port for libtropic and adds some very basic production tests (reading the chip info).
Somewhat conflicting and supplementary:) to https://github.com/trezor/trezor-firmware/pull/4172/
=> add Tropic01 HAL integration and basic production tests

core/embed/gfx/bitblt/dma2d_bitblt.h, core/embed/gfx/bitblt/stm32/dma2d_bitblt.c, core/embed/gfx/jpegdec/stm32u5/jpegdec.c
This PR enhances the HW JPEG decoder to support decoding grayscale images.
Although grayscale images are not accepted by `trezorctl`, we use them internally for the Trezor logo.
=> feat(core): enable hw decoding of grayscale JPEGs

core/embed/upymod/modtrezorcrypto/modtrezorcrypto-bip39.h, core/mocks/generated/trezorcrypto/bip39.pyi, crypto/bip39.c, crypto/bip39.h
Removes the unused function `mnemonic_generate()` from the trezor-crypto bip39.c module and the corresponding unused function `bip39.generate()` in python. The problem with this function is that it directly calls `random_buffer()`, but Trezor generates seeds using different entropy sources `random_buffer()`, Optiga's RNG and the host's RNG. Both legacy and core then use `mnemonic_from_data()` to convert the randomness to a BIP39 mnemonic.
Thanks to @invd for proposing this change.
=> Remove unused function mnemonic_generate()

core/embed/rust/src/ui/shape/bar.rs
This PR fixes a problem with rendering outlines of Bar. Previous implementation drawn sides of the rectangle one over another, which, in combination with `with_alpha` usage, cause different color then the rest of the rect.
=>  fix rendering of outlined Bars

core/embed/rust/src/ui/shape/jpeg.rs
clip was used instead of bounds
=> fix jpeg blurring and dimming area

core/embed/rust/src/ui/flow/swipe.rs, core/embed/rust/src/ui/layout_delizia/flow/confirm_output.rs
Using the script from https://github.com/trezor/trezor-firmware/pull/4555#issuecomment-2640767405:
```
$ python stack_sizes.py | sort -k1 -n | tail
7608	trezor_lib::ui::api::firmware_micropython::new_show_checklist
7904	trezor_lib::ui::api::firmware_micropython::new_show_share_words_delizia
7912	trezor_lib::ui::api::firmware_micropython::new_prompt_backup
7920	trezor_lib::ui::api::firmware_micropython::new_flow_confirm_set_new_pin
9864	trezor_lib::ui::api::firmware_micropython::new_confirm_fido
14104	trezor_lib::ui::api::firmware_micropython::new_tutorial
14648	trezor_lib::ui::api::firmware_micropython::new_continue_recovery_homepage
15184	trezor_lib::ui::api::firmware_micropython::new_flow_get_address
16608	trezor_lib::ui::api::firmware_micropython::new_confirm_summary
19392 …
```
=> fix(core): use `SwipeFlow::add_page` to save stack memory

core/embed/rust/src/ui/layout_eckhart/component/keyboard/mod.rs, core/embed/rust/src/ui/layout_eckhart/component/keyboard/word_count_screen.rs, core/embed/rust/src/ui/layout_eckhart/component/mod.rs, core/embed/rust/src/ui/layout_eckhart/component_msg_obj.rs, core/embed/rust/src/ui/layout_eckhart/ui_firmware.rs
This PR implements Eckhart UI trait function `select_word_count` using a full-screen keyboard component according to [Figma](https://www.figma.com/design/Dkl7W5PLqpr3TnXJ5hbnfd/%E3%80%94-Future-Prod-%E3%80%95Safe-7?node-id=6132-2331&t=GGQCtKryIDj3KN3m-0)
The keyboard works in 2 modes: 1 or 2 columns based on the number of the keys. The cancel button is always present on the bottom/bottom left.
=> Get word count keyboard screen for Eckhart

core/embed/rust/src/ui/layout_bolt/prodtest/mod.rs
The new touch-draw command stopped working properly after https://github.com/trezor/trezor-firmware/pull/4666 was merged.
The reason is that setting both fg and bg colors caused the square to be drawn as outline+background, but with 1px square the outline didn't draw due to the new algorithm cutting the thickness, and background also didn't render anything. So currently we can't draw 1px squares with bg+fg color set, which is a bug itself (i created https://github.com/trezor/trezor-firmware/issues/4702 for that), but there is no reason to set both fg and bg color in this screen, so i simplified it.
=> fix touch draw test

core/embed/sys/startup/stm32/bootutils.c
Initialize systick before jump, as the old bootloaders may not initialize systick on start and rely on systick running from boardloader or firmware. Only relevant for F4, otherwise we are jumping through reset.
=> fix jump to old bootloader

core/embed/rust/src/ui/flow/swipe.rs, core/embed/rust/src/ui/layout_delizia/flow/confirm_action.rs, core/embed/rust/src/ui/layout_delizia/flow/confirm_fido.rs, core/embed/rust/src/ui/layout_delizia/flow/confirm_firmware_update.rs, core/embed/rust/src/ui/layout_delizia/flow/confirm_homescreen.rs, core/embed/rust/src/ui/layout_delizia/flow/confirm_reset.rs, core/embed/rust/src/ui/layout_delizia/flow/confirm_set_new_pin.rs, core/embed/rust/src/ui/layout_delizia/flow/confirm_summary.rs, core/embed/rust/src/ui/layout_delizia/flow/continue_recovery_homepage.rs, core/embed/rust/src/ui/layout_delizia/flow/get_address.rs, core/embed/rust/src/ui/layout_delizia/flow/prompt_backup.rs, core/embed/rust/src/ui/layout_delizia/flow/request_number.rs, core/embed/rust/src/ui/layout_delizia/flow/request_passphrase.rs, core/embed/rust/src/ui/layout_delizia/flow/set_brightness.rs, core/embed/rust/src/ui/layout_delizia/flow/show_danger.rs, core/embed/rust/src/ui/layout_delizia/flow/show_share_words.rs, core/embed/rust/src/ui/layout_delizia/flow/show_tutorial.rs
Following https://github.com/trezor/trezor-firmware/pull/4696 (used to reduce `new_flow_confirm_output` stack size):
```
$ git lg -1
* 587b5e8eb tychovrahe:  (HEAD -> main, origin/main, origin/HEAD) fix(core): fix jump to old bootloader (3 days ago)
$ TREZOR_MODEL=T3T1 make -C core build_firmware; python ~/tmp/stack_sizes.py | sort -k1 -n | tail
...
7256	trezor_lib::ui::api::firmware_micropython::new_show_checklist
7440	trezor_lib::ui::api::firmware_micropython::new_flow_confirm_set_new_pin
7440	trezor_lib::ui::api::firmware_micropython::new_prompt_backup
7512	trezor_lib::ui::api::firmware_micropython::new_show_share_words_delizia
9224	trezor_lib::ui::api::firmware_micropython::new_confirm_fido
13176	trezor_lib::ui::api::firmware_micropython::new_tutorial
14096 …
```
=> feat(core): use `SwipeFlow::add_page` to reduce stack usage

core/embed/rust/src/ui/shape/bar.rs, core/site_scons/models/T3W1/trezor_t3w1_revA.py
This PR resolves #4702 and fixes the prodtest build for T3W1 rev A.
If the background and foreground colors are the same, the bar thickness is not considered. This fixes the problem with 1-pixel bars and also optimizes drawing, as suggested in #4702.
=> fix drawing of 1pix bar shape 

core/embed/gfx/terminal.c, core/site_scons/models/T3W1/trezor_t3w1_revA.py, core/site_scons/models/T3W1/trezor_t3w1_revB.py
This PR improves the readability of text on the terminal on T3W1 by doubling the character width and height and adding a small Y offset.
The terminal window size on T3W1 is now 31x31 characters, which seems sufficient for RSOD purposes.
On other models, the terminal screen remains unchanged.
=> feat(core): double glyphs on t3w1 terminal

core/embed/io/ble/stm32/ble.c
This PR fixes a bug that `ble_issue_command` function always returned false for some commands.
=> fix BLE issue command return value

.github/workflows/core-hw.yml
Also, print [the slowest 50 test durations](https://docs.pytest.org/en/latest/how-to/usage.html#profiling-test-execution-duration).
When analyzing the latest T2B1 CI run, the longest successful test took <5 minutes:
https://github.com/trezor/trezor-firmware/actions/runs/13687527271/job/38274226159
[tests.ods](https://github.com/user-attachments/files/19113891/tests.ods)
=> test(core): decrease single test timeout for HW devices to 10 minutes

core/SConscript.prodtest, core/embed/projects/prodtest/README.md, core/embed/projects/prodtest/cmd/prodtest_pmic.c, core/embed/projects/prodtest/cmd/prodtest_unit_test.c, core/embed/rtl/inc/rtl/unit_test.h, core/embed/rtl/unit_test.c, core/embed/sys/linker/stm32f4/prodtest.ld, core/embed/sys/linker/stm32u58/prodtest.ld, core/embed/sys/linker/stm32u5g/prodtest.ld
This PR introduce an extension to prodtest CLI which allows to register unit tests. 
Idea is, that every driver or firmware component may have a several low level unit tests exercising fundamental features, This should be giving user (or maybe in future to automated tester) the quick overview of the FW and HW integrity. 
Unit tests  ~ compared to prodtest commands ~ are not callable commands from prodtest CLI, but the prodtest CLI introduce new command `unit-test-run`, which run all registered unit tests and return trace of results followed with "OK" if all tests passed.
Example:
```
OK
```
```
ERROR
```
**Unit test design**
unit test of specific driver or FW component should be part of dedicated cmd/prodtest_x.c source file. Every unit test is a function with no arguments which returns …
=> Unit test extension for prodtest CLI 

.github/workflows/core.yml, python/src/trezorlib/_internal/emulator.py, tests/emulators.py
When an exception is raised in the wrong place, pytest exits but leaves emulator process running in the background. This can result in confusing behavior of further pytest invocations which will connect to this old emulator. The fix attempts to keep track of running emulators in a global variable and then kill them in `atexit()` hook.
Included are two more quality of life improvements.
=> fix(tests): don't leave emulator process running

poetry.lock, pyproject.toml, python/tox.ini, setup.cfg, tests/device_tests/test_bip32_speed.py, tests/device_tests/test_busy_state.py
Since it supports re-running all failures that match certain expressions:
https://github.com/pytest-dev/pytest-rerunfailures?tab=readme-ov-file#re-run-all-failures-matching-certain-expressions
=> chore(python): use `pytest-rerunfailures` instead of `flaky`

core/embed/sys/mpu/stm32f4/mpu.c, core/embed/sys/mpu/stm32u5/mpu.c
This PR fixes the MPU configuration for the assets memory area.
The assets memory area is always accessible in read-only mode for unprivileged applications. However, the kernel must use `mpu_reconfig(MPU_MODE_ASSETS)` to gain access. If the application passes references to assets memory via syscalls and the kernel attempts to read from them, an MM fault occurs. 
This issue has manifested since the introduction of DMA2D syscalls. In non-default languages using custom glyphs, the application passes pointers to glyphs in assets memory to the kernel. When glyphs are drawn to unaligned addresses, DMA2D acceleration cannot be used, and the glyphs are drawn manually by the CPU, leading to an MM fault.
The fix is straightforward: the `MPU_MODE_DEFAULT` now includes read-only access to assets …
=> fix(core): add kernel access to assets by default

core/embed/rust/src/ui/layout_delizia/flow/util.rs
It was increased by #4644 but eventually it wasn't used in #4639.
=> chore(core): use smaller vectors for `ShowInfoParams`

nordic/trezor/README.md, nordic/trezor/boards/arm/t3w1_d1_nrf52833/t3w1_d1_nrf52833.dts, nordic/trezor/boards/arm/t3w1_revA_nrf52832/t3w1_revA_nrf52832.dts, nordic/trezor/west.yml
Bump nRF build to latest Nordic Connect SDK to 2.9.0. Fixes build/linker errors caused by changes in NCS (BLE controller settings).
=> Bump Nordic Connect SDK to 2.9.0

core/.changelog.d/4771.fixed, core/src/trezor/ui/layouts/bolt/__init__.py
Otherwise, the translated `Install` text may overflow.
Also, changed the `Confirm` methods signature to minimize copies and reduce stack usage.
=> fix(core): use smaller button for upgrade cancellation

python/src/trezorlib/cli/device.py
Resolves #4694.
According to [docs](https://docs.trezor.io/trezor-firmware/core/index.html?highlight=safe%205#trezor-core):
```
Trezor Core is the second-gen firmware running on Trezor devices. 
It currently runs on Trezor T, Trezor Safe 3 and Trezor Safe 5.
```
I found [impl](https://github.com/trezor/trezor-firmware/blob/0fb1693ea8cb413cf43177d1bcbb033bb7685990/core/src/apps/management/reboot_to_bootloader.py#L57) for "reboot-to-bootloader"command in core, and therefore it's sufficient to remove the line about support for only Model One to make the documentation up-to-date again.
=> chore(python): update cli docs for `reboot-to-bootloader` command

.github/workflows/core-hw.yml, tests/conftest.py
It should help debugging stuck tests (e.g. https://github.com/trezor/trezor-firmware/actions/runs/13935367037/job/39002035625) and analyzing full test runs (e.g. [finding how much time does `DebugGetLinkState` request handling take](https://github.com/trezor/trezor-firmware/commit/75cc399e80d600494cc3510cf61fc3123f86a946#commitcomment-153830441)).
=> test(core): allow saving verbose log into a file

core/embed/rust/src/ui/layout_bolt/component/button.rs
```
`MnemonicKeyboard<Slip39Input>`: 1236 bytes, alignment: 4 bytes
print-type-size     field `.prompt`: 124 bytes
print-type-size     field `.swipe`: 20 bytes
print-type-size     field `.keys`: 792 bytes
print-type-size     field `.back`: 104 bytes
print-type-size     field `.input`: 192 bytes
print-type-size     field `.can_go_back`: 1 bytes
print-type-size     end padding: 3 bytes
```
```
`MnemonicKeyboard<Slip39Input>`: 1280 bytes, alignment: 4 bytes
print-type-size     field `.back`: 108 bytes
print-type-size     field `.input`: 196 bytes
print-type-size     field `.keys`: 828 bytes
print-type-size     field `.prompt`: 124 bytes
print-type-size     field `.swipe`: 20 bytes
print-type-size     field `.can_go_back`: 1 bytes
print-type-size     end padding: 3 bytes
```
=> perf(core): simplify Button struct to save RAM

core/embed/upymod/modtrezorutils/modtrezorutils.c
Otherwise, the unit-tests emit a lot of output:
https://github.com/trezor/trezor-firmware/actions/runs/13949157258/job/39043798020?pr=4798
=> fix(core): don't invoke `dump_meminfo_json` on emulator

core/embed/io/i2c_bus/stm32u5/i2c_bus.c, core/embed/sys/time/stm32/systimer.c
Adds another i2c bus. As we are running low on timers, this PR also adds more space for systimers.
=> add support for fifth I2C bus on STM32U5

nordic/trezor/trezor-ble/src/ble/advertising.c
If the bond memory is full, but pairing mode is on, we will signal this in manufacturer specific data.
=> signal full bond memory when advertising

core/SConscript.firmware, core/SConscript.unix, core/embed/rust/src/ui/api/firmware_micropython.rs, core/embed/upymod/modtrezorio/modtrezorio-poll.h, core/mocks/generated/trezorui_api.pyi, core/site_scons/site_tools/micropython/__init__.py, core/src/trezor/ui/layouts/homescreen.py
This PR adds a [BLE polling task](https://github.com/trezor/trezor-firmware/blob/5158b58b119631c213fd393781ed6f709f782927/core/src/trezor/ui/layouts/homescreen.py#L106) to homescreen layout.
It will fetch BLE events ([using `ble_get_event`](https://github.com/trezor/trezor-firmware/blob/5158b58b119631c213fd393781ed6f709f782927/core/embed/upymod/modtrezorio/modtrezorio-poll.h#L208)) and convert them to [`BLEEvent`](https://github.com/trezor/trezor-firmware/blob/5158b58b119631c213fd393781ed6f709f782927/core/embed/rust/src/ui/layout/obj.rs#L543) in Rust.
=> Add BLE support to `Homescreen` events

core/src/trezor/ui/layouts/homescreen.py
BLE event is a tuple and needs unpacking
=> fix homescreen ble checker task

core/embed/sec/secure_aes/inc/sec/secure_aes.h, core/embed/sec/secure_aes/stm32u5/secure_aes.c, core/embed/sys/powerctl/stm32u5/powerctl_suspend.c
This PR addresses an issue causing the SAES peripheral to become non-functional after returning from suspend mode, and also introduces minor improvements to the SAES driver:
- Enables SHSI clock after returning from suspend mode
- Completely resets the SAES peripheral in `secure_aes_init()`
- Add `secure_aes_deinit()`
=> fix(core): enable shsi clock after resuming from suspend mode

core/tools/codegen/gen_font.py, core/translations/cs.json, core/translations/de.json, core/translations/es.json, core/translations/fr.json, core/translations/it.json, core/translations/pt.json, core/translations/tr.json, python/src/trezorlib/_internal/translations.py
This PR resolves a small technical debt. As of https://github.com/trezor/trezor-firmware/pull/4536 the C-enum font names are no longer valid and foreign glyphs are mapped to fonts via `translation_blob_idx` in their respective `FontInfo` struct which are written by `gen_font.py`. The changes in the `gen_font.py` in this PR are just cosmetic.
In the future, we might want to specify the mapping in a separate file.
=> Remove obsolete font names from lang JSONs

core/src/apps/workflow_handlers.py
Otherwise, sending non-BTC requests results in the following error:
```
[11:42:37.114] 92750000 trezor.wire.message_handler DEBUG 0 receive: <704 - unknown message type>
[11:42:37.116] 92753000 trezor.wire ERROR exception:
[11:42:37.117] Traceback (most recent call last):
[11:42:37.117]   File "trezor/wire/__init__.py", line 87, in handle_session
[11:42:37.118]   File "trezor/wire/message_handler.py", line 79, in handle_single_message
[11:42:37.119]   File "trezor/wire/message_handler.py", line 197, in find_handler
[11:42:37.120]   File "apps/workflow_handlers.py", line 232, in find_registered_handler
[11:42:37.122]   File "apps/workflow_handlers.py", line 114, in _find_message_handler_module
[11:42:37.123] AttributeError: 'module' object has no attribute 'NostrGetPubkey'
```
=> fix(core): don't handle nostr-related messages in BTC-only firmware

core/embed/projects/prodtest/cmd/prodtest_pmic.c, core/embed/projects/prodtest/cmd/prodtest_wpc.c
This PR removes an unnecessary wait after last report in prodtests pmic-report and wpc-report commands
=> remove final wait from report commands

core/embed/rust/src/ui/layout_eckhart/component/button.rs, core/embed/rust/src/ui/layout_eckhart/firmware/action_bar.rs, core/embed/rust/src/ui/layout_eckhart/firmware/confirm_homescreen.rs, core/embed/rust/src/ui/layout_eckhart/firmware/text_screen.rs, core/embed/rust/src/ui/layout_eckhart/theme/mod.rs, core/embed/rust/src/ui/layout_eckhart/ui_firmware.rs
This PR:
- fixes pagination for `ActionBar` in `Single` mode
- adds `PaginateOnly` mode for `ActionBar`
- makes sure that `TextScreen` has at least `PaginateOnly` if the text does not fit
- add a few minor confirmation improvements
=> Eckhart UI - ActionBar pagination improvements

core/tools/analyze-memory-dump.py, docs/core/emulator/valgrind.md
Also, fix a small typo in `docs/core/emulator/valgrind.md`.
=> feat(tools): add an optional output argument to `analyze-memory-dump.py`

core/embed/rust/src/trezorhal/ble.rs, core/embed/upymod/modtrezorio/modtrezorio-ble.h, core/mocks/generated/trezorio/ble.pyi
Should make it possible to prevent responding to mismatched pairing request. Needs corresponding change to the nRF code - should be quite straightforward but I don't have means to test it.
The PR also exposes the `allow_pairing`/`reject_pairing` functions to python as I'd prefer not to call them directly from UI when possible.
=> Include pairing code in BLE_ALLOW_PAIRING command

core/embed/upymod/modtrezorutils/modtrezorutils.c
Otherwise, it fails to boot (following e6f96974d).
=> fix(core): correct `__main__` dict size retrieval in firmware

core/embed/projects/bootloader/.changelog.d/4649.fixed, core/embed/sec/secret/inc/sec/secret.h, core/embed/sec/secret/stm32f4/secret.c, core/embed/sec/secret/stm32u5/secret.c, core/embed/sec/secret/unix/secret.c
This PR modifies behavior of secret provisioning on devices with locked bootloader.
Now, firmware with allow_run_with_secret flag will be allowed to run even if it doesn't have full trust.
fixes #4649
=> allow running firmware based on allow_run_with_secret flag

core/SConscript.unix, core/site_scons/models/T3W1/emulator.py, core/site_scons/models/T3W1/trezor_t3w1_revA.py, core/site_scons/models/T3W1/trezor_t3w1_revB.py, core/site_scons/models/T3W1/trezor_t3w1_revC.py
The pinned version of libtropic had a `tests/platforms/libtropic-stm32` repostitory as a submodule. This would in turn pull in STM Cube SDK, which pulls in an insane number of per-platform submodules, exploding the total size of the checkout when using recursive submodules (our recommended default).
As of https://github.com/tropicsquare/libtropic/pull/55 this part is, rather sensibly, wholly excluded from the libtropic repo, so updating the submodule resolves the problem.
=> Remove a submodule subtree of libtropic

core/embed/rust/src/ui/layout_eckhart/component/button.rs, core/embed/rust/src/ui/layout_eckhart/firmware/action_bar.rs, core/embed/rust/src/ui/layout_eckhart/theme/firmware.rs, core/embed/rust/src/ui/layout_eckhart/ui_firmware.rs
This PR allows to construct buttons `.with_gradient()`. The button is then rendered with 3 layers
- vertical gradient of the `button_color` 
- horizontal gradient of black color factored by the distance from the middle
- overlay black overlay with 20% intensity
Stops and the intensities are specified in Figma.
Gradients are incompatible with radius.
=> Eckhart UI - button gradient

core/embed/io/ble/inc/io/ble.h, core/embed/io/ble/stm32/ble.c, core/embed/io/ble/stm32/ble_comm_defs.h, core/embed/projects/prodtest/cmd/prodtest_ble.c, nordic/trezor/trezor-ble/src/ble/advertising.c, nordic/trezor/trezor-ble/src/ble/ble_internal.h, nordic/trezor/trezor-ble/src/ble/ble_management.c, nordic/trezor/trezor-ble/src/ble/pairing.c
This PR addresses a potential problem with reconnecting when pairing. NRF now compares the pairing code received from UI with the one that is currently expected before confirming.
=> send pairing code back to nrf for verification

core/embed/rust/librust_qstr.h, core/embed/rust/src/ui/api/firmware_micropython.rs, core/embed/rust/src/ui/component/text/layout.rs, core/embed/rust/src/ui/layout_bolt/ui_firmware.rs, core/embed/rust/src/ui/layout_caesar/ui_firmware.rs, core/embed/rust/src/ui/layout_delizia/ui_firmware.rs, core/embed/rust/src/ui/layout_eckhart/component/button.rs, core/embed/rust/src/ui/layout_eckhart/component_msg_obj.rs, core/embed/rust/src/ui/layout_eckhart/firmware/device_menu_screen.rs, core/embed/rust/src/ui/layout_eckhart/firmware/mod.rs, core/embed/rust/src/ui/layout_eckhart/flow/continue_recovery_homepage.rs, core/embed/rust/src/ui/layout_eckhart/theme/firmware.rs, core/embed/rust/src/ui/layout_eckhart/ui_firmware.rs, core/embed/rust/src/ui/ui_firmware.rs, core/mocks/generated/trezorui_api.pyi, core/src/apps/homescreen/__init__.py
This PR introduces the "device menu", which is the main menu accessed by tapping the action bar on the home screen. It also includes Rust layouts for the BT pairing (which are triggered from the said device menu) - initially it was a separate PR, but decided to do is all here to simplify building the actual BT pairing before this gets merged. 
The device menu consists of multiple "subscreens" which are either **generic submenus** or **menus specific to a connected Bluetooth device** allowing the user to disconnect, or **the about screen**. Or anything else, really.
However, the actual subscreens are constructed on-demand as the user navigates to the desired screen. Creating a new `DeviceMenuScreen` object will just allocate the memory needed to store the information that will be used to …
=> Introduce the device menu

core/embed/rust/src/ui/layout_bolt/ui_firmware.rs, core/embed/rust/src/ui/layout_caesar/ui_firmware.rs, core/embed/rust/src/ui/layout_delizia/ui_firmware.rs, core/embed/rust/src/ui/ui_firmware.rs
Removes a few hardcoded error strings with one constant. This saves a little bit of space.
=> Remove redundant Error messages from FirmwareUI

core/SConscript.firmware, core/SConscript.unix, core/src/apps/homescreen/__init__.py, core/src/apps/homescreen/device_menu.py, core/src/apps/management/ble/pair_new_device.py
Cleaner separation for devices that don't have device menu. Placeholders for T3W1 remain.
=> refactor(core): device menu modules

core/SConscript.unix, core/embed/io/ble/unix/ble.c, core/embed/upymod/modtrezorio/modtrezorio-ble.h, core/mocks/generated/trezorio/ble.pyi, core/site_scons/models/T3W1/emulator.py, core/src/main.py
Several small BLE-related changes:
* 0d55e1a: enable _directed advertising_ on firmware startup if there are > 0 bonded devices, i.e. bonded devices can connect but device does not show up in scans
* 62ea246: stub implementation of ble IO for emulator - just enough to build: the actual implementation is in #4838 and needs a bunch of work, however I'd like to start building emulator with the `ble` SCons features so that we can refer to it from rust code
* c053ef3: enables `button` support in T3W1 emulator which should be now possible thanks to #4829, did not test anything if it works just that it doesn't break `touch`
* ada8814: typo in generated type signatures, remove obsolete nrf upgrade functions
* 7ac07be: expose `ble_get_state()` to micropython as flags
=> BLE: enable advertising on firmware boot

core/embed/io/display/ltdc_dsi/display_driver.c, core/embed/io/rgb_led/stm32u5/rgb_led_lp.c, core/embed/io/touch/ft6x36/ft6x36.c, core/embed/sec/tropic/stm32/tropic01.c, core/embed/sec/tropic/tropic.c, core/embed/sys/powerctl/npm1300/npm1300.c, core/embed/sys/powerctl/stm32u5/powerctl_suspend.c
This PR includes series of commits that optimize power consumption in suspend mode:
- Deinitialization routines were fixed (and in some case only refactored for consistency)
- The Tropic driver is now properly deinitialized before entering suspend mode 
- `tropic_deinit()` was modified to prevent crashes when called without a prior `tropic_init()`
- npm1300 configuration was slightly - the buck 1 output voltage settings is now left unchanged, relying on the bootstrap pin configuration instead
There's still some additional consumption caused by the BLE driver, which will be addressed in a separate PR.
=> T3W1 power optimization

core/src/apps/bitcoin/addresses.py, core/src/apps/bitcoin/authorization.py, core/src/apps/bitcoin/sign_tx/approvers.py, core/src/apps/bitcoin/sign_tx/matchcheck.py, core/src/apps/bitcoin/sign_tx/sig_hasher.py, core/src/apps/bitcoin/writers.py, core/src/trezor/crypto/bech32.py, core/src/trezor/wire/codec/codec_context.py
Before (9a1efead8):
```
48.04s call     tests/device_tests/bitcoin/test_authorize_coinjoin.py::test_sign_tx_large
```
This PR (fe6fc4b06, rebased over https://github.com/trezor/trezor-firmware/pull/4896):
```
38.62s call     tests/device_tests/bitcoin/test_authorize_coinjoin.py::test_sign_tx_large
```
No (observable) change in flash size:
https://github.com/trezor/trezor-firmware/actions/runs/14374615974/job/40304062435#step:8:1073
https://github.com/trezor/trezor-firmware/actions/runs/14354256681/job/40239922921#step:8:1073
```
Memory region         Used Size  Region Size  %age Used
FLASH:      585756 B       768 KB     74.48%
FLASH2:        479 KB       896 KB     53.46%
AUX1_RAM:        191 KB       191 KB    100.00%
AUX2_RAM:       38752 B        40 KB     94.61%
```
=> perf(core): remove imports from hot path

core/embed/projects/kernel/main.c, core/embed/sys/syscall/stm32/syscall_dispatch.c, core/embed/sys/syscall/stm32/syscall_stubs.c, core/embed/sys/syscall/stm32/syscall_verifiers.c, core/embed/sys/syscall/stm32/syscall_verifiers.h, core/embed/sys/task/inc/sys/sysevent.h, core/embed/sys/task/sysevent.c, core/embed/upymod/modtrezorio/modtrezorio-poll.h
This PR fixes a bug introduced in #4829.
`modtrezor_io_poll` returned `False` not only in case of a timeout, but also when events were signaled and then discarded due to various reasons - such as false positives or event rate throttling. That broke the task scheduling mechanism in MicroPython, which relies on it.
No changelog needed since the bug was not released yet.
=> fix(core):  make mod_trezorio_poll return False only on timeout

common/protob/pb2py, core/embed/rust/qstr.h
Requires https://github.com/trezor/micropython/pull/20.
Also, drops unneeded MicroPython support for excluding modules from being frozen (https://github.com/trezor/micropython/pull/19).
=> feat(vendor): update MicroPython to support sorted qstr pools

core/embed/rust/src/ui/layout_eckhart/component/button.rs, core/embed/rust/src/ui/layout_eckhart/firmware/action_bar.rs, core/embed/rust/src/ui/layout_eckhart/firmware/hint.rs, core/embed/rust/src/ui/layout_eckhart/theme/firmware.rs, core/embed/rust/src/ui/layout_eckhart/ui_firmware.rs
This PR does two things:
1. sets correct padding for `Hint` according to Figma
2. constructs the `right_button` of `ActionBar` with gradient settings which should be the right thing (according to Figma)
=> Echart UI - fix hint and gradient buttons

core/embed/io/usb/inc/io/usb_vcp.h, core/embed/io/usb/stm32/usb_class_vcp.c, core/embed/projects/prodtest/main.c
This PR fixes a freeze in the USB driver on T3W1 when receiving packets longer than 64 bytes.
On T3W1, we use USB High Speed, whereas other products use USB Full Speed. USB HS allows packets up to 512 bytes, which we weren’t prepared for. This PR provides a hotfix for the issue in prodtest, but we need to investigate further to determine if this difference should be accounted for elsewhere.
=> fix(core): fix USB VCP freeze on T3W1 in prodtest

core/embed/upymod/modtrezorutils/modtrezorutils.c
Otherwise, it's hard to understand which QSTR causes the assertion error.
Previously, it was enabled only for debug emulator builds.
=> fix(core): dump allocated QSTRs also in debug firmware

core/embed/rust/src/ui/component/base.rs, core/embed/rust/src/ui/layout/obj.rs
Following https://github.com/trezor/trezor-firmware/pull/4797#discussion_r2003021530.
=> perf(core): encode `Timer` using a single `u32`

core/embed/projects/prodtest/main.c
This PR fixes an issue with a small RX ring buffer for USB VCP.
Issue: In non-interactive CLI mode, when a large amount of data is received (e.g., a certificate larger than 1024 bytes), the data may be discarded if the RX ring buffer overflows. This issue was observed on the T3W1, where USB HS is used.
The fix increases both TX and RX buffer sizes.
=> fix(prodtest): increase vcp ring buffer size

core/embed/io/backlight/inc/io/backlight.h, core/embed/io/backlight/stm32u5/tps61062.c
Introduce max backlight limit in the T3W1 backlight driver. 
If user will request the backlight which is above the maximal set level, backlight will be automatically adjusted to maximal limit. if the user will increase the max backlight limit later, the backlight will be updated to originally requested level.
This feature is needed in power manager to decrease the backlight regardless to app in power save mode. 
This feature is intentionally not added in prodtest, since the API should be strictly used by kernel -> hence, should not be part of the general display driver.
=> Add max backlight limit to backlight driver

.github/workflows/core.yml
Most of the tests complete after a few seconds:
Sometimes upgrade tests fail due to flaky debuglink handling on old emulators.
In this case, the test can be terminated earlier.
=> test(core): reduce pytest timeout for upgrade tests

core/embed/rust/src/ui/layout_bolt/component/address_details.rs, core/embed/rust/src/ui/layout_bolt/component/mod.rs, core/embed/rust/src/ui/layout_bolt/ui_firmware.rs, core/embed/rust/src/ui/layout_caesar/component/address_details.rs, core/embed/rust/src/ui/layout_caesar/component/mod.rs, core/embed/rust/src/ui/layout_caesar/ui_firmware.rs, core/embed/rust/src/ui/layout_delizia/component/address_details.rs, core/embed/rust/src/ui/layout_delizia/component/mod.rs, core/embed/rust/src/ui/layout_delizia/flow/get_address.rs
It reduces `AddressDetails` size by 128 bytes from:
```
`ui::layout_delizia::component::address_details::AddressDetails`: 2080 bytes, alignment: 4 bytes
```
to
```
`ui::layout_delizia::component::address_details::AddressDetails`: 1952 bytes, alignment: 4 bytes
```
Relevant stack sizes are also reduced to:
```
11536	trezor_lib::ui::api::firmware_micropython::new_flow_get_address
16056	trezor_lib::ui::api::firmware_micropython::new_flow_confirm_output
```
(https://github.com/trezor/trezor-firmware/actions/runs/14601983369/job/40962113990?pr=4946)
from:
```
11800	trezor_lib::ui::api::firmware_micropython::new_flow_get_address
16312	trezor_lib::ui::api::firmware_micropython::new_flow_confirm_output
```
(https://github.com/trezor/trezor-firmware/actions/runs/14591197885/job/40926681094?pr=4941) …
=> perf(core): optimize `AddressDetails::xpubs` layout

tests/translations.py
An incorrect default value was used in https://github.com/trezor/trezor-firmware/commit/abcbb5c2ab5f5dcabf42bfffacca374d79cac712.
Currently, it takes at least ~0.2s (for every test case):
```
[2025-04-24 21:22:13,270] trezorlib.client DEBUG: sending message: ChangeLanguage
ChangeLanguage (2 bytes) {
data_length: 0,
}
[2025-04-24 21:22:13,270] trezorlib.client BYTES: encoded as type 990 (2 bytes): 0800
[2025-04-24 21:22:13,458] trezorlib.client BYTES: received type 2 (18 bytes): 0a104c616e6775616765206368616e676564
[2025-04-24 21:22:13,459] trezorlib.client DEBUG: received message: Success
Success (18 bytes) {
message: 'Language changed',
}
```
=> test(core): don't force changing language if not needed

crypto/hasher.h, crypto/sha2.h, legacy/firmware/crypto.c, legacy/firmware/reset.c, legacy/firmware/signing.c, legacy/firmware/transaction.c
Fixes #4547. See also https://github.com/trezor/trezor-firmware/pull/4396#discussion_r1931732669
=> refactor(legacy): check size of integers when hashing

core/embed/rust/src/ui/layout_eckhart/firmware/device_menu_screen.rs, core/embed/rust/src/ui/layout_eckhart/firmware/select_word_screen.rs, core/embed/rust/src/ui/layout_eckhart/firmware/vertical_menu.rs, core/embed/rust/src/ui/layout_eckhart/firmware/vertical_menu_screen.rs
This PR:
- Improves event processing for the `VerticalMenu` component
- Switches swiping on/off based on the `VerticalMenu` fitting/not fitting its bounds
- Implements function `update_screen` for `VerticalMenuScreen`. It has to be called in the `DeviceMenuScreen` whenever the screen is switched.
- Adds swiping functionality for testing purposes when animations are disabled:
- The menu is swipable until the the last item is visible on top of the menu area (even if an entire menu fits the screen).
- This way the device tests can select `n-th` item by swiping up `n-1` times and then clicking on the 1st item area no matter what the menu item height is. The behavior can be tested by spawning the emulator with disabled animations:`./emu.py -a`
=> Update VerticalMenu swiping behavior for Eckhart

core/SConscript.firmware, core/SConscript.unix, core/embed/upymod/qstrdefsport.h, core/embed/upymod/qstrdefsport.h.mako, core/src/trezor/log.py, core/src/trezor/wire/__init__.py, core/src/trezor/wire/codec/codec_context.py, core/src/trezor/wire/message_handler.py, core/src/trezor/wire/wire_log.py
Add `wire_log` that includes `WireInterface` (eg. `WebUSB`, `BleInterface`) in output when logging.
=> Add WireInterface to logging from `core/wire`

shell.nix
Should fix nightly hardware tests. Only tested that the shell starts.
=> ci(nix): bump ffmpeg

build-docker.sh
Likely caused by #4374. [git docs](https://git-scm.com/docs/git-config#Documentation/git-config.txt-safedirectory)
```
>>> DOCKER REFRESH trezor-firmware-env.nix__main
Cloning into 'trezor-firmware'...
warning: safe.directory 'file:///local/.git' not absolute
fatal: detected dubious ownership in repository at '/local/.git'
To add an exception for this directory, call:
git config --global --add safe.directory /local/.git
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
=> build: build-docker.sh: ignore dubious ownership

core/embed/projects/prodtest/README.md, core/embed/projects/prodtest/cmd/prodtest_nfc.c
For usage during testing, certifications it is needed to be able to have NFC turned on continuously
=> allow infinite testing of NFC functionalities

core/embed/rust/src/ui/layout_eckhart/firmware/device_menu_screen.rs, core/embed/rust/src/ui/layout_eckhart/ui_firmware.rs
It significantly reduces `new_show_device_menu` stack usage from:
```
20008	trezor_lib::ui::api::firmware_micropython::new_show_device_menu
```
to:
```
1744	trezor_lib::ui::api::firmware_micropython::new_show_device_menu
```
by moving the largest members `DeviceMenuScreen` to the heap, reducing its size from:
```
type: `ui::layout_eckhart::firmware::device_menu_screen::DeviceMenuScreen<'_>`: 6260 bytes, alignment: 4 bytes
field `.menu_screen`: 1260 bytes
field `.about_screen`: 1580 bytes
field `.firmware_version`: 12 bytes
field `.bounds`: 8 bytes
field `.submenus`: 3244 bytes
field `.subscreens`: 132 bytes
field `.active_subscreen`: 4 bytes
field `.parent_subscreens`: 16 bytes
field `.battery_percentage`: 1 bytes
end padding: 3 bytes
```
to
```
type: …
```
=> fixup! fix(eckhart): optimize device menu

core/src/trezor/utils.py
If an exception is being handled here by `unimport.__exit__()`, `check_free_heap()` will probably fail (since the exception type, value and traceback objects survive `gc.collect()` call).
Thus, we should prefer to skip the check, in order to preserve the "original" exception.
=> fix(core): propagate exceptions via `unimport.__exit__`

core/.changelog.d/4751.fixed, core/embed/rust/src/ui/layout_delizia/component/number_input.rs, core/embed/rust/src/ui/layout_delizia/component/number_input_slider.rs, core/embed/rust/src/ui/layout_delizia/flow/request_number.rs, core/embed/rust/src/ui/layout_delizia/flow/set_brightness.rs, tests/click_tests/test_reset_slip39_basic.py
- NumberInputDialog now reacts to tap to continue
- change the types there to u16 to be consistent with NumberInputSlider
=> Fix Delizia request number dialog

.github/actions/run-fuzzers/action.yml, .github/workflows/cflite.yml
Works around https://github.com/trezor/trezor-firmware/issues/4967.
Currently, there is no `cifuzz-corpus-fuzzer` to download, so let's make it fail faster :)
```
2025-04-29 08:13:36,609 - root - INFO - Fuzz targets: ['/github/workspace/build-out/fuzzer']
2025-04-29 08:13:36,609 - root - INFO - Running fuzzer: fuzzer.
2025-04-29 08:13:36,609 - root - INFO - Downloading corpus for fuzzer to /github/workspace/cifuzz-corpus/fuzzer.
2025-04-29 09:40:53,108 - root - WARNING - Could not find artifact: cifuzz-corpus-fuzzer.
2025-04-29 09:40:53,108 - root - WARNING - Could not download artifact: cifuzz-corpus-fuzzer.
2025-04-29 09:40:53,109 - root - INFO - Done downloading corpus. Contains 0 elements.
2025-04-29 09:40:53,109 - root - INFO - Starting fuzzing
```
CC: @AdamKorcz
=> Don't access GitHub artifacts from `cflite.yml` job

core/embed/projects/firmware/mphalport.c
This PR enables microsecond resolution for `mp_hal_ticks_us`.
=> chore(core): use `systick_us` for `mp_hal_ticks_us`

shell.nix
Since #4374 it seems `arm-none-eabi-gdb` v12 is broken. Let's have some moderate progress within the bounds of the law and bump to 13.3.1 which is not broken in this way?
```
$ arm-none-eabi-gdb
Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
File "/nix/store/hywjs3gs3fki9v8zpxxas8yra0gxpprm-python3-3.9.20/lib/python3.9/site.py", line 73, in <module>
import os
File "/nix/store/hywjs3gs3fki9v8zpxxas8yra0gxpprm-python3-3.9.20/lib/python3.9/os.py", line 29, in <module>
from _collections_abc import _check_methods
File "/nix/store/hywjs3gs3fki9v8zpxxas8yra0gxpprm-python3-3.9.20/lib/python3.9/_collections_abc.py", line 12, in <module>
GenericAlias = type(list[int])
TypeError: 'type' object is not …
```
=> shell.nix: bump arm-embedded-gcc to version 13

core/SConscript.unix, core/embed/io/display/inc/io/unix/sdl_display.h, core/embed/io/display/unix/display_driver.c, core/embed/io/rgb_led/unix/rgb_led.c, core/site_scons/models/T3W1/emulator.py
[no changelog]
This PR adds LED to the emulator. It is done via unix/display_driver.c which draws it right above the display to the padding area.
This is a 2nd PR which follows up from review concerns and changes the target branch to `main` https://github.com/trezor/trezor-firmware/pull/4854#pullrequestreview-2733908768
=> LED for emulator

core/embed/rust/src/ui/geometry.rs, core/embed/rust/src/ui/layout_eckhart/component_msg_obj.rs, core/embed/rust/src/ui/layout_eckhart/cshape/loader.rs, core/embed/rust/src/ui/layout_eckhart/cshape/mod.rs, core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs, core/embed/rust/src/ui/layout_eckhart/firmware/mod.rs, core/embed/rust/src/ui/layout_eckhart/firmware/progress_screen.rs, core/embed/rust/src/ui/layout_eckhart/theme/mod.rs, core/embed/rust/src/ui/layout_eckhart/ui_firmware.rs, core/src/trezor/ui/__init__.py, storage/storage.c
Implements `ProgressScreen` for Eckhart based on [Figma](https://www.figma.com/design/Z1NtDTu70Dl8dJrpLK1IEE/Sandbox-TS-7?node-id=3263-422&t=gcbcdFYj6Qkoroik-0).
- `ProgressLayout` now animates progress in Python loop. It is debatable whether we want to keep this functionality also for other layouts or whether we want it even for Eckhart
- because that slows down the rendering of `ProgressLayout` by a bit, an overflow protection in `storage.c` was implemented. Otherwise, "4294962 seconds left" could be seen for a moment.
- `indeterminate` loader is simplified in such a way that only one part of the loader is shown (not two as in Figma). This simplifies the implementation a lot.
- on the Rust side, Eckhart has only `ProgressScreen` which covers also the usecase for Coinjoin
=> Eckhart UI - loaders

core/embed/rust/src/translations/generated/translated_string.rs, core/embed/rust/src/translations/generated/translated_string.rs.mako, core/embed/rust/src/translations/translated_string.rs
It seems that Rust generates non-optimal code the giant `match` statements in `translated_string.rs`.
This PR reduces flash usage by ~5kB on T3B1:
`Memory region         Used Size  Region Size  %age Used`
`           FLASH:     1378816 B      1664 KB     80.92%`  this PR @ ce14a5990c          
`           FLASH:     1383936 B      1664 KB     81.22%`  `main`  @ 53225569c8
=> perf(core): use lookup tables for untranslated strings

.github/workflows/core-hw.yml
Tested on T2T1:
```
$ pytest -v tests/device_tests/ -k lots --durations 0
...
==================================================================== slowest durations ====================================================================
309.73s call     tests/device_tests/bitcoin/test_signtx.py::test_lots_of_inputs
61.37s call     tests/device_tests/bitcoin/test_signtx.py::test_lots_of_outputs
5.73s setup    tests/device_tests/bitcoin/test_signtx.py::test_lots_of_change
5.03s call     tests/device_tests/bitcoin/test_signtx.py::test_lots_of_change
4.10s setup    tests/device_tests/bitcoin/test_signtx.py::test_lots_of_outputs
4.09s setup    tests/device_tests/bitcoin/test_signtx.py::test_lots_of_inputs
...
===================================================== 3 passed, 1588 deselected in …
```
=> ci(core): update hardware CI tests

core/src/trezor/pin.py
Since `trezor.pin` is persisted across sessions, it should use constant-size globals.
Related to https://github.com/trezor/trezor-firmware/pull/4821.
=> fix(core): use `bool` for `trezor.pin._ignore_loader_messages`

.github/actions/ui-report/action.yml
Before this PR, it takes ~7m to upload click UI tests' results:
=> ci(core): increase S3 upload concurrency for `ui-report` action

core/embed/projects/bootloader/workflow/wf_host_control.c
Since host_control can be called without communication interfaces, we need to handle this properly.
=> fix null ios handling in host control

.github/actions/ui-report/action.yml, .github/workflows/core.yml, core/Makefile
Currently, running T3B1 click tests using a single worker take ~6.5 minutes:
Also, increase UI results' uploading concurrency, reducing upload results' duration by ~2x ([before](https://github.com/trezor/trezor-firmware/actions/runs/14954453993/job/42008339784), [after](https://github.com/trezor/trezor-firmware/actions/runs/14974386229/job/42063337230?pr=5028))
=> ci(core): run click UI tests in parallel

core/src/apps/bitcoin/common.py, core/src/apps/bitcoin/keychain.py, core/src/apps/bitcoin/scripts.py, core/src/apps/bitcoin/sign_tx/approvers.py, core/src/apps/bitcoin/sign_tx/bitcoin.py, core/src/apps/bitcoin/sign_tx/helpers.py, core/src/apps/bitcoin/sign_tx/matchcheck.py
Tested with the following MicroPython patch:
```diff
diff --git a/py/builtinimport.c b/py/builtinimport.c
index cd9636ccd..8cf93376e 100644
--- a/py/builtinimport.c
+++ b/py/builtinimport.c
@@ -468,14 +468,12 @@ STATIC mp_obj_t process_import_at_level(qstr full_mod_name, qstr level_mod_name,
}
mp_obj_t mp_builtin___import__(size_t n_args, const mp_obj_t *args) {
-    #if DEBUG_PRINT
-    DEBUG_printf("__import__:\n");
+    mp_printf(MICROPY_DEBUG_PRINTER, "__import__");
for (size_t i = 0; i < n_args; i++) {
-        DEBUG_printf("  ");
+        mp_printf(MICROPY_DEBUG_PRINTER, i == 0 ? "(" : ", ");
mp_obj_print_helper(MICROPY_DEBUG_PRINTER, args[i], PRINT_REPR);
-        DEBUG_printf("\n");
}
-    #endif
+    mp_printf(MICROPY_DEBUG_PRINTER, ")\n");
// This is the import path, with any …
```
=> perf(core): remove more local imports from Bitcoin signing flow

core/SConscript.firmware, core/embed/projects/firmware/main.c
If it is removed from `SOURCE_MOD_CRYPTO`, code size increases by ~0.5 kB on T3B1:
```
Memory region         Used Size  Region Size  %age Used
FLASH:     1383936 B      1664 KB     81.22%
AUX1_RAM:       10272 B     196096 B      5.24%
AUX2_RAM:        544 KB       544 KB    100.00%
...
code_length: 1382400        
```
```
Memory region         Used Size  Region Size  %age Used
FLASH:       1352 KB      1664 KB     81.25%
AUX1_RAM:       10268 B     196096 B      5.24%
AUX2_RAM:        544 KB       544 KB    100.00%
...
code_length: 1382912
```
We need to compile MicroPython without `-ffreestanding` to enable `strcmp` compile-time optimization which is required for https://github.com/trezor/trezor-firmware/pull/4961 (following https://github.com/micropython/micropython/pull/17196#issuecomm …
=> chore(core): keep `-ffreestanding` only for `SOURCE_MOD_CRYPTO`

core/src/apps/debug/__init__.py, python/src/trezorlib/debuglink.py, tests/upgrade_tests/recovery_old.py
Following https://github.com/trezor/trezor-firmware/issues/5039#issuecomment-2880239955.
=> fix(core): handle `DebugLink.input_wait_type` when `return_empty_state` is set

core/embed/rust/rust_types.h, core/embed/rust/src/ui/layout_eckhart/bootloader/bld_menu.rs, core/embed/rust/src/ui/layout_eckhart/bootloader/bld_menu_screen.rs, core/embed/rust/src/ui/layout_eckhart/bootloader/bld_text_screen.rs, core/embed/rust/src/ui/layout_eckhart/bootloader/confirm_pairing.rs, core/embed/rust/src/ui/layout_eckhart/bootloader/connect.rs, core/embed/rust/src/ui/layout_eckhart/bootloader/mod.rs, core/embed/rust/src/ui/layout_eckhart/bootloader/pairing_finalization.rs, core/embed/rust/src/ui/layout_eckhart/bootloader/pairing_mode.rs, core/embed/rust/src/ui/layout_eckhart/bootloader/welcome_screen.rs, core/embed/rust/src/ui/layout_eckhart/ui_bootloader.rs
Port of https://github.com/trezor/trezor-firmware/pull/4833 for Eckhart UI
@TychoVrahe since our testing on the device, I fixed the wrong menu button and missing "Cancel" button on "Waiting for host.." screen. 
I also kept the commit increasing the `c_layout_t` buffer. Let me know if I should remove it from this PR but note that without it, the bootloader crashes.
=> Eckhart UI - bootloader BLE handling

core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs
This PR removes the shadow effect from the device name on the homescreen in Eckhart UI. The reason is that it's not needed on the default pattern. However, it will be used when a user sets some custom image, the reason is that it makes the text more readable on light/dark backgrounds.
=> Eckhart UI: remove label shadow on default homescreen pattern

tests/click_tests/test_autolock.py, tests/click_tests/test_passphrase_bolt_delizia.py, tests/click_tests/test_passphrase_caesar.py
Currently, `PassphraseKeyboard` is shown after `request_passphrase_on_host()` layout, so in in order to avoid a race condition[^1][^2], an explicit synchronization was added.
[^1]: https://github.com/trezor/trezor-firmware/actions/runs/14999904818/job/42144246518?pr=5037
[^2]: https://github.com/trezor/trezor-firmware/actions/runs/15067093253/job/42354594590?pr=5041
=> test(core): deflake passphrase-related tests

tests/ui_tests/reporting/html.py, tests/ui_tests/reporting/testreport.css, tests/ui_tests/reporting/testreport.js
This makes long flows easier to review in the UI diff.
=> Collapse unchanged screenshots in UI diff

python/src/trezorlib/protobuf.py
Trying to solve some new issues with `trezorlib` I found recently when integrating new emulators into `trezor-user-env`.
1. `protobuf.py` had `# type: ignore [Type ["Unknown | None"]]`, which causes `mypy` to flag this as a syntax error in any project that uses `trezorlib` ... example fail in our CI: https://github.com/trezor/trezor-user-env/actions/runs/13370973357/job/37339166006?pr=290
- I found out that it is fine with other `type: ignore`s, and that the issue disappears when removing the inner `[]` ... `mypy` seems to have issues with this
2. Connected with `transport/bridge.py` - `call_bridge` is sending a POST request to bridge URL, but with no timeout. Just last week, with new release emulators, it started happening that the bridge just did not anwer at all. It is strange that it …
=> Trezorlib fixes

core/embed/sys/task/unix/system.c
This PR fixes the issue with truncated message string shown in RSOD in the emulator.
=> fix(core): fixed truncated strings in rsod on emulator

.github/workflows/core-hw.yml, setup.cfg
Following https://yaml-multiline.info, `>-` is used to split `TESTOPTS` in `core-hw.yml`.
=> ci(core): enable retries only for HW tests

core/embed/upymod/modtrezorcrypto/modtrezorcrypto-elligator2.h
Fix: elligator2 is missing MP_ERROR_TEXT macro, which causes THP builds to fail.
=> fix(core): add MP_ERROR_TEXT to elligator2

core/embed/rust/src/translations/blob.rs
Instead of doing it on every `TranslationStringsChunk::get()` call.
Rebased over https://github.com/trezor/trezor-firmware/pull/4987.
=> refactor(core): convert translation strings to `str` once

core/embed/projects/bootloader/bootui.c, core/embed/projects/bootloader/bootui.h, core/embed/projects/bootloader/emulator.c, core/embed/projects/bootloader/protob/protob.c, core/embed/projects/bootloader/workflow/wf_firmware_update.c, core/embed/projects/bootloader/workflow/wf_host_control.c, core/embed/projects/bootloader/workflow/wf_unlock_bootloader.c, core/embed/projects/bootloader/workflow/workflow.h, core/embed/sec/secret/inc/sec/secret.h, core/embed/sec/secret/stm32f4/secret.c, core/embed/sec/secret/stm32u5/secret.c, core/embed/sec/secret/unix/secret.c, core/embed/sys/syscall/stm32/syscall_dispatch.c, core/embed/sys/syscall/stm32/syscall_stubs.c, core/embed/upymod/modtrezorutils/modtrezorutils.c, core/site_scons/models/T2B1/emulator.py, core/site_scons/models/T2B1/trezor_r_v10.py, core/site_scons/models/T3B1/emulator.py, core/site_scons/models/T3B1/trezor_t3b1_revB.py, core/site_scons/models/T3T1/emulator.py, core/site_scons/models/T3T1/trezor_t3t1_revE.py, core/site_scons/models/T3W1/emulator.py, core/site_scons/models/T3W1/trezor_t3w1_revA.py, core/site_scons/models/T3W1/trezor_t3w1_revB.py, core/site_scons/models/T3W1/trezor_t3w1_revC.py
This PR adjust bootloader locking/unlocking mechanism to respect models with tropic.
When unlocking bootloader, secrets for both optiga and tropic should be erased. Therefore, for purpose of bootloader locked status detection, any secret that is not erased means that bootloader is locked and custom firmware should not be allowed to be installed and should not run.
Instead of relying on `USE_OPTIGA` for presence of bootloader lock functionality, new per-model compile flag is introduced: `LOCKABLE_BOOTLOADER`
=> adjust bootloader (un)locking for tropic-enabled models

core/.changelog.d/5099.fixed, core/embed/rust/src/ui/layout_delizia/component/number_input.rs
The bug was introduced in this PR https://github.com/trezor/trezor-firmware/pull/4763 which was released for `25.05`, i.e. Firmware version 2.8.10
Due to the bug, a user may have incorrect number of shares or threshold in multi-share backup. The incorrect value was always off by 1. It happened if the user incremented or decremented the value and then dirrectly tapped to the footer to confirm. If the user tapped somewhere else between inc/dec, the value was correct.
=> fix(core/delizia): incorrect shares number input

core/embed/projects/prodtest/cmd/prodtest_display.c, core/embed/projects/prodtest/main.c, core/embed/rust/src/ui/layout_bolt/prodtest/mod.rs
This PR fixes and issue with setting backlight in prodtest. while backlight could be set, it also causes screen to go blank and was reset after any other command (showing something on display), so not very useful.
Now prodtest homescreen will be shown after the backlight command, and other commands will not override the setting.
=> prodtest backlight control fix

core/translations/cli.py
```
>>> datetime.datetime.utcnow()
DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
datetime.datetime.utcnow()
datetime.datetime(2025, 5, 27, 10, 59, 12, 672487)
>>> datetime.datetime.now(datetime.UTC)
datetime.datetime(2025, 5, 27, 10, 59, 18, 590023, tzinfo=datetime.timezone.utc)
```
=> fix(core): fix `DeprecationWarning` for `datetime.datetime.utcnow()`

core/embed/rust/Cargo.lock, core/embed/rust/Cargo.toml, core/embed/rust/src/ui/constant.rs, core/embed/rust/src/ui/mod.rs, tests/device_tests/test_basic.py
IIUC, it should result in similar `#cfg`-based construction:
```rust
macro_rules! cfg_if {
// match if/else chains with a final `else`
($(
if #[cfg($meta:meta)] { $($tokens:tt)* }
) else * else {
$($tokens2:tt)*
}) => {
$crate::cfg_if! {
@__items
() ;
$( ( ($meta) ($($tokens)*) ), )*
( () ($($tokens2)*) ),
}
};
// match if/else chains lacking a final `else`
(
if #[cfg($i_met:meta)] { $($i_tokens:tt)* }
$(
else if #[cfg($e_met:meta)] { $($e_tokens:tt)* }
)*
) => {
$crate::cfg_if! {
@__items
() ;
( ($i_met) ($($i_tokens)*) ),
$( ( ($e_met) ($($e_tokens)*) ), )*
( () () ),
}
};
// Internal and recursive macro to emit all the items
//
// Collects all the negated cfgs in a list at the beginning and after the
// semicolon is all the remaining items
(@__items ($($not:meta,)*) ; ) => {}; …
```
=> refactor(core): simplify per-model imports using `cfg-if` macro

.github/workflows/core-hw.yml
T2B1 device seems to have a locked bootloader so #5087 is not enough.
https://github.com/trezor/trezor-firmware/actions/runs/15368486126/job/43244403997#step:8:19
=> ci(core): disable authenticity tests on HW CI

core/embed/projects/prodtest/main.c
This PR fixes the issue where the prodtest VCP got stuck when the USB is unplugged.
The problem is described in detail here: https://github.com/trezor/trezor-firmware/issues/4980
Ideally, this workaround should be improved by fully disconnecting the VCP whenever no USB cable is detected.
=> fix(core/prodtest): fix vcp jamming when USB unplugged.

core/embed/rust/src/translations/generated/translated_string.rs, core/embed/rust/src/ui/layout_eckhart/component_msg_obj.rs, core/embed/rust/src/ui/layout_eckhart/flow/confirm_summary.rs, core/embed/rust/src/ui/layout_eckhart/flow/confirm_with_menu.rs, core/embed/rust/src/ui/layout_eckhart/ui_firmware.rs, core/mocks/trezortranslate_keys.pyi, core/src/trezor/ui/layouts/eckhart/__init__.py, core/translations/en.json
This PR:
- updates `confirm_modify_output`, `new_confirm_with_menu`, `confirm_replacement` and `confirm_modify_fee` according to latest [Figma](https://www.figma.com/design/Dkl7W5PLqpr3TnXJ5hbnfd/--Future-Prod---Safe-7?node-id=6374-5404) design 
- adapts rules for the right action bar button in `new_confirm_with_menu` flow:
- hold is true -> green style
- empty verb param -> "Confirm" with green style
- otherwise -> verb with default style
- updates dependency importing  in `component_msg_obj.rs` to suppress clippy warning
TODO:
=> WIP: RBF update for Eckhart UI

.github/workflows/core.yml, core/embed/upymod/rustmods.c
=> fix(core): emulator build with PYOPT=1

core/.changelog.d/4975.added, core/embed/rust/src/translations/blob.rs, core/translations/signatures.json, docs/core/misc/translations.md, python/.changelog.d/4975.added, python/src/trezorlib/_internal/translations.py
It supports multiple translations strings chunks and allows total container size to be above 64kB.
Previous format is also supported by firmware.
Model | Language | Size [B] d579d87948 | Size [B] aafdfd20c8 | Delta [B] | Delta [%] | Capacity [B] | Utilization aafdfd20c8
-- | -- | -- | -- | -- | -- | -- | --
T2B1 | cs-CZ | 29258 | 29264 | 6 | 0.02% | 32768 | 89.31%
T2B1 | de-DE | 26920 | 26926 | 6 | 0.02% | 32768 | 82.17%
T2B1 | es-ES | 28568 | 28670 | 102 | 0.36% | 32768 | 87.49%
T2B1 | fr-FR | 30342 | 30348 | 6 | 0.02% | 32768 | 92.61%
T2B1 | it-IT | 25218 | 25224 | 6 | 0.02% | 32768 | 76.98%
T2B1 | pt-BR | 28092 | 28098 | 6 | 0.02% | 32768 | 85.75%
T2B1 | tr-TR | 24798 | 24804 | 6 | 0.02% | 32768 | 75.70%
T2T1 | cs-CZ | 39394 | 39272 | -122 | -0.31% | 49152 | 79.90%
T2T1 | de-DE | 29344 …
=> Support new translation blob format

core/embed/projects/prodtest/README.md, core/embed/projects/prodtest/cmd/prodtest_ble.c
This PR adds a ble-radio-test command to prodtest. Originally implemented by @kopecdav .
It assumes radio test is installed on nRF, and proxies the VCP data through uart.
Radio test is useful for i.e. certifications.
As we are also passing this functionality to partners, its useful to have it in main so we don't have to rebase stuff when we need this.
=> add radio test command to prodtest

core/embed/rust/src/time.rs, core/embed/rust/src/ui/geometry.rs, core/embed/rust/src/ui/layout_bolt/component/button.rs, core/embed/rust/src/ui/layout_bolt/theme/mod.rs, core/embed/rust/src/ui/layout_delizia/component/button.rs, core/embed/rust/src/ui/layout_delizia/component/hold_to_confirm.rs, core/embed/rust/src/ui/layout_delizia/theme/mod.rs, core/embed/rust/src/ui/layout_eckhart/component/button.rs, core/embed/rust/src/ui/layout_eckhart/firmware/device_menu_screen.rs, core/embed/rust/src/ui/layout_eckhart/firmware/hold_to_confirm.rs, core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs, core/embed/rust/src/ui/layout_eckhart/theme/firmware.rs
It should reduce stack and heap utilization for layouts using `Vec<Button>` (e.g. `LongMenuGc` containing 100 buttons).
```
print-type-size type: `ui::layout_eckhart::component::button::Button`: 136 bytes, alignment: 4 bytes
print-type-size     field `.long_press`: 8 bytes
print-type-size     field `.content`: 84 bytes
print-type-size     field `.stylesheet`: 12 bytes
print-type-size     field `.area`: 8 bytes
print-type-size     field `.content_offset`: 4 bytes
print-type-size     field `.long_timer`: 4 bytes
print-type-size     field `.touch_expand`: 10 bytes
print-type-size     field `.radius`: 2 bytes
print-type-size     field `.haptic`: 1 bytes
print-type-size     field `.gradient`: 1 bytes
print-type-size     field `.text_align`: 1 bytes
print-type-size     field `.state`: 1 bytes …
```
=> Optimize `Button` memory layout

core/src/trezor/utils.py
Fixes a `(PE)` error introduced by #5091 on non-debug builds.
=> test(core): don't call `clear_gc_info()` when PYOPT=1

core/embed/io/touch/stmpe811/touch.c, core/embed/projects/bootloader/workflow/wf_host_control.c
No changelog, since https://github.com/trezor/trezor-firmware/commit/c319e5fa208365c8c79efeea364903505d6de848 hasn't been released yet.
=> fix(core): use correct size in `workflow_ifaces_init()`

core/embed/sys/irq/inc/sys/irq.h, core/embed/sys/power_save/stm32u5/power_save.c
This PR removes functionality that the secure monitor no longer needs.
Recently added `irq_lock_ns()` and `irq_unlock_ns()`  functions are unnecessary, because the regular `irq_lock()` / `irq_unlock()` calls executed in Secure world already disable Non-Secure interrupts.
=> fix(core): remove unnecessary non-secure variant of irq_lock/unlock

core/embed/sys/power_manager/npm1300/npm1300.c, core/embed/sys/power_manager/stm32u5/power_monitoring.c
This small PR addresses two issues with charging to 100%.
First, we don't want to apply hysteresis when charging to full is enabled - its not expected by end user. Also we want to charge really to full, not 99 % which would be the result before as we comparing ceiled SOC.
Second, full battery detection is fixed - using correct bit and actually setting the value when reading PMIC data.
=> fix charging to 100%

core/embed/sys/tamper/stm32u5/tamper.c
Tiny adjustment in the tamper RSOD label, 
INTERNAL TAMPER was bit misleading, since it may report also external tampers  .
=> fix tamper RSOD label

core/embed/rust/src/coverage/mod.rs
Following, the upgrade to Rust 2024.
```
warning: creating a mutable reference to mutable static is discouraged
--> src/coverage/mod.rs:70:19
|
70 |             match COVERAGE_DATA.entry(key) {
|                   ^^^^^^^^^^^^^^^^^^^^^^^^ mutable reference to mutable static
|
= note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html>
= note: mutable references to mutable statics are dangerous; it's undefined behavior if any other pointer to the static is used or if any other reference is created for the static while the mutable reference lives
= note: `#[warn(static_mut_refs)]` on by default
warning: creating a shared reference to mutable static is discouraged
--> src/coverage/mod.rs:88:45
|
88 |         let list = unsafe { …
```
=> refactor(core): wrap coverage data map with `spin::RwLock`

docs/tests/device-tests.md, python/src/trezorlib/debuglink.py, tests/conftest.py
This PR:
- doesn't fail next tests in case of a GC leak.
- adds more details to the assertion failure message.
- allows disabling GC leak error via `--ignore-gc-leak` flag (will issue [a warning](https://docs.pytest.org/en/stable/how-to/capture-warnings.html) instead).
=> test(core): allow replacing GC leak error by warning via CLI flag

core/SConscript.bootloader, core/SConscript.kernel, core/SConscript.prodtest, core/embed/projects/bootloader/main.c, core/embed/projects/kernel/main.c, core/embed/projects/prodtest/main.c, core/embed/sys/power_manager/inc/sys/power_manager.h, core/embed/sys/power_manager/stm32u5/power_control.c, core/embed/sys/power_manager/stm32u5/power_manager.c, core/embed/sys/power_manager/stm32u5/power_manager_internal.h, core/embed/sys/time/inc/sys/rtc.h, core/embed/sys/time/stm32u5/rtc.c, core/site_scons/models/T3W1/trezor_t3w1_revA.py, core/site_scons/models/T3W1/trezor_t3w1_revB.py, core/site_scons/models/T3W1/trezor_t3w1_revC.py, core/site_scons/models/stm32u5_common.py
This PR introduces a mechanism that allows the device to automatically wake up from suspend mode after a defined timeout. For waking up, we use a dedicated wake-up timer that is part of the RTC peripheral.
A minimalistic RTC driver was implemented (now available in kernel, prodtest and the bootloader).
The `pm_control_suspend()` function now returns wake-up flags, so the caller can decide how to proceed appropriately.
The behavior of `pm_suspend()` hasn't changed yet - there is commented-out code inside suggesting how we can proceed in the future.
=> feat(core): wake up from suspend mode after timeout

core/embed/sys/power_manager/stm32u5/power_manager_internal.h, core/embed/sys/power_manager/stm32u5/power_monitoring.c
This PR removes WPC gradual charging from the power manager. 
unfortunately, NPM1300 has to stop the charging between every change of the charging current setting, which means that gradual charge makes no sense. 
WPC charging changed to start right at maximal charging current, and we may update the charging current to suitable value after thermal tests. 
Charging was tested with current WPC FW and config and all available coils and shows no anomaly.
=> fix: remove wpc gradual charging

core/embed/rust/src/ui/layout_eckhart/bootloader/bld_menu.rs, core/embed/rust/src/ui/layout_eckhart/bootloader/bld_menu_screen.rs, core/embed/rust/src/ui/layout_eckhart/component/button.rs, core/embed/rust/src/ui/layout_eckhart/component/error.rs, core/embed/rust/src/ui/layout_eckhart/component/mod.rs, core/embed/rust/src/ui/layout_eckhart/component/update_screen.rs, core/embed/rust/src/ui/layout_eckhart/firmware/share_words.rs, core/embed/rust/src/ui/layout_eckhart/firmware/vertical_menu.rs, core/embed/rust/src/ui/layout_eckhart/flow/request_passphrase.rs, core/embed/rust/src/ui/layout_eckhart/mod.rs, core/embed/rust/src/ui/layout_eckhart/theme/bootloader.rs, core/embed/rust/src/ui/layout_eckhart/theme/firmware.rs, core/embed/rust/src/ui/layout_eckhart/theme/mod.rs, core/embed/rust/src/ui/layout_eckhart/ui_bootloader.rs, core/embed/rust/src/ui/layout_eckhart/ui_firmware.rs
This PR:
- improves the bootloader menu (reorgs buttons, improves styling, removes "Trezor")
- improves `ErrorScreen` by showing "Wait for device restart" and also moves the "trezor.io" label above that
- implements "UpdateScreen" by delegating to a `TextScreen`/`BldTextScreen` based on `cfg(feature = "..")`
=> Eckhart UI: low hanging bootloader updates

core/translations/de.json, core/translations/signatures.json
This PR ensures consistency in German translation of labeling-related translations:
```
"misc__enable_labeling": "Kennzeichnung aktivieren?",
"misc__title_suite_labeling": "Suite-Kennzeichnung",
```
Translation correctness was also checked with ChatGPT:
=> Ensure consistent German translation for 'labeling'

core/.changelog.d/5218.changed, core/embed/rust/librust_qstr.h, core/embed/rust/src/translations/generated/translated_string.rs, core/embed/rust/src/ui/layout_eckhart/flow/confirm_output.rs, core/embed/rust/src/ui/layout_eckhart/ui_firmware.rs, core/mocks/trezortranslate_keys.pyi, core/src/apps/bitcoin/sign_tx/layout.py, core/src/trezor/ui/layouts/bolt/__init__.py, core/src/trezor/ui/layouts/caesar/__init__.py, core/src/trezor/ui/layouts/delizia/__init__.py, core/src/trezor/ui/layouts/eckhart/__init__.py, core/translations/en.json, core/translations/order.json, core/translations/signatures.json, tests/device_tests/bitcoin/test_signtx_invalid_path.py, tests/device_tests/bitcoin/test_signtx_mixed_inputs.py, tests/device_tests/bitcoin/test_signtx_segwit.py, tests/device_tests/bitcoin/test_signtx_segwit_native.py, tests/device_tests/bitcoin/test_signtx_taproot.py, tests/input_flows.py
This PR includes the following changes:
- Promotes the **multiple accounts warning** to a **cancel-type** warning for **Delizia** and **Eckhart** UIs.
- Fixes the **design** of the **Eckhart** `warning` `FirmwareUI` function.
- Fixes the **title** in the **Eckhart**  `confirm_output` `FirmwareUI` function.
---
- Changed `confirm_output` titles from **"Amount"** and **"Address"** to **"Send"**, per [Figma](https://www.figma.com/design/Dkl7W5PLqpr3TnXJ5hbnfd/--Future-Prod---Safe-7?node-id=6374-1612&t=yfEc0J1asekmLh0U-0) design.
- Introduced new per-layout `confirm_multiple_accounts_warning` function:
- For **[Delizia](https://www.figma.com/design/n43caWJFGJlT167AQcxruu/--Prod---Safe-5?node-id=2033-935&t=xcsxOxPmj95GqOyf-0)** and **[Eckhart](https://www.figma.com/design/Dkl7W5PLqpr3TnXJ5hbnfd …
=> Promote `confirm_multiple_accounts_warning` to danger

core/embed/models/D002/model_D002.h, core/embed/models/D002/secret_layout.h, core/embed/models/T2B1/model_T2B1.h, core/embed/models/T2B1/secret_layout.h, core/embed/models/T3B1/model_T3B1.h, core/embed/models/T3B1/secret_layout.h, core/embed/models/T3T1/model_T3T1.h, core/embed/models/T3T1/secret_layout.h, core/embed/models/T3W1/model_T3W1.h, core/embed/models/T3W1/secret_layout.h, core/embed/projects/bootloader/emulator.c, core/embed/projects/prodtest/cmd/prodtest_optiga.c, core/embed/projects/prodtest/emulator.c, core/embed/projects/unix/main.c, core/embed/sec/monoctr/stm32u5/monoctr.c, core/embed/sec/optiga/optiga_config.c, core/embed/sec/secret/inc/sec/secret.h, core/embed/sec/secret/inc/sec/secret_keys.h, core/embed/sec/secret/stm32f4/secret.c, core/embed/sec/secret/stm32f4/secret_keys.c, core/embed/sec/secret/stm32u5/secret.c, core/embed/sec/secret/stm32u5/secret_keys.c, core/embed/sec/secret/unix/secret.c, core/embed/sec/secret/unix/secret_keys.c, core/embed/sec/tropic/tropic.c, core/site_scons/models/stm32f4_common.py, core/site_scons/models/stm32u5_common.py, core/site_scons/models/unix_common.py
This PR refactors secret API to accommodate needs for more complex keys handling.
Secret API is unified to be independent on optiga/tropic presence, and a specific secret_keys extension is introduced to handle these specific keys. 
Secret storage layout is now model dependent.
On U5, new key variant, public, is introduced: such keys are always provided to FW and are not erased on bootloader unlock. 
On T3W1 we still use original secret layout with three keys stored, change to 'root key' and derivations are left to next work. 
Ad review: @andrewkozlik and @onvej-sl as you will be working on the derivations, please look over the API to see if it can work. No need to go trough implementation details if you dont want to.
=> make secret api more versatile

core/embed/io/display/display_utils.c, core/embed/projects/bootloader/workflow/wf_empty_device.c, core/embed/rust/src/ui/layout/simplified.rs, core/embed/rust/src/ui/layout_bolt/bootloader/mod.rs, core/embed/rust/src/ui/layout_caesar/bootloader/mod.rs, core/embed/rust/src/ui/layout_delizia/bootloader/mod.rs, core/embed/rust/src/ui/layout_eckhart/ui_bootloader.rs
Removed boot stage 1 to optimize UX when booting.  
there is now larger delay between first screen is shown, we can probably optimize a bit more but it will be larger than 1 s anyway i guess. currently at about 1.4 s, which seems bordeline to me. Product confirmation needed.
Some backlight fading was removed to optimize the boot a bit.
=> Eckhart: remove boot stage 1 screen

core/embed/sys/startup/inc/sys/sysutils.h, core/embed/sys/task/stm32/system.c
This small PR fixes an issue with RSOD in the secure monitor.
The fix removes the transition from handler mode to thread mode inside the `system_emergency_rescue()` function, which is responsible for cleaning up memory and resources before the RSOD is displayed.
It appears that transitioning from handler mode to thread mode cannot be reliably performed in all circumstances when running in the secure monitor. Since we don't need to invoke `error_handler` (because we use `USE_BOOTARGS_RSOD` in the secure monitor), we can safely skip this automatic transition.
=> fix(core): fix RSOD handling in secmon

core/embed/sec/secret/stm32f4/secret.c
Otherwise, it fails with:
```
$ TREZOR_MODEL=T2B1 BITCOIN_ONLY=0 PYOPT=0 QUIET_MODE=1 make -C core build_firmware
...
embed/sec/secret/stm32f4/secret.c: In function 'secret_unlock_bootloader':
embed/sec/secret/stm32f4/secret.c:74:39: error: implicit declaration of function 'secret_erase'; did you mean 'secret_read'? [-Werror=implicit-function-declaration]
74 | void secret_unlock_bootloader(void) { secret_erase(); }
|                                       ^~~~~~~~~~~~
|                                       secret_read
embed/sec/secret/stm32f4/secret.c: At top level:
embed/sec/secret/stm32f4/secret.c:135:6: error: conflicting types for 'secret_erase'; have 'void(void)' [-Werror]
135 | void secret_erase(void) {
|      ^~~~~~~~~~~~
embed/sec/secret/stm32f4/secret.c:74:39: note: previous …
```
=> build(core): fix T2B1 build

core/SConscript.prodtest, core/SConscript.prodtest_emu, core/embed/projects/prodtest/.changelog.d/5162.added, core/embed/projects/prodtest/cmd/common.c, core/embed/projects/prodtest/cmd/common.h, core/embed/projects/prodtest/cmd/prodtest_optiga.c, crypto/der.h
This pull request introduces two features in the validation of the certification chain during provisioning:
1. In https://github.com/trezor/trezor-firmware/commit/05f875da328da82998e8df896dd9d2777b01075c, it parses the common name from the device certificate and verifies that it matches the Trezor model being provisioned.
2. In https://github.com/trezor/trezor-firmware/commit/10b07eb417b378cc4183d42ed51e291d3ad3ff9e, it adds support for certificates based on ed25519.
=> Validation of certificates in prodtest

core/embed/projects/bootloader/bootui.c, core/embed/projects/bootloader/main.c, core/embed/rust/src/ui/layout_bolt/bootloader/mod.rs, core/embed/rust/src/ui/layout_caesar/bootloader/mod.rs, core/embed/rust/src/ui/layout_delizia/bootloader/mod.rs, core/embed/rust/src/ui/layout_eckhart/bootloader/bld_header.rs, core/embed/rust/src/ui/layout_eckhart/ui_bootloader.rs
In eckhart UI, after wiping device from bootloader, the success screen now include a restart button, so that user doesn't have to wait until rebooot.
Same applies to unlock bootloader flow. 
Some minor adjustments to unlock bootloader screens were made too.
Also, integer overflow in wipe progress calculation is fixed.
Other models will hang in the success screen until unplugged.
=> Eckhart: adjust wipe success screen in bootloader

core/embed/projects/prodtest/README.md, core/embed/projects/prodtest/cmd/prodtest_power_manager.c, core/embed/sys/backup_ram/inc/sys/backup_ram.h, core/embed/sys/backup_ram/stm32u5/backup_ram.c, core/embed/sys/power_manager/fuel_gauge/fuel_gauge.c, core/embed/sys/power_manager/stm32u5/power_monitoring.c
This tiny PR fix an issue with out-of-bound SoC estimation during battery initialization.
The initial estimate was not bounded, so time to time it returned crazy estimates when battery was not connected and then showing SoC 255% in the core app.
This PR also add simple prodtest command `pm-new-soc-estimate` which is helpful when a user need to test battery initialization several times. Command disable the power manager, erase recovery data from backup ram an reboot the device to get a new estimate. 
Before, this was usually done by simply erasing the backup ram and manually rebooting the device, but after backup ram refactor this is no longer possible, since now it could recover from data loss.
=> Fix fuel gauge soc limit during initial estimation

core/embed/io/nrf/inc/io/nrf.h, core/embed/io/nrf/stm32u5/nrf_uart.c, core/embed/rust/src/smp/echo.rs, core/embed/rust/src/smp/mod.rs, core/embed/rust/src/smp/reset.rs, core/embed/rust/src/smp/upload.rs, core/embed/rust/src/trezorhal/nrf.rs
This PR introduces timeout detection for uart/dfu communication with nRF. This helps in situation where the nrf is not communicating - instead of hanging forever there will be more appropriate timeout failure.
=> add timeout to nrf uart communication

core/SConscript.bootloader_emu, core/embed/io/ble/inc/io/ble.h, core/embed/io/ble/stm32/ble.c, core/embed/io/ble/unix/ble.c, core/embed/projects/bootloader/wire/wire_iface_ble.c, core/embed/projects/bootloader/workflow/wf_ble_pairing_request.c, core/embed/projects/bootloader/workflow/wf_empty_device.c, core/embed/projects/bootloader/workflow/workflow.h, core/embed/rust/rust_ui_bootloader.h, core/embed/rust/src/ui/api/bootloader_c.rs, core/embed/rust/src/ui/layout_bolt/bootloader/mod.rs, core/embed/rust/src/ui/layout_caesar/bootloader/mod.rs, core/embed/rust/src/ui/layout_delizia/bootloader/mod.rs, core/embed/rust/src/ui/layout_eckhart/bootloader/pairing_mode.rs, core/embed/rust/src/ui/layout_eckhart/ui_bootloader.rs, core/embed/rust/src/ui/ui_bootloader.rs
This PR introduces wireless setup flow for BLE-enabled bootloader.
Screens are just mocks that need proper UI implementation.
Random part to advertising name was added in pairing mode.
=> bootloader wireless setup flow

core/embed/rust/src/ui/api/firmware_micropython.rs, core/embed/rust/src/ui/layout_bolt/ui_firmware.rs, core/embed/rust/src/ui/layout_caesar/ui_firmware.rs, core/embed/rust/src/ui/layout_delizia/flow/util.rs, core/embed/rust/src/ui/layout_delizia/ui_firmware.rs, core/embed/rust/src/ui/layout_eckhart/ui_firmware.rs, core/embed/rust/src/ui/ui_firmware.rs, core/mocks/generated/trezorui_api.pyi, core/src/trezor/ui/layouts/menu.py
Rebased over https://github.com/trezor/trezor-firmware/pull/5295.
Can be tested using the following snippet:
```python
from trezor.ui.layouts.menu import Details, Menu, Properties, show_menu
menu = Menu.root(
Details("Blockhash", Properties.data("00000000000000000000e8e69d805078afa15947eaf0cc3fe0a9f563da20f93c")),
Details("Fee info", Properties.paragraphs(fee_details)),
cancel=TR.send__cancel_sign,
)
await show_menu(menu, br_name=None)
```
[Screencast from 2025-07-03 18-16-03.webm](https://github.com/user-attachments/assets/ac9b15da-9a60-4753-b2bf-ff902ba14554)
Currently supports up to 3 items per menu.
=> Introduce menu-related layouts for Delizia

core/src/apps/thp/credential_manager.py
All `SLIP-21` paths in FW start either with the `"SLIP-XXXX"` prefix if they are used for a purpose defined in some SLIP, or with `"TREZOR"` prefix when the purpose is not part of any SLIP.
This PR adds the `"TREZOR"` prefix to the THP credential key derivation path. The path is also modified to reflect that the credential key is used for THP and not other type of Trezor-specific credentials.
=> Unify SLIP-21 paths used in FW

core/embed/rust/src/ui/api/firmware_micropython.rs, core/embed/rust/src/ui/layout_caesar/component/input_methods/simple_choice.rs, core/embed/rust/src/ui/layout_caesar/component_msg_obj.rs, core/embed/rust/src/ui/layout_caesar/ui_firmware.rs, core/embed/rust/src/ui/layout_delizia/flow/set_brightness.rs, core/mocks/generated/trezorui_api.pyi, core/src/trezor/ui/layouts/caesar/__init__.py, core/src/trezor/ui/layouts/delizia/__init__.py, core/src/trezor/ui/layouts/menu.py, python/src/trezorlib/debuglink.py, tests/device_tests/test_msg_applysettings.py, tests/input_flows.py
~Rebased over #5296.~
In Delizia, it should be possible to cancel the flow using the menu.
In Caesar, the menu doesn't support cancellation - so it should return `CONFIRMED` instead.
Also, allow menu details (the leaves of the menu hierarchy) to be generic awaitables.
It should be useful for [payment requests confirmation UI](https://github.com/trezor/trezor-firmware/pull/5253).
Tested by replacing `set_brightness` menu in Delizia.
=> fix(core): don't ignore `ActionCancelled` exception from menu

core/embed/projects/bootloader/workflow/wf_ble_pairing_request.c, core/embed/rust/rust_ui_bootloader.h, core/embed/rust/src/ui/api/bootloader_c.rs, core/embed/rust/src/ui/layout_bolt/bootloader/mod.rs, core/embed/rust/src/ui/layout_caesar/bootloader/mod.rs, core/embed/rust/src/ui/layout_delizia/bootloader/mod.rs, core/embed/rust/src/ui/layout_eckhart/ui_bootloader.rs, core/embed/rust/src/ui/ui_bootloader.rs
removing final screen, as we now returning to the welcome screen after pairing is done
=> simplify wireless setup flow

tests/click_tests/recovery.py
It seems that there is a race between starting the recovery flow and verifying its layout, causing [test failures when running persistence_tests on THP](https://github.com/trezor/trezor-firmware/actions/runs/16174356159/job/45656150594#step:6:235).
https://github.com/trezor/trezor-firmware/blob/953b0e23d1ae4ba433f512df95530154d13ace5d/tests/persistence_tests/test_shamir_persistence.py#L47-L49
=> test(core): fix waiting for recovery

core/embed/projects/bootloader/workflow/wf_host_control.c, core/embed/rust/build.rs, core/embed/rust/src/trezorhal/power_manager.rs, core/embed/rust/src/trezorhal/sysevent.rs, core/embed/rust/src/ui/layout/simplified.rs, core/embed/sys/power_manager/unix/power_manager.c
This PR introduces auto dimming and auto suspending of bootloader on inactivity.
After suspending and resuming, the flow continues where it ended.
Timing is subject to further tuning.
=> autodim & autosuspend bootloader on inactivity

core/embed/sys/smcall/stm32/smcall_verifiers.h, core/site_scons/models/D002/discovery2.py
This small PR fixes the firmware build for the D002 model.
- It enables `LOCKABLE_BOOTLOADER` for discovery kit as well.
- Fixes conditional compilation of backup ram smcalls
=> fix(core): fix D002 model build

core/embed/projects/bootloader/main.c, core/embed/projects/bootloader/workflow/wf_empty_device.c, core/embed/projects/bootloader/workflow/wf_firmware_update.c, core/embed/projects/bootloader/workflow/wf_wipe_device.c, core/embed/projects/prodtest/cmd/prodtest_backup_ram.c, core/embed/sys/backup_ram/inc/sys/backup_ram.h, core/embed/sys/backup_ram/stm32u5/backup_ram.c, core/embed/sys/power_manager/inc/sys/power_manager.h, core/embed/sys/power_manager/stm32u5/power_manager.c, core/embed/sys/power_manager/stm32u5/power_manager_internal.h, core/embed/sys/smcall/stm32/smcall_dispatch.c, core/embed/sys/smcall/stm32/smcall_stubs.c, core/embed/sys/smcall/stm32/smcall_verifiers.c, core/embed/sys/smcall/stm32/smcall_verifiers.h
This PR prepares backup ram for future use cases where we would store sensitive data in backup ram
Such data will be erased along with storage when bootloader i.e. changes firmware vendor.
=> erase backup ram in bootloader when erasing storage

core/embed/rust/src/ui/layout_eckhart/prodtest/welcome.rs
Sets screen green when charging is done, red when discharging.
Applies to T3W1 prodtest homescreen only.
=> adjust screen color according to charging state in prodtest

core/src/apps/management/ble/pair_new_device.py, core/src/trezor/ui/layouts/bolt/__init__.py, core/src/trezor/ui/layouts/bolt/reset.py, core/src/trezor/ui/layouts/caesar/__init__.py, core/src/trezor/ui/layouts/caesar/reset.py, core/src/trezor/ui/layouts/common.py, core/src/trezor/ui/layouts/delizia/__init__.py, core/src/trezor/ui/layouts/delizia/recovery.py, core/src/trezor/ui/layouts/delizia/reset.py, core/src/trezor/ui/layouts/eckhart/__init__.py, core/src/trezor/ui/layouts/eckhart/recovery.py, core/src/trezor/ui/layouts/eckhart/reset.py
We do not care about the result of `interact` call, we let it raise if the action is cancelled. If the `interact` does not raise, any output (eg. `UiResult.CONFIRMED`, `UiResult.INFO`) is treated as valid - thus the renaming brings clarity to what this function actually does.
=> Rename  `raise_if_not_confirmed` to `raise_if_cancelled`

core/.changelog.d/5308.fixed, core/src/apps/solana/layout.py
Also, confirm each account separately, in order to avoid overflowing `ParagraphVecLong`.
Tested locally using `solana/test_sign_tx.py::test_solana_sign_tx[unknown_instruction]` transaction:
```
$ SOLTX=0200010300d1699dcb1811b50bb0055f13044463128242e37a463b52f6c97a1f6eef88ad8f41927b2e58cbc31ed3aa5163a7b8ca4eb5590e8dc1dc682426cd2895aa9c0a8f41927b2e58cbc31ed3aa5163a7b8ca4eb5590e8dc1dc682426cd2895aa9c0a1aea57c9906a7cad656ff61b3893abda63f4b6b210c939855e7ab6e54049213d010202000104deadbeef
$ core/emu.py -sea -c trezorctl -v solana sign-tx -n 'm/44h/501h/0h/0h' $SOLTX
```
[Screencast from 2025-07-13 21-27-39.webm](https://github.com/user-attachments/assets/237961d1-8b2d-43de-9e68-138feff62e90)
Followups:
=> fix(core): add missing `PropertyType` element for Solana confirmation

.github/workflows/core.yml, core/Makefile
Don't use `trezorctl` for sanity test, since it requires pairing confirmation.
Should be squashed in fd6135445859c7c315f598bc89a3046e26d6b6bc.
=> fixup! test(core): fix `test_emu_sanity` on THP emulators

core/embed/rust/src/ui/layout_delizia/component/vertical_menu.rs, core/embed/rust/src/ui/layout_delizia/flow/confirm_action.rs
Rebased over #5333.
Also, refactor `new_confirm_action_uni` a bit.
=> test(core): visit `confirm_action()` menu during tests

core/embed/sys/smcall/stm32/smcall_dispatch.c, core/embed/sys/syscall/stm32/syscall_dispatch.c, legacy/sys/mpu.h, storage/storage.c, storage/tests/c/sys/mpu.h
This PR moves MPU reconfiguration - enabling access to the storage flash region - directly to the storage module. 
This change fixes the following issues:
1) The MPU was reconfigured in the wrong place - the storage API could only be called via smcall or syscall
2) The MPU reconfiguration code was duplicated in both the smcall and syscall dispatchers
3) On models with secmon, the MPU was reconfigured in the kernel even when it was not necessary
The change has no effect on device behavior.
=> refactor(core):  reconfigure mpu directly in the storage

core/embed/io/display/ltdc_dsi/display_driver.c, core/embed/io/rgb_led/stm32u5/rgb_led_lp.c, core/embed/io/usb/stm32/usbd_conf.c
Few drivers were using this - display, usb, led
=> save flash by not using HAL for periph clock configuration

core/embed/util/rsod/rsod.c
This tiny PR saves about 2 KB of flash in the bootloader when `FANCY_FATAL_ERROR` is enabled (T3T1/T3W1).
It removes an unnecessary terminal-based RSOD that never appears to the user.
=> perf(core): save flash by not unnecessary linking terminal RSOD

core/embed/sys/power_manager/stm32u5/power_states.c
This PR add transition from PM_STATE_SHUTTING_DOWN to PM_STATE_SUSPEND to power manager state machine, which means that app is now able to suspend the device during the device 15s shutting down period.
Even though such transition do not make a perfect sense, pm is suspended from lots of different places (core app + several bootloader workflows) and some of those workflows do not handle the shutting down corner case. In case the `pm_suspend` was called during shutting down it led to weird behavior when device fade down while trying to suspend -> suspend got rejected -> device fade up again and hibernate next couple of seconds. 
Now if the workflow call `pm_suspend`, device got suspended with slightly higher power consumption but on wake-up it goes back to PM_STATE_POWER_SAVE, from which …
=> Power manager suspend during shutting down

core/src/apps/nostr/sign_event.py, core/src/apps/solana/layout.py, core/src/trezor/ui/layouts/caesar/__init__.py, core/src/trezor/ui/layouts/menu.py, tests/input_flows_helpers.py
Also, move Solana `blockhash` to the first confirmation menu on all layouts.
=> feat(core): use menu for `confirm_value`-related info items on Caesar

.github/workflows/core.yml
- the comment action fails when run on a PR created from a fork
- see https://github.com/peter-evans/create-or-update-comment/blob/9fa92b4fea95714d51d64d8e90d8817fe499e1cb/README.md
[no changelog]
=> ci(core): skip UI comment job on external PRs

core/.changelog.d/5378.fixed, core/embed/sys/mpu/stm32u5/mpu.c
This PR fixes an issue that causes a crash on STM32U5 devices (T3B1, T3T1, and T3W1) when the firmware is downloaded and run for the first time.
The crash results in a RSOD, but it does not leave the device in an invalid state. After a power cycle (powering the device off and on), the device operates normally.
The issue is caused by incorrect MPU configuration for a specific sequence of FLASH memory writes that occurs immediately after the device is run for the first time. For more details, see the added comment in the source code.
=> fix(core): fix MPU configuration

core/.changelog.d/4410.fixed, core/embed/rust/src/ui/layout_bolt/component/set_brightness.rs, core/embed/rust/src/ui/layout_bolt/ui_firmware.rs, core/embed/rust/src/ui/layout_delizia/flow/set_brightness.rs, core/embed/rust/src/ui/layout_delizia/ui_firmware.rs, core/embed/rust/src/ui/layout_eckhart/firmware/brightness_screen.rs, core/embed/rust/src/ui/layout_eckhart/ui_firmware.rs, core/src/apps/management/set_brightness.py, core/src/trezor/ui/layouts/delizia/__init__.py, tests/device_tests/test_msg_applysettings.py, tests/input_flows.py
This PR:
1. adds the missing brightness value parameter in `set_brightness` function
2. If the value has been passed, the brightness is set to this value
3. Parametrizes existing tests to test different scenarios (screenshots do not show the brightness correctly, but locally it works well)
4. [delizia] Fixes inconsistent brightness in `set_brightness` flow by making the flow have 1 screen only.
=> chore(core): add missing parameter to set_brightness function

core/embed/io/nrf/inc/io/nrf.h, core/embed/io/nrf/stm32u5/nrf_test.c, core/embed/projects/prodtest/README.md, core/embed/projects/prodtest/cmd/prodtest_nrf.c, core/embed/projects/prodtest/cmd/prodtest_secrets.c, core/embed/sec/secret/inc/sec/secret_keys.h, core/embed/sec/secret/stm32u5/secret_keys.c, nordic/trezor/trezor-ble/src/prodtest/prodtest.c
This PR adds support for basic pairing of main MCU and nRF. 
Symmetric keys is exchanged in prodtest and stored on nRF. Trezor derives the key from master secret key.
=> nrf pairing

core/embed/sys/power_manager/stm32u5/power_manager.c, core/embed/sys/power_manager/stm32u5/power_manager_internal.h, core/embed/sys/power_manager/stm32u5/power_monitoring.c
This PR introduce simple temperature controller which limits the charging current based on the device temperature to prevent overheating during charging (especially on WPC).
Temperature controller defines 4 temperature bands for which continuously decrease charging current limit. 
- T < 39°C : NO LIMIT
- T >= 39°C && T < 43°C : 70% of max charging current
- T >= 43°C && T< 45°C : 50% of max charging current
- T >=45°C && T< 47°C : 30% of max charging current
- T >= 47°C : CHARGING STOPPED
temperature controller is debounced with 2min interval after every control action to avoid fuzzy behavior during crossing the threshold from band to band. 
PR also refactors some charging controller variables which were to long.
=> power managere simple temperature controller

core/embed/projects/prodtest/cmd/prodtest_power_manager.c
Fix leftover 'limit' in pm-set-soc-target prodtest command parameter parser.
=> fix parameter parsing in pm-set-soc-target command.

core/embed/projects/prodtest/cmd/prodtest_secrets.c
as requested by tester team, it makes their live easier - if the keys are not writable and present, lets just say that the command succeeded.
=> make secrets-init calling repeatable

.github/workflows/core.yml
Most of the tests take ~1s, so let's print only the top 10:
After this PR:
=> ci(core): print less test durations

core/embed/projects/prodtest/cmd/prodtest_optiga.c
Pairing was not functional - optiga is weird state after failed handshake attempt. This behavior is also applied in `optiga_init_and_configure`.
=> reset optiga after failed handshake during pairing

core/embed/io/ble/inc/io/ble.h, core/embed/io/ble/stm32/ble.c, core/embed/io/nrf/stm32u5/nrf.c
nRF driver wasn't properly reinitializaed
BLE advertising name wasn't preserved during suspend/resume cycle
=> fix ble suspend/resume

shell.nix
Emulator can't be started on default Ubuntu 25.04 install. Let's see if it resolves in time or if we need to fix our code (or rewrite it to use SDL3, not sure if it doesn't break our library of old emulator binaries).
=> shell.nix: workaround ERROR: SDL_CreateRenderer error

python/src/trezorlib/debuglink.py, tests/click_tests/test_autolock.py
Otherwise, some commands (e.g. `DebugLinkRecordScreen`) could fail without raising `TrezorFailure`.
=> test(core): check `DebugLink._call()` response to avoid dropping errors

python/src/trezorlib/debuglink.py, tests/device_tests/test_msg_changepin_t2.py
Also, keep the previous GC info result when creating a new THP channel.
=> test(core): use a shorter pin sequence

python/src/trezorlib/transport/thp/protocol_v2.py
If the device is locked, `ThpDeviceLockedError` is raised and `ThpErrorType.DEVICE_LOCKED` error packet is sent to the host (which doesn't require an ACK).
=> fix(python): verify THP handshake init response before `ACK`ing it

core/src/apps/debug/__init__.py, tests/device_tests/test_debuglink.py
Following #5457.
Previously the device responded with `FirmwareError: 'module' object has no attribute 'reseed'`.
Tested 44639cb9c9b21c807fac898ada3d1e9c2ffdd97b on T3T1:
```
[2025-08-02 19:09:54,105] trezorlib.transport.thp.protocol_v1 DEBUG: sending message: DebugLinkReseedRandom
DebugLinkReseedRandom (2 bytes) {
value: 0,
}
[2025-08-02 19:09:54,293] trezorlib.transport.thp.protocol_v1 DEBUG: received message: Failure
Failure (37 bytes) {
code: UnexpectedMessage (1),
message: 'reseed only supported on emulator',
}
```
=> test(core): fix `test_softlock_instability` failure on hardware tests

nordic/trezor/trezor-ble/src/ble/ble_internal.h, nordic/trezor/trezor-ble/src/ble/inc/ble/ble.h, nordic/trezor/trezor-ble/src/management/management.c
This PR fixes issue with advertising still running in suspend mode, if some device was connected before suspending and there is more than one device bonded.
=> ble: stop advertising when suspended

core/embed/sys/suspend/stm32u5/suspend.c
When the device is woke up from suspend by connecting the USB cable or WPC, WAKEUP_FLAG_POWER is not set during the interrupt right after the CPU wakes up, but only after the pmic driver is resumed in `background_task_resume()` function. 
This caused that suspend flag is missed, suspend loop will start another iteration and start suspending the background task again. After doing that, WAKEUP_FLAG_POWER is read while waiting to all background tasks to get suspended, resumed drivers again and finally exit the suspend. 
This PR fixes this by reading the wakeup flags again after the background tasks got resume
=> Fix suspend loop exit after wakeup from connected power source

python/src/trezorlib/transport/thp/protocol_v2.py
IIUC, it's possible that the device will retransmit old packets while a new test is being started.
=> fix(core): skip unexpected THP packet during channel allocation

python/src/trezorlib/_internal/emulator.py, python/src/trezorlib/debuglink.py
Currently `TrezorClientDebugLink` is trying to perform THP pairing, which fails without DebugLink:
https://github.com/trezor/trezor-firmware/actions/runs/16763491862/job/47463919195
```
File "/home/runner/work/trezor-firmware/trezor-firmware/core/emu.py", line 278, in cli
emulator.start()
~~~~~~~~~~~~~~^^
File "/home/runner/work/trezor-firmware/trezor-firmware/python/src/trezorlib/_internal/emulator.py", line 197, in start
self._client = TrezorClientDebugLink(
~~~~~~~~~~~~~~~~~~~~~^
self.transport,
^^^^^^^^^^^^^^^
...<2 lines>...
debug_transport=debug_transport,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
)
^
File "/home/runner/work/trezor-firmware/trezor-firmware/python/src/trezorlib/debuglink.py", line 1319, in __init__
self.do_pairing(pairing_method=messages.ThpPairingMethod.SkipPairing) …
```
=> test(core): fix `test_emu_sanity` on T3W1 non-debug emulators

core/src/apps/homescreen/device_menu.py
Put `log.debug` call in `device_menu` into an `if __debug__` block.
=> fix(core): remove log from prod

python/src/trezorlib/_internal/firmware_headers.py, python/src/trezorlib/firmware/core.py, python/src/trezorlib/firmware/models.py
ROOT keys are _common_ and should not be part of `BootloaderV2Image` only.
=> chore(python): move dev keys from BootloaderV2Image

core/src/apps/debug/__init__.py, tests/conftest.py
It allows THP-based debug builds to be wiped without unlocking.
Also, some of the entropy-related UI fixtures had to be changed.
~Rebased over #5493.~
=> test(core): allow wiping via DebugLink

core/embed/rtl/error_handling.c, core/embed/rust/src/ui/layout_caesar/component/error.rs, core/embed/rust/src/ui/layout_caesar/theme/mod.rs, core/embed/rust/src/ui/layout_eckhart/bootloader/bld_header.rs, core/embed/rust/src/ui/layout_eckhart/component/error.rs, core/embed/util/rsod/rsod.c
- Eckhart RSOD now says "Wait for Trezor shutdown" (not restart)
- the footer now says "Please visit trezor.io/rsod" after wipe code entry or running out of PIN attempts
- default title/message/footer texts are lowercase for T3W1
- titles used in `error_handling.c` are lowercase so that it looks nicer. However we want to keep the readability on T2B1/T3B1 so the `_UPPER` font is used which renders it uppercase
=> feat(core): adjust RSOD

core/src/trezor/loop.py
Following https://github.com/trezor/trezor-firmware/issues/5472#issuecomment-3174382038 and https://github.com/trezor/trezor-firmware/pull/5523.
Also related to https://github.com/trezor/trezor-firmware/issues/5526.
=> fix(core): don't reuse `TASK_CLOSED` exception object

core/src/trezor/wire/thp/__init__.py, core/src/trezor/wire/thp/interface_context.py, python/src/trezorlib/debuglink.py, python/src/trezorlib/transport/thp/message_header.py, python/src/trezorlib/transport/thp/protocol_v2.py, tests/ui_tests/__init__.py
It will be also used to allow stopping an idle workflow due to an unresponsive host.
=> feat(core): add THP transport-level `PING`/`PONG` messages

core/embed/rust/src/ui/layout_eckhart/firmware/action_bar.rs, core/embed/rust/src/ui/layout_eckhart/firmware/hold_to_confirm.rs
implementation equivalent to `Delizia`'s `HoldToConfirmAnim` component.
=> feat(core/eckhart): haptic feedback for HTC animation

core/embed/projects/prodtest/.changelog.d/5604.fixed, core/embed/projects/prodtest/cmd/prodtest_secrets.c
This PR fixes argument count checking of `secrets-certdev-write` command.
=> fix(prodtest): fix secrets-certdev-write arg count check

core/src/trezor/wire/thp/channel.py, core/src/trezor/wire/thp/interface_context.py
=> feat(core): reimplement THP retransmissions

core/embed/io/haptic/drv2625/drv2625.c, core/embed/io/haptic/inc/io/haptic.h, core/embed/projects/bootloader/main.c
This PR increases the strength of haptic effect played when the device is powered on.
=> stronger haptic effect on power on

core/embed/rust/src/ui/layout_eckhart/firmware/device_menu_screen.rs
Otherwise, [entering the menu when connected via BLE results in a RSOD](https://drive.google.com/file/d/1RPv42auw1Ya6XWB0NJ3zy8ZD54m4AR0J).
```
[23:04:01.509] === FATAL ERROR
[23:04:01.509] Location: src/ui/layout_eckhart/firmware/device_menu_screen.rs:373
[23:04:01.509] Message: unwrap failed
```
Reproduced on 375d6e10ca.
=> fix(core): increase `MAX_SUBSCREENS` a bit

core/src/trezor/wire/thp/channel.py, core/src/trezor/wire/thp/session_context.py
In case of an error, we cannot re-use the same message that has caused the error in the first place.
<details>
<summary> Device debug log </summary>
```
[22:14:24.273] 429.849 trezor.loop DEBUG finish: <generator object 'timer_task' at 0x201e3c20>
[22:14:24.387] 429.963 trezor.loop DEBUG finish: <generator object 'timer_task' at 0x201e3d50>
[22:14:24.503] 430.079 trezor.loop DEBUG finish: <generator object 'timer_task' at 0x201e3e80>
[22:14:24.618] 430.193 trezor.loop DEBUG finish: <generator object 'timer_task' at 0x201e3fb0>
[22:14:24.733] 430.309 trezor.loop DEBUG finish: <generator object 'timer_task' at 0x201e40e0>
[22:14:24.975] 430.551 trezor.loop DEBUG finish: <generator object 'timer_task' at 0x201d3640>
[22:14:24.976] 430.552 trezor.loop DEBUG finish: <generator object …
```
=> fix(core): avoid infinite THP error loop

common/tests/fixtures/ethereum/sign_tx.json, core/.changelog.d/5134.changed, core/src/apps/ethereum/keychain.py
- Previously only non-standard networks (not SLIP-44 60 or 1) could cross-sign with Ethereum mainnet. Now any network that isn't Ethereum mainnet can use Ethereum derivation paths
- This is a workaround enabling access to networks like Hyperliquid that have conflicting chain IDs and can't claim official SLIP-44 registration.
closes #5134
=> Allow cross-sign with ETH mainnet for all non-ETH networks

core/src/apps/thp/pairing.py, python/src/trezorlib/cli/__init__.py, python/src/trezorlib/client.py, python/src/trezorlib/exceptions.py, python/src/trezorlib/transport/thp/protocol_v2.py, tests/device_tests/thp/test_pairing.py
Following https://github.com/trezor/trezor-firmware/pull/5613.
A few error examples:
```md
$ trezorctl ping 123 
Failed to connect: TransportException (No Trezor device found)
$ trezorctl ping 123
Please confirm action on your Trezor device.
Failed to connect: Cancelled
$ trezorctl btc get-address -n m/44h/0h/0h/0/0 
Please confirm action on your Trezor device.
Failed to connect: TrezorFailure (NotInitialized: Device is not initialized)
$ trezorctl ping 123
Please confirm action on your Trezor device.
Enter code from Trezor: 000000
Failed to connect: TrezorFailure (FirmwareError: Unexpected Code Entry Tag)
$ trezorctl ping 123 -b
Please confirm action on your Trezor device.
Action was cancelled.
```
=> fix(python): improve `trezorctl` THP error handling

core/src/apps/thp/pairing.py, core/src/trezor/wire/__init__.py, core/src/trezor/wire/context.py, core/src/trezor/wire/thp/channel.py, core/src/trezor/wire/thp/interface_context.py, core/src/trezor/wire/thp/session_context.py
In case an existing channel becomes unresponsive, we allow another channel on the same interface to preempt the active workflow (by restarting the event loop).
If there are no other active channels, the existing channel will not be preempted.
In the future, we should use [the newly introduced `Ping`/`Pong` messages](https://github.com/trezor/trezor-firmware/pull/5563) - but since they are not supported by Suite, a channel can be preempted only 1 second after the last THP device->host write (giving the host enough time to respond).
- the "preempting" message will be responded with `TRANSPORT_BUSY` so the host needs to retry to "acquire" its channel (after the stale workflow is cancelled and the event loop is restarted).
- initially it was done by time-based buffers locking, but was dropped …
=> Allow preempting stale THP channels

core/embed/io/ble/inc/io/ble.h, core/embed/io/ble/stm32/ble.c, core/embed/projects/bootloader/wire/wire_iface_ble.c, core/embed/projects/bootloader/workflow/wf_bootloader.c
This PR fixes a bug that caused disconnection of BLE when deinitializing interface and thus, caused unexpected disconnection when jumping to firmware.
Along with that, an edge situation is fixed where leaving pairing mode in bootloader left the device advertising even if the paring was launched from bootloader state that did not allow connection to host. For this, new BLE driver state is introduced to keep track whether advertisement should be restarted after disconnect (end of KEEP_CONNECTED mode) , and a new command that resets this flag when needed.
=> do not disconnect BLE when rebooting to firmware

core/embed/projects/bootloader/workflow/wf_wipe_device.c, nordic/trezor/trezor-ble/src/ble/bonds.c
This PR fixes an unexpected behavior which caused BLE central to stay connected when its bond was deleted on Trezor. We now force a disconnect of the device which bond is deleted.
When doing factory reset, answer to host is send prior to deleting bonds, as the connection will be dropped and no (BLE) communication is possible.
=> disconnect BLE on bond erase

core/embed/projects/bootloader/bootui.h, core/embed/projects/bootloader/workflow/wf_host_control.c, core/embed/projects/prodtest/cmd/prodtest_touch.c, core/embed/projects/prodtest/main.c, core/embed/rust/src/ui/layout_eckhart/theme/backlight.rs
Update of default normal backlight settings from 150->85 according to request from design
=> Adjust backlight normal settings to 85

core/embed/rust/src/ui/layout_eckhart/firmware/vertical_menu_screen.rs
Seems like only `request_paint` was omitted when updating the clip position.
=> fix(core/eckhart): make scrolling smoother

python/README.md
Add git submodule instruction to local trezorctl setup, because it is not clear at first glance that I have to do it.
When I don't, `poetry install` crashes because `vendor/ts-tvl/` is not a python module.
=> docs(python): mention git submodules in trezorctl setup

core/embed/rust/src/ui/layout_eckhart/component/button.rs, core/embed/rust/src/ui/layout_eckhart/firmware/device_menu_screen.rs
1. In the device menu, the device name could be longer than what fits in the subtitle, so we should let it overflow rather than crash!
2. In the pair & connect menu, the device name could be longer than what can fit in the text, so we should let that overflow as well!
Related to #4897
Basically we need to revert the debug-only check for the subtext introduced by #4907 in the case of the device name, while letting it crash in any other case to catch copy errors...
And also we should allow *menu items with text and subtext* have `single_line` text - which does not use `split_two_lines` which checks for overflow...
=> Allow device name to overflow

core/embed/rust/librust_qstr.h, core/embed/rust/src/trezorhal/ble/micropython.rs, core/embed/upymod/modtrezorio/modtrezorio.c, core/mocks/generated/trezorble.pyi, core/mocks/generated/trezorio/__init__.pyi, core/src/apps/management/reboot_to_bootloader.py, core/src/trezor/wire/thp/interface_context.py
In general, Trezor should not wait for too long for a THP ACK when sending the `Success` response (since the last ACK may be lost, similar to [Two generals' agreement and TCP handshake](https://stackoverflow.com/q/36352236)).
This PR will allow sending `Success` response 3 times (due to THP retransmissions) and proceed to reboot the device.
Fixes #5667.
=> Use a shorter timeout when rebooting

core/embed/rust/librust_qstr.h, core/embed/rust/src/translations/generated/translated_string.rs, core/embed/rust/src/ui/api/firmware_micropython.rs, core/embed/rust/src/ui/layout/device_menu_result.rs, core/embed/rust/src/ui/layout_eckhart/component_msg_obj.rs, core/embed/rust/src/ui/layout_eckhart/firmware/device_menu_screen.rs, core/embed/upymod/modtrezorio/modtrezorio-pm.h, core/mocks/generated/trezorio/pm.pyi, core/mocks/generated/trezorui_api.pyi, core/mocks/trezortranslate_keys.pyi, core/src/apps/homescreen/device_menu.py, core/translations/en.json, core/translations/order.json, core/translations/signatures.json
Temporary power menu for Eckhart with the following actions:
- restart
- reboot to bootloader
- turn off (hibernate)
This should be reverted when we are able to implement the design in [Figma](https://www.figma.com/design/Dkl7W5PLqpr3TnXJ5hbnfd/--Future-Prod---Safe-7?node-id=11722-3609&t=eLZgwJFpPqTYQnfa-0).
=> Power device menu for Eckhart

core/src/trezor/ui/layouts/eckhart/__init__.py
It was added to T3W1, but not to other Core models - and unfortunately, it results in a timeout when using Suite Desktop.
=> chore(core): remove "Continue in the app" screen after label is set

core/src/apps/management/wipe_device.py, core/src/trezor/wire/context.py, tests/persistence_tests/test_shamir_persistence.py
[Slack](https://satoshilabs.slack.com/archives/C082Q0Y6WP3/p1756967548060319)
Also, don't fail when cancelling recovery via UI:
```
12.414 trezor.loop ERROR exception:
Traceback (most recent call last):
File "trezor/loop.py", line 162, in _step
File "apps/management/recovery_device/homescreen.py", line 33, in recovery_homescreen
File "apps/management/recovery_device/homescreen.py", line 65, in recovery_process
File "trezor/wire/context.py", line 154, in try_get_ctx_ids
File "trezor/wire/context.py", line 114, in get_context
NoWireContext: 
```
=> Erase BLE bonds when wiping the device

core/embed/io/ble/stm32/ble.c
device did not start accepting messages in case it was suspended without BLE connection. This caused busy errors in Suite
=> fix device not accepting BLE messages after wakeup

core/SConscript.firmware, core/SConscript.kernel, core/embed/io/usb/usb_config.c
This PR:
- Enables the debuglink interface in the hardware build when PYOPT=0, which was unintentionally disabled in #5619.
- Fixes an invalid buffer size used for VCP on STM32F4, which caused broken or missing functionality.
Fixes #5708
=> fix(core): enable debuglink when PYOPT=0

core/embed/rust/src/ui/api/firmware_micropython.rs, core/mocks/generated/trezorui_api.pyi, core/src/apps/debug/__init__.py, core/src/trezor/loop.py, core/src/trezor/ui/__init__.py
Added type annotation to `race`, `sleep`, and `spawn` functions in `loop.py`.
Type annotation for `wait` and `mailbox` would be nice too, but it is harder to do because the type cannot be (easily) inferred from the constructor. It either requires implementing "true" Generic, or passing the types to the constructor directly. There might be other solutions. However, I have not found anything nice-enough/user-friendly that would be without impact on PROD, yet.
EDIT:
Both `mailbox` and `wait` are annotated, too. However, `wait` annotation does not work properly yet as it would require additional changes mentioned here: https://github.com/trezor/trezor-firmware/pull/5713#issuecomment-3257947079
=> Add type annotation to `loop.py`

core/src/apps/common/passphrase.py, core/src/trezor/wire/thp/session_manager.py, tests/device_tests/test_session.py
Raise exception on receiving `ThpCreateNewSession` message with `passphrase` field not equal to `None` when Trezor has `passphrase_always_on_device` set to `True`.
=> Raise exception for invalid ThpCreateNewSession messages 

core/src/apps/management/recovery_device/homescreen.py, core/src/apps/management/recovery_device/layout.py, core/src/trezor/ui/layouts/eckhart/recovery.py, tests/click_tests/recovery.py, tests/click_tests/test_recovery.py, tests/device_tests/reset_recovery/test_recovery_slip39_basic.py, tests/input_flows.py, tests/input_flows_helpers.py
=> chore(core/eckhart): enable going back in the 1st recovery word

core/embed/projects/prodtest/README.md, core/embed/projects/prodtest/cmd/common.c, core/embed/projects/prodtest/cmd/prodtest_nrf.c, core/embed/projects/prodtest/cmd/prodtest_otp_variant.c, core/embed/projects/prodtest/cmd/prodtest_secrets.c, core/embed/projects/prodtest/cmd/prodtest_tropic.c, core/embed/projects/prodtest/cmd/prodtest_tropic.h
Changes:
- Return `OK NO` in `tropic-lock-check` if Tropic hasn't been paired.
- Fail `secrets-init` if Tropic locking has already started so that we don't overwrite MCU's pairing secrets.
- Changed global static variable `tropic_is_paired` to a local static variable. It seems confusing to me that it can and was being read, when we don't know whether it has been set correctly.
- Make sure that Tropic is paired before locking. Probably not necessary, since if the privileged key works, everything is probably OK, and if it is partially paired, e.g. factory slot was not erased, then access to it's functionality should be blocked by the config. But better safe than sorry.
=> Improve state handling around Tropic locking

core/embed/rust/src/ui/layout_eckhart/firmware/device_menu_screen.rs, core/embed/rust/src/ui/layout_eckhart/firmware/header.rs, core/embed/rust/src/ui/layout_eckhart/firmware/vertical_menu.rs, core/embed/rust/src/ui/layout_eckhart/firmware/vertical_menu_screen.rs
- Fix misplaced overflow arrow: [Figma](https://www.figma.com/design/MXUm0sDc1CjPNTIzzWwTAu/DQA?node-id=12054-2165&t=Nhz9Nwo2H57Y9ihg-0) 
- Header + VerticalMenu
- shift the menu up by approx. a top button padding: [Figma](https://www.figma.com/design/MXUm0sDc1CjPNTIzzWwTAu/DQA?node-id=12054-2164&t=tVjTW0eOF8oRPHQY-0)  
- Header + Subtitle + VerticalMenu: [Figma](https://www.figma.com/design/Dkl7W5PLqpr3TnXJ5hbnfd/--Future-Prod---Safe-7?node-id=9814-10156&t=joyZlW6Kzw9NENoC-0)
- Do not overlap the menu with the subtitle
- render the separator even before the first menu item
- Do not hide partially hidden device menu items. Limit their touch area instead.
=> Eckhart vertical menu DQA

core/embed/rust/src/ui/component/marquee.rs, core/embed/rust/src/ui/layout_caesar/component/title.rs, core/embed/rust/src/ui/layout_eckhart/component/button.rs
Optimization: when a marquee is not needed due to the text fitting we should not request animation frames!
=> Don't request marquee animation frames if text fits

legacy/firmware/ethereum.c
Similar to how it's done in core.
Following https://github.com/trezor/trezor-firmware/issues/4932#issuecomment-2820458343, we should use Gwei for "per gas" fee rates:
After this PR:
https://data.trezor.io/dev/firmware/ui_report/16425051463/T1B1-en-legacy_device_test-index.html
=> fix(legacy): always use Gwei for ETH fee rates

core/embed/rust/src/ui/api/firmware_micropython.rs, core/embed/rust/src/ui/layout_bolt/ui_firmware.rs, core/embed/rust/src/ui/layout_caesar/ui_firmware.rs, core/embed/rust/src/ui/layout_delizia/flow/confirm_set_new_code.rs, core/embed/rust/src/ui/layout_delizia/ui_firmware.rs, core/embed/rust/src/ui/layout_eckhart/flow/confirm_set_new_code.rs, core/embed/rust/src/ui/layout_eckhart/ui_firmware.rs, core/embed/rust/src/ui/ui_firmware.rs, core/mocks/generated/trezorui_api.pyi, core/src/apps/management/change_pin.py, core/src/apps/management/change_wipe_code.py, core/src/trezor/ui/layouts/bolt/__init__.py, core/src/trezor/ui/layouts/caesar/__init__.py, core/src/trezor/ui/layouts/delizia/__init__.py, core/src/trezor/ui/layouts/eckhart/__init__.py, tests/device_tests/test_msg_change_wipe_code_t2.py, tests/input_flows.py
Following #5782 some parameters became useless...
Also added a test that cancels the wipe code setup on all models to exercise the new code path.
=> Remove useless change_code params

core/embed/sec/tropic/stm32/tropic01.c
This pull request addresses an issue where trezor returns `LT_L1_SPI_ERROR` after waking up.
=> Fix tropic deinitialization

core/embed/rust/src/ui/layout_eckhart/component/button.rs
Continuation of https://github.com/trezor/trezor-firmware/pull/5810
=> chore(core/eckhart): use marquee only for the button subtext rendering

core/embed/rust/src/ui/layout_eckhart/firmware/action_bar.rs, core/embed/rust/src/ui/layout_eckhart/firmware/hold_to_confirm.rs, core/embed/rust/src/ui/layout_eckhart/firmware/mod.rs, core/embed/rust/src/ui/layout_eckhart/theme/mod.rs
This PR adds `Finalizing` phase to `HoldToConfirmAnim` for Eckhart UI. The controlling component `ActionBar` was adjusted accordingly. 
The Finalizing phase turns on the LED, shows the `ICON_DONE`, progressively dims the border and icon. `ActionBar` only waits for the result in this phase.
In the process, I slightly refactored the code, especially the animation state is now contained in one enum.
=> feat(core/eckhart): LED effect in HoldToConfirm

python/src/trezorlib/cli/__init__.py, python/src/trezorlib/cli/firmware.py
Tested locally:
```
$ TREZOR_MODEL=T3T1 QUIET_MODE=1 make -C core build_firmware upload
...
Please confirm action on your Trezor device.
Waiting for bootloader...
Failed to close <usb1.USBDeviceHandle object at 0x7254f9adbb10>: LIBUSB_ERROR_NO_DEVICE [-4]
Uploading  [####################################]  100%
make: Leaving directory '/home/rzeyde/src/trezor-firmware/core'
```
=> Fix disconnection while waiting for the bootloader

core/.changelog.d/5882.fixed, core/embed/rust/src/ui/component/text/layout.rs
- proper rendering of default leading ellipsis
- do not show incomplete chunks
- proper evaluation of the last chunk
- render trailing ellipsis within the text bound
=> Proper rendering of default ellipsis

core/src/boot.py
Found via the following traceback in emulator log:
```
0.419 trezor.loop ERROR exception:
Traceback (most recent call last):
File "trezor/loop.py", line 169, in _step
File "boot.py", line 117, in bootscreen
NameError: name 'workflow' isn't defined
```
=> fix(core): add missing `if utils.USE_POWER_MANAGER`

core/embed/io/usb/stm32/usb_class_vcp.c, core/embed/io/usb/stm32/usb_rbuf.c, core/embed/io/usb/stm32/usb_rbuf.h, core/embed/projects/prodtest/.changelog.d/5940.added, core/embed/projects/prodtest/.changelog.d/5940.fixed, core/embed/projects/prodtest/README.md, core/embed/projects/prodtest/cmd/prodtest_ping.c, core/embed/projects/prodtest/main.c, core/embed/sys/task/sysevent.c, core/site_scons/models/stm32f4_common.py, core/site_scons/models/stm32u5_common.py
This PR fixes several issues in USB VCP communication:
1) RX side fixes - completely refactored the USB VCP driver ring buffer
- when the buffer is full, incoming data from the host is suspended
- ring buffer synchronization between interrupt and main task
- the buffer is no longer a true ring buffer
2) TX side fixes
- `syshandle_write_blocking()` now uses the entire timeout to send data
- prodtest console writes to USB with a longer timeout
3) Improved the prodtest ping command to support an optional text parameter to return - so the ping command can be used for vcp stress test.
=> USB VCP fixes

core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs, core/embed/rust/src/ui/layout_eckhart/firmware/regulatory_screen.rs, tests/click_tests/device_menu/common.py
- temporarily remove the regulatory screen for Japan until the certification process is completed
[no changelog]
=> chore(core): remove Japan from regulatory screen

core/embed/sys/power_manager/stm32u5/power_manager.c, core/embed/sys/power_manager/stm32u5/power_manager_internal.h, core/embed/sys/power_manager/stm32u5/power_monitoring.c
Add compile time switch to quickly disable power manager thermal control. Which is needed for battery characterization in thermal chamber.
=> Add compile time switch to disable power manager thermal control
