trezor/trezor-firmware

- common/defs/bitcoin/fujicoin.json
The following changes will be made to the minimum remittance fee from now on as Fujicoin was attacked by Spam Tx.
Before change: 0.001 FJC / kB
After change: 0.1 FJC / kB
Currently, the pool equivalent to about 95% of the network hash rate has completed measures. These pools do not handle low fee remittances. Therefore, the low fee remittance takes about 20 blocks (20 minutes) on average.
Please change Fujicoin remittance fee.
Thanks.
> mod fujicoin tx fees

- core/embed/bootloader/bootui.c
- core/embed/extmod/modtrezorui/display.c
- core/embed/extmod/modtrezorui/display.h
- core/embed/extmod/modtrezorui/modtrezorui-display.h
- core/mocks/generated/trezorui.py
- core/src/apps/monero/layout/confirms.py
- core/src/apps/monero/signing/state.py
- core/src/apps/monero/signing/step_01_init_transaction.py
- core/src/apps/monero/signing/step_02_set_input.py
- core/src/apps/monero/signing/step_03_inputs_permutation.py
- core/src/apps/monero/signing/step_04_input_vini.py
- core/src/apps/monero/signing/step_05_all_inputs_set.py
- core/src/apps/monero/signing/step_06_set_output.py
- core/src/apps/monero/signing/step_07_all_outputs_set.py
- core/src/apps/monero/signing/step_09_sign_input.py
Based on the testing feedback I've made slight modifications to the UI.
Main points:
- running on the full brightness during the process (previously dimmed, felt broken). Progress steps are thus using `ui.layout_no_slide` to remove dimming. The performance should be better also. 
- overlaying layout fix after transaction confirmation. There was screen clear missing this "Signing..." was rendered over the confirmation. 
Slightly related to #83 although you may plan major UI overhaul and this is just a minor fix.
Update: I've added a sketch of overall progress counting.
Update: In the last two commits I've added support for the indeterminate loader as I could not find such feature.
> xmr.ui: improves UX of the monero app

- core/src/apps/wallet/sign_tx/addresses.py
- legacy/firmware/fsm_msg_coin.h
Non-existing BIP-48 is causing mess among implementations.
Tested in Electrum - all 3 multisig types work without warning now.
> core+legacy: make path checks more benevolent

- legacy/memory.c
Before erasing any sector, flash should be unlocked and it also should be locked after erasing.
> Unlock flash before erasing

- core/src/apps/common/cache.py
- core/src/apps/monero/__init__.py
- core/src/apps/monero/live_refresh.py
Improves UX as the live refresh prompts were too often.
Fixes #128.
The idea is to cache the passphrase fingerprint for which the user live-refresh authorized.
The state is stored in the main monero module.
@tsusanka @prusnak is there a better way to store the state or is my approach OK?
> xmr: authorize live refresh per passphrase

- core/src/apps/ethereum/layout.py
- core/tests/test_apps.ethereum.layout.py
Current behavior: 
Check the value of the ERC20 transfer in Wei - if the value is less than `10^9`, display the value on-screen as the wei value, with zero decimals.
Because of this, tokens with small decimal values will end up displaying the wei values even when the device could be displaying a very reasonable human-friendly number. 
Example when sending $25 USDC (ETH token with 6 decimals) with the model T:
This appears to be a non-issue on the Trezor One firmware
New behavior:
Measure the value of the transfer relative to the token's decimals. If the value we are going to display is less than `1e-9` (0.000000001) of that token's human-friendly format, then we display the value in Wei, setting `decimals = 0`. 
This means that tokens where `decimals == 18` should behave the same as they …
> Do not display token values in Wei for low-decimal value tokens

- legacy/firmware/ethereum.c
If the length of the message was exactly a power of `10` the initial `1` was omitted.
> Fix message composing in ethereum signature

- core/SConscript.firmware
Updated to latest secp256k1-zkp to allow building on Cortex-M4 devices (https://github.com/ElementsProject/secp256k1-zkp/pull/56).
> Use ARM assembly for field operations

- core/src/apps/wallet/sign_tx/scripts.py
Otherwise, it will extend the pre-allocated bytearray and the resulting script will be incorrect:
```
>>> x = bytearray(10)                                                                                                                                                                                                                                                       
>>> x[4:6] = b'111111111111111111111111111111111111111'                                                                                                                                                                                                                     
>>> x
bytearray(b'\x00\x00\x00\x00111111111111111111111111111111111111111\x00\x00\x00\x00')
```
> core: ensure pubkeyhash/scripthash have the correct length

- core/src/trezor/wire/__init__.py
Not sure it's the best way, but it helped me to debug a few out-of-memory errors :)
> core: return exception details in debug mode

- core/src/apps/wallet/sign_tx/scripts.py
> core: ensure correct pubkeyhash/witprog length in scripts.py

- core/emu.sh
Use #!/usr/bin/env instead of #!/bin/bash so it would be more general.
> Use #!/usr/bin/env instead of #!/bin/bash

- core/src/apps/wallet/sign_tx/segwit_bip143.py
IIUC, there is no need to convert them to `bytearray`.
> core: keep BIP143 hashes as bytes

- core/src/apps/wallet/sign_tx/__init__.py
It could be simplified due to similar handlers.
> core: unify exception handling at wallet.sign_tx

- legacy/README.md
- legacy/script/test
A search seems to indicate that this environment variable is not attached to anything.
> legacy: remove last mentions of TREZOR_TRANSPORT_V1

- core/src/apps/management/common/layout.py
- python/trezorlib/tests/device_tests/test_msg_resetdevice_shamir.py
- added device tests for reset device workflow using shamir backup
- comparing the resulting secret with shamir mnemonic reference implementation is commented out for now pending [#14 in python-shamir-mnemonic repo](https://github.com/trezor/python-shamir-mnemonic/issues/14)
> Shamir reset device tests

- core/src/apps/common/layout.py
We've disccussed with UX, it'd be desired to have a single page for Success and Warning, which will be used everywhere.
We came up with this:
Where the bold text is voluntary:
Also any redesign of those pages will then be quite easy.
> Add common page for success and warning

- common/defs/bitcoin/namecoin.json
Update Namecoin (NMC) minimal fee to 100,000 or 100 sat/B
> Update minimal fee for Namecoin

- Pipfile.lock
- python/requirements.txt
- python/setup.cfg
- python/setup.py
- python/trezorlib/tests/device_tests/test_msg_resetdevice_shamir.py
This PR adds comparing of generated secret with shamir reference implementation. 
the tests passed but didn't sync to github. [here](https://gitlab.corp.sldev.cz/trezor/trezor-firmware/pipelines/6410)
> re-enable shamir mnemonic tests

- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-bip32.h
- core/mocks/generated/trezorcrypto/bip32.pyi
- core/src/apps/cardano/seed.py
- core/src/apps/common/mnemonic.py
- core/tests/test_apps.cardano.address.py
- crypto/bip32.c
- crypto/bip32.h
- crypto/tests/test_check_cardano.h
This should fix https://github.com/trezor/trezor-firmware/issues/272
I created SLIP-0023 to solve this issue, see https://github.com/satoshilabs/slips/blob/andrewkozlik/slip-0023/slip-0023.md. In https://forum.cardano.org/t/cardano-with-slip-0039/25443 I asked people to make comments on the new specification in the pull request https://github.com/satoshilabs/slips/pull/712.
- I have not checked the code, so please review carefully.
- I have not tested this.
- I have not been able to create test vectors yet. If anybody knows about a tool like https://iancoleman.io/bip39/ for Cardano, where I can input a private key and chain code and derive an address, then please let me know.
- There is a bizzare merge conflict, that I am now too tired to resolve - mnemonic.get() now returns module …
> cardano: Implement SLIP-0023 and add SLIP-0039 support for Cardano.

- python/trezorlib/tests/device_tests/test_msg_recoverydevice_shamir.py
- python/trezorlib/tests/device_tests/test_msg_recoverydevice_shamir_dryrun.py
this PR implements #342 except the "reboot" tests
> added device tests for shamir dry run and warnings

- core/embed/unix/common.c
It seems to me 99% I'm getting this red screen on unix is because the emulator is already running. Just an idea..
> core/embed: add hint in fatal error on unix

- python/trezorlib/tests/device_tests/conftest.py
- python/trezorlib/tests/device_tests/test_msg_cardano_get_address_shamir.py
- python/trezorlib/tests/device_tests/test_msg_cardano_get_public_key.py
- python/trezorlib/tests/device_tests/test_msg_cardano_get_public_key_shamir.py
- python/trezorlib/tests/device_tests/test_msg_cardano_sign_tx_shamir.py
- python/trezorlib/tests/device_tests/test_shamir_passphrase.py
This PR implements #367 
the test vectors for sign_tx were generated using [this code](https://repl.it/@stanociny/JuicyShamefulAbstractions), you can uncomment various parts to verify the vectors we use. 
note: INVALID_VECTORS test in sign_tx worked without changes (or using a passphrase with slip39). Maybe it would be worth looking into whether we're testing what we think we're testing.
> Tests: cardano slip39 device tests

- common/protob/messages-debug.proto
- core/src/apps/debug/__init__.py
- core/src/apps/management/common/layout.py
- core/src/apps/nem/mosaic/layout.py
- core/src/trezor/loop.py
- core/src/trezor/messages/DebugLinkGetState.py
- core/src/trezor/ui/__init__.py
- core/src/trezor/wire/__init__.py
- core/src/trezor/workflow.py
- python/trezorlib/debuglink.py
- python/trezorlib/messages/DebugLinkGetState.py
- python/trezorlib/tests/device_tests/test_msg_eos_signtx.py
- python/trezorlib/tests/device_tests/test_msg_nem_signtx_mosaics_t2.py
- python/trezorlib/tests/device_tests/test_msg_recoverydevice_shamir.py
- python/trezorlib/tests/device_tests/test_msg_recoverydevice_shamir_dryrun.py
- python/trezorlib/tests/device_tests/test_msg_recoverydevice_t2.py
- python/trezorlib/tests/device_tests/test_msg_resetdevice_shamir.py
- python/trezorlib/tests/device_tests/test_msg_resetdevice_t2.py
- python/trezorlib/tests/device_tests/test_msg_tezos_sign_tx.py
This allows us to get rid of sleeps in tests for pagination and inputs. In Shamir recovery tests that's 20s per mnemonic, which taken together is A Lot(tm)
i left the shamir tests out of this PR in order not to conflict with #358 
@jpochyla plz review, i am VERY unsure about the `feedback_signal` class
> Send completion info from DebugLinkDecisions

- core/src/apps/wallet/sign_identity.py
See https://github.com/romanz/trezor-agent/pull/293 for the client-side tool (currently using `gpg://` protocol for [SLIP-0013](https://github.com/satoshilabs/slips/blob/master/slip-0013.md) identity derivation):
```bash
$ trezor-signify init JohnDoe
$ trezor-signify sign JohnDoe -m blob.txt
$ signify-openbsd -V -p JohnDoe.pub -m blob.txt
```
> apps/wallet: support Signify Ed25519 signatures

- core/src/apps/wallet/sign_tx/scripts.py
- core/tests/test_apps.wallet.address.py
`m` should be less than or equal to `n`.
> core: ensure multisig (m,n) parameters are valid

- core/src/apps/wallet/sign_tx/addresses.py
OTOH, would it be clearer if it would be marked as `List[bytes]`?
> core/wallet: fix 'pubkeys' type to be list

- core/src/apps/common/storage/__init__.py
I can't remember why I have written `and not recovery.is_in_progress()` but I don't think it is needed at this moment.
We call `device.is_version_stored()` in `is_initialized()` and we store the version in `store_mnemonic_secret()`, which is called only after the reset/recovery/load is done.
@ciny @jpochyla plrease review just to make sure
closes #387
> core: fix initialized to be unrelated to recovery

- core/src/trezor/log.py
I consider the ui.Result exceptions in log output as a bit confusing. This logs them in a nicer way without the traceback.
We might also consider adding something like ControlException, which ui.Result would extend, in case we have more such exceptions.
Also updates #373, which was closed already though.
> core: improve log output for ui.Result exception

- ci/build.yml
- ci/test.yml
- core/tests/run_tests_device_emu.sh
- legacy/script/test
- tests/upgrade_tests/download_emulators.sh
- tests/upgrade_tests/emulator_wrapper.py
- tests/upgrade_tests/emulators/.gitignore
- tests/upgrade_tests/test_firmware_upgrades.py
This introduces upgrade tests. The Emulator Wrapper and python script were written by @prusnak originally with some modifications of mine. The emulators are built on CI and stored on our [internal dev server](https://firmware.corp.sldev.cz/upgrade_tests/).
All versions that are found on the website are tested. I will also add a CI job, which will deploy new emulators to this website if a new tag occurs (meaning anytime we tag a new version, it will be deployed there automatically and therefore upgrade-tested). This closes #126.
----
We need to:
@matejcik do you think I could leave this one for you to finish? Might be more effective than doing the review ping-ping.
> ci: introduce upgrade tests (WIP)

- core/src/apps/cardano/seed.py
- core/src/apps/common/mnemonic.py
- core/src/apps/common/storage/recovery.py
- core/src/apps/common/storage/recovery_shares.py
- core/src/apps/management/backup_device.py
- core/src/apps/management/common/layout.py
- core/src/apps/management/recovery_device/homescreen.py
- core/src/apps/management/recovery_device/layout.py
- core/src/apps/management/recovery_device/recover.py
- core/src/apps/management/reset_device.py
- core/src/trezor/errors.py
- tests/device_tests/test_msg_recoverydevice_supershamir.py
- tests/device_tests/test_msg_recoverydevice_supershamir_dryrun.py
- tests/device_tests/test_msg_resetdevice_shamir.py
- tests/device_tests/test_msg_resetdevice_supershamir.py
- tests/device_tests/test_shamir_reset_recovery_groups.py
Pull request implementing #346 .
What remains to be done:
@tsusanka for starters could you have a look at storage? I'm mainly interested if set/get_slip39_shares_remaining in storage.recovery makes sense. 
~~I decided to use a new storage value so we don't break recovery people who are in the middle of it during fw upgrade. It's only used if group_count > 1 so single-level shamir shouldn't be affected.~~ - no longer applies.
> UI for multi level Shamir reset and recovery

- core/src/apps/common/seed.py
- core/tests/test_apps.common.seed.py
Following #66 and #317, it would allow [deriving confidential addresses](https://github.com/romanz/trezor-firmware/blob/a9ec7775b4fe01a0ab6814970f3ba1189dffa002/core/src/apps/wallet/get_address.py#L28) and
[unblinding confidential transactions' outputs](https://github.com/romanz/trezor-firmware/blob/a9ec7775b4fe01a0ab6814970f3ba1189dffa002/core/src/apps/liquid/unblind_output.py#L19) (according to [SLIP-0077](https://github.com/satoshilabs/slips/blob/master/slip-0077.md)).
> core/seed: Add SLIP-0077 derivation to Keychain

- common/defs/misc/misc.json
Adding [Yoroi](https://yoroi-wallet.com) as another wallet that supports integration with Trezor.
> common: adding Yoroi wallet for Cardano

- .gitlab-ci.yml
- ci/build.yml
- shell.nix
The following changes are a proof of concept of builds on darwin.
- The job is for now marked as ``allowed_failure`` as we are still seeing some slowness and glitches on the darwin builder, this will help us troubleshoot the issue
- We ask ``pkg-config`` to build it as a static library so Mac OS users don't have to install SDL2 and dependencies (I thought of making it as a default on darwin, but it's specific to our use case)
- We do check if pipenv is installed
> Adding darwin static build

- core/src/apps/common/storage/recovery.py
- core/src/apps/common/storage/recovery_shares.py
- core/src/apps/management/load_device.py
- core/src/apps/management/recovery_device/backup_types.py
- core/src/apps/management/recovery_device/homescreen.py
- core/src/apps/management/recovery_device/layout.py
- core/src/apps/management/recovery_device/recover.py
- core/src/trezor/errors.py
The only thing I'm not sure about is how the backup type will work when you do an upgrade from older version during a recovery.
I'll look into it.
> Refactor homescreen and backup types

- core/src/apps/common/confirm.py
- core/src/apps/management/recovery_device/homescreen.py
- core/src/apps/management/recovery_device/layout.py
- core/src/trezor/ui/confirm.py
- tests/common.py
This adds another Confirm dialog with an Info button and closes #512.
Although the Confirm dialogs bloat a little I think we might use the Info button somwhere else as well. Or we refactor this as soon as we have a new styleguide.
> core: add InfoConfirm

- common/defs/support.json
The wallet software is ready now. It's a Trezor-only wallet. It's currently deployed for another coin (FLO) at https://wallet.chaintek.net. It's my understanding that this PR is needed to get Ritocoin details pulled into Trezor Connect so the wallet can work for that coin as well.
> Add Connect support indicator for Ritocoin

- core/src/apps/common/storage/recovery.py
- core/src/apps/common/storage/recovery_shares.py
- core/src/apps/management/recovery_device/recover.py
- core/src/apps/management/reset_device/layout.py
This PR implement a few small fixes:
- wording change on share threshold page
- check for group_count None in storage.recovery.fetch_slip39_remaining_shares
- pass group_index to storage.recovery_shares and handle index calculations there
- remove duplicate words when checking shares during reset device
> core: various fixes to slip39

- core/src/apps/common/storage/recovery.py
- core/src/apps/common/storage/recovery_shares.py
- core/src/apps/management/backup_types.py
- core/src/apps/management/recovery_device/homescreen.py
- core/src/apps/management/recovery_device/layout.py
- core/src/apps/management/recovery_device/recover.py
This removes both recovery.backup_type and recovery.group_threshold because we can infer these data quite easily. The https://github.com/trezor/trezor-firmware/commit/6731d1bbf2df69046469291638a7b29235f8fa60 commit is a joint work with @matejcik.
I do not like the `_require_progress` function very much. It is indeed true that now every reading/writing takes twice as long. On the other hand it provides a nice check the code is in a correct state and the functions are not misused. Also, this code is used during the recovery only, therefore I believe a small inefficiency is acceptable.
Closes  #532
> Shamir Recovery: Remove unnecessary fields from storage

- core/src/apps/management/reset_device/layout.py
> core: fixed success screen during advanced slip39 reset flow

- core/src/apps/management/recovery_device/homescreen.py
If something does not have a test it does not work :(. We need to do #487 as soon as possible.
I don't like naming the variable just `m`, but I didn't want to shadow the module name. Should I come up with another name? Or keep `mnemonic` since we are not using the module in the function?
closes #562
> core/recovery: fix Info dialog

- common/defs/support.json
We have an integration with Magnum Wallet (https://magnumwallet.co) that supports Trezor Connect. I think we are otherwise ready for Trezor Connect since XRC support is currently supported on Trezor 1 and 2.
> Add Connect flag for Bitcoin Rhodium

- core/src/apps/cardano/seed.py
- core/src/apps/common/seed.py
- core/src/apps/management/backup_device.py
- core/src/apps/management/change_pin.py
- core/src/apps/management/recovery_device/__init__.py
- core/src/apps/management/reset_device/__init__.py
- core/src/apps/management/sd_protect.py
- legacy/firmware/fsm_msg_common.h
Fixes https://github.com/trezor/trezor-firmware/issues/599.
> core, legacy: Don't allow change_pin if device is not initialized.

- core/src/apps/management/recovery_device/recover.py
- core/tests/test_apps.management.recovery_device.py
Adds unit test for `process_slip39` function. Note that it still can happen that an unfitting mnemonic is stored in the storage and then later combined together with valid ones in `combine_mnemonics`. In such case, the MnemonicError is thrown and later caught in `_continue_recovery_process` and an error is shown. I believe that's an expected behaviour since this can happen very rarely, I doubt it can happen under "real-life" circumstances.
An example of this when the user enters a second mnemonic, which has the same identifier, but different member threshold. In this case the user needs to enter all mnemonics to get an error. However, entering different identifier leads to an early error (as soon as the second word is entered) and since that is way more common case I believe that's …
> Add unit test for process_slip39 function

- core/src/apps/management/recovery_device/homescreen.py
- core/src/apps/management/recovery_device/layout.py
Replace list with set, since that's what we want anyway. We need to change the identifier to tuple, so the object is hashable.
@ciny could you check this still behaves as expected?
Mypy will be fixed properly in the mypy branch.
> Small refactor in Info dialog

- core/src/apps/common/sd_salt.py
- core/src/apps/management/sd_protect.py
- Improve SD-protect error handling and messages. The correct errors are now always raised inside the `_wrong_card_dialog`, `_insert_card_dialog` and `_write_failed_dialog` functions. It was a bit messy before.
- Add SD_CARD_HOT_SWAPPABLE option to prepare for devices which allow swapping SD cards while running.
- If writing to SD card fails, allow user to retry or abort:
> SD-protect error handling

- core/src/apps/common/confirm.py
- core/src/apps/common/sd_salt.py
core/sd-protect: If writing to the SD card fails in request_sd_salt(), inform the user and allow them to retry or abort.
> SD protect: Allow user to retry/abort on write failure 

- common/protob/messages-management.proto
- core/src/apps/homescreen/__init__.py
- core/src/trezor/messages/Features.py
- python/src/trezorlib/device.py
- python/src/trezorlib/messages/Features.py
- tests/REGISTERED_MARKERS
- tests/conftest.py
- tests/device_tests/test_msg_sd_protect.py
I've added a boolean to DebugLinkState to indicate if a SD card is present or not. We may add it to Features at some point if desired.
I'll run the tests over night to see if some other stall or that's it.
Updates #591
> Skip sd protect test on device

- ci/test.yml
- core/Makefile
- core/tests/run_tests_click_emu.sh
- tests/README.md
- tests/persistence_tests/test_shamir_persistence.py
The only dubious thing is now that `persistence_tests` include `from ..upgrade_tests import core_only`, which is not very nice. Should we move `upgrade_tests/__init__` to `tests/__init__`?
> Reorder tests 2

- core/src/trezor/ui/loader.py
When there was no time difference between
```python
def start(self) -> None:
self.start_ms = utime.ticks_ms()
```
and
```python
now = utime.ticks_ms()
```
the loader wouldn't start loading.
> core/trezor/ui/loader: fixes #655 Button hold-to-confirm press detection.

- core/src/apps/common/mnemonic.py
- core/src/apps/homescreen/__init__.py
- core/src/apps/management/recovery_device/__init__.py
- core/src/apps/management/recovery_device/homescreen.py
- core/src/boot.py
- core/src/main.py
- core/src/trezor/workflow.py
- python/src/trezorlib/debuglink.py
This was a great idea! We set the recovery homescreen as a default workflow and return to that if some message is received. We do not unregister anything.
The work in workflow.py was based on a fair amount of guessing, so I would like to discuss that part mainly. I'm not sure why I can't call `close_default` (or `loop.close` respectively), in that case the emulator exits.
Closes #558.
> Remove persistence boot and set recovery as a default workflow

- python/src/trezorlib/eos.py
Fix for trezor/trezor-firmware/#680. ABI for (un)delegatebw seems to have changed slightly. Tested `delegatebw` action, generated by cleos, is signed correctly.
> Field "sender" is renamed to "from" in eosio ABI for un/delegatebw

- core/src/apps/webauthn/__init__.py
- core/src/usb.py
- core/tests/run_tests_device_emu_fido2.sh
- core/tests/run_tests_device_emu_u2f.sh
Let's have WebAuthn interface available for the Debug firmware.
Fixes https://github.com/trezor/trezor-firmware/issues/677
There is no configuration present, but arguably someone in need of having VCP interface for the debug firmware can edit `usb.py` easily. (Plus VCP is enabled for Bitcoin-only debug firmware).
> Rework USB interfaces for debug firmware

- core/ChangeLog
- core/src/apps/management/recovery_device/__init__.py
- legacy/firmware/fsm_msg_common.h
- python/src/trezorlib/device.py
- tests/device_tests/test_msg_recoverydevice_bip39_dryrun.py
On core, dry-run will allow four whitelisted fields: `dry_run` (obviously), `enforce_wordlist` (allowed but if sent, must be True), `word_count` and `type` (for T1 compatibility, so that it is possible to send an identical message to T1 and TT).
As an extra protection, any device settings are only done if `dry_run` is not true.
On legacy, fields other than those above are blacklisted. Also, dry-run is disallowed when the device is not initialized, to synchronize behavior with core.
An exhaustive test tries to set each field in dry-run and checks that the device reports failure.
> disallow most RecoveryDevice fields in dry-run (fixes #666)

- core/src/apps/webauthn/fido2.py
- core/src/trezor/ui/__init__.py
Note that this is branched off of andrewkozlik/733 (Fix continuous display blinking with Android #734), so preferably review that first.
This resolves https://github.com/trezor/trezor-firmware/issues/731 and introduces some improvements to the UX such as automatically closing the U2F confirmation screen if the browser stops polling for more than 3 seconds. This is especially relevant when there are two devices connected to the computer. When the user confirms the registration or login on one of them, the other used to be left hanging on the U2F screen until the user pressed something. Chrome normally polls every 200ms and Firefox appears to be polling at around the same rate, so a 3 second timeout should be more than enough. However, I didn't find any official minimum polling interval in …
> U2F UX improvements

- common/defs/fido/binance.json
- common/defs/fido/microsoft.json
- common/tools/coin_info.py
- common/tools/cointool.py
- core/src/apps/webauthn/fido2.py
- core/src/apps/webauthn/knownapps.py
- core/src/apps/webauthn/knownapps.py.mako
Based on user feedback and experimenting I found that Microsoft Azure AD doesn't allow registering security keys which use self attestation, so we need to use basic attestation for login.microsoft.com. The reason why we had chosen to use basic attestation is that previous experiments had shown that Binance won't allow us to use basic attestation. The solution is to add a use_self_attestation flag which will allow us to control this on a per-app basis similar to the use_sign_count flag.
> Add use_self_attestation flag to FIDO apps

- core/embed/unix/main.c
Emulator part of the #194
The logging and plotting of the peak-mem values should be considered in #468
> core/unix/main: Print memory info (peak memory) when TREZOR_LOG_MEMORY env var is set. Part of #194

- storage/storage.c
- storage/tests/python/src/storage.py
- storage/tests/tests/test_set_get.py
As brought up by @andrewkozlik, the storage lock state was based on the previous one. Probably because of some tests failing. However, it seems this is not the case anymore, tests are passing.
We have decided to always unlock the storage after wipe because the storage is empty anyway.
@andrewkozlik please review this thoroughly. I have also added a fix and test for non-existing key, because the python implementation acted differently.
> Unlock storage after wipe

- core/embed/unix/flash.c
Prevent test fail on macOS in `test_trezor.config.py`. Some opened file limit is triggered here or smthng.
```python
def test_lock(self):
for _ in range(128):
config.init() # flash_init is called here
```
> Don't reopen flash emulation file.

- python/src/trezorlib/cli/device.py
Accept a custom u2f-counter value when recovering a device.
> trezorctl: add u2f-counter to recover

- core/src/apps/management/recovery_device/layout.py
- core/src/apps/management/recovery_device/word_validity.py
- core/tests/test_apps.management.recovery_device.py
This started as #770 and got a bit out of hand :). But it makes sense to split the check_word_validity into more functions, since it was quite long, and also separate the evaluation logic and the display of the warnings.
The test is probably not exhaustive and might be expended later on.
> Recovery: refactor word checks and add a test

- python/default.nix
This PR allows building and testing python-trezor from master locally on NixOS.
Example usage:
`[example@example:~/trezor-firmware/python]$ nix-build .`
`$ /nix/store/<hash>/bin/trezorctl version`
> Allow building python-trezor from master on NixOS

- core/src/apps/webauthn/fido2.py
Fixes FIDO2 Register screen freezes with no error message #790.
> core/fido2: Check for HID timeout in send_cmd().

- common/protob/messages-monero.proto
- core/src/trezor/messages/MoneroTransactionFinalAck.py
- core/src/trezor/messages/MoneroTransactionInputViniRequest.py
- core/src/trezor/messages/MoneroTransactionSignInputRequest.py
- core/src/trezor/messages/MoneroTransactionSourceEntry.py
- python/src/trezorlib/messages/MoneroTransactionFinalAck.py
- python/src/trezorlib/messages/MoneroTransactionInputViniRequest.py
- python/src/trezorlib/messages/MoneroTransactionSignInputRequest.py
- python/src/trezorlib/messages/MoneroTransactionSourceEntry.py
This change allows further improvements:
* *Subaddresses*: Do not compute subaddr array as it can grow as large as |UTXO|. 
* Compute subaddr per UTXO as it now contains subaddr minor index (major is shared, sent in step 1). 
* Step 2 recomputes subaddr and checks the keys. This saves UTXO-related memory (quite a lot).
* If each UTXO is sent to a subaddr (preferred now), size savings are based on the UTXO size: `{4: 496B, 8: 994B, 16: 1856B, 32: 2712B, 64: 7360B, 128: 15008B}`
* *Decoy keys*: Sort UTXO ring on the host such that real key is always at 0 position. Randomize ring later in Trezor when doing MLSAG.
* step 2 and 4 do not need decoys, mixin independent. faster comm, faster HMAC. 
* decoys do not need to be HMACed, needed only in step 9, thus no need to commit to them. Increases …
> xmr: message changes optimizing runtime and memory

- core/src/apps/binance/layout.py
- core/src/apps/cardano/layout/__init__.py
- core/src/apps/ethereum/layout.py
- core/src/apps/lisk/layout.py
- core/src/apps/management/recovery_device/homescreen.py
- core/src/apps/management/recovery_device/layout.py
- core/src/apps/monero/layout/common.py
- core/src/apps/nem/layout.py
- core/src/apps/nem/transfer/layout.py
- core/src/apps/ripple/layout.py
- core/src/apps/stellar/layout.py
- core/src/apps/tezos/layout.py
- core/src/apps/wallet/sign_tx/layout.py
- core/src/apps/wallet/sign_tx/omni.py
- core/src/trezor/strings.py
- core/src/trezor/utils.py
- core/tests/test_trezor.strings.py
- core/tests/test_trezor.utils.py
I'm filing a PR to find out what you think before I reformat the rest.
- I'm not sure about the named parameters, should we use unnamed instead?
- Do we want to support irregularities? Or let's do it later when needed? @prusnak gave some hints from [django](https://github.com/django/django/blob/8f6860863e34cb1cbe24161f1c4e7c79007e93dc/django/template/defaultfilters.py#L851-L890).
- Fix support for 0 (it should use plural).
> Introduce format_plural

- core/emu.py
This looks like an overlook when the frozen argument was removed.
Also `-w` needs inotify, but we do not include that in Pipfile - shouldn't we? I believe pipenv should give you a complete environment even with some "debugging" tools.
> emu.py: remove frozen variable

- common/protob/messages-common.proto
- core/src/trezor/messages/PassphraseAck.py
- legacy/firmware/protob/messages-common.options
- python/src/trezorlib/client.py
- python/src/trezorlib/messages/PassphraseAck.py
- python/src/trezorlib/protobuf.py
- python/tests/test_protobuf_encoding.py
- python/tests/test_protobuf_misc.py
- tests/conftest.py
- tests/upgrade_tests/__init__.py
- tests/upgrade_tests/test_firmware_upgrades.py
- tests/upgrade_tests/test_passphrase_consistency.py
This removes the `state` field from PassphraseAck, which is not needed for backwards-compatibility after all. The removal fixes legacy CI failure in master.
Also adding an upgrade-test for the trezorlib "retain passphrased session" feature.
Unrelated, the fix for #832 is included, because as it turns out the same code caused problems when testing on old emulators.
> do not send state in PassphraseAck

- core/src/apps/lisk/layout.py
- core/src/apps/monero/layout/confirms.py
- core/src/apps/ripple/layout.py
- core/src/apps/tezos/get_public_key.py
- core/src/apps/tezos/layout.py
This changeset also includes fix where `await require_confirm` was called with superfluous `return`
> core/monero: add confirmation dialog for unlock_time

- core/embed/bootloader/bootui.c
- core/embed/extmod/modtrezorui/display.c
- core/embed/extmod/modtrezorui/display.h
- core/embed/extmod/modtrezorui/modtrezorui-display.h
- core/mocks/generated/trezorui.pyi
Fixes https://github.com/trezor/trezor-firmware/issues/36
> core/bootloader: split long vendor string

- core/src/apps/binance/sign_tx.py
- core/src/apps/common/address_type.py
- core/src/apps/debug/load_device.py
- core/src/apps/nem/sign_tx.py
- core/src/apps/ripple/sign_tx.py
- core/src/apps/wallet/get_ecdh_session_key.py
- core/src/apps/wallet/sign_tx/signing.py
- core/tests/test_apps.wallet.segwit.signtx.native_p2wpkh.py
Fixes #332.
At most places we have used wire.errors correctly so this was not that big of a deal. There still might be places where wire.error si more appropriate but I did not want to fix something that does not seem broken. So I have fixed the two bugs mentioned in #332, explored the rest and fixed it in places where it seemed reasonable.
> Use wire errors where applicable

- core/src/apps/management/reset_device/layout.py
Backups on 18-word seed phrases are currently broken on `master` as the code does not check for 18 word phrases when deciding what layout to render when viewing the mnemonic. 
To replicate the bug which this PR fixes:
- Start with wiped model T
- Create fresh wallet of 18 words
- Attempt to backup
- Firmware Error, [raised here](https://github.com/trezor/trezor-firmware/blob/2f905a115749ae7e3d4da8f7c65fd9632e0136db/core/src/apps/management/reset_device/layout.py#L145)
This PR fixes the bug by also checking for 18 word seed lengths. 
Tested using Emulator with 18 word seed.
> Fix BackupDevice layout on 18-word seed wallets

- core/embed/extmod/modtrezorconfig/modtrezorconfig.c
- core/mocks/generated/trezorconfig.pyi
- core/src/apps/common/request_pin.py
- core/src/boot.py
- storage/storage.c
- storage/storage.h
- tests/device_tests/test_sdcard.py
- tests/ui_tests/fixtures.json
Note that in `verify_user_pin()` I started using `config.unlock()` instead of `config.check_pin()`. The functions are actually identical, `check_pin()` just calls `unlock()` at the moment. If we start to differentiate the behavior one day, then we will need to have something like `verify_user_pin()` and `verify_user_pin_unlock()` for use in boot.py, but no point doing that now.
> Allow PIN entry without SD card

- python/AUTHORS
Seems that some commit history vanished during the MONOREPO merge last year.
Example: The old [docs/EXAMPLES.rst](https://github.com/trezor/trezor-firmware/blob/6dd261f4c040a32a5ff6d7472b7cdbfd4deb4eb5/docs/EXAMPLES.rst) was moved to [python/docs/EXAMPLES.rst](https://github.com/trezor/trezor-firmware/blob/master/python/docs/EXAMPLES.rst) and all history was lost.
Although I clearly have not done as much as most on this list, I would like to humbly request that my contributions ([commits](https://github.com/search?q=org%3Atrezor+author%3Ajonathancross&type=Commits), [issues](https://github.com/search?q=org%3Atrezor+type%3Aissue+author%3Ajonathancross&type=Issues)) be acknowledged with this PR adding my name to the list.
Thanks. :-)
> Adding @jonathancross to AUTHORS

- Pipfile
- Pipfile.lock
- ci/deploy.yml
- ci/hardware_tests/README.md
- ci/hardware_tests/bootstrap.py
- ci/hardware_tests/default.nix
- ci/hardware_tests/device/device.py
- ci/hardware_tests/device/t1.py
- ci/hardware_tests/hardware.cfg
- ci/hardware_tests/record_video.sh
- ci/test.yml
Based on the great work by @mmahut and his [tpmb](https://github.com/mmahut/tpmb) we have an actual T1 connected to our CI:
---------
This enables us to test the firmware on an actual device! This PR in particular adds a job to GitLab, which uploads the currently build debug firmware to the device and then runs the device tests on it. It uses the _tpmb_ to access the bootloader and confirm the firmware update, the rest is done using the debug link.
--------
This is a draft and although I do not think we should spend too much time fine-tuning it (now), there are a few things that should be considered before merging this:
- It uses `trezorctl` to update the firmware. I guess there is no reason not to use trezorlib directly, right?
- Wrap the `uhubctl` usage somehow?
- Should this be in …
> Run device tests on an actual T1 in CI

- core/SConscript.firmware
- core/SConscript.unix
- core/embed/extmod/modtrezorconfig/modtrezorconfig.c
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto.c
- core/embed/extmod/modtrezorio/modtrezorio.c
- core/embed/extmod/modtrezorui/modtrezorui.c
- core/embed/extmod/modtrezorutils/modtrezorutils.c
- core/embed/firmware/modutime.c
- core/embed/firmware/mpconfigport.h
- core/embed/unix/main.c
- core/embed/unix/mpconfigport.h
This should unify enabled features between the firmware and the emulator config.
Expected flow of upstream changes is as follows:
`micropython/ports/stm32/mpconfigport.h` -> `embed/firmware/mpconfigport.h` -> `embed/unix/mpconfigport.h`
and then
`micropython/ports/unix/mpconfigport.h` -> `embed/unix/mpconfigport.h`
the emulator mpconfigport should only accept upstream changes that relate to _building_, not to enabled uPy features
---
changes to **`firmware/mpconfigport.h`** are minimal:
- disable readline support unconditionally
- disable threading unconditionally
- disable "reverse special methods" `__radd__` and `__rmul__` (enabled by default  but we don't need them; seems in line with disabling all other special methods)
- remove `MICROPY_PY_VFS_FAT` because it's covered by …
> unify mpconfigport.h

- core/Makefile
- core/SConscript.firmware
- core/SConscript.unix
- core/embed/firmware/main.c
- core/embed/trezorhal/rdi.c
- core/embed/trezorhal/rdi.h
- core/embed/trezorhal/systick.c
- core/embed/trezorhal/usb.c
- crypto/Makefile
- crypto/chacha_drbg.c
- crypto/chacha_drbg.h
- crypto/tests/test_check.c
Solves https://github.com/trezor/trezor-firmware/issues/654.
I implemented:
1.  Very fast chacha based DRBG. It needs about 40 cpu ticks per one generated byte, which is about 10 times faster than hmac_drbg.
2.  Countermeasure against side channels attacks on Trezor T called random delay interrupts. It consist of an interrupt handler that is called every millisecond and that waits for a random number of cpu ticks. The random number is a sample of so called floating mean distribution.
RDI can be turned on and off by an environment variable during build process. By default it is turned on for `build_firmware` target.
@prusnak Please review `SConscript.firmware`, `Makefile`, `main.c` and `systick.c`.
@andrewkozlik Please review the rest.
> Random delay interrupts and chacha based DRBG

- core/Makefile
- core/embed/firmware/firmware_flash_t1.jlink
- core/embed/firmware/startup.s
Added a few flashing commands for openocd and jlink as well.
> T1 core port able to run on T1 bootloader if it has MEMORY_PROTECT=0 or FW is signed

- legacy/firmware/stellar.c
Solves the second part of https://github.com/trezor/trezor-firmware/issues/921.
It makes price format in stellar on trezor one same as it is on trezor T (that is `"%f" % (op.price_n / op.price_d)`).
| price | trezor one old       | trezor one new | trezor T  |
|-------|----------------------|----------------|-----------|
| 13/1  | 13                   | 13.000000      | 13.000000 |
| 1/13  | 0.076923076923076923 | 0.076923       | 0.076923  |
> legacy/stellar: change price format

- core/src/apps/bitcoin/get_public_key.py
- tests/device_tests/test_msg_getpublickey.py
- tests/device_tests/test_msg_getpublickey_curve.py
fixes #1011 by removing all restrictions on path for `GetPublicKey`, thus reverting to pre-#959 levels
this seems necessary due to the sheer amount of different uses of GetPublicKey:
- in trezor-agent, SLIP-13 and SLIP-17 paths are used
- in hwi, m/0' (and m/0 due to a bug) are used to retrieve master fingerprint
- in electrum, m/ELE'/something is used to derive a password for wallet file encryption
- in mytrezor wallet, m/44/1/0 path is used to check, uh, something
- in Exodus, `GetPublicKey` is used with valid paths, but without specifying `coin_name` and also for currencies other than Bitcoin-likes.
we can still decide to implement a whitelist based on the above, but it is unclear if that is worth it.
> core: relax path checks on GetPublicKey

- legacy/firmware/recovery.c
Before:
After:
I was unable to come up with any better wording.
---
Closes #972.
---
I am also wondering we might backport this to 2020/06 (1.9.1) because it will take a long time to publish another T1 FW (I guess).
> legacy: add ToS dialog to recovery

- legacy/firmware/config.c
- legacy/firmware/config.h
- legacy/firmware/fsm_msg_common.h
- storage/storage.c
- storage/storage.h
Older firmware supported direct mnemonic load or xprv import. This support was removed from the latest firmware. If someone used this feature and upgraded to the latest fw node deriving does not work anymore and we also incorrectly state that the device as initialized (`features.initialized`).
This PR modifies this field to `isInitialized() && hasMnemonic()` as @prusnak suggested to declare the device as initialized only if it has a mnemonic stored. Because of that I have added `storage_has` (maybe `storage_key_exists` is better?) to only check if mnemonic is present instead of fetching it.
I also had to modify the wipedevice test, which now fails on TT, but that will be fixed by the changes in #958. So I suggest to merge this after the soft lock.
Closes …
> legacy: initialized field in Features is true only if mnemonic is stored

- core/src/apps/management/apply_flags.py
- core/src/apps/management/apply_settings.py
- core/src/apps/management/get_next_u2f_counter.py
- core/src/apps/management/set_u2f_counter.py
- core/src/apps/webauthn/add_resident_credential.py
- core/src/apps/webauthn/remove_resident_credential.py
- tests/upgrade_tests/test_firmware_upgrades.py
I have added the check everywhere (hopefully) where something was being stored in the storage. it is something to be discussed however. The check does not have to be in places where the seed is touched obviously.
I am still wondering if we should wipe the device before reset/recovery to make sure it is in the expected state. What do you think?
Closes #1056.
> core: forbid all settings if not initialized

- crypto/bignum.c
- crypto/ecdsa.c
This PR:
1. Makes the function `ecdsa_recover_pub_from_sig` as fast as `ecdsa_verify_digest` (330 ms vs 190 ms).
2. Removes a guarantee for `bn_cnegate` that obviously doesn't hold for `x = 0`. I checked that no caller relies on the guarantee.
> Make `ecdsa_recover_pub_from_sig` faster

- common/protob/messages-management.proto
- core/src/apps/base.py
- core/src/trezor/messages/Features.py
- legacy/firmware/fsm_msg_common.h
- python/src/trezorlib/messages/Features.py
- tests/device_tests/test_msg_changepin_t2.py
- tests/device_tests/test_protection_levels.py
On a quick test on https://suite.corp.sldev.cz/suite-web/feat/232-pinentry/wallet/ (develop does not work due to the new PinEntry btn request) this seems to work just fine. But we still need to check with Suite if this is alright.
Updates  #1066.
> Rename Features.pin_cached to unlocked and unify

- common/protob/messages-bitcoin.proto
- common/protob/messages-ethereum.proto
- common/protob/pb2py
- core/ChangeLog
- core/src/trezor/messages/EthereumAddress.py
- core/src/trezor/messages/PassphraseAck.py
- core/src/trezor/messages/PassphraseRequest.py
- legacy/firmware/protob/messages-ethereum.options
- python/src/trezorlib/messages/EthereumAddress.py
- python/src/trezorlib/messages/SignTx.py
- python/src/trezorlib/messages/TransactionType.py
- tools/build_protobuf
We have to keep the overwintered flag for Suite otherwise Connect needs to have another copy of protobuf messages for older firmwares. We have decided with @matejcik we will solve this using the `deprecated` flag and at the same time we will not generate these fields for Core to make it a bit clearer.
> Skip protobuf deprecated fields for Core and deprecate Overwintered

- crypto/CONTRIBUTORS
- crypto/Makefile
- crypto/fuzzer/README.md
- crypto/fuzzer/fuzzer.c
- crypto/memzero.c
This PR adds a self-contained fuzzer harness collection for individual trezor-crypto functions. It is meant to be extended in the next months with additional fuzzer harnesses.
So far, this approach does not require any changes to the library functions (_with the limited exception of `memzero()`_) and should not have any negative effects on the regular code. It was necessary to modify the Makefile, but as discussed internally, this should also not have an impact on T1/T2 usage of the crypto code.
Most of this code has been reviewed and accepted as part of https://github.com/satoshilabs/trezor-firmware/pull/84 .
> crypto: add fuzz testing harnesses and documentation

- core/src/apps/management/recovery_device/keyboard_bip39.py
- core/src/apps/management/recovery_device/keyboard_slip39.py
- core/src/trezor/loop.py
- core/src/trezor/ui/passphrase.py
- docs/SUMMARY.md
- docs/tests/click-tests.md
- python/CHANGELOG.md
- python/src/trezorlib/cli/settings.py
- tests/click_tests/record_layout.py
- tests/click_tests/test_autolock.py
- tests/conftest.py
- tests/device_handler.py
fixes #1099 by making sure the device does not auto-lock while entering a word.
also adds a warning to trezorctl that you don't have PIN and you're trying to set up autolock. should help testers out
---
Also adds a little tool that can record and generate a click-test case from a trezorctl sequence.
It's a horrible thrown-together hack, and at this moment I'm not interested in improving the code of this tool even a little.
If you feel that a tool in this state should not be commited into our repository, I'll remove it from the PR and publish separately as a gist. If someone wants to dive in, add comments and improve it, feel free.
> Ping idle timer while in recovery mode

- core/embed/firmware/firmware_flash_t1.jlink
- core/embed/firmware/main.c
- replace bootloader in core firmware's `main` only when `PRODUCTION` is set.
- proper device description for T1 core port when flashing via JLink
> Debugging helpers

- core/src/apps/management/apply_settings.py
- core/src/trezor/strings.py
- core/tests/test_trezor.strings.py
- legacy/firmware/config.c
- legacy/firmware/config.h
- legacy/firmware/fsm_msg_common.h
- legacy/firmware/layout2.c
- legacy/firmware/layout2.h
- tests/device_tests/test_autolock.py
- tests/ui_tests/fixtures.json
Fixes #1093. The confirmation screen was changed to show the value in more human-readable units.
> Autolock delay setting: raise error when out of range

- core/src/apps/bitcoin/sign_tx/bitcoin.py
- core/src/apps/bitcoin/sign_tx/bitcoinlike.py
- core/src/apps/bitcoin/sign_tx/decred.py
- core/src/apps/bitcoin/sign_tx/helpers.py
Fixes (partially) #1108.
TT runtime for `test_msg_signtx.py::TestMsgSigntx::test_lots_of_inputs` :
* master (48e1dc9): ~23m30s
* this branch: ~17m30s
* this branch + [another gc.collect removed](https://github.com/trezor/trezor-firmware/blob/48e1dc957f00d95585fefb3e8b362abef75977f4/core/src/apps/bitcoin/sign_tx/bitcoin.py#L441): ~17m30s
* removing unimports in [\_\_init.py__](https://github.com/trezor/trezor-firmware/blob/48e1dc957f00d95585fefb3e8b362abef75977f4/core/src/apps/bitcoin/sign_tx/__init__.py) also doesn't seem to make any difference in speed
Not really sure how to benchmark this better or how to verify that the changes don't break anything - tests on hardware are pretty slow. Suggestions appreciated.
> core: reduce gc.collect calls during bitcon sign_tx

- core/src/apps/bitcoin/sign_tx/__init__.py
- core/src/apps/bitcoin/sign_tx/layout.py
Fixes #1132. Seems to speed up `TestMsgSigntx::test_lots_of_inputs` on device further ~25 % compared to #1128.
Tested with `tests/device_tests/test_msg_signtx{,_external,_mixed_inputs,_prevhash,_segwit,_segwit_native}.py` though I haven't been able to set up the white noise homescreen.
> core: remove unimports from bitcoin sign_tx layouts

- core/embed/extmod/modtrezorui/display-unix.h
Makes the emulator look nicer in tiling window managers. Not tested on a non-tiling WM.
> core: don't scale emulator background image

- core/tests/unittest.py
this adds the ability to run all tests in the test class, even if some of them failed
additionally, it detects when a function call returns a coroutine (can't do that on the function object itself AFAICT, as the type of it is "bound method" regardless of whether it's a generator or not) and raises an error. Error is also raised when a test method returns anything (other than `None`), because test methods should not do that and it probably indicates some sort of problem.
> core/tests: improve test harness (fixes #1157)

- core/src/apps/cardano/get_public_key.py
In Shelley, Cardano started using the purpose 1852'. Unfortunately, we completely missed that the public key path validation function checks for purpose 44' explicitly, which means that the user is shown a warning when deriving public key with the purpose 1852'. Which is always when "logging in" to a wallet. This commit should fix that.
I've also updated type hinting in get_public_key.
What is the status of this months' release? Can this still be added as a bug fix?
I'll check if the UI tests need to be regenerated a bit later.
> Fix Cardano Shelley Public Key Validation

- tests/device_tests/test_msg_webauthn.py
- tests/ui_tests/fixtures.json
by not asking for a full-capacity list of credentials, which will
usually not fit in an unfragmented chunk of memory
i also moved the test function to top-level so make sure to [hide whitespace changes](https://github.blog/2018-05-01-ignore-white-space-in-code-review/)
> tests: fix test_msg_webauthn on-device

- python/CHANGELOG.md
- python/src/trezorlib/__init__.py
- python/src/trezorlib/cli/btc.py
Fixes a bug introduced in 95f33a77c737e0f1c20cf20c1fd3aebb99f48eb0:
```
File "/home/andrew/firmware/python/src/trezorlib/cli/btc.py", line 143, in get_address
multisig=multisig,
UnboundLocalError: local variable 'multisig' referenced before assignment
```
> python: Fix UnboundLocalError in trezorctl btc get-address.

- ci/posttest.yml
- core/Makefile
- core/tools/coverage-report
Fixes #1051. 
Opening as draft until micropython/micropython#6335 is merged.
The PR also adds configurable coverage threshold which makes the CI fail if the coverage drops below. There is however a problem with the current implementation because when such failure happens, no artifact is generated and the developer won't be able to access the report. Not sure if GitLab CI allows jobs to produce artifacts even when they fail, or whether we need a separate job for this check.
> Fix test coverage reports

- core/src/trezor/ui/qr.py
Looks like I found another issue like https://github.com/trezor/trezor-firmware/commit/cea634158a92e69587471477748b1c9eba435c5f, but not as serious as #1095. I was able to produce it only once and it won't end in a RSOD.
This fix is OK, but in my opinion we really should be calling `super().__init__()` whenever we define an initializer in a derived class and then the proper way to do this would be to initialize `repaint` in the initializer of `Component`, because that's the topmost class that uses it, even though it doesn't read it: https://github.com/trezor/trezor-firmware/blob/5536fbb98a8214279d6d45052d1c30109f5f79a7/core/src/trezor/ui/__init__.py#L242-L252
> core/ui: Initialize Qr class properly.

- common/defs/bitcoin/stakenet.json
- core/src/apps/common/coininfo.py
Stakenet is working on a hardfork to support extra_data like Dash does, hence, we are enabling it.
> Enable extra_data for Stakenet

- legacy/firmware/crypto.c
It seems that some people use single-sig paths (e.g. m/49') for participating in multisig schemes. While this is not a good idea in general, I don't think we should disallow this completely as this can lock user's funds with no obvious way how to spend them.
See https://github.com/trezor/trezor-firmware/issues/1214 for such example
I propose to backport this fix to September release
> legacy/firmware: validate script type only in full-mode known_path_check

- common/protob/messages-bitcoin.proto
- common/protob/messages.proto
I chose to `import messages.proto` instead of putting the option into `messages-common.proto` because of namespacing; we'd have to call `option (common.unstable) = true;` then.
The other option is removing namespaces completely, because we don't need them. But maybe some third parties do, and maybe Connect does? (@szymonlesisz?)
> common: add "unstable" as a custom protobuf extension (fixes #1220)

- python/src/trezorlib/cli/binance.py
- python/src/trezorlib/cli/cardano.py
- python/src/trezorlib/cli/eos.py
- python/src/trezorlib/cli/lisk.py
- python/src/trezorlib/cli/nem.py
- python/src/trezorlib/cli/ripple.py
- python/src/trezorlib/cli/settings.py
- python/src/trezorlib/cli/tezos.py
It seems that Click doesn't do the right thing when argument and hidden option with the same name exist, which was introduced in commit 2678e64a9923e56345054daf6eb87ba17b9d3169.
```
$ trezorctl set homescreen /some/image.png 
Usage: trezorctl set homescreen [OPTIONS] [FILENAME]
Try 'trezorctl set homescreen --help' for help.
Error: Invalid value for '-f' / '--filename': /some/image.png is not a valid boolean
```
Not familiar with Click so this might not be the best fix. Renaming the argument also works.
> python: fix cli --file handling

- python/src/trezorlib/cli/firmware.py
Or maybe we want to fix this instead of dropping the option?
It doesn't seem to do anything and it's been like this for at least a year.
> python/trezorctl: remove --skip-vendor-header from firmware-update

- core/src/apps/monero/signing/__init__.py
- core/src/apps/monero/signing/state.py
- core/src/apps/monero/signing/step_01_init_transaction.py
- core/src/apps/monero/signing/step_07_all_outputs_set.py
- core/src/apps/monero/signing/step_09_sign_input.py
- Changes required to make CLSAG working.
- Transaction type was not set accordingly
- Related to the https://github.com/monero-project/monero/pull/6798
- New binary tests testing both HF=12 and HF=13: https://github.com/ph4r05/monero/releases/tag/v16.0.0.0-tests-u18.04-01
> xmr: fix new transaction type for CLSAG, HF=13

- common/protob/messages-bitcoin.proto
- core/src/apps/bitcoin/ownership.py
- core/src/apps/bitcoin/sign_tx/bitcoin.py
- core/src/apps/bitcoin/sign_tx/helpers.py
- core/src/trezor/messages/TxInputType.py
- legacy/firmware/protob/messages-bitcoin.options
- python/src/trezorlib/messages/TxInputType.py
- tests/device_tests/test_msg_authorize_coinjoin.py
When proving non-ownership of an input we need to allow the host to specify the commitment data that was used to create the ownership proof. This PR adds the new field to `TxInputType` and uses it in `authorize_coinjoin` tests.
> Allow host to specify commitment data in TxInputType

- python/tools/build_tx.py
The "Input amount" was being parsed and displayed incorrectly sometimes while the user was entering the previous outputs to spend.
Also, amount values in the generated bin_outputs of the prev_txes were incorrect sometimes.
Only some amounts were wrong, and each time that I witnessed this, the values were off by one in the least significant digit.
This fix of parsing the amounts with the Decimal class fixed all the problems that I encountered.
> [python] build_tx tool: fix amount inaccuracy by parsing with Decimal

- python/tools/firmware-fingerprint.py
Fixes #1256. 
For core the fingerprints now match https://wallet.trezor.io/data/firmware/2/releases.json:
```
$ ./build-docker.sh core/v2.3.3
...
$ python/tools/firmware-fingerprint.py build/core/firmware/firmware.bin
46326222f8afcb82e1cd07867bc3bf8836f4e9d0f367e23b58d1e9bc32cd032e
$ python/tools/firmware-fingerprint.py build/core-bitcoinonly/firmware/firmware.bin
dda77cd7893a5f413f8fc4b2f44d1d43ed4b26e8ced5e6e578cc6b302c1a2310
```
For legacy the fingerprints still do not match as documented on https://wiki.trezor.io/Developers_guide:Deterministic_firmware_build
> build-docker.sh: fix fingerprint calculation for model T production builds

- COMMITS.md
- README.md
Sending this PR to start a discussion whether we want to do this.
I am thinking about making the "scope" mandatory (we have a monorepo so having a scope is important), so the structure would go like this:
```
<type>(<scope>): <description>
[optional body]
[optional footer(s)]
```
Should we make a list of allowed scopes?
Similar PR sent to trezor-suite by Martin: https://github.com/trezor/trezor-suite/pull/2007
> docs: introduce conventional-commits

- common/tests/fixtures/cardano/get_address_byron.json
- common/tests/fixtures/cardano/get_address_byron.slip39.json
- common/tests/fixtures/cardano/get_base_address.json
- common/tests/fixtures/cardano/get_base_address_with_staking_key_hash.json
- common/tests/fixtures/cardano/get_enterprise_address.json
- common/tests/fixtures/cardano/get_pointer_address.json
- common/tests/fixtures/cardano/get_reward_address.json
- core/src/apps/cardano/get_address.py
- core/src/apps/cardano/layout.py
- core/src/apps/cardano/sign_tx.py
Problem: Trezor's call to verify the address on-screen cuts the path for basically any kind of address, given that the new derivation paths introduced by shelley became longer with the `m/1852'/1815'/` common prefix. Example below:
```trezorctl cardano get-address -n "m/1852'/1815'/15'/0/100" -s "m/1852'/1815'/0'/2/0" -t enterprise -d``` results in
So the `m/1852'/1815'/15'/0/100` gets cut to just `m/1852'/1815'/15'/0` which provides an incomplete information to the user wanting to verify the given address (same problem for double digit address indices for single digit account numbers which is the most common case indeed)
Sugested fix: swap the address type information (fittable on a single line) with the derivation path, like this
Other examples:
long path:
legacy (byron) address …
> Cardano get address - swap path with address type to fit longer paths

- ci/test.yml
- tests/conftest.py
- tests/ui_tests/.gitignore
- tests/ui_tests/__init__.py
Closes #1263. The UI test job now prints: 
```
-------- Suggested fixtures.json diff: --------
{
"cardano-test_sign_tx.py::test_cardano_sign_tx[parameters0-result0]": "6aa71de5007b0faf1eea4b1cfda1da6a739f852c0d875a1e59d83c03178c2f98",
"cardano-test_sign_tx.py::test_cardano_sign_tx[parameters1-result1]": "7abf2e87a9b1e50afdf3502ba9480b07a59d59ccccf24915b46fb81285ae3fa8",
...
```
which you can simply copy and paste into `fixtures.json`. It does not make a git patch but simply prints the expected JSON as a whole. I can do git patch but it seemed as not necessary (although the log would be shorter).
> Print expected fixtures in UI tests

- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-bip32.h
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-bip39.h
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-blake256.h
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-blake2b.h
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-blake2s.h
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-chacha20poly1305.h
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-curve25519.h
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-ed25519.h
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-groestl.h
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-monero.h
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-nist256p1.h
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-pbkdf2.h
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-ripemd160.h
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-secp256k1.h
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-secp256k1_zkp.h
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-sha1.h
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-sha256.h
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-sha3-256.h
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-sha3-512.h
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-sha512.h
- crypto/bip32.h
- crypto/tests/test_check.c
- legacy/firmware/fsm.c
I replaced most of the `mp_obj_new_bytes()` calls in modtrezorcrypto with `mp_obj_new_str_from_vstr()`, because often this usage has led to sensitive data being left on the call stack. The other option would have been to clean up using `memzero()`, but this way the data isn't even placed on the stack, so there is nothing to clean up, i.e. no chance of forgetting to clean it up. There are a number of places where the data in question is not sensitive like addresses or public keys, so the changes there are not necessary. Nevertheless, I made them anyway, because based on earlier discussion we want the returning of buffers to be handled consistently throughout modtrezorcrypto. It also reduces the likelihood of repeating this mistake in future code.
> Keep call stack clean in modtrezorcrypto

- ci/Dockerfile
- ci/shell.nix
- ci/test.yml
- core/tests/run_tests_device_emu_monero.sh
Handling of full dependencies (multiple python versions, Monero tests) is moved from `Dockerfile` to `shell.nix`.
The Python packages are installed from the pinned nixpkgs revision and do not depend on nix-channel state at the time of docker build anymore.
The Monero test binary is now downloaded using fetchurl which fails the build if the file hash doesn't match.
Note: the file hash currently **doesn't match**: https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/785178967#L843
Note: we install python 3.9 for python tests but it's not in [tox.envlist](https://github.com/trezor/trezor-firmware/blob/master/python/tox.ini), should it be there?
> ci: handle full dependencies in shell.nix

- python/CHANGELOG.md
- python/docs/transaction-format.md
- python/setup.py
- python/src/trezorlib/btc.py
- python/src/trezorlib/cli/btc.py
- python/src/trezorlib/debuglink.py
- python/src/trezorlib/protobuf.py
- python/tests/test_protobuf_encoding.py
- python/tests/test_protobuf_misc.py
- python/tools/build_tx.py
- python/tox.ini
- tests/bip32.py
This PR implements a bunch of tricks to make sure that code built on trezorlib 0.12 continues to work on trezorlib 0.13, namely:
* old-style `btc.sign_tx` with `details` argument continues to be accepted
* constructing protobuf classes with positional arguments, or with no arguments, is still possible. (sending a protobuf message without filling out required fields will fail, of course)
both are guarded by deprecation warnings and might be removed in trezorlib 0.14.
> trezorlib 0.13 backwards compatibility

- ci/test.yml
- core/Makefile
- core/SConscript.unix
- core/emu.py
- core/prof/prof.py
- core/tools/alloc.py
Based on @matejcik 's `alloc-counter` branch. [Example report](https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/812968996/artifacts/core/prof/memperf-html/index.html) (yeah the html output could use some improvement).
Since it needs to rerun all tests with different micropython build (that is slower than normal) the job is a manual job so as not to waste CI and developer time.
Needs corresponding micropython changes that are by default disabled at compile time:  trezor/micropython#3.
What do you think? Is this useful?
> Add CI job for generating memory usage report

- common/defs/README.md
There is no coins/ subdirectory anymore so it makes no sense to describe it.
> clean README from mention of deprecated folder

- core/embed/bootloader/messages.c
- core/embed/bootloader_ci/messages.c
- legacy/bootloader/usb.c
- legacy/bootloader/usb_send.h
Fixes https://github.com/trezor/trezor-firmware/issues/1334 by unifying the codes used in legacy and core bootloaders
I have not added text messages to legacy bootloader messages, I think it's not worth the effort.
Also legacy bootloader now sends Failure_UnexpectedMessage instead of being silent when an unexpected message is encountered (the same behaviour we see core bootloader).
> legacy+core: unify error codes in bootloaders

- core/src/apps/bitcoin/sign_tx/approvers.py
- core/src/apps/bitcoin/sign_tx/tx_info.py
- tests/device_tests/test_msg_signtx_replacement.py
- tests/txcache/testnet/43d273d3caf41759ad843474f960fbf80ff2ec961135d018b61e9fab3ad1fc06.json
- tests/txcache/testnet/70f9871eb03a38405cfd7a01e0e1448678132d815e2c9f552ad83ae23969509e.json
- tests/ui_tests/fixtures.json
Implements https://github.com/trezor/trezor-firmware/issues/1343
Spec: https://github.com/bitcoin/bips/blob/master/bip-0125.mediawiki
UI: https://satoshilabs.gitlab.io/-/trezor/trezor-firmware/-/jobs/861475851/artifacts/master_diff/added/test_msg_signtx_replacement.py::test_p2wpkh_finalize.html
> Inform user about transaction finalization

- core/src/storage/device.py
- legacy/firmware/config.c
- legacy/firmware/config.h
Fixes #1351. Core + legacy.
Upgrade: if storage has <1minute the effective value is 1 minute. Less than one minute cannot be set.
Downgrade: the new set of valid timeouts is subset of the old one so downgrade should always be safe.
We've discussed lowering the minimum if `experimental_features` is set but I haven't implemented this (yet). Is it something that would make life easier for @trezor/qa?
> Increase minimum auto-lock delay to 1 minute

- python/src/trezorlib/debuglink.py
- tests/device_tests/test_debuglink.py
Reseeding does not make sense on actual hardware so skip the test.
Please let me know if there's a better way to detect we're testing an emulator.
Also not sure whether skip/xfail makes a difference here.
> fix(tests): run test_softlock_instability on emulator only

- crypto/ecdsa.c
- crypto/tests/test_check.c
Based on a bug report from Guido Vranken:
> Here's a new discrepancy I found.
> 
> operation name: ECDSA_Verify
> ecc curve: secp256k1
> public key X: 55066263022277343669578718895168534326250603453777594175500187360389116729240
> public key Y: 32670510020758816978083085130507043184471273380659243275938904335757337482424
> in: {0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xfe,
>  0xba, 0xae, 0xdc, 0xe6, 0xaf, 0x48, 0xa0, 0x3b, 0xbf, 0xd2, 0x5e, 0x8c, 0xd0, 0x36, 0x41, 0x41} (32 bytes)
> signature R: 72687201794607335770376625339678533083457947201644627590368835286197510267364
> signature S: 8109447218838624529250472094270127202499713651044141199238310867220054199890
> 
> This fails verification in Trezor, but passes verification in …
> In ecdsa_verify_digest() allow the digest to be equal to the order of the group

- crypto/monero/serialize.c
We might also want to move `xmr_read_varint()` to crypto/tests/test_check_monero.h, see https://github.com/satoshilabs/trezor-firmware/issues/98#issuecomment-736367363.
> Fix undefined behavior in xmr_read_varint()

- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-slip39.h
- core/mocks/generated/trezorcrypto/slip39.pyi
- core/src/apps/management/recovery_device/keyboard_slip39.py
- core/src/trezor/crypto/slip39.py
- crypto/slip39.c
- crypto/slip39.h
- crypto/slip39_wordlist.h
- crypto/tests/test_check.c
Resolves https://github.com/satoshilabs/trezor-firmware/issues/99.
I made the following changes:
- Made the crypto/slip39.c functions more robust and moved any input validation from core to slip39.c.
- Added tests for the edge cases that @invd encountered.
- Renamed `compute_mask()` in slip39.c to `slip39_word_completion_mask()` to better correspond with the naming from bip39.c. There is an unrelated Python function `compute_mask()` in keyboard_bip39.py which makes things confusing because it does something different (computes the mask for a button).
- Added a proper SLIP39 word completion test, which goes through all the words in the wordlist and checks that they can be written with the masks that are returned by `slip39_word_completion_mask()`.
- Made the `find()` function static, since …
> Problems in slip39 find()

- core/src/apps/monero/sign_tx.py
- core/src/apps/monero/signing/step_06_set_output.py
- core/src/apps/monero/signing/step_10_sign_final.py
Either async protobuf leftover or an optimization I don't understand.
> chore(core): monero: drop extraneous async/await

- core/src/apps/webauthn/__init__.py
- core/src/usb.py
changes `usb.py` to be more user-friendly when configuring enabled endpoints, both automatically and by hand
> feat(core): make usb endpoints registration nicer

- core/embed/extmod/modtrezorconfig/modtrezorconfig.c
- core/embed/firmware/mpconfigport.h
- core/embed/unix/mpconfigport.h
Previously, the static could contain a pointer to the upy heap. It needs to be rooted properly in order for GC to find it.
> fix(core): root ui callback for trezorconfig mod

- pyproject.toml
`poetry install` copies trezorlib under `.venv` and then uses that copy which makes it hard to work on trezorlib. IIRC pipenv did not do this? This PR avoids the copying, `python/src/trezorlib` is used directly. The option does not seem to be much documented and I'm not sure it doesn't screw up the package release process.
> build(core): install trezorlib in development mode

- common/tests/fixtures/cardano/sign_tx.json
- core/src/apps/cardano/layout.py
- core/src/apps/cardano/sign_tx.py
Motivation: IOHK (namely Daedalus wallet devs) requested being able to send transactions without outputs, for example in case of transactions with stake delegation certificates. This PR relaxes the requirement of sending at least one output to ensure verifiablilty of the transaction network id, replacing it with a warning at the beginning instead.
Until now, at least 1 output was required; now we allow transactions without outputs. This has minor security implications: a tx that contains no outputs, no withdrawals and no pool registration certificates does not contain any identification of the particular blockchain it will be submitted to, hence Trezor user can be theoretically fooled into signing a tx that (on his computer) appears to be for a testnet, but will actually be submitted to …
> Disable "at least one output in tx" restriction for Cardano, warn instead

- core/embed/bootloader_ci/README.md
- core/embed/bootloader_ci/main.c
Currently if the device is rebooted in a state where it has pin set there's not much you can do with it without someone physically entering the pin. This PR removes confirmation dialog for wiping the storage so that we can automatically do it before flashing new firmware to be tested.
> CI bootloader: wipe storage without confirmation

- poetry.toml
This is supposed to help with occasional CI failures like https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/992276339  probably caused by https://github.com/python-poetry/poetry/issues/3199.
IIUC it disables parallel installation which seems to make each CI job ~45s slower. It's questionable whether not having to retry a CI job manually from time to time is worth couple of minutes longer pipeline.
> build: workaround poetry x gitlab-runner bug

- python/CHANGELOG.md
- python/src/trezorlib/btc.py
If the device asks for a tx_hash which is not present in prev_txes,
raise a ValueError with some more detailed messaging about the missing
hash rather than the default dictionary lookup failure of KeyError.
> python: Raise ValueError for non-existant tx hashes

- python/src/trezorlib/client.py
Not all clients want to do `init_device` immediately. So instead of always doing `init_device()`, allow the caller to tell `TrezorClient` to not. The caller can then do `init_device()` when it is ready.
> python: Optionally init_device in TrezorClient

- ci/hardware_tests/device/t1.py
Fix for https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/1012382702. According to the [video](https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/1012382702/artifacts/file/ci/hardware_tests/video_48d1a7a8_1612600513.mp4) we may just need to wait a little bit longer before the fw boots up.
> ci: wait longer for T1 bootup

- ci/test-hw.yml
It seems *some* test permutations result in FirmwareError most likely caused by OOM.
> ci: deterministic order for hardware TT btconly testcases

- core/src/apps/common/cbor.py
- core/src/apps/common/readers.py
- core/tests/test_apps.common.cbor.py
I was hoping that using a BufferReader for CBOR decoding would save some memory allocations and reduce fragmentation, but it turns out that there is practically no difference. In fact, it occasionally seems to add a few allocations, which we were not able to explain. Still, it makes the code a bit cleaner, so seems worth merging.
> Use BufferReader for CBOR decoding

- ci/build.yml
- core/embed/bootloader_ci/messages.c
Port over changes to normal bootloader from f46380147f390bd880a1431a8fa3fa542ce30a67.
> Fix bootloader_ci build

- core/Makefile
There are just "no GUI" flags added to flashing with JLink so that it can run from script again without GUI.
> Update flashing procedure for new version of JLink software

- core/tools/alloc.py
It can be good to know if the number goes up by a lot, however it's currently not shown anywhere.
> chore(core): show total number of allocations in memperf html report

- python/CHANGELOG.md
- python/src/trezorlib/ui.py
When I enter the PIN on computer without the numeric keypad (most of the laptops), the operation is quite tedious.
Let's allow also PIN entry via (lowercase) letters.
I chose the following layout for couple of reasons:
```
e r t
d f g
c v b
```
* this layout avoids using Y/Z keys which are commonly swapped on localized keyboard layouts (qwerty vs qwertz)
* this layout avoids using AS/QW keys which are commonly swapped on localized keyboard layouts (qwerty vs azerty)
> feat(python): add possibility to enter PIN via letters

- tests/device_tests/test_autolock.py
- tests/device_tests/test_msg_wipedevice.py
We've probably hit a race condition in https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/1045486303
Increase the sleep a bit to reduce probability of this happening again.
> test: wait longer for autolock

- common/protob/messages-debug.proto
- core/CHANGELOG.md
- core/src/apps/base.py
- core/src/apps/debug/__init__.py
- core/src/apps/homescreen/__init__.py
- core/src/apps/homescreen/homescreen.py
- core/src/apps/homescreen/lockscreen.py
- core/src/apps/management/apply_settings.py
- core/src/trezor/messages/DebugLinkDecision.py
- core/src/trezor/ui/loader.py
- python/src/trezorlib/debuglink.py
- python/src/trezorlib/messages/DebugLinkDecision.py
- tests/click_tests/test_lock.py
Fixes #1404. The usual hold-to-confirm animation is shown after first 500ms and finishes in 5s in total. The PR also extends debuglink to support touch hold events.
Please test on actual device as the overall impression can be very different from emulator:)
([regular debug build](https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/972529766/artifacts/file/trezor-fw-regular-debug-2.3.6-6ce0745b.bin))
> Lock TT by holding finger on home screen

- common/tests/fixtures/cardano/sign_tx.json
- core/src/apps/cardano/helpers/paths.py
- core/src/apps/cardano/sign_tx.py
- core/tests/test_apps.cardano.sign_tx.py
- tests/ui_tests/fixtures.json
Motivation: @tsusanka and Trezor QA noticed that Trezor shows the base address change output if some of the inputs happens to be a Byron era input. This is the result of the current `_should_hide_output()` logic in Cardano which hides outputs only if their path matches with all the inputs up to the account index which is stricter than it needs to be and causes issues when Byron/Shelley paths otherwise belonging to the same logical account are mixed.
Changes: relax the `_should_hide_output()` logic to look only at the account indices when matching the tx output with the inputs. The path roots (`m/1852'/1815'/` for Shelley and `m/44'/1815'/` for Byron) are being enforced by the Keychain (core/src/apps/cardano/seed.py) already. Also sending funds the other way around, i.e. from shelley to …
> fix(core/Cardano): do not show change output in byron-shelley transfers

- common/protob/messages-crypto.proto
- core/src/apps/misc/get_ecdh_session_key.py
- core/src/trezor/messages/ECDHSessionKey.py
- legacy/firmware/fsm_msg_crypto.h
- legacy/firmware/protob/messages-crypto.options
- python/src/trezorlib/messages/ECDHSessionKey.py
- tests/device_tests/test_msg_getecdhsessionkey.py
This would allow implementing [age](https://age-encryption.org/) decryption plugin without caching the public key on the host: https://github.com/romanz/trezor-agent/commit/13531b8fd2ce09c5fbe0f0c588f507e6ea8791ef
> Add public_key to ECDHSessionKey

- crypto/Makefile
- crypto/README.md
- crypto/schnorr.c
- crypto/schnorr.h
- crypto/tests/test_check.c
Support Schnorr signature and verification defined in
https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/2019-05-15-schnorr.md.
The implementation is based on https://github.com/Bitcoin-ABC/secp256k1
as well as the test vectors.
This is a first step toward adding support for Schnorr signature and verification to trezorlib.
> Add support for Schnorr crypto (BCH variant)

- core/embed/extmod/modtrezorio/modtrezorio-hid.h
- core/embed/extmod/modtrezorio/modtrezorio-vcp.h
- core/embed/extmod/modtrezorio/modtrezorio-webusb.h
- core/embed/trezorhal/usb_hid-defs.h
- core/embed/trezorhal/usb_vcp-defs.h
- core/embed/trezorhal/usb_webusb-defs.h
- core/embed/unix/usb.c
- core/mocks/generated/trezorio/__init__.pyi
- core/src/usb.py
- core/tools/hid-bridge/hid-bridge
When running `emu.py` (debug) and `emu.py -d` (production), the WebAuthn UDP port is different in each case, 21326 and 21325, respectively. There are two problems:
1. This is an unwelcome complication when running `hid-bridge`, because you have to set the port manually.
2. `emu.py -d` shows the wrong port number:
```
TREZOR_PATH=udp:127.0.0.1:21324
TREZOR_PROFILE_DIR=/var/tmp
TREZOR_UDP_PORT=21324
TREZOR_FIDO2_UDP_PORT=21326  # <---- here
```
We can easily unify the WebAuthn port for both debug and production by reserving the second interface for debug. That way, if WebAuthn is enabled, it will always be on the third interface, meaning that by default the emulator will run WebAuthn on port 21326 every time (except for bitcoin-only).
> WebAuthn on port 21326

- legacy/firmware/fsm.c
- legacy/firmware/messages.c
- legacy/firmware/messages.h
- legacy/firmware/protob/Makefile
- legacy/firmware/protob/messages-bitcoin.options
- legacy/firmware/protob/messages-common.options
- legacy/firmware/protob/messages-debug.options
- legacy/firmware/protob/messages_map.py
- legacy/firmware/udp.c
- legacy/firmware/usb.c
- legacy/firmware/usb.h
Fixes https://github.com/trezor/trezor-firmware/issues/1460.
beb64e9: Replaces the magic number 64 in with USB_PACKET_SIZE in a number of places. This would be very helpful for code legibility. I hope I didn't replace any of the magic values incorrectly. @prusnak please check.
5eefe07: Adds compile-time checks for msg_tiny sizes.
2802060: It seems to me that `msg_read_tiny()` should respond with a Failure message when the received packet is malformed, similar to what the code further down the function does. This would make debugging a bit easier, because returning basically causes the emulator to hang there and the test suite to wait for a response. Are there some instances where it makes sense to return from the function without sending a Failure message @prusnak?
> Improve error handling for msg_tiny

- python/src/trezorlib/cli/btc.py
`trezorctl btc get-descriptor -c Regtest -t wpkh -n 0`
was returning: `ValueError: Unsupported coin`
the current workaround is to use the output of: `trezorctl btc get-descriptor -c Testnet -t wpkh -n 0`
the workaround may not be immediately obvious without looking at the chain params.
this PR makes the Regtest version work. this is useful for tinkering with psbt and the trezor t in a regtest environment.
a quick test is to start a fresh regtest node: `bitcoin-qt -regtest -txindex -datadir=/tmp/node1`
get an address to geneate coins to: `trezorctl btc get-address -t wpkh -n "m/84h/1h/0h/0/0" -c Regtest`
in node console: `generatetoaddress 1 address-from-last-step`
in node console: `createwallet trezor_t true true "" true true true`
get the descriptor from the trezor t: `trezorctl btc …
> python/trezorctl: make bitcoin regtest a supported coin for trezorctl btc get-descriptor

- core/embed/extmod/modtrezorconfig/modtrezorconfig.c
- core/mocks/generated/trezorconfig.pyi
- core/src/storage/common.py
- core/src/storage/device.py
- core/tests/test_storage.py
- core/tests/test_trezor.config.py
- storage/storage.c
- storage/storage.h
- storage/tests/c/storage.py
- storage/tests/python/src/consts.py
- storage/tests/python/src/storage.py
- storage/tests/tests/test_set_get.py
- Improve range checking in modtrezorconfig and raise ValueError on invalid input.
- `config.set_counter()` allowed specifying `count=None` to delete a counter, which seems like a bad choice. Counter should be deleted explicitly by calling `config.delete()`.
- Detect counter overflow when incrementing.
- Add unit tests.
> Improve error handling in modtrezorconfig

- legacy/firmware/CHANGELOG.md
- legacy/firmware/layout2.c
- legacy/oled.c
`nLockTime` = 500000000:
`nLockTime` = 499999999:
I also fixed a bug due to which all bitmaps we flipped incorrectly.
> Show nLockTime in human-readable form

- legacy/firmware/protob/messages-bitcoin.options
The goal is to allow Trezor 1 to create TPoS contracts for Stakenet.
Last year, Stakenet introduced a hard-fork [1] to change the way TPoS contracts
are created, instead of a custom signature method, now it works with the
output from the signMessage method, while this works for Trezor T, it doesn't
work for Trezor 1 due to the 80 bytes limit on the OP_RETURN output while
Stakenet allows up to 150 bytes [2], in a gitter discussion [3] we concluded that
the change should be fine.
The hard-fork was introduced because we couldn't got our TPoS contracts PR accepted [4],
the OP_RETURN still contains the same data, its just stored in a different way:
- The TPoS address, where the coins to stake are stored, and where rewards are received.
- The merchant address, where the merchant receives its …
> legacy: Update op_return max size to 150 bytes

- crypto/memzero.c
When building for windows on a case-sensitive system, mingw always comes with a lower-case windows.h .
Fixing this case prevents build failure when cross-compiling for windows.
> Fix case of windows.h

- core/embed/trezorhal/usbd_conf.c
- core/src/usb.py
- docs/core/build/embedded.md
for history, see #1517. this is that work just rebased on top of the current upstream master branch commit.
> core/embed/usb: use all available usb endpoints and update the usb fifo sizing

- core/.changelog.d/24.fixed
- core/src/apps/common/request_pin.py
- core/src/trezor/ui/layouts/t1.py
Currently core on T1 errors out on ImportError before the firmware initializes USB. While this is mostly solved by #1545 it's probably not going to be in master soon so I'd like to propose this change to at least make T1 fully boot.
> fix(core): imports needed for T1 startup

- legacy/intermediate_fw/trezor.c
Fixes https://github.com/trezor/trezor-firmware/issues/1619
> fix(legacy): set STAY_IN_BOOTLOADER_FLAG before the reboot of intermediate_fw

- common/defs/bitcoin/dogecoin.json
This change was implemented as a [hotfix in trezor-connect](https://github.com/trezor/connect/commit/9b3bd1313de15fe53edc61abb3aeab5f82075fac) a while ago but i totally forget to do this here.
-------------
```
DOGE fee policies have been changed to:
1 DOGE base fee
+ 1 DOGE per 1000 bytes
+ 1 DOGE for every output below 1 DOGE
```
sources:
https://github.com/dogecoin/dogecoin/issues/1650#issuecomment-722229742
https://github.com/trezor/trezor-suite/issues/2973#issuecomment-730607729
> common: update DOGE min_fee and dust_limit

- core/src/apps/management/recovery_device/homescreen.py
- core/src/session.py
- core/src/trezor/wire/__init__.py
- tests/persistence_tests/test_shamir_persistence.py
Introduces `wire.AVOID_RESTARTING_FOR` and the recovery workflow will set it whenever it runs.
This also allows us to e.g. avoid restarting for GetPublicKey and thus make the old Wallet significantly faster, at the cost of some memory fragmentation. I am not doing that now, but it would be easy if we actually needed it.
> feat(core): avoid restarting session for select messages (fixes #1631)

- crypto/tests/test_check.c
An issue was found with some BIP32 implementation, causing incorrect keys with certain seeds (starting with zeroes), see
https://blog.polychainlabs.com/bitcoin,/bip32,/bip39,/kdf/2021/05/17/inconsistent-bip32-derivations.html
Trezor implementation is not affected.
Nonetheless the newly added test vector can be included as an extra test (BIP32 test vector #4).
Test vector 4 is being added to the BIP32 BIP here:
https://github.com/bitcoin/bips/pull/1030
> Extra BIP32 test (new test vector #4)

- ci/check_changelog.sh
- ci/prebuild.yml
- ci/test-hw.yml
- docs/misc/changelog.md
`check_changelog.sh`:
- ignore `master` branch
- treat `secfix/` same as `release/` branches
- allow skiping check with `[no changelog]` in commit message
> ci: improve changelog check, longer timeout for T1 hw test

- ci/shell.nix
- ci/test-hw.yml
- ci/test.yml
The option will allow us to see the duration of each step in test jobs we run on ci. This is mainly for better debugging of legacy test job, which sometimes takes 30 minutes to finish.
> ci: add duration timestamps on all test jobs

- core/.changelog.d/1658.fixed
- core/SConscript.firmware
- core/embed/boardloader/startup.s
- core/embed/bootloader/startup.s
- core/embed/bootloader_ci/startup.s
- core/embed/firmware/main.c
- core/embed/firmware/startup.S
- core/embed/prodtest/startup.s
- core/embed/reflash/startup.s
- core/embed/trezorhal/common.c
- core/embed/trezorhal/common.h
- core/embed/trezorhal/random_delays.c
- core/embed/trezorhal/stm32.c
- core/embed/trezorhal/supervise.h
- core/embed/trezorhal/util.s
- core/embed/trezorhal/vectortable.s
This PR fixes https://github.com/trezor/trezor-firmware/issues/1658.
From my point of view, the cause of the issue is that `shutdown()` is called from the unprivileged mode (see [this comment](https://github.com/trezor/trezor-firmware/issues/1658#issuecomment-865883049)). To solve that, I implemented a SVC handler that calls `shutdown()` from the privileged mode.
> Fix of red screen

- core/embed/firmware/main.c
- core/embed/firmware/startup.S
This requires moving the DRBG initialization in `reset_handler` while interrupts are still forbidden, otherwise SysTick will fail when called before DRBG is initialized.
Tested both on T1 and TT.
Needs a bit more though, as I found out disabling RDI from SConscript still leaves some code behind, e.g. T1 will trip up on `drbg_generate` even if RDI is off. So probably some `#ifdef` is missing somewhere.
> Make RDI work also on T1

- python/.changelog.d/1258.added
- python/.changelog.d/1258.changed
- python/AUTHORS
- python/docs/OPTIONS.rst
- python/src/trezorlib/cli/firmware.py
- python/src/trezorlib/cli/trezorctl.py
Adding new CLI command - (firmware), with three subcommands (update, download, verify).
Creating a prototype of CLI testing under cli/tests.
Fixes #1258
> feat(python/trezorctl): new firmware commands (update, download, verify), CLI tests

- ci/test-hw.yml
Increase timeout since 4h isn't always enough.
> ci/hardware: enable SD card tests and btc tests on regular build

- build-docker.sh
- ci/environment.yml
This should add sha checksum and changes the download of alpine to https. For our GitLab ci and also inside the 
`build-docker.sh ` script. Both should fail with a message `sha256sum: WARNING: 1 computed checksum did NOT match` script and ci will fail if the sha of the file does not match the one in the script. 
Resolves #1714
> feat(ci): add sha checksum for alpine download and change to https

- core/embed/extmod/modtrezorui/display-stm32_1.h
- core/embed/extmod/modtrezorui/display-stm32_T.h
- core/embed/extmod/modtrezorui/display-unix.h
- core/embed/extmod/modtrezorui/display.c
- core/src/trezor/ui/__init__.py
It is my understanding that we need to explicitly push pixel data to the OLED display on T1, while the TT display is mapped to memory and does not need to be told about changes.
Such explicit refresh is already implemented for emulator where it is invoked after every event loop step. This patch mostly adds tracking whether the pixel contents were modified since last refresh so that we don't spend time redrawing display needlessly.
> core: explicitly refresh display on T1

- core/.changelog.d/1581.changed
- core/src/apps/binance/helpers.py
- core/src/apps/bitcoin/addresses.py
- core/src/apps/bitcoin/common.py
- core/src/apps/bitcoin/ownership.py
- core/src/apps/bitcoin/readers.py
- core/src/apps/bitcoin/scripts.py
- core/src/apps/bitcoin/scripts_decred.py
- core/src/apps/bitcoin/sign_tx/bitcoin.py
- core/src/apps/bitcoin/sign_tx/bitcoinlike.py
- core/src/apps/bitcoin/sign_tx/decred.py
- core/src/apps/bitcoin/sign_tx/hash143.py
- core/src/apps/bitcoin/sign_tx/tx_info.py
- core/src/apps/bitcoin/sign_tx/zcash.py
- core/src/apps/bitcoin/verification.py
- core/src/apps/bitcoin/writers.py
- core/src/apps/cardano/helpers/utils.py
- core/src/apps/common/cbor.py
- core/src/apps/common/coininfo.py
- core/src/apps/common/coininfo.py.mako
- core/src/apps/common/writers.py
- core/src/apps/webauthn/fido2.py
- core/src/trezor/crypto/der.py
- core/src/trezor/crypto/scripts.py
- core/src/trezor/utils.py
- crypto/tests/test_check_cashaddr.h
- legacy/firmware/layout2.c
- legacy/firmware/recovery.c
This PR aims to reduce memory allocations and fragmentation mainly in Bitcoin signing by using writer semantics and memoryviews instead of string manipulations. I am not sure how effective the individual changes are, for example the global static buffer for Tx serialization might be pointless now that we have the workflow restarts.
> Reduce string manipulations in BTC signing

- core/embed/extmod/modtrezorutils/modtrezorutils-meminfo.h
- core/embed/rust/librust.h
- core/embed/rust/src/protobuf/obj.rs
- core/tools/analyze-memory-dump.py
Followup of #1557. Not sure whether shortval is the right place for the message name.
> feat(core/emulator): support protobuf messages in memory dumps

- core/src/trezor/utils.py
- core/src/trezor/wire/__init__.py
Useful for debugging, but makes the log much chattier.
Probably the usefulness outweighs the chattiness.
> feat(core): in debug mode, dump contents of received protobuf messages

- legacy/firmware/bl_check.c
- legacy/firmware/bl_data.py
This kicked me in the nuts during the last singing round.
Not ideal way how to do it, but can't think of a prettier method.
> feat(legacy): make sure that known_bootloader check contains the hash of our bundled bootloader

- .github/workflows/prebuild.yml
Set to fetch all history for GitHub actions changelog check. Possible fix for changelog script not working correctly on GitHub actions.
> fix(ci): gh actions set to fetch all history for changelog check

- python/.changelog.d/1167.changed
- python/.changelog.d/1193.added
- python/.changelog.d/1232.fixed
- python/.changelog.d/1257.fixed
- python/.changelog.d/1363.added
- python/.changelog.d/1496.added
- python/.changelog.d/1682.changed
- python/.changelog.d/1738.added
- python/CHANGELOG.md
Merge changelog entries from branch python/v0.12.x, delete towncrier snippets that were already included.
> docs(python): update changelog for 0.12.3

- legacy/emulator/emulator.h
- legacy/emulator/udp.c
- legacy/firmware/.changelog.d/1743.changed
- legacy/firmware/trezor.c
- legacy/firmware/udp.c
1. I use `poll()` to check data on normal and debug interfaces at the same time...
2. which allows me to use timeout on the `poll()` call...
3. so I can implement `usbSleep(millis)` in terms of that timeout, instead of busy-looping over `usbPoll()`
So I changed current `usbPoll()` to `usbSleep()`, and implement `usbPoll()` as `usbSleep(0)`
The more important busy loop is in `main.c`. In order to make that sleep sensibly, I had to modify the `usbSleep()` function so that it will send/receive the whole protobuf message in a single call -- otherwise we'd be inserting delays in the middle of messages.
> Avoid busy loop in legacy emulator

- python/.changelog.d/1565.added
- python/.changelog.d/1668.changed
- python/src/trezorlib/debuglink.py
- python/src/trezorlib/transport/udp.py
- tests/conftest.py
- tests/device_tests/test_msg_recoverydevice_bip39.py
- tests/device_tests/test_msg_signidentity.py
- tests/device_tests/test_msg_signtx.py
- tests/device_tests/test_msg_signtx_bcash.py
- tests/device_tests/test_msg_signtx_bgold.py
- tests/device_tests/test_msg_signtx_segwit.py
- tests/device_tests/test_multisig.py
Main part is reusing `client` across test runs, which makes skipping tests significantly faster because we don't have to wait to figure out the model of the device every time.
Locally this speeds up legacy emulator test by 30 seconds, which is nice.
Also makes sure the whole suite always runs against the same device (modulo emulator being restarted).
0deffdb should help with the "invalid chunk size" occasional CI failure, as described in #1668. This is not proven however, we will see in practice.
> Testsuite improvements

- crypto/fuzzer/README.md
- crypto/fuzzer/extract_fuzzer_dictionary.sh
- crypto/fuzzer/fuzzer.c
This PR extends the self-contained fuzzer harness collection for trezor-crypto. For some background, see the previous #1090 PR.
The added code is stand-alone and adds no functional changes to the library itself. The fuzzer improvements have been relevant in #1219, c5f26beeeae315faf8e4be4476cf92949048101c and the SLIP39 find() topic.
> crypto: improve fuzz testing code, harnesses, documentation and scripts

- python/.changelog.d/1745.added
- python/.changelog.d/1745.incompatible
- python/README.md
- python/requirements-optional.txt
- python/setup.py
- python/src/trezorlib/cli/stellar.py
- python/src/trezorlib/stellar.py
- python/tests/test_stellar.py
- python/tox.ini
This PR mainly introduces the [Stellar Python SDK](https://github.com/StellarCN/py-stellar-base) to reduce the maintenance cost of the Stellar code.
- `trezorlib.stellar.parse_transaction_bytes` was removed. (We can keep it if needed.)
- `trezorlib.stellar` now relies on stellar-sdk, please check the README.md for more information.
- `trezorlib.stellar.parse_transaction` was added, it includes support for the Stellar [TransactionV1](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0015.md#xdr) format transaction.
> refactor(python/stellar): Use Stellar Python SDK to parse Stellar transactions.

- python/src/trezorlib/stellar.py
- python/tests/test_stellar.py
The type of `StellarAllowTrustOp.is_authorized` is `uint32`, and I mistakenly treated it as a `bool` type in [this PR](#1745).
> fix(python/stellar): correct the data type passed to StellarAllowTrustOp.is_authorized.

- python/CHANGELOG.md
- python/src/trezorlib/__init__.py
- python/src/trezorlib/cli/__init__.py
the following option definition:
```
@click.option("-t", "--script-type", type=ChoiceType(INPUT_SCRIPTS), default="address")
```
```
Options:
-t, --script-type [address|segwit|p2shsegwit|pkh|wpkh|sh-wpkh]
```
works fine in Click 7.x
and we use this in several places
in 8.x, if `-t` is not specified, the following error appears:
```
Error: Invalid value for '-t' / '--script-type': 0 is not one of 'address', 'segwit', 'p2shsegwit', 'pkh', 'wpkh', 'sh-wpkh'.
```
This is because Click 8.0 first converts the _default value_ to the destination type (which is `int` for trezorlib 0.12.x and `IntEnum` in master), and then runs `ChoiceType.convert` on it again as a part of some subsequent step.
This is not strictly a Click bug, as their docs explicitly state that "The custom type should check at …
> Fix Click 8.x problem when a ChoiceType argument has a default value

- core/.changelog.d/1642.security
- core/embed/bootloader/.changelog.d/1642.security
- core/embed/bootloader/main.c
- core/embed/firmware/main.c
- core/embed/trezorhal/compiler_traits.h
- legacy/bootloader/.changelog.d/1642.security
- legacy/bootloader/.gitignore
- legacy/bootloader/bootloader.c
- legacy/compiler_traits.h
- legacy/firmware/.changelog.d/1642.security
- legacy/firmware/trezor.c
Per https://blog.inhq.net/posts/faulty-stack-canary-arm-systems/ ARM gcc versions 9.2.1-10.2 have broken stack smash protector. Unfortunately these are still included in distros.
The main purpose of the PR is to prevent build of bootloader.bin with broken gcc which gets bundled with firmware since that is done usually manually and not in CI.
> Avoid accidental build with broken stack protector, especially for bundled bootloader.bin

- core/embed/boardloader/.changelog.d/1642.security
- core/embed/boardloader/main.c
We omitted boardloader from https://github.com/trezor/trezor-firmware/pull/1642
This PR fixes this.
> fix(core): avoid accidental build with broken stack protector (boardloader)

- core/SConscript.unix
Some Linux distros at least will build emulator debug build that segfaults on start - #304 
The only stable workaround is using `-Og` instead of `-O0` which is also preferred by gcc manual.
> Fix core emulator debug build segfault

- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-bip32.h
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-nist256p1.h
- crypto/bip32.c
- crypto/bip32.h
- crypto/ecdsa.c
- crypto/ed25519-donna/ed25519.c
- crypto/schnorr.c
- crypto/tests/test_check.c
- crypto/tests/test_check_cardano.h
- crypto/tests/test_openssl.c
- legacy/firmware/fsm_msg_coin.h
- legacy/firmware/fsm_msg_crypto.h
- legacy/firmware/fsm_msg_ethereum.h
- legacy/firmware/fsm_msg_nem.h
- legacy/firmware/signing.c
- legacy/firmware/stellar.c
- legacy/firmware/transaction.c
- legacy/firmware/u2f.c
Addresses https://github.com/satoshilabs/trezor-firmware/issues/111 and https://github.com/satoshilabs/trezor-firmware/issues/112, i.e.:
1. Treat edge cases in `ecdsa_sign_digest()` same as `ecdsa_verify_digest()` does (all-zero private key and all-zero digest).
2. Check private key validity when deriving public key.
For 2 I decided to propagate the error to the calling functions, namely `hdnode_fill_public_key()` and further on. I think it's not really necessary to do this, because in the vast majority of cases the error is unreachable, but in the future it might help us in catching some bug early on. So, better safe than sorry.
I also noticed that `ed25519.c` wasn't doing any stack cleanup of sensitive values, so I added that.
@onvej-sl please make sure that 1 and 2 is implemented in …
> ECDSA error handling

- common/.gitrepo
- python/.changelog.d/1896.fixed
- python/tools/build_tx.py
Also improve script type selection.
> fix(python/build_tx): make build_tx work again after blockbook protection upgrades

- crypto/blake2_common.h
- crypto/byte_order.h
- crypto/monero/base58.c
- crypto/monero/xmr.c
- crypto/sha2.c
- crypto/sha2.h
- crypto/sha3.c
- crypto/tests/test_check.c
This patch fixes multiple errors in the crypto routines, related to lack of big-endian support.  Correctness is measured by using test_check.
Big-endian builds already needed `CFLAGS="-DSPH_BIG_ENDIAN=1 -DSPH_LITTLE_ENDIAN=0 -DBYTE_ORDER=BIG_ENDIAN"` for some existing endian support; this does not change.
x86_64 (little-endian, 64-bit): `test_check` passes 100%
MIPS (big-endian, 32-bit): `test_check` **passes 81%, 28 failures** (and 0 errors)
x86_64 (little-endian, 64-bit): `test_check` passes 100%
MIPS (big-endian, 32-bit): `test_check` passes 100%
- All adjustments re-use the `BIG_ENDIAN` / `LITTLE_ENDIAN` / `BYTE_ORDER` defines and swap functions already present in `sha2.h`, for consistency
- Fixed endian issues in `sha3` (this fixes many failed tests, as sha3 is a dependency to much …
> crypto big endian support

- ci/shell.nix
- core/embed/unix/mpconfigport.h
Supersedes https://github.com/trezor/trezor-firmware/pull/1899
ifdef from https://github.com/micropython/micropython/blob/ff4f1f3ab395a6be426cc1b6ce0839bf65574f45/ports/unix/mpconfigport.h#L189-L192
Also let's not try to harden emulator binaries via stackprotector, it does not work on Apple Silicon atm.
> fix(core): fix emulator build on Apple Silicon

- poetry.lock
continuation of #1900
cryptography 3.3.1 does not provide wheels built for Apple Silicon.
https://cryptography.io/en/latest/api-stability/#version-35-0-0
> chore: bump cryptography from 3.3.1 to 35.0.0

- crypto/sha3.c
Fixes https://github.com/satoshilabs/trezor-firmware/issues/121.
> fix(crypto): fix undefined behaviour of IS_ALIGNED_64 macro

- ci/shell.nix
- core/embed/extmod/modtrezorui/display.c
- legacy/firmware/crypto.c
New clang-format does weird thing with `} else // comment<lf> if (...) {`: https://github.com/trezor/trezor-firmware/commit/7a35984591e2efbaa38bd6ef5a96221a89052677 . I don't know [which new option](https://releases.llvm.org/13.0.0/tools/clang/docs/ReleaseNotes.html#clang-format) disables this behavior, if any, so I moved the comments inside the `if` body instead.
Requires #1924.
> style(all): reformat with clang-format 13.0

- common/protob/messages-management.proto
At the moment trezor-connect holds [4 sets of protobuf definitions](https://github.com/trezor/connect/tree/develop/src/data/messages) and loads them dynamically based on the version of currently connected device.
We would like to upgrade to the [new trezor-link version](https://github.com/trezor/trezor-link/pull/44). To be able to do that we kind of need to get rid of multiple messages.json files. 
So we started digging into "what got wrong" to find out why we needed to introduce this workaround in the past. Obviously it was because of some backwards incompatible changes to .proto files and our lack of assertiveness probably :joy_cat: 
We (me and @szymonlesisz) propose re-introducing some of the fields that used to exist in past. ack @matejcik 
So far I have added those that seem to be …
> chore(proto): backwards compatibility changes for protobuf defs

- legacy/layout.c
Fixes overflow caused by layout change. By inlining we spare 92 bytes.
> Make T1 bootloader fit into its region

- legacy/firmware/layout2.c
Fixes https://github.com/trezor/trezor-firmware/issues/1341
Relevant to https://github.com/trezor/trezor-suite/issues/4534
----
The only thing I am not happy about is the need to abbreviate the "Legacy Segwit" to "L.SegWit" because of not enough pixel estate. 
"Legacy"
"Legacy Segwit"
"SegWit"
"Taproot"
> fix(legacy): update account naming

- core/embed/firmware/memory_T.ld
Since 9e0cfa678382b607664300dc1c714c48c4e4ea50 core fw fails to build with `PRODUCTION=1`:
```
/nix/store/z8qcil5m2l7xm5r4r604kikm60bli625-gcc-arm-embedded-10.3.1/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: build/firmware/firmware.elf section `.flash' will not fit in region `FLASH'
/nix/store/z8qcil5m2l7xm5r4r604kikm60bli625-gcc-arm-embedded-10.3.1/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: region `FLASH' overflowed by 62984 bytes
collect2: error: ld returned 1 exit status
```
This reverts to linker script with explicit secp256k1-zkp handling.
> build(core): place secp256k1-zkp in FLASH2 to make space for bootloader

- core/embed/firmware/memory_T.ld
This is supposed to catch early cases when `PRODUCTION=1` build would overflow, but doesn't overflow for developer since linker normally drops the bootloader image, as `check_and_replace_bootloader` is ifdef-ed out.
Obviously the size still differs a bit from full production build, but not by so much.
> Keep bootloader image in non-production builds

- ci/build.yml
Runs the "production" build, then make clean, then the developer build. No artifacts retained. I tried to avoid adding 4 more jobs.
@hiviah suggested to always build bootloader with `MEMORY_PROTECT=1` but this raises question how to build the files common among firmware and bootloader. Also I would prefer not to introduce another parameter passed to the build, nor do some major build refactoring if possible.
> ci: also build legacy firmware with MEMORY_PROTECT=1

- ci/build.yml
- ci/posttest.yml
- ci/prebuild.yml
- ci/test-hw.yml
- ci/test.yml
This introduces caching of `.venv` with GitLab cache. Related to this [issue](https://github.com/satoshilabs/devops/issues/49)
I hope I didn't miss any job that is installing poetry and would benefit from this. Also, this type of cache is per branch it means that the first time branch runs, the ci will create cache for it and use that next time that branch runs in the ci.
> ci: introduce gitlab cache for vnev

- .github/workflows/project_automation.yml
This GitHub workflow automatically adds every newly created issue to the Inbox column in the Backlog project. This is the same setup as we have for the trezor-suite.
> ci: auto add new issues to backlog project

- legacy/bootloader/Makefile
Some objects from libtrezor were compiled with `-O3` even when used in bootloader. This changes their compilation to size optimization `-Os`, saving currently 1116 bytes in legacy bootloader.
> Build legacy bootloader with size optimization

- python/.changelog.d/1959.fixed
- python/src/trezorlib/ui.py
Trying to solve https://github.com/trezor/trezor-firmware/issues/1737
Allowing the input for PIN/passphrase on Windows in Git Bash, which has issues with hidden input.
Recognizing the situation (through `sys.stdin.isatty()`) and in negative case disallowing the hidden feature and reporting this to the user.
Screenshot from Git Bash on Windows:
> fix(python): allowing PIN/passphrase input for Git Bash

- ci/shell.nix
Supersedes https://github.com/trezor/trezor-firmware/pull/1968
Fixes #1934
> ci(nix): use explicit versions for clang and gcc

- legacy/firmware/.changelog.d/1985.fixed
- legacy/firmware/fsm.c
- legacy/firmware/udp.c
- legacy/firmware/usb.c
- legacy/firmware/usb.h
This fixes showing reboot dialog twice from #1983 by explicitly calling USB flush (write and wait) instead of USB sleep which has side effect of handling messages.
The client will still get LIBUSB error when sending messages too quickly.
> Prevent recursing in handling RebootToBootloader by USB flush

- legacy/Makefile.include
This creates option to turn off stack protector on ARM builds which fixes emulator stack smashing bug for @vdovhanych .
Setting `NO_STACK_PROTECT=1` environment variable when building removes stack smash protector.
(Default build is with stack protector enabled)
> Option to turn off stack protector on legacy build

- python/src/trezorlib/protobuf.py
Using `__`-prefixed names seems to be a convention for specifying position-only arguments before Python 3.8. Pyright respects this convention and in fact requires it since version 1.1.192.
> style(python): mark Reader/Writer protocol arguments as position-only

- crypto/bignum.c
Discovered via clang-14 warnings for -Wbitwise-instead-of-logical
Closes https://github.com/satoshilabs/trezor-firmware/issues/129
> fix(crypto): avoid warnings and document bitwise operator use

- ci/shell.nix
- ci/test.yml
- tests/.gitignore
- tests/connect_tests/connect_tests.sh
Starting to experiment with https://github.com/trezor/trezor-firmware/issues/1932
Goal is to get the `connect` repository and run all its tests in our CI using out freshly-build emulator.
For quicker feedback loop, I have disabled all other CI stages apart from the new `connect`.
To be done:
- `tenv` image being able to run a local emulator (as we will have the build emulator as artifact on CI server and we could use it to the tests)
- other possibility is just sending it the URL with the CI artifact (this is already implemented [in this PR](https://github.com/trezor/trezor-user-env/pull/120)
> Connect tests against current firmware branch in CI

- ci/test.yml
In `tenv` we have disabled emulator/bridge output into `stdout` and it goes into a logfile instead (by default for CI jobs).
Adding this logfile as an artifact into the `connect` test stage, so in case of problems we have access to it.
> chore(ci): connect tests - exporting emu/bridge logfile from tenv as artifact

- docs/SUMMARY.md
- docs/hardware/model-t/boot.md
- docs/hardware/model-t/index.md
- docs/index.md
- docs/misc/coins-bip44-paths.md
- docs/misc/monorepo.md
- docs/tests/device-tests.md
Tried to run the docs through https://github.com/Michael-F-Bryan/mdbook-linkcheck. It prints a bunch of false positives so integrating it in CI is probably not worth it now.
@gabrielKerekes do you know where to find `Ed25519_BIP.pdf`?
```
error: File not found: docs/
┌─ python/trezorlib.md:98:29
│
98 │ info and addresses. See the [docs/](docs/) sub folder for detailed
│                             ^^^^^^^^^^^^^^ File not found: docs/
error: File not found: tools/
┌─ python/trezorlib.md:108:44
│
108 │ your application. See examples here in the [tools/](tools/) sub folder.
│                                            ^^^^^^^^^^^^^^^^ File not found: tools/
error: Server returned 404 Not Found for https://cardano.org/assets/Ed25519_BIP.pdf
┌─ misc/coins-bip44-paths.md:76:41
│
76 │ 4. <a …
```
> docs: fix dead links

- ci/check_changelog.sh
- common/protob/messages-ethereum-eip712.proto
- common/protob/messages-ethereum.proto
- common/protob/messages.proto
- common/tests/fixtures/ethereum/sign_typed_data.json
- core/src/trezor/enums/MessageType.py
- core/src/trezor/enums/__init__.py
- core/src/trezor/messages.py
- legacy/firmware/.changelog.d/131.added
- legacy/firmware/ethereum.c
- legacy/firmware/ethereum.h
- legacy/firmware/fsm.h
- legacy/firmware/fsm_msg_ethereum.h
- legacy/firmware/layout2.c
- legacy/firmware/layout2.h
- legacy/firmware/protob/Makefile
- legacy/firmware/protob/messages-ethereum.options
- python/.changelog.d/1970.added
- python/src/trezorlib/cli/ethereum.py
- python/src/trezorlib/ethereum.py
- python/src/trezorlib/messages.py
- tests/device_tests/ethereum/test_sign_typed_data.py
- tests/ui_tests/fixtures.json
Hey :wave: 
In this PR I have implemented a basic EIP-712 typed data signing for T1 based on Ledger. In this approach, The client calculates sha-3 of the `domain separator` and and `message` then sends them to trezor for signing. On the device, both of the signatures will be combined and prefixed with `\x19\x01` and then get signed and sent back.
This is NOT the most secure way since an attacker can send any other message and you cannot see the actual data on the device screen, on the other hand showing a large message data is not feasible on a T1's screen and having this feature which is becoming a de-facto standard is better than not having it at all I guess.
This should not compromise anything else as the client data for signature is prefixed with `\x19\x01`.
I have also made the …
> feat(legacy): Implement EIP-712 signing

- .gitlab-ci.yml
- ci/build.yml
- ci/deploy.yml
This PR adds a build for arm emulators needed for trezor-user-env running on arm version of nix. See why [here](https://github.com/trezor/trezor-user-env/pull/114).
This is now done with our m1 runner as docker executor.  I used my nixos image as nixos/nix is completely broken since they switched from alpine to native nixos one. See [here](https://github.com/NixOS/nix/issues/5777#issuecomment-996242619). Once the upstream image is fixed, we can change to that.
This pr also adds native fixes manual macOS build using our runner and built on x86_64 via rosseta2.
> ci: add arm build for core unix and legacy emulators

- common/protob/messages-management.proto
- core/embed/bootloader/.changelog.d/1599.changed
- core/embed/bootloader/main.c
- core/embed/bootloader/messages.c
- core/embed/bootloader/protob/messages.options
- core/embed/bootloader/protob/messages.pb.h
- core/embed/bootloader/protob/messages.proto
- core/embed/bootloader_ci/.changelog.d/1599.changed
- core/embed/bootloader_ci/main.c
- core/embed/bootloader_ci/messages.c
- core/embed/trezorhal/flash.h
- core/embed/trezorhal/image.c
- core/embed/trezorhal/image.h
- core/src/trezor/messages.py
- legacy/firmware/protob/messages-management.options
- python/src/trezorlib/messages.py
Previously we checked whether the current vendor header and
the new vendor header are the same by comparing the embedded keyset.
What originally looked like a good idea is not that good, because
this disallows us from ever changing the vendor header signing keys
without causing erasure of the storage during the version update.
This commit fixes that by changing the logic to comparing just the
vendor string.
Change of function names is purely cosmetic:
* vendor_keys_hash -> vendor_header_hash
* check_vendor_keys_lock -> check_vendor_header_lock
> fix(core): change logic of vendor header comparison

- crypto/ecdsa.c
- crypto/tests/test_check.c
Resolves https://github.com/satoshilabs/trezor-firmware/issues/131.
Treat point at infinity as an invalid public key in `ecdsa_recover_pub_from_sig()`.
> Treat point at infinity as an invalid public key

- crypto/tests/test_check.c
The function expects `sig` to be larger, see `// signature_bytes has 64 bytes`.
Correcting the buffer resolves memory safety issues during the test run.
Closes https://github.com/satoshilabs/trezor-firmware/issues/130.
> fix(crypto): fix incorrect sig buffer size

- crypto/tests/test_wycheproof.py
The JSON schema of the test cases has slightly changed.
The "curve" field has moved to the "testGroups" level and the X25519 algorithm has been renamed, which requires adjustments in the parsing code.
A duplicate definition of "ecdh_vectors" has also been removed.
> tests(crypto): update wycheproof testcase source and parsing

- python/.changelog.d/2023.added
- python/src/trezorlib/cli/__init__.py
- python/src/trezorlib/cli/trezorctl.py
- python/src/trezorlib/ui.py
- python/tools/trezorctl_script_client.py
Connected with https://github.com/trezor/trezor-firmware/issues/1737 and using suggestions in https://github.com/trezor/trezor-firmware/pull/1959
Creating a possibility of more reliable usage of `trezorctl` by other scripts.
Making a new `ScriptUI` class that has a lot in common with `ClickUI`. 
It is not final by any means, the `ScriptUI` will need to be changed quite a lot and in the end we may somehow connect it with `ClickUI` - or create a `BaseUI` and both will inherit from it.
New (temporary) file `python/src/trezorlib/cli/test_script_client.py` allows for quick testing and developing - currently it only tries `get-address` without the passphrase.
> ScriptUI for trezorctl

- crypto/address.c
- crypto/tests/test_check.c
- legacy/firmware/ethereum.c
- legacy/firmware/fsm_msg_ethereum.h
This is just a simple refactor which moves `resp->address[0] = '0'; resp->address[1] = 'x';` into the `ethereum_address_checksum` function.
> fix(crypto): refactor ethereum_address_checksum to prepend "0x"

- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-monero.h
- core/embed/extmod/trezorobj.h
Inspired by the change in https://github.com/trezor/trezor-firmware/pull/317
Also simplified `trezor_obj_get_uint64` to look more like `trezor_obj_get_uint`
> chore(core/embed): refactor trezor_obj_get_uint64 into trezorobj.h

- .github/workflows/project_automation.yml
This will set up permissions for GitHub token to only access issues pr and project. If the automation on the marketplace gets compromised, the job would not be able to access anything else.
> (ci): set permissions for github token on workflow

- ci/environment.yml
This will allow us to have the base docker image be built once a week and keep the manual build of the image if needed.
> ci: build base docker image once a week on schedule

- ci/build.yml
Fixes #1937. Core only, legacy already builds with PRODUCTION=1 as part of the normal job. Relevant to #2059 if I figure out how to parametrize our jobs.
Note to self: uncomment the `only: schedules` lines before merging.
> ci(core): add nightly builds with PRODUCTION=1

- ci/Dockerfile
- ci/common_sync/common_repo_sync.sh
- ci/common_sync/git-filter-repo
- ci/deploy.yml
This automates sync with the trezor-common repository. 
For now, it pushes to the filter-repo branch. It will be changed to master after we switch branches in the repository. With this script, there is no option to run it easily manually. If we need to push the changes sooner than in the nightly job, I can set up a manual job for this.
> ci: add script for automating common sync

- ci/shell.nix
- ci/test.yml
This pr adds hwi trezor test to our CI. Not sure if this is the best solution for adding the tests to our ci. 
Also, If you have any idea how to not directly point to /nix/store for bitcoind binary, use a relative path so it doesn't break with each nix update. Suggestions welcome.
> ci: add hwi tests for core and legacy builds

- core/src/apps/bitcoin/authorization.py
- core/tests/test_apps.bitcoin.authorization.py
- tests/device_tests/bitcoin/test_authorize_coinjoin.py
Implements https://github.com/trezor/trezor-firmware/issues/1160#issuecomment-984727902.
This PR modifies the validation rules for pre-authorized `GetOwnershipProof` messages. Trezor will only check that commitment data starts with a length-prefixed name of the CoinJoin coordinator. The name can be followed by any other challenge that the coordinator chooses, typically a 32-byte round ID.
> Tweak validation of pre-authorized GetOwnershipProof

- crypto/bip32.c
- crypto/bip32.h
- crypto/bip39.c
- crypto/bip39.h
Internal trezor-crypto caches have messed up reproducible UI tests many times before. Let's finally have an explicit API to clear them when the device is wiped. Although it doesn't seem to matter in practice, it's cleaner anyway.
We might want to export something like `crypto_clear_caches()`, but I didn't know where to put it.
> feat(crypto): API for clearing internal caches

- legacy/bootloader/CHANGELOG.md
Checked the actual unreleased changes and everything seems to match except the missing date.
> docs(legacy/bootloader): fix changelog date

- legacy/common.c
- legacy/firmware/.changelog.d/2107.fixed
- legacy/firmware/config.c
- legacy/firmware/protect.c
- legacy/firmware/recovery.c
- legacy/firmware/trezor.c
- legacy/firmware/udp.c
- legacy/firmware/usb.c
- legacy/firmware/usb.h
This change is aimed to make USB handling in T1 legacy more readable and also remove states where handling of USB protobuf messages should not happen (even if not exploitable right now, it helps prevent accidental bugs in future).
FSM and message handling is already complicated due to call graph being complex.
> Fix legacy technical debt in USB handling

- common/defs/misc/misc.json
[As discussed](https://five-binaries.slack.com/archives/C0292ULQHGD/p1645522020708709) we are changing slip44/coin_type part of cardano testnet definition to `1815`
> fix: cardano testnet slip44/coin_type

- core/src/trezor/enums/__init__.py
- core/src/trezor/messages.py
- tools/build_protobuf
Simplifications in `tools/build_protobuf`:
- explicitly rejecting `messages-bootloader.proto` file from the list of `core` proto files (so that new files do not need to be registered here)
- deleting unused `*_MESSAGES_IGNORE` variables
As the order of files changed a little bit (alphabetically), there are small changes in generated files
> chore(tools): simplify build_protobuf file sources creation

- common/protob/check.py
Adding error explanation to protobuf messages check, which is part of `common prebuild` job in `CI`.
Currently, the error message does not say why it happened.
> chore(common): include error explanation in protobuf messages check

- ci/shell.nix
Tried to set up a `rust` environment in `VS Code` and the `rust-analyzer` extension was not working out of the box. Some small change needed in `shell.nix`
> feat(shell.nix): enable rust extensions in VS Code

- core/emu.py
- python/src/trezorlib/_internal/emulator.py
I was under impression that headless mode disables animation. However, this is not the case.
If we do not want this by default (for some reason I don't see/understand), feel free to close this PR.
> feat(core): headless emulator implies disabled animations

- Makefile
- ci/build.yml
- ci/environment.yml
- ci/prebuild.yml
- ci/test-hw.yml
- ci/test.yml
- docs/ci/jobs.md
- tools/generate_ci_docs.py
Connected with https://github.com/trezor/trezor-firmware/issues/2064
Working prototype of taking all the `CI` jobs and their descriptions from `.yml` files and creating a `README` out of them.
The generated `.md` file is included as `docs/ci/jobs.md` and its current status can be seen here - https://github.com/trezor/trezor-firmware/blob/grdddj/docs_improvements_and_autogeneration/docs/ci/jobs.md
> Autogenerating CI docs from .yml files

- core/SConscript.firmware
- core/SConscript.unix
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-bip340.h
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto.c
When SECP256K1_ZKP is set to False in SConscript.{firmware,unix} the build fails.
This PR fixes the issue. However, this still does not mean the firmware is usable as is, since we use the bip340 in our codebase unconditionally. 
The change is still beneficial IMHO because this allows development of a completely custom firmware (i.e. different `core/src`) with SECP256K1_ZKP not included in the build.
> fix(core): fix build with FEATURE_FLAGS.SECP256K1_ZKP=False

- ci/test.yml
Currently the `Connect` job in `CI` is broken because of `tenv` changes (the image is being uploaded on `GitHub`'s `ghcr.io` instead of `Gitlab`). This makes the relevant changes to make it work again.
Running it now also uncovered that there is **a lot** of errors caused by `Input does not match scriptPubKey` and `Failed to decode message: Missing required field collateral_inputs_count` - https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/2233814735
> Connect tests fix

- core/embed/extmod/modtrezorui/display-unix.h
- core/embed/unix/touch.c
- legacy/emulator/buttons.c
- legacy/emulator/oled.c
The default include path for SDL2 is `/usr/include/SDL2` not `/usr/include`
```
$ pkg-config --cflags sdl2
-D_THREAD_SAFE -I/usr/include/SDL2
```
> fix(core+legacy): fix SDL2 include path

- ci/shell.nix
- tests/download_emulators.sh
NixOS recently switched to different autoPatchelfHook implementation which doesn't work for us in NixOS/nixpkgs#149731. This PR forces the use of the older implementation as a temporary measure.
> ci: use autoPatchelfHook from pinned nixpkgs for emulators

- tests/device_tests/bitcoin/test_getaddress_show.py
Reading the screen lines seems to be time-sensitive, e.g. https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/2125107052
Should be ultimately fixed by switching to the new UI.
> test: mark test_show_multisig_xpubs as flaky

- crypto/Makefile
- crypto/fuzzer/README.md
- crypto/fuzzer/extract_fuzzer_dictionary.py
- crypto/fuzzer/extract_fuzzer_dictionary.sh
- crypto/fuzzer/fuzzer.c
- crypto/fuzzer/sanitizer_ignorelist.txt
Introduce fuzzing harnesses for zkp* and other functions
Adapt some differential fuzzing and other logical checks
Add a new dictionary extraction program
Additional documentation and minor cleanup
Add a temporary workaround for clang-14 and more explicit Makefile behavior
> feat(crypto): improve trezor-crypto fuzzer

- core/Makefile
JLink command line parameters have changed, this needs to be reflected in Makefile, otherwise flashing will fail.
> Update JLink command line flashing parameters

- core/embed/rust/build.rs
- core/embed/rust/src/micropython/buffer.rs
- core/embed/rust/src/trezorhal/display.rs
- core/embed/rust/src/ui/component/label.rs
- core/embed/rust/src/ui/component/paginated.rs
- core/embed/rust/src/ui/component/text/formatted.rs
- core/embed/rust/src/ui/component/text/iter.rs
- core/embed/rust/src/ui/component/text/layout.rs
- core/embed/rust/src/ui/component/text/paragraphs.rs
- core/embed/rust/src/ui/display.rs
- core/embed/rust/src/ui/model_t1/component/button.rs
- core/embed/rust/src/ui/model_t1/component/dialog.rs
- core/embed/rust/src/ui/model_t1/component/frame.rs
- core/embed/rust/src/ui/model_t1/layout.rs
- core/embed/rust/src/ui/model_tt/component/button.rs
- core/embed/rust/src/ui/model_tt/component/frame.rs
- core/embed/rust/src/ui/model_tt/component/keyboard/bip39.rs
- core/embed/rust/src/ui/model_tt/component/keyboard/common.rs
- core/embed/rust/src/ui/model_tt/component/keyboard/mnemonic.rs
- core/embed/rust/src/ui/model_tt/component/keyboard/passphrase.rs
- core/embed/rust/src/ui/model_tt/component/keyboard/pin.rs
- core/embed/rust/src/ui/model_tt/component/keyboard/slip39.rs
- core/embed/rust/src/ui/model_tt/component/page.rs
- core/embed/rust/src/ui/model_tt/layout.rs
The current Rust layout is not string-aware and passes bytes everywhere.
This PR converts most usage sites to &str, String and friends, so that we have UTF-8 enforced in the type system.
A `StrBuffer` type is introduced in the FFI to load `str` from MicroPython side properly.
> Use &str in place of &[u8] where appropriate

- core/embed/rust/build.rs
- storage/tests/c/Makefile
- storage/tests/c/norcow_config.h
Fixes [storage test](https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/2386665118). Related: #2222.
> fix(core): leftover TREZOR_MODEL defines

- tools/firmware_hash.py
The official T1 firmware has an extra 256 bytes at the beginning of the file, starting with "TRZR". This needs to be stripped when we compute the hash in the firmware_hash.py tool to get the right result. I am not exactly sure what this header is called, "old T1 header"? Also not entirely sure whether it's always 256 bytes. @prusnak 
I also made some improvements to the usability of the tool.
> Strip old T1 header in firmware_hash.py

- core/.changelog.d/973.fixed
- core/embed/extmod/modtrezorio/modtrezorio-poll.h
- core/embed/unix/common.c
- core/embed/unix/common.h
- core/embed/unix/touch.c
Emulator will only process quit signals (close window, ctrl+c, Esc) when polling for SDL events.
SDL events are only polled while the emulator is waiting for **user interaction**.
There are a lot of situation when emulator is NOT actually waiting for user interaction. Usually these will occur in the middle of something like a signing flow, when the firmware is expecting USB events but not user events. Such situation can also occur by programmer error.
(this is the inverse of incorrect use of `await layout_obj` instead of `await ctx.wait(layout_obj)`, where the firmware would wait for touch but not for USB events)
This PR inserts an explicit "poll for emulator events" into `trezorio.poll` so that we have a higher chance to react in more situations.
(if the poll event loop stops, we are in …
> Make sure emulator can be shut down while waiting

- python/src/trezorlib/toif.py
When a grayscale icon with odd-width is provided, the conversion ends up with the following error:
``` python
File ".../trezor-firmware/python/src/trezorlib/toif.py", line 70, in _from_pil_grayscale
left, right = pixels[i], pixels[i + 1]
IndexError: image index out of range
```
The rendering code also assumes that provided icons are even-width.
Let's check this before conversion takes place.
Last, but not least, I checked and there are no icons with odd width in the repository.
> fix(python): only even-width grayscale icons are supported

- ci/build.yml
- docs/ci/jobs.md
This fixes the build job of arm emulators to run on tagged branches. Meaning the deployment after release should pass after this. I also changed the image to upstream nixos one as the issues with the old one were fixed.
> ci: update arm jobs to run on tags and use the official nix image

- common/protob/messages-cardano.proto
- common/protob/messages.proto
- core/src/trezor/enums/MessageType.py
- core/src/trezor/enums/__init__.py
- python/src/trezorlib/messages.py
Since Connect's `cardanoSignTransaction` will drop support for firmware versions <2.4.2 that do not support transaction streaming ([PR](https://github.com/trezor/connect/pull/1087)), it should be safe to remove the legacy protobuf types.
> chore(cardano): remove legacy types

- common/defs/wallets.json
- common/tools/coin_info.py
- common/tools/cointool.py
Connected with https://github.com/trezor/trezor-firmware/issues/2278:
- add wallet support for `common/tools/cointools.py dump` command
The goal was for `cointool.py dump` to generate the same wallet data as in `coins_details.json`. To test it, I created a small [snippet](https://gist.github.com/grdddj/c253bd9346081bf40c8ea9afbefc2582) for comparing these two ( `python cointool.py dump -o new.json -p --list` must be run beforehand to generate the new report). It passes fine, except for `eth:AUX` and `eth:XDC`, which however have exceptions in `coins_details.override.json`. (should we also look at `coins_details.override.json`?)
Also, the actual `dump` command itself got (hopefully) a little improved and documented.  
Before doing the actual new feature, I wanted to add type-hints to both …
> Cointool improvements, wallet data

- Makefile
- ci/test.yml
- common/tools/coin_info.py
- docs/ci/jobs.md
- tests/test_python_support.py
- tools/generate_ci_docs.py
- tools/pyright_tool.py
Fixes #2305:
- modifying type hints so that even older (`3.7` and `3.8`) python versions understand it
- also the test for this was created and added into `CI`
- it is currently in the `Test` stage, but could be probably moved to `Prebuild` thanks to its nature (it is not dependent on `Build` and it is very similar to `style prebuild`)
In [this CI](https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/pipelines/549800707) the tests should fail, as it only has the first commit with tests - it is "fixed" in [subsequent CI](https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/pipelines/549805580), so the difference can be seen.
> Type hints fixes for older python versions

- core/SConscript.firmware
- core/SConscript.unix
- core/embed/rust/Cargo.lock
- core/embed/rust/Cargo.toml
- core/embed/rust/src/trezorhal/bip39.rs
- crypto/Makefile
- crypto/bip39.c
- crypto/bip39.h
- crypto/bip39_english.c
- crypto/gui/gui.pro
- crypto/tests/test_check.c
- legacy/demo/Makefile
- legacy/firmware/Makefile
- legacy/firmware/recovery.c
For Trezor R, we need to be able to refine subsets of the wordlist, which is difficult to do without having the wordlist. We _could_ repeatedly call `mnemonic_get_word(i)` but that seems pointless.
Is there any particular reason the wordlist was not exposed in the original code?
tagging @andrewkozlik or @onvej-sl for review of the crypto-side changes
@mmilata and @grdddj for review of the Rust part
> Expose BIP-39 wordlist array from trezor-crypto to Rust code

- legacy/Makefile.include
- legacy/firmware/Makefile
- legacy/firmware/trezor.c
- legacy/oled.c
- legacy/oled.h
Fixes https://github.com/trezor/trezor-firmware/issues/2184
Before the change:
```
$ ls -l legacy/bootloader/bootloader-unaligned.bin 
-rwxr-xr-x 1 stick staff 31400 Mar 22 20:36 legacy/bootloader/bootloader-unaligned.bin
```
After the change:
```
$ ls -l legacy/bootloader/bootloader-unaligned.bin 
-rwxr-xr-x 1 stick staff 31276 Mar 22 20:32 legacy/bootloader/bootloader-unaligned.bin
```
Difference: -124 bytes
> fix(legacy): refactor oledInvertPixel to not use static bool variable, but ifdef constant

- ci/shell.nix
- core/src/apps/monero/signing/step_06_set_output.py
- core/tests/run_tests_device_emu_monero.sh
I was notified that Monero changed a BP+ result format in this PR: https://github.com/monero-project/monero/pull/8277
As it affects XMR transaction signing, we have to adapt to the change. Corresponding changes in the Trezor-client code in the XMR wallet are already incorporated in the https://github.com/monero-project/monero/pull/8299
I will send a testing binary once I manage to build it (should be soon).
PR is related to the:
- https://github.com/trezor/trezor-firmware/pull/2232
- https://github.com/trezor/trezor-firmware/pull/2219
- https://github.com/monero-project/monero/pull/8299
- https://github.com/monero-project/monero/pull/8277
> fix(xmr): Remove inv8 optimization as in xmr master

- core/embed/extmod/modtrezorui/display.h
- core/embed/rust/Cargo.lock
- core/embed/rust/Cargo.toml
- core/embed/rust/build.rs
- core/embed/rust/src/trezorhal/bip39.rs
- core/embed/rust/src/trezorhal/display.rs
- core/embed/rust/src/trezorhal/ffi.rs
- core/embed/rust/src/trezorhal/mod.rs
- core/embed/rust/src/trezorhal/random.rs
- core/embed/rust/src/trezorhal/slip39.rs
- core/embed/rust/trezorhal.h
Working off @jpochyla's commit from #2171, this replaces all manual ffi blocks with bindgen.
Also adds support for reading `TREZOR_MODEL` envvar in cargo.
> feat(core/rust): add trezorhal bindings

- core/.changelog.d/2297.added
- core/embed/extmod/modtrezorui/display-stm32_1.h
- core/embed/extmod/modtrezorui/display-stm32_R.h
- core/embed/extmod/modtrezorui/display-stm32_T.h
- core/embed/extmod/modtrezorui/display-unix.h
- core/embed/extmod/modtrezorui/display.c
- core/embed/extmod/modtrezorui/display.h
- core/embed/rust/src/trezorhal/display.rs
- core/embed/rust/src/ui/display.rs
Exposing to Rust functions needed for raw pixel access: pixeldata, pixeldata_dirty and set_window
Solves #2297
> Expose raw pixel access to rust

- tools/check-bitcoin-only
#2336 added cloudflare, since there is a coin named 'flare', this causes bitcoin only check to fail. added 'cloudflare' to exceptions.
> Fix bitcoin only pipeline check

- core/.changelog.d/2300.added
- core/SConscript.boardloader
- core/SConscript.bootloader
- core/SConscript.firmware
- core/embed/bootloader/.changelog.d/2300.added
- core/embed/bootloader/main.c
- core/embed/bootloader/memory.ld
- core/embed/bootloader/messages.c
- core/embed/firmware/main.c
- core/embed/rust/build.rs
- core/embed/rust/src/trezorhal/mod.rs
- core/embed/rust/src/trezorhal/rgb_led.rs
- core/embed/rust/trezorhal.h
- core/embed/trezorhal/rgb_led.c
- core/embed/trezorhal/rgb_led.h
- core/embed/unix/rgb_led.h
This implements RGB LED driver for model R, makes LED initialization in bootloader and firmware and exposes relevant functions to rust. 
Added small SRAM section to bootloader in order to be able to use DMA. Had to also add compiler flag to distinguish boardloader/bootloader/firmware to place DMA buffer correct section.
Fixes #2300
> RGB LED driver for model R

- core/embed/extmod/modtrezorcrypto/modtrezorcrypto-ed25519.h
- crypto/bip32.c
- crypto/ed25519-donna/README.md
- crypto/ed25519-donna/ed25519-keccak.h
- crypto/ed25519-donna/ed25519-sha3.h
- crypto/ed25519-donna/ed25519.c
- crypto/ed25519-donna/ed25519.h
- crypto/fuzzer/fuzzer.c
- crypto/nem.c
- crypto/tests/test_check.c
- crypto/tests/test_check_cardano.h
- crypto/tests/test_speed.c
- legacy/firmware/stellar.c
Resolves https://github.com/trezor/trezor-firmware/issues/2338.
> Remove public key from the ed25519 signing API

- ci/shell.nix
- core/.changelog.d/2232.added
- core/src/apps/monero/signing/step_06_set_output.py
- core/tests/run_tests_device_emu_monero.sh
- core/tests/test_apps.monero.crypto.py
Adds support for view-tags https://github.com/monero-project/monero/pull/8061, new HF15 feature that was missing in the recent PRs. @selsta pinged me with this missing feature https://github.com/monero-project/monero/pull/8299#issuecomment-1160510870
As wallet is using view_key to derive view tags, tx receiving code on the wallet side does not require changes. 
PR is related to the:
- https://github.com/trezor/trezor-firmware/pull/2232
- https://github.com/trezor/trezor-firmware/pull/2219
- https://github.com/monero-project/monero/pull/8299
- https://github.com/monero-project/monero/pull/8061
> fix(xmr): add missing view_tags to hf15

- ci/test.yml
- core/embed/rust/src/trezorhal/bip39.rs
- docs/ci/jobs.md
by using `cstr!` to generate 0-terminated strings
> Fix overflow in bip39.rs tests

- ci/test.yml
- tests/connect_tests/connect_tests.sh
Allowing the `Connect` tests to run again in `CI`.
- "fixing" the situation on our (CI server) side - changing `localhost` to `127.0.0.1` as a `tenv`'s websocket address - because the CI servers could not resolve `localhost`
- we could change it in `Connect` code, but I think there is no need - our servers are "broken", not the `Connect` side
- slightly changing the logic of patching the emulators - using `autoPatchelf` directly from the `tenv`'s `nix-shell` - change in `tenv` necessary
- TODO: remove the `:185` image tag from `tenv` once [this tenv PR](https://github.com/trezor/trezor-user-env/pull/185) gets merged
There are still 24 failing tests - see [last CI](https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/2661501018) - but these are not `CI` issues, but some …
> fix(ci): make Connect tests run properly in CI

- crypto/bip39.c
- Fixes a possible out-of-bounds-read bug that was introduced in https://github.com/trezor/trezor-firmware/commit/61adb0a62b5cb0566b5bb5733091d86947731896.
- Replaces linear search of the wordlist in `mnemonic_to_bits()` with a binary search.
> Fix bip39 out of bounds read

- ci/shell.nix
> chore(nix): don't install autoPatchelfHook on MacOS

- core/src/apps/bitcoin/sign_tx/approvers.py
- core/src/apps/bitcoin/sign_tx/tx_weight.py
Implements https://www.notion.so/satoshilabs/Add-dust-upper-bound-to-Trezor-CoinJoin-checks-f1265e781d6847f49b2f0029401339b0.
> Account for minimum registrable output amount in CoinJoin checks

- core/.changelog.d/2130.changed
- core/.changelog.d/2130.removed
- core/embed/bootloader/main.c
- core/embed/firmware/main.c
- core/embed/trezorhal/touch.c
This PR partially reintroduces touch controller initialization in firmware:
- turns out that if we want to change operation mode of the controller in future, we might have issues when settings from bootloader being incompatible with algorithm used in firmware - this could happen for example if new bootloader is used with intentionally downgraded firmware
- the removal of initialization also caused uninitialized i2c handler being used, which only accidentally didn't cause crashes due to fact that the touch_read function evaluated the uninitialized handler as being BUSY, and thus did I2C reset cycle, which fixed things - but this introduced some unnecessary delays
- this PR also fixes Model R firmware initialization, where some stuff wasn't called and some stuff was called twice or …
> Fix firmware initialization

- tools/check-bitcoin-only
Show an error string like in the example below on line 323. Otherwise it's not clear why the build failed.
> Add error message to check-bitcoin-only

- ci/build.yml
- ci/shell.nix
- docs/ci/jobs.md
Nixpkgs bump #2344 caused poetry to fail when old .venv is present: https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/2625709443. Currently in GitLab CI we cache .venv across builds on the same branch so master branch keeps failing.
The PR changes the cache key so that the cache is only shared by jobs with the same git commit. This makes the cache less effective but improves isolation of builds on long-lived branches.
> ci: only use .venv from gitlab cache if commit matches

- core/.changelog.d/2415.fixed
- core/src/apps/bitcoin/sign_tx/bitcoin.py
Fixes a bug in verifying external inputs in Taproot-only transactions. `self.external` is a `set`, not a `list`, so the external inputs might be walked through in non-sequential order, which results in `h_check` not matching `self.h_external_inputs`.
> Ensure correct order when verifying external inputs in BTC signing

- docs/misc/monorepo.md
As per [Notion discussion](https://www.notion.so/satoshilabs/Broken-Links-5771-66fdc1b727a048648aba5ae0cc3fc325) and [Suite issue](https://github.com/trezor/trezor-suite/issues/5771), there is a broken link on https://docs.trezor.io/trezor-firmware/misc/monorepo.html pointing at https://docs.trezor.io/create_monorepo.py, which does not exist - because it is a relative link.
Making that link to `create_monorepo.py` absolute so it can be accessed even on `docs.trezor.io`
> fix(docs): make create_monorepo link absolute to work on docs.trezor.io

- core/.changelog.d/262.added
- core/embed/bootloader/.changelog.d/262.added
- core/embed/trezorhal/touch.c
This PR optimizes polling the touch controller by only polling when new data are ready, which significantly reduce cpu load when touch is active. 
Also removed the duplicate data detection, with reasoning that previously we filtered this out because we were literally polling the same data multiple times until new data were ready. We might still receive new data with same values though, not sure we would ever find this useful, so maybe the filtering should stay?
This could be also taken a bit further, using interrupts and DMA we could probably offload most of the work to peripherals, but it brings some issues to solve like polling done in the background even when no one wants the data, possibly synchronizing the access to the read buffer, and introducing new interrupt(s) brings some …
> Optimize touch controller polling

- core/.changelog.d/2427.added
- core/embed/bootloader/.changelog.d/2427.added
- core/embed/bootloader/memory.ld
- core/embed/firmware/main.c
- core/embed/firmware/memory_1.ld
- core/embed/firmware/memory_1_min.ld
- core/embed/firmware/memory_T.ld
- core/embed/firmware/startup.S
- core/embed/trezorhal/supervise.h
Moved stack to the start of RAM in bootloader & firmware. In case of stack overflow, this causes MemManage fault with properly configured MPU.
Since inside the MemManage handler stack is out of bounds, the error display function does not work, so i changed the handler so it resets the MSP. I think it might be handy to see whether the fault is stack overflow or some other MM, so i check this and show different error on the display inside the handler - not sure it't the right approach though. (this paragraph applies to FW only)
> Introduce stack overflow detection by moving stack to the start of RAM

- ci/deploy.yml
- docs/ci/jobs.md
Fixes the job deploy emulators to aws which causes jobs on tag to not run, this should solve the error.
> ci: fix data deploy job for release

- common/protob/messages-management.proto
- common/protob/messages.proto
- core/.changelog.d/2445.added
- core/src/all_modules.py
- core/src/apps/base.py
- core/src/apps/homescreen/busyscreen.py
- core/src/storage/cache.py
- core/src/trezor/enums/MessageType.py
- core/src/trezor/enums/__init__.py
- core/src/trezor/messages.py
- legacy/firmware/protob/Makefile
- python/.changelog.d/2445.added
- python/src/trezorlib/cli/device.py
- python/src/trezorlib/device.py
- python/src/trezorlib/messages.py
- tests/device_tests/test_busy_state.py
- tests/ui_tests/fixtures.json
This PR implements a new `SetBusy` message in `core` which causes Trezor T to show a "Do not disconnect" screen instead of the standard homescreen or lockscreen. Suite will need to display this screen at the moment before it commits to participate in a CoinJoin round. The message should appear for about 2 minutes, after which the CoinJoin transaction will be signed. During these two minutes Trezor is just waiting for the signing phase. It is possible for other operations to be called, but UI workflows should be discouraged, because if the UI workflow is running when Suite needs to sign the CoinJoin, then the workflow will be interrupted. Applications should check the `busy` parameter in `Features` and prevent the user from launching a UI workflow if `busy == True`, e.g. by disabling the …
> Add busy screen

- ci/shell.nix
- core/SConscript.firmware
- docs/core/build/emulator.md
We require nightly Rust compiler for the panic_immediate_abort feature of core libraries. This feature will compile all panic!s into a single fault instruction, which saves significant amount of space.
For now, we are not using any nightly code features. But now that we need nightly Rust anyway, we can start.
supersedes #2460 , branch rename so that we get HW tests on this
> Switch to nightly Rust 

- core/embed/rust/src/trezorhal/uzlib.rs
- core/embed/rust/src/ui/display.rs
Fixing window allocation problem in Uzlib. Pins window location on stack.
> Fix uzlib window allocation in rust

- core/Makefile
- poetry.lock
- pyproject.toml
- python/src/trezorlib/_internal/emulator.py
- tests/conftest.py
- tests/emulators.py
Addresses https://github.com/trezor/trezor-firmware/issues/2432:
- add options to run device tests in parallel, with `make` commands like `test_emu_multicore` or `test_emu_ui_record_multicore`
- is for local purposes only, the `CI` still runs the "normal" serial tests
It does it using the suggested [pytest-xdist](https://pypi.org/project/pytest-xdist/), and running `pytest` with `-n auto` for using as many processes as possible.
The whole test suite finished in under 5 minutes for the simplest `test_emu_multicore`. The other versions including `UI` checks take longer.
Seems to be working fine with the `UI` tests, no changes needed to be done on that front.
Theoretically it can slow down the "normal" tests, as now the `_raw_client` fixture is not valid for the whole session, but is …
> feat(tests): add possibility to run device/UI tests in parallel

- ci/test.yml
- tests/.gitignore
- tests/connect_tests/connect_tests.sh
Connected with https://github.com/trezor/trezor-firmware/issues/2295:
- updating `connect` tests to account for their move into `Suite` monorepo
> Migrate connect tests

- core/embed/trezorhal/usb.c
Linux has by default 2 seond autosuspend for USB devices. This means on PCs with autosuspend supported, TT showed "USB NOT CONNECTED" when entering suspend.
We now treat switching to USB suspended from configured state as still connected.
This will still work for people plugging TT into charger or using cable without data pins to alert them.
> Do not show "USB NOT CONNECTED" if device enters USB suspend state

- core/embed/rust/src/micropython/buffer.rs
- core/embed/rust/src/protobuf/decode.rs
- core/embed/rust/src/protobuf/encode.rs
This PR adds the possibility of allocating strings on the GC heap -- useful whenever we need to perform some string manipulations and pass the results into a `StrBuffer`-based UI structure.
Example:
```rust
let somestr = String::<50>::new();
somestr.push_str("hello");
somestr.push_str("world");
let strbuf = StrBuffer::alloc(somestr.as_str())?;
```
---
This also removes the `Buffer` struct, because it is difficult to build it safely:
- in case of python `memoryview`s, an interior pointer would be stored as `ptr`
- it is difficult to get to the head pointer, because `get_buffer_info` does not return it and the original `Obj` is not it: the data pointer from, say, a `bytearray` object, might get reallocated between `Buffer` construction and use, so the `Buffer` stores stale pointer data.
If …
> StrBuffer::alloc

- legacy/firmware/config.c
- legacy/firmware/fsm.h
- legacy/firmware/fsm_msg_crypto.h
Added `fsm_clearCosiNonce()` to `config_wipe()` to fix CI issues with `test_cosi_nonce`. To reproduce the failing test run:
```
pytest -k test_cosi_pubkey -s --ui=test
pytest -k test_cosi_nonce -s --ui=test
```
i.e. `test_cosi_pubkey` needs to run immediately before `test_cosi_nonce` and UI tests need to be active in order for reseeding to be taking place. The reason why the test fails is https://github.com/trezor/trezor-firmware/blob/77cdf4b43c8630878b8fb8ad4c362ba2a7ed5a47/legacy/firmware/fsm_msg_crypto.h#L274
which allows the nonce to persist between tests if it is not depleted by a `cosi.sign()` call, which it's not in `test_cosi_pubkey`. There was some rate-limiting rationale for not generating the nonce every time: https://github.com/satoshilabs/trezor-firmware/pull/154/files#r907239 …
> Clean up T1 state in config_wipe()

- tests/connect_tests/connect_tests.sh
This test expect actual firmware to have been released. At the moment version is set to 2.5.3 but it has not been released yet. So I suggest that we exclude this test from running in firmware repo.
> ci(connect): exclude checkFirmwareAuthenticity test

- core/embed/firmware/main.c
The handlers were already there, this just enables them, which helps debugging the faults as you get different error message (hard fault occurs otherwise)
> Enable bus fault and usage fault handlers in core

- legacy/Makefile
- legacy/bootloader/bootloader_flash.jlink
- legacy/firmware/firmware_flash.jlink
Add two commands for commandline flashing of T1 legacy bootloader and firmware with JLink.
Both commands are marked `.PHONY` so that it won't trigger rebuild, since (re)build needs to be done with `cibuild` script.
> Add Makefile commands to be able to flash T1 legacy bootloader and firmware via JLink

- core/embed/extmod/modtrezorio/modtrezorio.c
- core/embed/trezorhal/usb.c
- core/src/apps/homescreen/homescreen.py
- core/src/trezor/ui/__init__.py
- core/src/trezor/ui/components/tt/recovery.py
This fixes flashing USB DISCONNECTED ERROR by adding 2s grace period after usb disconnection is detected. 
Change detection logic is removed from homescreen as it this object is rectreated sometimes and than the logic fails, futthermore it was redundant to the polling mechanism.
Also the header warning does not clear entire screen when it get drawn/removed, which eliminates flickering of the avatar.
The grace period is not only on startup but after every disconnection, as i was getting some brief warnings when suite started up - somehow the USB was for a small amount of time in `USBD_STATE_DEFAULT`.
> fix flashing usb disconnected error

- core/embed/firmware/memory_T.ld
This PR redistributes content in flash a bit, so that all UI1 and UI2 on TT and TR can be linked. TT with UI2 and PYOPT=0 however does not fit, there just isn't enough space left in both sections to fit that right now. 
With logic that we are moving UI from python to rust, i moved the rust library into same section as python, so that overall size of that section is not changed too much when code is rewritten from py to rs.
closes #2417
> Redistribute contents in flash 

- python/.changelog.d/2517.added
- python/src/trezorlib/btc.py
- python/src/trezorlib/cli/btc.py
- tests/device_tests/bitcoin/test_authorize_coinjoin.py
Trezorlib shouldn't support preauthorized operations for `get_public_node()` and `get_address()`. I forgot to remove this code during code review of the SLIP-25 implementation. The Trezor function `get_public_key()` doesn't work with `DoPreauthorized`. The Trezor function `get_address()` should work with `DoPreauthorized`, but it's more natural to use `UnlockPath` instead.
No QA needed.
> Don't support preauthorized operations for get_public_node() and get_address() in trezorlib

- core/SConscript.unix
This PR fixes asan builds, which are broken since the introduction of num_derive crate.
> Fix ASAN build

- core/src/apps/base.py
- core/src/apps/common/request_pin.py
- core/src/storage/cache.py
- core/tests/test_storage.cache.py
The resolution of the `ticks_ms()` is 62 bits in unix builds. On the CI machines which run continuously for days the value can overflow the 4 bytes that are available for it in the storage cache. This could cause `test_busy_state` to fail randomly.
- I increased the size of `APP_COMMON_REQUEST_PIN_LAST_UNLOCK` and `APP_COMMON_BUSY_DEADLINE_MS` to 8 bytes.
- I also introduced `set_int()` and `get_int()` which automatically deal with the encoding/decoding of integers in the storage cache. One of the reasons why this was so hard to debug is that in micropython `int.to_bytes()` does not fail when the value cannot be encoded into the specified number of bytes.
> Fix bug in SetBusy when running CI tests

- core/tools/codegen/gen_keys.py
not sure why the python style checker decided to look at this file all of a sudden, but it did and it is failing our CI.
> chore(core): fix import in key generator

- core/emu.py
- python/.changelog.d/2547.added
- python/src/trezorlib/cli/debug.py
- python/src/trezorlib/cli/trezorctl.py
- python/src/trezorlib/debuglink.py
Connected with https://github.com/trezor/trezor-firmware/issues/2547:
- allowing for `trezorctl` specifying the directory where all the screen changes from emulator will be saved
There are two possibilities how to do that, each with a little different use-case:
1. Via `-r / --record` option directly in `trezorctl` command, so it can be used together with any other action - e.g. `trezorctl -r screenshots ping "Hello world" -b`. This allows for recording separate `trezorctl` actions.
2. Via separate `record` command - `trezorctl record screenshots`, it also allows for stopping the recording with `trezorctl record -s/--stop`. This will save all the screens from the current "session" - until the emulator does not die.
Both will do basically the same - create `screenshots` directory in current …
> feat(python): add trezorctl possibility to record screen changes

- core/embed/extmod/modtrezorio/modtrezorio.c
The check is used in all models in python, but was only exposed for TT so far, causing some exceptions.
> expose USB_CHECK for all models

- core/embed/rust/src/lib.rs
Something needs the symbol even though we don't do unwinding (I think):
```
/bin/ld: build/unix/rust/debug/libtrezor_lib.a(core-05898138a596088a.core.4cbccd39-cgu.0.rcgu.o):(.data.DW.ref.rust_eh_personality[DW.ref.rust_eh_personality]+0x0): undefined reference to `rust_eh_personality'
```
Defining one that does nothing seems to avoid the problem, not sure what happens when it actually gets called. Needs nightly rustc. Possibly related: https://github.com/rust-lang/rust/issues/56152, https://docs.rust-embedded.org/embedonomicon/smallest-no-std.html#eh_personality
> Workaround failing build_unix_debug

- core/embed/trezorhal/touch.c
This reintroduces touch event filtering at the driver level.
The previous removal (in https://github.com/trezor/trezor-firmware/pull/2412) caused that UI was spammed with same events when user was just holding, making the UI less responsive to other events, like timers.
> Re-introduce touch event filtering

- core/embed/rust/src/ui/display/mod.rs
- core/embed/rust/src/ui/model_tt/component/keyboard/common.rs
- core/embed/rust/src/ui/model_tt/component/keyboard/passphrase.rs
Connected with https://github.com/trezor/trezor-firmware/issues/2499:
- enabling longer passphrases up to 50 characters - the limit was already there, just handling all the edge cases and visuals
- also fixing the change of the character categories - previously the swipes were not changing the buttons, as the new buttons were not placed - there is a need to re-place them on each swipe
- we could solve it also by reusing the 10 already places buttons, and just changing the content of the buttons via `Button::set_content()` - in that case we would need to place them only once in the beginning and would not have to store the `PassphraseKeyboard::key_grid`, which is necessary for later placement
> feat(core/rust/ui): support longer passphrases

- common/protob/messages-bitcoin.proto
- core/.changelog.d/2577.added
- core/src/apps/bitcoin/authorization.py
- core/src/apps/bitcoin/sign_tx/approvers.py
- core/src/apps/bitcoin/sign_tx/bitcoin.py
- core/src/apps/bitcoin/sign_tx/decred.py
- core/src/apps/zcash/signer.py
- core/src/trezor/messages.py
- core/tests/test_apps.bitcoin.approver.py
- legacy/firmware/protob/messages-bitcoin.options
- python/src/trezorlib/messages.py
- tests/device_tests/bitcoin/payment_req.py
- tests/device_tests/bitcoin/test_authorize_coinjoin.py
- tests/device_tests/test_msg_applysettings.py
We decided to strengthen the security guarantees that will be provided by the signed affiliate data in CoinJoin. Due to these changes it is becoming a little more complicated to reuse the solution that is based on payment requests, although technically it could still be done if we wanted to. Payment requests are meant for individual outputs or sets of outputs in a transaction, whereas the affiliate data is now working with the entire set of inputs and outputs. I'd call this a "transaction request" and in this particular case a `CoinJoinRequest`. Since there is only one such transaction request per transaction it makes sense to put it into `SignTx`, which is what I did here.
There is an optional commit d54758415ea8fabf995cd8c21db255f33b4797ac that I could add, which adds a fee tolerance of …
> Implement CoinJoin requests

- core/embed/rust/src/ui/model_tt/layout.rs
I wonder if we should change `LayoutObj` so that it only wraps `Child<T>` as the top-level component. Or we can start returning `Child<SomeComponent>` from constructors like `SomeComponent::new`.
> fix(core/rust/ui): add missing Child wrappers

- core/embed/rust/src/ui/model_tt/component/keyboard/pin.rs
Fixes a bug introduced in https://github.com/trezor/trezor-firmware/pull/2567 , i missed that textbox needs clearing when warning timer expires
> fix(core/rust): fix prompt rendering over warning in pin keyboard

- common/protob/messages-nem.proto
- core/src/apps/nem/transfer/serialize.py
- core/src/trezor/messages.py
- python/src/trezorlib/_proto_messages.mako
- python/src/trezorlib/messages.py
Connected with https://github.com/trezor/trezor-firmware/issues/2527:
- add missing default value into creation of `protobuf.Field` in `python/src/trezorlib/messages.py`
There were two possible ways how to include the `default` kwarg :
1. when `field.default_value is not None`, as `None` is the "default-default" value
2. when `not field.required` - for all fields that do not enforce a value to be set
In the end, I chose `#2`, so seeing `default=...` is another sign that the field is not required.
> (Somewhat related, the Rust protobuf descriptors [wrongly decode](https://github.com/trezor/trezor-firmware/blob/master/common/protob/pb2py#L641) default=true as false)
I did not look into this, how can I replicate the issue?
> fix(python): add default value to protobuf.Field

- core/embed/rust/src/ui/layout/obj.rs
> UI2: avoid nested Child as LayoutObj root

- core/.changelog.d/2587.changed
- core/embed/boardloader/.changelog.d/2587.changed
- core/embed/boardloader/main.c
- core/embed/bootloader/.changelog.d/2587.changed
- core/embed/bootloader/main.c
- core/embed/firmware/main.c
- core/embed/trezorhal/common.c
- core/embed/trezorhal/stm32.c
- core/embed/trezorhal/stm32.h
Increases CPU frequency to 180MHz for TT (and models based on STM32F42x)
On TT: for compatibility between older firmware/new bootloader and vice versa when switching layers the frequency is returned to original 168MHz.
Other models: frequency is set in boardloader.
Also the configuration for F405 / 120MHz was wrong, so i fixed that (wasn't used anywhere since T1 isnt using core boardloader).
> Increase clock frequency to 180 MHz

- core/tests/run_tests_device_emu_monero.sh
Related to #2570. Also fixes shasum input format which requires two spaces on my system, hopefully it will work with two spaces with other implementations if there are any.
> fix(core/tests/monero): docker command line

- poetry.toml
We've been sticking to the old poetry installer because of https://github.com/python-poetry/poetry/issues/3199
But it seems the issue is gone now (fixed in poetry 1.1.6) and we can use the new (parallel) installer again.
Change was introduced in https://github.com/trezor/trezor-firmware/pull/1436 and this PR reverts it
<table>
<tr><th>machine</th><th>before</th><th>after</th></tr>
<tr><td>Intel Xeon Desktop</td>
<td>
```
$ time poetry shell
...
real	2m11.478s
user	1m43.056s
sys	0m9.334s
```
</td>
<td>
```
$ time poetry shell
...
real	0m32.622s
user	2m26.914s
sys	0m12.072s
```
</td>
<tr><td>Macbook Air M1</td>
<td>
```
$ time poetry install
...
real	1m13.131s
user	0m52.100s
sys	0m7.698s
```
</td>
<td>
```
$ time poetry install
...
real	0m22.092s
user	1m14.373s
sys	0m12.048s
```
</td> …
> build(poetry): use new (parallel) installer

- core/embed/extmod/modtrezorui/display-stm32_R.c
Given that on Model R we have a frame buffer, let's not push out pixels one by one.
Takes code from #2307 to dump the whole frame buffer at once.
> feat(core/model_r): only refresh screen on display_refresh

- common/defs/bitcoin/bcash.json
The default fees defined in `bcash.json` is an one-to-one copy of Bitcoin fees, which is _not_ correct.
As a Trezor user myself I **overpay** BCH fees in Trezor as well as losing some _privacy_ due to the high default fees.  
Thanks.
Best regards,
Melroy van den Berg
> Lower the default fees on Bitcoin Cash

- core/embed/rust/build.rs
- core/embed/rust/src/micropython/list.rs
While working on #2532 it turned out that this would be very useful. My guess is that there are several places in the codebase where it might come in handy.
> Expose micropython lists as slices

- core/.changelog.d/2595.changed
- core/embed/boardloader/.changelog.d/2595.changed
- core/embed/bootloader/.changelog.d/2595.changed
- core/embed/trezorhal/common.c
- core/embed/trezorhal/displays/st7789v.c
- core/embed/trezorhal/displays/st7789v.h
Increased PWM freq from 100Hz to about 4kHz. The TPS61043 driver has 100Hz to 50kHz range, the 100Hz minimum causes visible(sometimes, depends on what is shown on the display) and annoying blinking effect.
4kHz produces much better result. 
For compatibility purposes the setting is reset when switching layers. 
Builds on refactoring done in #2565
> Fix TT display blinking by increasing backlight PWM frequency

- core/embed/rust/src/micropython/buffer.rs
- core/embed/rust/src/ui/component/text/paragraphs.rs
- core/embed/rust/src/ui/layout/util.rs
- core/embed/rust/src/ui/model_tr/component/result_popup.rs
- core/embed/rust/src/ui/model_tt/component/dialog.rs
- core/embed/rust/src/ui/model_tt/component/number_input.rs
- core/embed/rust/src/ui/model_tt/component/page.rs
- core/embed/rust/src/ui/model_tt/layout.rs
Fixes #2665. It seems to me we actually can't implement indexing by ranges as the type signature is `fn index(&self, index: Idx) -> &Self::Output` but we need to return new StrBuffer value, not a reference.
We can't create new `StrBuffer` from stack data so I had to drop the scratch buffer handling (introduced in #2575), the hexadecimal representation is now written to GC-allocated buffer. We can't do hexadecimal conversion without StrBuffer but I guess that shouldn't be a problem.
> UI2: support StrBuffer slicing

- ci/test.yml
Lets allow it to fail for now until i figure it out. We are missing latest master builds in tenv due to this.
> chore(ci): temporary allow_failure for connect tests

- core/embed/rust/src/ui/model_tt/component/keyboard/bip39.rs
when the word is complete but also has some possible continuations like:
all / alley
mix / mixed
it was not recognized by the keyboard and input was not possible
closes #2677
> fix bip39 input not recognizing some words

- core/embed/trezorhal/displays/st7789v.c
Fixes settings of FMC - timing was too fast for the display driver, occasionally could cause packet loss.
> Fix model T FMC timing

- README.md
Changes the link from trezor.io/security to https://trezor.io/support/a/how-to-report-a-security-issue which is more concrete. We need to improve this further, but it will do for now as a "hotfix".
> Add link to trezor.io KB disclosure article

- build-docker.sh
It seems that bridge is not a good default because it does not always work out of the box.
see https://docs.docker.com/network/ for more info
edit: also [podman](https://podman.io) is a thing, so make it possible to override the docker command
> chore(build): use host network instead of the default (bridge)

- core/embed/firmware/main.c
Unfortunately the FMC timing fix #2698  introduced a bug that crashes firmware startup, because the FMC initialization accesses area of memory that is under MPU protection at that point.
> fix model T display reinitialization crash

- legacy/firmware/.changelog.d/2743.changed
- legacy/firmware/protob/messages-crypto.options
Following https://github.com/romanz/trezor-agent/issues/408.
> Increase 'SignIdentity.challenge_hidden' max_size to 512 bytes

- docs/legacy/index.md
This is needed for a successfull build for the legacy firmware as well (at least I had to on my machine)
> Specify --recurse-submodules as in core doc

- core/Makefile
- tests/conftest.py
- tests/ui_tests/.gitignore
- tests/ui_tests/__init__.py
- tests/update_fixtures.py
Some device tests usability improvements done in `model R` branch, but wanting to move them to `master`, as `model R` branch will not be there any time soon.
1. Possibility to accept the UI diff (change hashes in `fixtures.json`) after running tests with `--ui=test`, without having to call them again with `--ui=record`
- by `make test_emu_accept_fixtures`
- the quickest workflow is then `make test_emu_ui_multicore` to generate the UI diff as quickly as possible, and immediately update those changes by abovementioned command
2. Quickening the tests in CI by not generating `index.html` after each test case
- by the usage of `--not-generate-report-after-each-test` `pytest` flag
> Device test features

- python/.changelog.d/2745.changed
- python/src/trezorlib/cli/firmware.py
Fixes https://github.com/trezor/trezor-firmware/issues/2711:
- showing fingerprint even when the signatures are invalid
> feat(python): show fingerprint before signatures in `trezorctl firmware verify`

- core/.changelog.d/2746.changed
- core/src/apps/ethereum/sign_typed_data.py
- core/tests/test_apps.ethereum.sign_typed_data.py
Fixes https://github.com/trezor/trezor-firmware/issues/1909:
- removing the limitation of `EIP-712` message's fields to be smaller than 1024 bytes
> feat(core/ethereum): remove EIP-712 field size limitation of 1024 bytes

- common/tests/fixtures/ethereum/signmessage.json
- core/src/apps/bitcoin/keychain.py
- core/src/apps/common/paths.py
- core/src/apps/ethereum/keychain.py
- tests/device_tests/bitcoin/test_nonstandard_paths.py
Casa and other multisig providers have learned that the use of extensive key hardening causes usability issues. This is due to additional complexities that arise from having to coordinate the use of multiple geographically distributed keys. The degradation of user experience is not offset by any security improvements because the primary security of a multisignature wallet comes from preventing any given key from being a single point of failure. 
With that said, multisig coordinators should only need to harden up to the purpose path.
Mutlisig coordinators should sign at `m / 45' / coin_type / account / change / address_index`.
> refactor(core): Allow eth & btc signing at m / 45' / coin_type / account / change / address_index

- core/src/trezor/utils.py
This PR adds a simple tool to help debugging issues which involve incorrect digests being computed. The wrapper allows the developer to log what data the Trezor is hashing when computing the digest.
I don't know whether `utils.py` is the best place for this. I put it there, because `HashContext` and `HashWriter` are defined there. Possible alternatives:
1. Split off these hashing-related classes, including the new wrapper, into a separate file.
2. Introduce a file with debugging tools. There is `apps/debug/__init__.py`, but I think that's for handling debuglink messages.
> Add debugging tool for hashing operations

- core/embed/bootloader/messages.c
- core/embed/bootloader_ci/messages.c
fixes a bug recently introduced, causing installed firmware always evaluated as new.
> fix(core/bootloader): fix detection of installed firmware

- core/.gitignore
- core/Makefile
- core/SConscript.boardloader
- core/SConscript.bootloader
- core/SConscript.bootloader_ci
- core/SConscript.firmware
- core/SConscript.prodtest
- core/SConscript.reflash
- core/SConscript.unix
- core/site_scons/tools.py
- core/tools/make_cmakelists.py
Generates `CMakeLists.txt` automatically during compilation, respecting what is currently being build (eg. firmware/ bootloader/emulator) and other settings like model, bitcoin only etc. This enables IDE to correctly parse the C source code
@hiviah since you probably use this the most, let me know if this is useful to you and doesn't break your workflow somehow.
> automatic generation of CMakeLists

- ci/prepare_ui_artifacts.py
- core/Makefile
- python/src/trezorlib/debuglink.py
- tests/conftest.py
- tests/ui_tests/.gitignore
- tests/ui_tests/__init__.py
- tests/ui_tests/common.py
- tests/ui_tests/reporting/testreport.py
Fixes https://github.com/trezor/trezor-firmware/issues/2727
Introduces two new reports and one fix connected with UI tests:
- when accepting UI diff manually with `make test_emu_accept_fixtures`, also copying the content of `actual` dir into `recorded` to mimic what would happen in `--ui=record`
- possibility to save text layout as sent from `Rust` (debugging trace) with each `Debuglink` decision (corresponding to each screenshot) - saving as downloadable artifact under `screen_text.txt`
- allowing for a text search when looking for a test-case(s) where a certain string is appearing
- example output for `TT` below:
```
TT_eos-test_signtx.py::test_eos_signtx_buyram
< Homescreen label :  test >
////////////////////////////////////////////////////////////////////////////////
< Frame title : …
```
> New UI tests reports

- core/embed/rust/build.rs
- core/embed/rust/src/trezorhal/display.rs
- core/embed/rust/src/ui/component/image.rs
- core/embed/rust/src/ui/display/loader.rs
- core/embed/rust/src/ui/display/mod.rs
- core/embed/rust/src/ui/display/toif.rs
- core/embed/rust/src/ui/model_tt/component/fido_icons.rs
- core/embed/rust/src/ui/model_tt/component/fido_icons.rs.mako
- core/embed/rust/src/ui/model_tt/component/homescreen/render.rs
- core/embed/rust/src/ui/model_tt/component/keyboard/passphrase.rs
- core/embed/rust/src/ui/model_tt/theme.rs
Fixes #2779, related to #2708.
Size of `PassphraseKeyboard`:
* original: 4340 B
* after 24bcb74: 3668 B
* after 3487811: 2996 B
* after 6a4d470: 956 B
Not implemented:
* placement new (=construct object directly on micropython heap): seems tricky at the moment, would probably be feasible with global allocator
* further refactoring of `Button`: it's possible to reduce memory usage even further but the gains are not as big but with more effort
> core: fix stack overflow when displaying passphrase keyboard

- core/embed/extmod/modtrezorui/display_interface.h
- core/embed/rust/build.rs
- core/embed/rust/src/trezorhal/display.rs
- core/embed/rust/src/ui/display/mod.rs
- core/embed/rust/src/ui/layout/obj.rs
- core/embed/trezorhal/common.c
- core/embed/trezorhal/displays/st7789v.c
- core/embed/trezorhal/displays/ug-2828tswig01.c
- core/embed/trezorhal/displays/vg-2864ksweg01.c
- core/embed/unix/display-unix.c
Introduces `display_sync` function that synchronizes writing to display RAM with panel refresh. This is called before every relevant paint so that optimally the paint is done before the corresponding panel part is refreshed.
`display_orientation` function is modified so that the panel refresh direction respects the orientation. This is only possible for north and south orientation with current display driver. 
For west and east orientation, the display refresh direction is perpendicular to the orientation so the tearing effect prevention is not working and the effect is actually diagonal, but at least the display is synchronized so the UI should behave less randomly in this regard.
closes #2546 , builds on #2714
> tearing effect prevention improvement

- ci/test.yml
It has been failing for something like a year now? We deserve green pipelines
> ci: run `connect test core` manually

- ci/deploy.yml
- docs/ci/jobs.md
the master diff was failing in #2799 because of missing fixtures on the server.
those are in fact not actually deployed because the deploy job was not requesting results from the clicktest job
> build: also deploy click-test fixtures

- .gitlab-ci.yml
- ci/build.yml
- ci/deploy.yml
- ci/posttest.yml
- ci/prebuild.yml
- ci/test-hw.yml
- ci/test.yml
- docs/ci/jobs.md
Followup of #2816. Also remove `yaml prebuild` because it's a strict subset of `style prebuild`.
> ci: fix cached-nix-shell failure in hardware tests

- core/tests/test_apps.bitcoin.ownership_proof.py
See https://github.com/satoshilabs/slips/blob/master/slip-0019.md#test-vector-2-p2wpkh-nested-in-bip16-p2sh.
> Fix ownership proof unit test to match test vector 2 from SLIP-19

- tests/ui_tests/reporting/master_diff.py
Fixes https://github.com/trezor/trezor-firmware/issues/2799
There was a little mismatch in looping through the `same` testcases, because it also contained the `removed` cases - `master_tests.items() - removed_here.items()` did not work, as they had different keys - one with the `group` inside and one without it.
Also when we cannot find an arbitrary `actual` directory, defaulting to `recorded`, so that it can be run even after the `actual` directory is deleted (which happens every time a new UI-test suite is called).
Tested locally and as a part of https://github.com/trezor/trezor-firmware/pull/2803 - https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/3782160703
> fix(tests): make master_diff more reliable

- common/protob/messages-management.proto
- core/src/apps/base.py
- core/src/apps/common/passphrase.py
- core/src/apps/management/apply_settings.py
- core/src/storage/device.py
- core/src/trezor/messages.py
- python/src/trezorlib/cli/settings.py
- python/src/trezorlib/device.py
- python/src/trezorlib/messages.py
- tests/device_tests/test_session_id_and_passphrase.py
- tests/ui_tests/fixtures.json
Fixes https://github.com/trezor/trezor-firmware/issues/2598:
- adds the optional possibility of hiding the passphrase coming from host
Allows for changing this behavior by `trezorctl set passphrase hide {on,off}`.
It is currently hidden behind `safety checks`.
It is being shown in `Features` as `hide_passphrase_from_host: {True,False}`.
Trezorlib step-by-step flow I used when testing this:
- $ `trezorctl device wipe && trezorctl device load -s && trezorctl set pin`
- $ `trezorctl get-features | grep passphrase_protection` 
- `passphrase_protection: False`
- $ `trezorctl set passphrase on` 
- $ `trezorctl get-features | grep passphrase_protection` 
- `passphrase_protection: True`
- $ `PASSPHRASE=abc trezorctl -P btc get-address -n "84'/0'/0'/1/0"`
- shows `Next screen will show the …
> Hide passphrase from host

- common/defs/fido/google.json
- core/.changelog.d/2834.changed
- core/src/apps/webauthn/knownapps.py
Fixes https://github.com/trezor/trezor-firmware/issues/2205#issuecomment-1109755886 for Chrome. Tested on Linux and Mac.
> Force basic attestation in FIDO2 for google.com

- core/SConscript.firmware
Currently when executing `make build_firmware` without `BITCOIN_ONLY` set the resulting filename has `-btconly` even though it isn't.
> build(core): fix filename when BITCOIN_ONLY is unset

- core/.changelog.d/2841.added
- core/src/apps/management/reboot_to_bootloader.py
Fixes https://github.com/trezor/trezor-firmware/issues/2316:
- not needing experimental features to trigger reboot-to-bootloader functionality
> chore(core): enable reboot-to-bootloader without experimental features

- legacy/firmware/layout2.c
- tests/ui_tests/fixtures.json
Fixes https://github.com/trezor/trezor-firmware/issues/2638:
- show the taproot QR code smaller, but complete
> fix(legacy): show complete taproot QR code

- ci/hardware_tests/device/t1.py
- ci/test-hw.yml
The automation currently pushes yes button while the firmware is still being installed, probably because coinjoin and/or ethereum networks made the image larger. Also due to coinjoin we now run more tests so the job timeout needs to be increased.
Tested working in the private repo.
> ci: hardware: wait longer for T1 firmware to install

- core/embed/rust/src/ui/model_tt/component/welcome_screen.rs
Changed from 62 to 48 px. Before vs After
> chore(rust): decrease icon top margin on welcome screen to 48 px

- core/src/apps/webauthn/fido2.py
This should fix the missing logo reported in https://github.com/trezor/trezor-firmware/pull/2844#issuecomment-1443747492
> first FIDO2 screen does not display Google logo
For reasons stated in https://github.com/trezor/trezor-firmware/pull/2844#issuecomment-1443823464, it does not fix:
> you have to confirm login twice FIDO2 and then U2F
> Show app icon in Fido2ConfirmNoCredentials

- ci/test.yml
- core/.coveragerc
- core/Makefile
- core/prof/prof.py
- core/tools/coverage-report
- docs/ci/jobs.md
- docs/tests/ui-tests.md
- tests/conftest.py
- tests/emulators.py
Creating a draft from the experiments I tried.
The time-saving of all these changes _could_ be around 2-3 minutes per test, when nothing breaks.
WRT to `danger_no_wipe_device` marker, it is a really extreme measure, saves `0.1-0.2` seconds from each saved wipe-initialize cycle, but it takes some development time to try where it works and where not. 
Currently, the `skip_ui` option is not being used, as it made some UI tests break - but with some effort, it should be compatible.
> Faster device/UI tests

- ci/shell.nix
- core/tests/run_tests_device_emu_monero.sh
Improved Monero-Trezor test suite as occasionally passphrase-related bug reports have surfaced.
Tests revamp, always use passphrase flow with transaction signing, more passphrase-related tests, pin test, invalid passphrase test. Chain generation optimized. 
Using release: https://github.com/ph4r05/monero/releases/tag/v0.18.1.1-dev-tests-u18.04-02
Related to this PR: https://github.com/monero-project/monero/pull/8752
> chore: update trezor_tests binary

- .gitmodules
We don't use any ZKP features at the moment, so we might as well switch to upstream [secp256k1](https://github.com/bitcoin-core/secp256k1) which does stable releases now.
I am keeping the original submodule name and "zkp" in all integrations, because it seemed kind of pointless to try to rename/refactor everything, especially when we might want to switch back to secp256k1-zkp in the future.
This PR might cause some headaches with local checkouts, so `git submodule sync` might be in order.
> chore(vendor): replace secp256k1-zkp with secp256k1 (v0.3.0)

- core/.changelog.d/2899.fixed
- core/SConscript.bootloader
- core/SConscript.bootloader_ci
- core/SConscript.firmware
- core/SConscript.prodtest
- core/SConscript.unix
- crypto/Makefile
- crypto/rand.c
- legacy/Makefile.include
Fixes #2828 .
Bootloader now uses TRNG for `random32()`. The old opt-out misnomer definition `RAND_PLATFORM_INDEPENDENT` was changed opt-in `USE_INSECURE_PRNG` which needs to be specified explicitly to use predictable PRNG (for non-production code such as emulators).
> Fix bootloader using predictable PRNG. Fix build logic to make predictable PRNG opt-in, not opt-out

- core/embed/extmod/modtrezorui/buffers.h
Increasing the work buffer size a bit to make it more reliable.
> increase work buffer size for jpeg decompression

- core/embed/trezorhal/displays/st7789v.c
- core/embed/trezorhal/displays/ug-2828tswig01.c
Fixes initialization of FMC, where unitialized pointer could cause a write to invalid memory.
> fix(core): fix FMC initialization

- common/defs/fido/apple.json
- common/tools/coin_info.py
- common/tools/cointool.py
- core/.changelog.d/2784.fixed
- core/src/apps/webauthn/credential.py
- core/src/apps/webauthn/fido2.py
- core/src/apps/webauthn/knownapps.py
- core/src/apps/webauthn/knownapps.py.mako
Fixes #2784
Trezor T can't be used as an Apple security key, because the FIDO2 credentials are a bit larger than U2F credentials. Apple has some internal size limit on credentials and refuses to store them. As a result it's possible to use Trezor One as a security key with Apple, but not Trezor T. In this PR I introduce the `use_compact` option which reduces the amount of information stored in the credential to a minimum. After enabling this option for Apple, the FIDO2 registration works fine.
<s>Before merging @vdovhanych just needs to confirm that it works fine with `"use_sign_count": false`.</s>
> Enable Trezor to work as a FIDO2 authenticator for Apple.

- core/.changelog.d/2651.changed
- core/src/apps/base.py
- core/src/apps/bitcoin/sign_tx/bitcoin.py
- core/src/apps/debug/__init__.py
- core/src/storage/cache.py
- core/src/trezor/wire/__init__.py
- core/src/trezor/workflow.py
- python/src/trezorlib/debuglink.py
- tests/click_tests/test_autolock.py
- tests/device_tests/test_autolock.py
- tests/ui_tests/fixtures.json
~~Given the timeline and complexity I did not feel confident implementing the proposed solution of #2651. This PR introduces different solution which avoids touching the idle timer when processing message listed as allowed to be processed when device is locked.~~
~~The disadvantage is that with unfortunate timing the autolock interrupts coinjoin signing if there's one in progress.~~
Fixes #2651.
> core: prevent USB events from waking autolock timer

- tests/device_tests/test_autolock.py
On _hardware_ this test is often failing, both on CI and my machine. After changing the wait time to 8s the test passes 20+ times in a row on my machine.
> tests: tweak wait time for test_autolock_ignores_getaddress

- core/embed/rust/src/ui/model_tt/component/homescreen/mod.rs
- core/embed/rust/src/ui/model_tt/component/homescreen/render.rs
Support is added for non-square full-screen homescreen image
> support differently sized homescreen

- core/tools/alloc.py
Done as a secondary product of researching allocation differences between UI1 and UI2:
- typing improvements
- moving from custom-HTML creation into using `dominate`
- color highlights of most allocated lines
- list of most allocated lines
Comparison made between current `master` and `release/22.11` branches.
Steps (inspired by `core unix memory profiler` CI job):
- `TREZOR_MEMPERF=1 PYOPT=0 make build_unix_frozen`
- `TREZOR_MEMPERF=1 make test_emu`
- ... it takes a very long time ...
- `mkdir prof/memperf-html`
- `tools/alloc.py --alloc-data=src/alloc_data.txt html prof/memperf-html`
Results of the comparison:
- U1 data - https://grdddj.github.io/allocations_UI1/
- UI2 data - https://grdddj.github.io/allocations_UI2/
Note that the `Total allocations: XXX` is bigger in case of `UI1`, even …
> Improve allocation report

- common/protob/pb2py
- core/.changelog.d/2341.changed
- core/SConscript.firmware
- core/SConscript.unix
- core/embed/extmod/modtrezorconfig/modtrezorconfig.c
- core/embed/extmod/modtrezorcrypto/modtrezorcrypto.c
- core/embed/extmod/modtrezorio/modtrezorio-fatfs.h
- core/embed/extmod/modtrezorio/modtrezorio-flash.h
- core/embed/extmod/modtrezorio/modtrezorio-hid.h
- core/embed/extmod/modtrezorio/modtrezorio-sbu.h
- core/embed/extmod/modtrezorio/modtrezorio-vcp.h
- core/embed/extmod/modtrezorio/modtrezorio-webusb.h
- core/embed/extmod/modtrezorio/modtrezorio.c
- core/embed/extmod/modtrezorui/modtrezorui-display.h
- core/embed/extmod/modtrezorui/modtrezorui.c
- core/embed/extmod/modtrezorutils/modtrezorutils-meminfo.h
- core/embed/extmod/modtrezorutils/modtrezorutils.c
- core/embed/extmod/modutime.c
- core/embed/extmod/rustmods/modtrezorproto.c
- core/embed/extmod/rustmods/modtrezorui2.c
- core/embed/extmod/trezorobj.c
- core/embed/firmware/main.c
- core/embed/firmware/mpconfigport.h
- core/embed/firmware/mphalport.c
- core/embed/rust/qstr.h
- core/embed/unix/main.c
- core/embed/unix/mpconfigport.h
- core/site_scons/site_tools/micropython/__init__.py
- core/site_scons/site_tools/micropython/moduledefs.py
Current MicroPython patches: https://github.com/micropython/micropython/compare/v1.19.1...trezor:trezor-v1.19.1
Upstreamed micropython/micropython#10588, micropython/micropython#10589.
No changes in Rust bindings needed. Fixes #2341.
> chore(vendor): bump micropython to 1.19.1

- core/Makefile
- core/tools/combine_firmware
- core/tools/snippets/README.md
- core/tools/snippets/decombine.py
Improved the `combine_firmware` script to make it easier to manually pass the parts from outside.
Added a "decombine" snippet that can take apart the result, so that, e.g., we can pull out the boardloader from a previous version instead of having to compile it from the current code version.
> Firmware combining tweaks

- ci/shell.nix
This makes it possible to start the shell however build still fails: https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/4182963058
> Update to clang-14 to fix nix-shell on darwin

- core/SConscript.bootloader_emu
the https://github.com/trezor/trezor-firmware/pull/2912 refactoring moved some files and didn't address bootloader emu which was introduced in meantime
> fix bootloader emulator compilation

- ci/build.yml
- docs/ci/jobs.md
- storage/tests/c/flash.c
- storage/tests/c0/flash.c
#3005 caused clang to be used instead of gcc in some CI jobs. I modified the storage test to also work with clang and forced the use of gcc in the crypto test - it could work with clang but needs to be run as `LD_PRELOAD=/path/to/libclang_rt.asan-x86_64.so ITERS=10 pytest tests`.
Passing jobs:
* https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/4295068658
* https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/4295068687
> ci: fix crypto test, storage test

- ci/deploy.yml
- ci/posttest.yml
- ci/test.yml
- docs/ci/jobs.md
Fixes https://github.com/trezor/trezor-firmware/issues/3066
- add UI report into `TR` device tests
Fixes https://github.com/trezor/trezor-firmware/issues/3070
- add `TR` into `master-diff`
We should merge this before all other `TR` PRs, because this will upload all the missing screens (click tests) from `master`, so other PRs will have full `master-diff`
> T2B1 CI fixes

- core/embed/trezorhal/touch/ft6x36.c
Do i2c cycle also if one of the initialization commands fail. 3 tries before fatal error.
> improve touch driver robustness

- core/embed/rust/Cargo.toml
- core/embed/rust/build.rs
- core/embed/rust/src/lib.rs
- core/embed/rust/src/micropython/iter.rs
- core/embed/rust/src/micropython/list.rs
- core/embed/rust/src/micropython/obj.rs
- core/embed/rust/src/micropython/qstr.rs
- core/embed/rust/src/micropython/testutil.rs
- core/embed/rust/src/micropython/typ.rs
- core/embed/rust/src/protobuf/encode.rs
- core/embed/rust/src/ui/component/text/op.rs
- core/embed/rust/src/ui/layout/util.rs
- core/embed/rust/src/ui/model_tr/layout.rs
- core/embed/rust/src/ui/model_tt/layout.rs
Fixes test failure in nightly ASAN jobs by disabling Micropython's built-in stack checking in the Rust test suite (where we don't actually need it for anything).
That is commit 81051d1368855e7cb88453d92e79c8ce9108bc9d, the rest is just gravy.
Namely:
17e25c60cab78b0b11a4e35fdfa4f54d0707fab1 allows easier examination of arbitrary `Obj`s, in particular in debug builds where you can retrieve the name of the type.
3f228c368e61e392830e2d31e7c6d7cef5c72f81 moves the iteration method from `Iter` to `IterBuf`, streamlining from:
```
let mut iter_buf = IterBuf::new();
let iter = Iter::try_from_obj_with_buf(obj, &mut iter_buf)?;
for x in iter { ... }
```
to:
```
for x in IterBuf::new().try_iterate(obj)? { ... }
```
0cc15629e853c3c1646312c27cc9b4a332d9d1b9 fixes an oversight that prevented our …
> Iter changes

- core/embed/rust/src/ui/display/toif.rs
- core/embed/rust/src/ui/macros.rs
- core/embed/rust/src/ui/model_tt/component/welcome_screen.rs
emitted when compiling bootloader or TT
> fix rust compilation warnings

- core/SConscript.bootloader_emu
- core/embed/rust/src/ui/display/mod.rs
broken by the recent backlight refactoring
> fix TT bootloader emulator backlight, fix rust warning

- .github/workflows/fixup_check.yml
- .github/workflows/prebuild.yml
was going trough some repositories and updating some of the actions, this only updates checkout as we do not have that much in here.
> chore: update actions checkout version

- python/docs/EXAMPLES.rst
The derivation path format of Bitcoin/0h/0/0 is out of date. Updating to m/84h/0h/0/0 format.
> Update derivation path format in the example

- ci/prepare_ui_artifacts.py
- core/Makefile
- tests/conftest.py
- tests/ui_tests/.gitignore
- tests/ui_tests/__init__.py
- tests/ui_tests/common.py
- tests/ui_tests/reporting/common.py
- tests/ui_tests/reporting/master_diff.py
- tests/ui_tests/reporting/testreport.py
Fixes https://github.com/trezor/trezor-firmware/issues/3099:
- mostly code reorganization (moving things to `common.py`) to allow creating master-diff report after each individual UI test
- each UI test will have `master_diff.html` in the main report dir
- added new `--do-master-diff` `pytest` option to do this (`False` by default)
- master screens are being cached locally in `tests/ui_tests/reporting/master_cache` to allow for quick results and less traffic
> feat(tests): running master-diff report after each UI test

- .clusterfuzzlite/Dockerfile
- .clusterfuzzlite/build.sh
- .clusterfuzzlite/project.yaml
- .github/workflows/cflite.yml
This PR adds [ClusterfuzzLite](https://google.github.io/clusterfuzzlite/) which runs the crypto fuzzer when PRs are made. 
ClusterfuzzLite  can be extended beyond this PR with code coverage and batch fuzzing: https://google.github.io/clusterfuzzlite/running-clusterfuzzlite/github-actions/
Signed-off-by: AdamKorcz <Adam@adalogics.com>
> Run fuzzer in CI

- rust/trezor-client/Cargo.toml
This PR updates the Manifest Data for `trezor-client` crate to reflect the recent changes in the registry.
Bumps version of trezor-client to 0.1.1.
> feat(rust): update trezor-client crate metadata

- rust/trezor-client/Cargo.lock
- rust/trezor-client/Cargo.toml
Followup to https://github.com/trezor/trezor-firmware/pull/3137
When trying to publish the create I noticed the Cargo.lock file hasn't been updated - run `cargo build` to update the crate version in the lock file.
Also updated the authors section to match reality.
Once this is merged I will tag the commit and publish the trezor-client v0.1.1 crate.
> feat(rust): update trezor-client crate metadata + run cargo build

- ci/test.yml
- docs/ci/jobs.md
- tests/gitlab.py
- tests/show_results.py
- tests/ui_tests/.gitignore
- tests/ui_tests/__init__.py
- tests/ui_tests/common.py
- tests/update_fixtures.py
Fixes https://github.com/trezor/trezor-firmware/issues/3052:
- saving `fixtures.results.json` file with the UI hashes of all the tests that were running in a specific test-pipeline
- allowing to download all the CI results and refresh the local `fixtures.json` with a simple script - `python tests/update_fixtures.py ci`
Also found out why the `fixtures.suggestion.json` is not being generated anymore - it requires that some tests are not being run - `if test_ui == "test" and check_missing and list_missing()` ... we might want to change this probably
> Get UI fixtures from CI

- core/embed/trezorhal/stm32f4/displays/vg-2864ksweg01.c
replace systick based wait in display SPI with loop as systick does not work in fault handlers, hence the rendering gets stuck
> replace systick based wait in display SPI with loop

- core/embed/trezorhal/stm32f4/mpu.c
> fix MPU settings

- tests/ui_tests/reporting/html.py
- tests/ui_tests/reporting/testreport.py
Fixes https://github.com/trezor/trezor-firmware/issues/3118:
- prepares the UI tests for automatic retrieval of specific images and allows for linking to a given screen
The mapping itself and the application/dashboard code are currently stored at https://github.com/grdddj/figma_ui repository
The app itself is running under https://figma.grdddj.eu
> feat(tests): number the screens in UI test reports, give unique IDs to images

- core/SConscript.firmware
- core/embed/firmware/main.c
- core/embed/trezorhal/boards/trezor_r_v10.h
- core/embed/trezorhal/optiga/optiga_commands.c
- core/embed/trezorhal/optiga/optiga_transport.c
- core/embed/trezorhal/optiga_commands.h
- core/embed/trezorhal/optiga_common.h
- core/embed/trezorhal/optiga_hal.h
- core/embed/trezorhal/optiga_transport.h
- core/embed/trezorhal/stm32f4/optiga_hal.c
- core/site_scons/boards/trezor_r_v10.py
Further work in this PR:
- <s>I am probably doing the initialization of the I2C interface wrong. There has been some refactoring recently around I2C, so that's not reflected in this PR. @TychoVrahe </s> (_Edit: Done_)
- <s>Maybe move the code to a subdirectory in `core/embed/trezorhal` such as `se` or `optiga`.</s> (_Edit: Done_)
Further work, that can be split into separate issues/PRs:
- <s>Not sure why I can't use the full capacity of the data register. See `OPTIGA_DATA_REG_LEN` in `transport.h`.  @TychoVrahe </s> (_Edit: Solved_)
- We will need to agree on how to integrate this with the emulator. My plan is to add a new file `optiga.h`, which will implement some higher level operations, such as `optiga_get_device_cert()` or `optiga_check_pin()`. Only these would be used by the firmware …
> Integrate OPTIGA Trust M

- python/src/trezorlib/log.py
this way logger is properly nested even when the library is used as submodule (e.g. HWI)
see https://github.com/bitcoin-core/HWI/pull/697
> nest logger in the proper way

- core/src/trezor/ui/layouts/tr/__init__.py
- tests/click_tests/test_tutorial.py
Fixes https://github.com/trezor/trezor-firmware/issues/3187:
- differentiates the case when the user cancels the tutorial, in comparison to successfully finishing it
> fix(core): raise ActionCancelled when cancelling tutorial flow for TR

- rust/trezor-client/src/transport/mod.rs
This is needed for async-hwi, where the struct Trezor is passed to async functions.
> feat(trezor-client): Add Sync and Send to Transport

- core/embed/bootloader/bootui.c
- core/embed/models/model_D001.h
- core/embed/rust/rust_ui.h
- core/embed/rust/src/ui/display/toif.rs
- core/embed/rust/src/ui/model_tr/bootloader/mod.rs
- core/embed/rust/src/ui/model_tt/bootloader/mod.rs
- core/src/apps/base.py
- core/src/apps/debug/__init__.py
- core/src/apps/management/apply_settings.py
- core/src/apps/management/recovery_device/homescreen.py
- core/src/apps/workflow_handlers.py
- core/src/trezor/ui/__init__.py
- core/src/trezor/ui/layouts/__init__.py
- core/src/trezor/ui/layouts/fido.py
- core/src/trezor/ui/layouts/homescreen.py
- core/src/trezor/ui/layouts/progress.py
- core/src/trezor/ui/layouts/recovery.py
- core/src/trezor/ui/layouts/reset.py
- python/src/trezorlib/client.py
- python/src/trezorlib/models.py
Design for 'unsafe, do not use' screen is updated. Part of the rendering is done in rust. The logic however stays in C. This has a disadvantage that the CONTINUE button is not highlighted in pressed state.
Also: 
- In micropython, the MODEL ifs are replaced with INTERNAL_MODEL
- in trezorctl the model is also derived from INTERNAL_MODEL field in features
> unsafe screen design for T2B1

- core/embed/trezorhal/unix/secret.c
(fixes bootloader_emu build because there was an error in the unix dummy impl)
> fix(core): use stm32f4 implementation of secret.c for unix too

- docs/core/build/embedded.md
- docs/core/build/emulator.md
Seems like `protoc` (the protobuf compiler binary) is now a required dependency to build the firmware and emulator. Following the instructions in `docs/core/embed.md`:
```
make vendor build_boardloader build_bootloader build_firmware
```
```
scons -Q -j 4 CFLAGS="-DSCM_REVISION='\"\x77\xf1\x37\x9d\xc8\x3c\xde\x21\xa8\x70\x37\x3c\x31\xd5\xe1\xca\xa6\xe6\x98\x62\"'" PRODUCTION="0" \
TREZOR_MODEL="T" CMAKELISTS="0" \
PYOPT="1" BITCOIN_ONLY="0" \
BOOTLOADER_QA="0" BOOTLOADER_DEVEL="0" build/firmware/firmware.bin
python ../common/protob/pb2py /home/user/src/conduition/trezor-firmware/common/protob/messages-binance.proto /home/user/src/conduition/trezor-firmware/common/protob/messages-bitcoin.proto /home/user/src/conduition/trezor-firmware/common/protob/messages-cardano.proto …
```
> docs(core): add protoc installation instructions

- python/.changelog.d/3227.fixed
- python/src/trezorlib/cli/firmware.py
print correct model in print_firmware_version
> print correct model in print_firmware_version

- core/embed/bootloader/bootui.c
- core/embed/bootloader/bootui.h
- core/embed/bootloader/main.c
- core/embed/bootloader/messages.c
- core/embed/bootloader/messages.h
Somehow we didn't add it with the last T2B1 bootloader changes. 
Also fixes residual "attestation present" wording. Especially the return message when failing to install might be a reason to add this to earliest production bootloader version, as its something a user see in trezorctl and suite can react to it too, so having two version might be annoying.
> add install restricted screen on installation with locked bootloader

- core/SConscript.boardloader
- core/SConscript.bootloader
- core/SConscript.bootloader_ci
- core/SConscript.bootloader_emu
- core/SConscript.firmware
- core/SConscript.prodtest
- core/SConscript.reflash
- core/SConscript.unix
Change build to use GNU11 standard instead of very old GNU99. Allows better compile time checks.
C and Rust binaries like boardloader, bootloader, prodtest are bit-by-bit identical. Firmware has same size, but I needed to check with binary diffing and testing to make sure compiler has not generating something weird.
> Change core builds to use GNU11 standard instead of GNU99

- core/embed/firmware/main.c
- core/embed/trezorhal/stm32f4/mpu.c
disable access to secret in flash after boot.
> disable access to secret in flash after boot

- common/protob/messages-management.proto
- core/SConscript.bootloader_emu
- core/embed/bootloader/emulator.c
- core/embed/bootloader/messages.c
- core/embed/bootloader/protob/messages.pb.h
- core/embed/bootloader/protob/messages.proto
- core/embed/extmod/modtrezorutils/modtrezorutils.c
- core/embed/trezorhal/secret.h
- core/embed/trezorhal/stm32f4/secret.c
- core/mocks/generated/trezorutils.pyi
- core/src/apps/base.py
- core/src/apps/management/authenticate_device.py
- core/src/trezor/messages.py
- core/src/trezor/utils.py
- python/src/trezorlib/messages.py
Resolves https://github.com/trezor/trezor-firmware/issues/3268, as discussed [here](https://github.com/trezor/trezor-firmware/pull/3255#discussion_r1324385328).
Adds `bootloader_locked` to `Features` message for Trezor Model R in both firmware and bootloader.
If the bootloader is unlocked, then `AuthenticateDevice` will return `ProcessError("Bootloader unlocked.")` before asking the user to confirm device authenticity check.
> Add bootloader_locked to Features

- core/Makefile
Since the recent vendor header changes, these commands were not usable with dev bootloader. I think that this is mostly used by devs so the check is not important, and the shortcut is handy.
> skip signature check for make_upload commands

- core/embed/bootloader/bootui.c
- core/embed/bootloader/emulator.c
- core/embed/rust/rust_ui.h
- core/embed/rust/src/ui/model_tr/bootloader/mod.rs
- core/embed/rust/src/ui/model_tr/component/result.rs
- core/embed/rust/src/ui/model_tt/bootloader/mod.rs
- core/embed/rust/src/ui/model_tt/component/error.rs
- core/embed/rust/src/ui/model_tt/component/result.rs
- moved the message composition to rust, had to adjust few things to satisfy lifetimes etc.
- positioning of the message is also fixed to better match the design
- one reconnect message is also fixed
> fix T2B1 "restarting in" label capitalization

- core/embed/rust/src/ui/model_tr/bootloader/confirm.rs
- core/embed/rust/src/ui/model_tr/bootloader/intro.rs
- core/embed/rust/src/ui/model_tr/bootloader/menu.rs
- core/embed/rust/src/ui/model_tr/component/address_details.rs
- core/embed/rust/src/ui/model_tr/component/button_controller.rs
- core/embed/rust/src/ui/model_tr/component/flow.rs
- core/embed/rust/src/ui/model_tr/component/homescreen.rs
- core/embed/rust/src/ui/model_tr/component/input_methods/choice.rs
- core/embed/rust/src/ui/model_tr/component/input_methods/number_input.rs
- core/embed/rust/src/ui/model_tr/component/input_methods/passphrase.rs
- core/embed/rust/src/ui/model_tr/component/input_methods/pin.rs
- core/embed/rust/src/ui/model_tr/component/input_methods/simple_choice.rs
- core/embed/rust/src/ui/model_tr/component/input_methods/wordlist.rs
- core/embed/rust/src/ui/model_tr/component/page.rs
- core/embed/rust/src/ui/model_tr/component/result_popup.rs
- core/embed/rust/src/ui/model_tr/component/show_more.rs
Fixes https://github.com/trezor/trezor-firmware/issues/3264:
- allows for longer `DELETE` press to delete the whole inputted content, not just one character - in `PIN` or `passphrase` inputs
> feat(core/rust): differentiate between short and long button press

- tests/device_tests/test_busy_state.py
Durations seems to work on T2B1 hardware. See also #3158.
> tests: tweak wait time for test_busy_expiry

- core/embed/rust/src/ui/model_tr/component/input_methods/wordlist.rs
- tests/ui_tests/fixtures.json
Fixes https://github.com/trezor/trezor-firmware/issues/3291:
- makes sure the letter always changes after selection in recovery flow
> Recovery shuffle letters in T2B1

- core/SConscript.bootloader_emu
- core/embed/bootloader/.changelog.d/3122.changed
- core/embed/bootloader/bootui.c
- core/embed/bootloader/bootui.h
- core/embed/bootloader/main.c
- core/embed/rust/rust_ui.h
- core/embed/rust/src/trezorhal/mod.rs
- core/embed/rust/src/trezorhal/secbool.rs
- core/embed/rust/src/ui/model_tr/bootloader/intro.rs
- core/embed/rust/src/ui/model_tr/bootloader/menu.rs
- core/embed/rust/src/ui/model_tr/bootloader/mod.rs
- core/embed/rust/src/ui/model_tt/bootloader/intro.rs
- core/embed/rust/src/ui/model_tt/bootloader/menu.rs
- core/embed/rust/src/ui/model_tt/bootloader/mod.rs
- core/embed/rust/src/ui/model_tt/bootloader/theme.rs
this was only triggered when bootloader does not detect valid firmware, therefore shows "get started with your trezor" screen, but at least firmware header is valid so bootloader asks for confirmation.
> fix erroneous shutdown when rejecting firmware upload

- core/SConscript.bootloader_emu
- core/embed/bootloader/main.c
- core/embed/firmware/main.c
- core/embed/trezorhal/common.h
- core/embed/trezorhal/optiga/optiga_transport.c
- core/embed/trezorhal/stm32f4/common.c
- core/embed/trezorhal/stm32f4/i2c.c
- core/embed/trezorhal/stm32f4/optiga_hal.c
- core/embed/trezorhal/stm32f4/supervise.h
- core/embed/trezorhal/unix/optiga_hal.c
- adds delays to physical layer
- resets the optiga via pin during initialization
> improve optiga communication reliability

- crypto/Makefile
- crypto/bignum.c
- crypto/bignum.h
- crypto/hash_to_curve.c
- crypto/hash_to_curve.h
- crypto/tests/test_bignum.py
- crypto/tests/test_check.c
This pull requests implements hashing to a curve that is compatible with the suite [`P256_XMD:SHA-256_SSWU_RO_`](https://www.rfc-editor.org/rfc/rfc9380.html#name-suites-for-nist-p-256) from RFC9380.
> Implement hashing to curve

- core/embed/rust/src/ui/component/marquee.rs
Fixes https://github.com/trezor/trezor-firmware/issues/3204:
- makes marquee to always take 2 seconds to animate from end to end (pause of 1 second persists)
- @Hannsek not sure what are the exact requirements for "behaving consistently" - but this way it works fine with the multisig xpubs titles
- It might now work so well with much shorter or much longer texts, but we should not use these extensively
> Fix marquee in T2B1

- legacy/intermediate_fw/trezor.c
I have removed redundant display initialization in the intermediate firmware on T1. This change should reduce the probability of display glitches described in issue #3308. However, please note that this is just a workaround, as the root cause of the problem is still unknown.
fixes #3308
> Remove redundant display initialization in the intermediate firmware on T1

- core/embed/rust/src/ui/model_tr/component/homescreen.rs
Fixes https://github.com/trezor/trezor-firmware/issues/3355:
- middle-click also unlocks the device from lock-screen (in addition to single left or right clicks)
> feat(core): make middle-click unlock the device for T2B1

- core/embed/bootloader/emulator.c
this adds nicer option parsing to `bootloader_emu`, with some usage documentation, and allows you to configure the bootloader to report as bitcoinonly device
> feat(core/bootloader_emu): add support for setting device variant

- core/embed/bootloader/.changelog.d/2794.added
- core/embed/bootloader/.changelog.d/2919.added
- core/embed/bootloader/.changelog.d/3205.added
- core/embed/bootloader/CHANGELOG.md
- core/embed/bootloader/version.h
Just generate a changelog and bump version. Commit 22e48717a67171b14de0bec0921cf9389bb3247f -- or what it ends up after merging -- will be tagged `core/bl2.1.4` for signing.
> Bootloader release 2.1.4

- core/CHANGELOG.T2B1.md
- core/CHANGELOG.T2T1.md
- docs/misc/changelog.md
- tools/generate-changelog.py
Fixes #3159. Not sure if we actually want the `CHANGELOG.XXXX.md` files but we should at least update the docs.
Rendered:
* [CHANGELOG.md](https://github.com/trezor/trezor-firmware/blob/mmilata/changelog-models/core/CHANGELOG.md)
* [CHANGELOG.T2B1.md](https://github.com/trezor/trezor-firmware/blob/mmilata/changelog-models/core/CHANGELOG.T2B1.md)
* [CHANGELOG.T2T1.md](https://github.com/trezor/trezor-firmware/blob/mmilata/changelog-models/core/CHANGELOG.T2T1.md)
> docs(core): differentiate changelog entries between models

- core/tools/size/compare_master.py
Changing the comparison branch (for CI artifacts) from outdated `master` to current `main`
> chore(core): replace master branch comparison with main branch

- core/Makefile
- core/SConscript.firmware
- core/embed/trezorhal/boards/trezor_r_v10.h
- core/site_scons/boards/trezor_r_v10.py
This is needed for hardware tests in CI until we figure out some way how not to trip up the security monitor by running testsuite. Only works with `PYOPT=0`.
> Add build flag for disabling Optiga

- core/SConscript.firmware
- core/embed/firmware/bl_check.c
- core/site_scons/tools.py
- tools/check-bitcoin-only
Save flash space: `SUMMARY: 63 rows, -38_400 bytes in total (L-38_424 D24).`
> compress embedded bootloader

- core/SConscript.bootloader_ci
- core/embed/bootloader_ci/messages.c
It builds now but I'm not able to test it. I'd be very grateful if somebody with a devkit can confirm that it always waits for firmware update after reboot and installs it without any user interaction.
> Fix CI bootloader build for T2B1

- core/embed/trezorhal/stm32u5/mpu.c
I've refactored MPU initialization routine to be more clear and maintainable. Now it's just a draft for further discussion.
> MPU initialization refactoring

- core/SConscript.bootloader_emu
- core/embed/boardloader/main.c
- core/embed/boardloader/memory_stm32u5a.ld
- core/embed/boardloader/startup_stm32u5.s
- core/embed/bootloader/main.c
- core/embed/bootloader/memory_stm32u5a.ld
- core/embed/bootloader/startup_stm32u5.s
- core/embed/bootloader_ci/memory_stm32u5a.ld
- core/embed/bootloader_ci/startup_stm32u5.s
- core/embed/firmware/main.c
- core/embed/firmware/memory_DISC2.ld
- core/embed/firmware/startup_stm32u5.S
- core/embed/prodtest/main.c
- core/embed/prodtest/memory_stm32u5a.ld
- core/embed/prodtest/startup_stm32u5.s
- core/embed/reflash/memory_stm32u5a.ld
- core/embed/reflash/startup_stm32u5.s
- core/embed/trezorhal/fault_handlers.h
- core/embed/trezorhal/stm32f4/fault_handlers.c
- core/embed/trezorhal/stm32u5/fault_handlers.c
- core/embed/trezorhal/stm32u5/limited_util.s
- core/embed/trezorhal/stm32u5/mpu.c
- core/embed/trezorhal/unix/fault_handlers.c
This pull request introduces better stack overflow protection for STM32U5 (Cortex-M33) by configuring the MSPLIM register and managing the UsageFault exception. The initial implementation utilizing MPU has been removed.
This change has a minor impact on older models since UsageFault and BusFault are now enabled in production firmware, bootloader, and the bootloader as well (`fault_handlers_init()` called in main()).
> Improve stack protection on STM32U5

- core/embed/rust/src/ui/display/toif.rs
- core/embed/rust/src/ui/model_tt/bootloader/mod.rs
- core/embed/rust/src/ui/model_tt/layout.rs
So that it correctly renders on the edge of display and such.
Also display_refresh calls are added in TT UI, as a preparations for models with displays that actually needs this. Shouldn't affect TT.
> add boundaries checks for icon rendering (framebuffer variant)

- core/embed/bootloader/emulator.c
- core/embed/extmod/modtrezorutils/modtrezorutils.c
- core/embed/trezorhal/flash.h
- legacy/flash.c
- legacy/flash.h
- legacy/intermediate_fw/trezor.c
- legacy/memory.c
- storage/flash_common.c
- storage/flash_common.h
should only be using `flash_area_xx` functions now - at least in core
> remove residual usage of old flash api

- core/embed/bootloader/messages.c
- core/embed/firmware/bl_check.c
- core/embed/firmware/main.c
- core/embed/trezorhal/flash.h
- core/embed/trezorhal/mpu.h
- core/embed/trezorhal/stm32f4/mpu.c
- core/embed/trezorhal/stm32u5/mpu.c
Adjusts bootloader upgrade mechanism to use bursts to ensure compatibility with U5.
> bld upgrade on U5

- rust/trezor-client/examples/sign_message.rs
The existing code fails (tested on Model T 2.6.0):
```
2023-11-25T15:52:06.035004Z TRACE trezor_client::client: Sending MessageType_SignMessage msg: SignMessage { address_n: [2147483648, 2147483648, 2147483649], message: Some([114, 101, 103, 101, 108, 32, 104, 101, 116]), coin_name: Some("Testnet"), script_type: Some(SPENDADDRESS), no_script_type: None, chunkify: None, special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }
2023-11-25T15:52:06.413333Z DEBUG trezor_client::client: Received failure: Failure { code: Some(Failure_DataError), message: Some("Forbidden key path"), special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }
thread 'main' panicked at …
```
> fix(rust/trezor-client): update `sign_message` example

- core/embed/rust/Cargo.lock
- core/embed/rust/Cargo.toml
- core/embed/rust/librust_qstr.h
- core/embed/rust/src/error.rs
- core/embed/rust/src/protobuf/error.rs
- core/embed/rust/src/trezorhal/storage.rs
- core/embed/rust/src/ui/display/toif.rs
- core/embed/rust/src/ui/layout/util.rs
- core/embed/rust/src/ui/model_tr/component/homescreen.rs
- core/embed/rust/src/ui/model_tr/component/mod.rs
- core/embed/rust/src/ui/model_tr/layout.rs
- core/embed/rust/src/ui/model_tt/component/homescreen/mod.rs
- core/embed/rust/src/ui/model_tt/component/mod.rs
- core/embed/rust/src/ui/model_tt/layout.rs
- core/mocks/generated/trezorui2.pyi
- core/src/apps/management/apply_settings.py
closes #3263 
- Only TOIG is accepted as homescreen format.
- Default image is painted if something else is stored in storage.
> improve T2B1 homescreen checks

- .github/workflows/prebuild.yml
- ci/check_changelog.sh
- ci/shell.nix
Changelog check was broken because:
* actions triggered on pull requests run on merge commit of base branch + PR branch by default (on gitlab they run on PR branch),
* we were cloning shallow git repo without history
> ci: fix changelog check for github

- core/src/apps/management/reboot_to_bootloader.py
Fixes https://github.com/trezor/trezor-firmware/issues/3416:
- change the text before going to bootloader
> chore(core): change `Go to bootloader` screen text

- core/embed/rust/src/ui/display/mod.rs
Fixing integer overflow and subsequent panic when rendering to large enough area.
> fix large area marquee rendering

- core/.changelog.d/3244.fixed
- core/src/apps/base.py
- core/src/boot.py
fixes https://github.com/trezor/trezor-firmware/issues/3244
also fixes a fading glitch when changing the device orientation (display was cleared before the fade-out)
> fix delay on startup when other than north orientation of the screen is set

- core/embed/rust/src/lib.rs
- core/embed/rust/src/trezorhal/display.rs
- core/embed/rust/src/trezorhal/secbool.rs
- core/embed/rust/src/ui/component/base.rs
- core/embed/rust/src/ui/display/toif.rs
- core/embed/rust/src/ui/model_tr/bootloader/mod.rs
- core/embed/rust/src/ui/model_tr/layout.rs
- core/embed/rust/src/ui/model_tt/bootloader/mod.rs
- core/embed/rust/src/ui/model_tt/component/homescreen/render.rs
- core/embed/rust/src/ui/model_tt/layout.rs
just to have clean slate. 
Not entirely sure about the `#![allow(internal_features)]` which is needed to suppress warning about `#![feature(lang_items)]`
> fix rust warnings and clippy errors

- .github/actions/ui-comment/action.yml
- .github/actions/ui-report/action.yml
- .github/workflows/core.yml
- .github/workflows/legacy.yml
- tests/ui_tests/reporting/__main__.py
- tests/ui_tests/reporting/common.py
- tests/ui_tests/reporting/master_diff.py
Github Actions only exposes artifacts as .zip files with a bunch of limitations, which makes them unsuitable for UI reports HTML. This PR implements copying the reports to an external server. Links to the reports are then posted to the pull request discussion. To minimize noise, comments are edited if they already exist, and are not posted at all when there are no changes.
Example comment with working links: https://github.com/trezor/trezor-firmware/pull/3436#issuecomment-1841808188
@vdovhanych can you please take over the PR and replace the `rsync` invocations with `aws s3 sync` or anything else that is needed to get the reports to data.trezor.io? Currently they are copied to my [throwaway VPS](https://trezorui.martinmilata.cz/) that will be deleted 31.12. You may also want to set up …
> ci: HTML UI reports for github actions
